### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by scargill** [nodemcu/nodemcu-firmware#1]
Current issues I'm aware of.. the latest http: server demo, every time it is used, the heap drops - starting at 6k and dropping eventually to 3k at which point the board reboots. The heap management needs sorting other wise any kind of fast polling (remote phone monitoring of output state or similar) would be impossible.

Secondly - - the Telnet demo just fails. Two of us have tested both of these on different installations, same response. REALLY would appreciate any fixes.

Are you planning to use the new SDK?

**Comment by amancinellib** [comment]
I'm using firmware 0.9.6 build 20150704 on ESP01 to send data over internet, but each tcp call the heap consumes about 500 bytes.

The code in the alarm is:

conn=net.createConnection(net.TCP, false) 
                    print("init:create="..node.heap())
                    conn:on(CONST_CONN_RECEIVE, function(conn, pl) 
                        print(pl)
                        pl=nil
                        collectgarbage();
                    end)
                    conn:on(CONST_CONN_CONNECTION, function(c)
                        c:send(HTTP_REQ_GET..jsonTemp..HTTP_HEADER)
                        end)
                    conn:on(CONST_CONN_SENT, function(conn) collectgarbage("collect") end)
                    conn:connect(SERVER_PORT,SERVER_IP)
                    print("init:finishconn="..node.heap())
                    conn=nil;t=nil;h=nil;
collectgarbage();

**Comment by TerryE** [comment]
Use a current build. See #719 for comments on 0.96 builds.
