### ISSUE TITLE
mqtt client connection not working and provides no output

### ISSUE THREAD

**Issue by axill86** [nodemcu/nodemcu-firmware#1003]
Hi, I am trying to connect my local mosquitto server using mqtt lib and following code provides no output at all:
```

m=mqtt.Client("nodemcu_box", 120)

m:connect("192.168.1.3", 1883, 0, function(conn) 
    print("connected") 
end)

m:publish("hello/world","hello from nodemcu",0,0, function(conn) 
    print("sent") 
end)

```
but I can send messages to the broker using console client

`$ mosquitto_pub -h 192.168.1.3 -p 1883 -d -t hello/world -m "hello"`

**Comment by marcelstoer** [comment]
This is not a support forum. See http://nodemcu.readthedocs.org/en/dev/en/support/.
