### ISSUE TITLE
Thoroughly document how NodeMCU handles esp_init_data_defaults

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#1009]
This topic comes up with surprising frequency, so it could do with better explanations in the docs.

**Comment by marcelstoer** [comment]
Do you plan to expand http://nodemcu.readthedocs.org/en/dev/en/flash/#upgrading-from-sdk-09x-firmware?

**Comment by jfollas** [comment]
As a reader, part of my confusion comes from the fact that init_data exists in flash_api.c, so I'm not sure when I need to flash a .bin vs. allowing the ESP to write the init data itself.

**Comment by marcelstoer** [comment]
Superseded by #1285.
