### ISSUE TITLE
MOD_CHECK_TIMER

### ISSUE THREAD

**Issue by nickandrew** [nodemcu/nodemcu-firmware#1011]
platform.h includes a macro `MOD_CHECK_TIMER` which calls a function `platform_timer_exists()` but there's no such function in the codebase.

The correct name is `platform_tmr_exists()`

Nobody noticed because nothing calls `MOD_CHECK_TIMER(id)`. Instead, the tmr module calls `MOD_CHECK_ID(tmr, id)`.

Placeholder for me or whoever gets around first to making a commit to fix.

**Comment by TerryE** [comment]
I am working on platform.\* as we write. Change made. Will get swept up with my GPIO PR.
