### ISSUE TITLE
Contributing guidance

### ISSUE THREAD

**Issue by cheloftus** [nodemcu/nodemcu-firmware#1013]
I recently had a perfectly valid comment that [my PR](../pull/1004) adding a new Lua export was missing relevant documentation for the additional function.
Clearly I should have thought of this myself - but it might be worth adding this as a requirement to contributing.md?

**Comment by marcelstoer** [comment]
> it might be worth adding this as a requirement to contributing.md

Indeed... #1016 is pending verification and merge.

**Comment by TerryE** [comment]
I w read this and went to merge it, but realised that you've still to make the PR here.  Whenver you re ready :)
