### ISSUE TITLE
New module for easy bit banging?

### ISSUE THREAD

**Issue by romanchyla** [nodemcu/nodemcu-firmware#1015]
Following the contributor's guide, I'd like to ask if there is an interest in having a generic module for reading GPIO sensors. I've built it for reading hx711 (which is already inside nodemcu), but then I made it more generic - so it might be more useful for any sensor where the data has to be read using 'bit banging'

https://github.com/romanchyla/nodemcu-firmware/blob/hx711/app/modules/easygpio.c

**Comment by romanchyla** [comment]
alright, I took the chance - please see #1017

**Comment by marcelstoer** [comment]
Thanks for contributing.

> alright, I took the chance - please see #1017

And where are we supposed to leave comments now, here or at the PR? I suggest you close either of the two.
