### ISSUE TITLE
hello !  ws2812B  Soft AP not works

### ISSUE THREAD

**Issue by Retroaktiv** [nodemcu/nodemcu-firmware#1019]
hello!

I have problems with the DEV version of nodemcu. 
I used DEv with:
adc,bit,bmp085,cjson,coap,crypto,dht,file,gpio,hx711,i2c,mqtt,net,node,ow,pwm,rtcfifo,rtcmem,rtctime,sntp,spi,tmr,tsl2561,u8g,uart,ucg,wifi,ws2801,ws2812
Modules.
The Softap starts and the Index.html works. 
On the ESPlorer  see the commds from my handy ( ~00ff2a)
but the Led Stripe is not lit.

With nodemcu_integer_0.9.5_20150318.bin works my Lua-Skript ind the Stripe lights.

I I tried several and some modules, but no change. Where can my fault?

I hope I can write here!
Thanks for your help. Sorry for my bad English
Retroaktiv

**Comment by devsaurus** [comment]
The WS2812 module is currently only able to drive LEDs via GPIO2. See #966 for details.

**Comment by Retroaktiv** [comment]
OMG ! 
Thank you !
