### ISSUE TITLE
Enable 250kbit baud rate in Uart module

### ISSUE THREAD

**Issue by marki555** [nodemcu/nodemcu-firmware#1045]
Why is the 250kbit baud rate not enabled in the Uart module? I see it defined in ` app/include/driver/uart.h ` as `BIT_RATE_256000 = 256000`, but not in `platform_uart_setup()` function in `app/platform/platform.c`.
Is it possible to enable also this bitrate? It is used for example in the DMX512 serial protocol.

**Comment by dnc40085** [comment]
Unless I'm mistaken, I believe this same question was asked previously in issue #856

**Comment by marki555** [comment]
Yes, seems to be the same... however I don't see any reason why it couldn't be implemented as https://github.com/Rickgg/ESP-Dmx already does this on ESP8266 in Arduino. Also the define in `uart.h` suggests that this shoud be possible (unless there is some reason why Lua implementation would not support this particular bitrate from all those available).

**Comment by devsaurus** [comment]
Agreed, there's no obvious reason why the definition from `app/include/uart.h` shouldn't be picked up by the platform code. #856 suggests that it would be best to actually verify the HW support for this setting with a scope.
I'll look at it during the next days.

**Comment by devsaurus** [comment]
The related PR has been merged to `dev`. Please check whether it resolves your issue.
