### ISSUE TITLE
I2C Rework

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#1052]
After I finish the GPIO module, I've got a few small bits of backlog like the encode module that I want to flush through as commits, but I am thinking of doing a higher level I2C implementation to make it  lot simpler to write I2C based drivers -- possibly along the printf / scanf lines. 

This may seem an odd idea but I2C drivers at the moment are very cumbersome since a lot of API calls are involved, and so take up a lot of code space.  In reality the drivers spend most of their time in delay loops, so parsing a format-style encapsulation can be lost in these time windows.  This would also mean that coding up such drivers as Lua modules would be just as simple and fast as having to drop down into a C module.

This is just a place-holder for feedback and comment, before I start this mini-project.

**Comment by IVI053** [comment]
Will this include adding the functionality of running as slave device?

**Comment by TerryE** [comment]
Running the ESP8266 architecture as a slave is a lot more challenging as the host controls the clock and this would need time critical ISR-based timing. This is an my medium term more of a wish list priority, because I need to sort out a quite a few other PRs first.

**Comment by robstarling** [comment]
Do you plan to support clock-stretching? It appears that the current implementation completely ignores it. This is important for slower I2C slaves. I believe i can help implement it.

**Comment by jsaily** [comment]
robstarling: Connecting with a slow I2C slave is exactly my problem too! I can easily connect to a PCF8574 I/O expander but my PIC18F2520 slave processor is not even giving ACK to the ESP8266 running NodeMCU. I would only need a basic NodeMCU build with file, GPIO, net, node, timer, UART, WiFi and slow I2C modules. 

I was wondering if I could hack the I2C module to increase delays everywhere, and compile with Docker build tool? https://hub.docker.com/r/marcelstoer/nodemcu-build/

**Comment by Xasin** [comment]
@jsaily 
And, did things work out? If so, I might be interested in doing the reverse - speeding things up a bit to communicate at faster speeds with my Arduino.

**Comment by TerryE** [comment]
Just a codocil on this one: to be honest, on reflection reworking I2C isn't a high priority for me now.  Yes, there would be lots of nice-to-have items here, but the current I2C implementation is pretty solid and usable for everything I've used it for, so I am inclined to close this issue.

**Comment by Xasin** [comment]
OK for me - A lot of optimization could be squeezed out by storing all variables to be sent in a single-layer array, instead of a 2D one that had to be "squeezed flat" first.
Brought send time down from ca. 12ms to 5ms, enough for me.
