### ISSUE TITLE
crypto module lacks fromBase64 function

### ISSUE THREAD

**Issue by marcoskirsch** [nodemcu/nodemcu-firmware#1053]
Per https://nodemcu.readthedocs.org/en/dev/en/modules/crypto/
There is a crypto.toBase64() function, but no symmetrical fromBase64().
Some projects can benefit from such a thing and seems like an odd omission.

Workaround: use Lua implementation such as https://github.com/marcoskirsch/nodemcu-httpserver/blob/master/httpserver-b64decode.lua but this has memory and speed implications, plus as is doesn't work well on firmware builds with floating point enabled.

**Comment by TerryE** [comment]
See #475, #925 .  I've got the working code but just want to clear out the tasking / gpio PR first.  Please use #925 for future discussions.
