### ISSUE TITLE
How register callback when call coap.client:get()

### ISSUE THREAD

**Issue by tranphong213** [nodemcu/nodemcu-firmware#1097]
Hi,
I use coap.client:get() but i don't recieve data from server coap. I used cooper cu(add firefox) and recieved data but esp8266 did not receive the data . How register callback when call coap.client:get() ?

**Comment by dnc40085** [comment]
The issues section of the NodeMCU github is for reporting bugs and issues with the firmware. To get help with Lua scripts please refer to the [Random Lua Chat](http://www.esp8266.com/viewforum.php?f=24) subforum of [esp8266.com](http://www.esp8266.com).

Please see #719 for details.
