### ISSUE TITLE
Crash on dev branch with pwm.setup if LUA_USE_MODULES_GPIO not defined

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#1099]
It turns out that the function get_pin_map() never gets called unless LUA_USE_MODULES_GPIO is not defined. Also, I don't think it gets called unless GPIO_INTERRUPT_ENABLE is set either.

This function initializes various crucial data structures that are used by the pwm code (e.g. to enable the pin for output).

I'm about to file a PR to fix this.

**Comment by TerryE** [comment]
#1100 now merged.  We may not be done with this, but the bug has been fixed.
