### ISSUE TITLE
TCP connection does not appear to use random port for SRC port?

### ISSUE THREAD

**Issue by xlfe** [nodemcu/nodemcu-firmware#110]
I have my ESP module setup to send temperature data to the server at regular intervals, and as part of the debugging process I've been examining the TCP packets it sends/receives.

Not sure why but it is consistently using a SRC port of 4097 when connecting to a HTTP server on port 80

![image](https://cloud.githubusercontent.com/assets/1177787/5790779/aa999450-9efc-11e4-8cdd-72f48e1db360.png)

**Comment by xlfe** [comment]
Just to confirm - different devices use different ports - ie one is always using SRC port 4097, another is always using SRC port 1038...

**Comment by xlfe** [comment]
Ok.. after further analysis it looks to be increasing. So i have two modules where the SRC port (is increasing by one each time) in the 1xxx range and a third module which is stuck on 4097 for source port.

**Comment by nodemcu** [comment]
please try latest build 20150118

**Comment by xlfe** [comment]
Thanks @nodemcu - that fixed it. I just wanted to say that I really appreciate all the time and effort you and your team are putting into NodeMCU - very much appreciated!

Cheers
