### ISSUE TITLE
node.dsleep wrong argument check

### ISSUE THREAD

**Issue by DesperateProgrammer** [nodemcu/nodemcu-firmware#1109]
At https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/modules/node.c#L58
the us argument is retrieved and afterwards checked for less then zero.

This check will never succeed and thus the error is not caught.
It is either dead code or if values >= 2^31 are not allowed as the delay applied on the wrong variable type.

From a quick peak I could not find the documentation of what is the maximum deepsleep time at system_deep_sleep, so I do not have the needed info for a solid fix right now.

PS: Stumbled uppon this while reading https://www.mikrocontroller.net/topic/391502

**Comment by jmattsson** [comment]
Would be nice to check this in code and not just have it in the documentation.
