### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by eliabieri** [nodemcu/nodemcu-firmware#111]
When will you make a new version and update the binaries?

**Comment by nodemcu** [comment]
build a bin with spi module in master branch.
mqtt bin is built in mqtt branch temporary, will merge to master soon.

**Comment by GeoNomad** [comment]
Did you notice that this binary is called 20150108 but today is 20150118?

Confusing.

**Comment by vowstar** [comment]
Please use our binary at pre_build folder, every new binaries get there
