### ISSUE TITLE
Module connects to Wifi with wifi.sta.autoconnect(0)

### ISSUE THREAD

**Issue by alex3kov** [nodemcu/nodemcu-firmware#1118]
I've put this simple script into lua file and running it via ESPlorer:
```
wifi.setmode(wifi.STATION)
wifi.sta.config("SSID", "pass")
wifi.sta.autoconnect(0)
```
The idea is to set wifi parameters so it is ready to connect with `wifi.sta.connect()`. I want to connect it later in a callback function as a reaction to an event. But after this script runs, couple of seconds later `=wifi.sta.status()` returns 5 and `=wifi.sta.getip()` returns IP information.  
I'm running cloud-built NodeMCU:  
```
NodeMCU custom build by frightanic.com
branch: master
commit: c8037568571edb5c568c2f8231e4f8ce0683b883
```

**Comment by kms** [comment]
Try this instead:
```
wifi.setmode(wifi.STATION)
wifi.sta.config("SSID", "pass", 0)
```

**Comment by alex3kov** [comment]
Thanks, I missed that in documentation.
