### ISSUE TITLE
MQTT CONNACK

### ISSUE THREAD

**Issue by jfollas** [nodemcu/nodemcu-firmware#1122]
Recently at work, we got into a situation where NodeMCU was not connecting to our MQTT broker, and there was absolutely no feedback as to why. Turning on debugging showed that it kept trying to connect every second (as it should, since autoconnect was enabled), but again, we couldn't tell what was failing other than seeing it keep trying to connect.

It turns out that the broker was replying as it should, stating in the CONNACK that the password was invalid. But, there was absolutely no way to receive that feedback from the Lua side because CONNACK is not being processed by our MQTT client.

CONNACK return values are declared on pages 32-33 of OASIS spec:

MQTT 3.1.1 Specs: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

**Comment by pjsg** [comment]
PR merged
