### ISSUE TITLE
can we configure the gpio push mode ?

### ISSUE THREAD

**Issue by wuyuanyi135** [nodemcu/nodemcu-firmware#1139]
In the doc
```
gpio.mode(pin, mode [, pullup])
```
I wonder if we can specify the pull mode (push pull/ open drain) here?

**Comment by marcelstoer** [comment]
Not sure I really get the question. The docs seem very clear to me. You either use pullup or leave it floating, that's it.

**Comment by wuyuanyi135** [comment]
So this "pull up" actually mean push-pull? Then is it possible to activate
internal pull-up resistor

2016-03-09 17:31 GMT-05:00 Marcel Stör <notifications@github.com>:

**Comment by devsaurus** [comment]
@wuyuanyi135 looking at the code in `set_gpio_no_interrupt()` of platform.c I'd say that the output driver stages of the GPIOs are always configured to push-pull mode when set to output with `gpio.mode()`. There's currently no way to put them into open-drain mode.

The `pullup` parameter you mentioned controls whether the weak pull-up resistor is enabled or not.

Adding open-drain capability (and improving the docs) sounds like a valid improvement.

**Comment by wuyuanyi135** [comment]
@devsaurus Thanks. Great to implement push mode configuration

**Comment by pjsg** [comment]
The hardware supports all four pin settings (LO, HI, Hi-impedance, weak pullup).

**Comment by TerryE** [comment]
See the GPIO V0.5 Spec ([here](http://bbs.espressif.com/viewtopic.php?f=51&t=819]) I believe a later version is also available.

**Comment by devsaurus** [comment]
Thanks for the links. I'll follow up with a PR for adding open-drain mode.

**Comment by devsaurus** [comment]
The respective enhancement was merged some time ago.
