### ISSUE TITLE
Expose custom DHCP options in Lua

### ISSUE THREAD

**Issue by deece** [nodemcu/nodemcu-firmware#1145]
It would be useful to expose custom DHCP options delivered by the server to the Lua scripts.

For example, which server address to use, what URL to poll and what MQTT topic to interact on, could all be configured from the DHCP server, without requiring the user to configure it explicitly on each module.

**Comment by jmattsson** [comment]
Interesting idea. Sounds similar to what @TerryE is doing (but not over DHCP afaik).

**Comment by viperidae** [comment]
Would be quite handy but looks like it would require changes to the lwip dhcp client.
I don't see where all the options are made available.
