### ISSUE TITLE
HTTP module - binary download issue

### ISSUE THREAD

**Issue by jfollas** [nodemcu/nodemcu-firmware#1152]
Download binary files using the HTTP client is failing for me when there's 0x00 in the data. Pretty sure it's because the buffer is a char\* in the HTTP client and C null termination is coming into play.

_Edited_

Researching this some more, I think to get around my first symptom (truncation of binary data), the Lua callback needs to use `lua_pushlstring` instead of `lua_pushstring` in the following:

``` c
  if (http_callback_registry != LUA_NOREF)
  {
    lua_rawgeti(http_client_L, LUA_REGISTRYINDEX, http_callback_registry);

    lua_pushnumber(http_client_L, http_status);
    if ( http_status != HTTP_STATUS_GENERIC_ERROR )
    {
      lua_pushstring(http_client_L, response);
    }
    else
    {
      lua_pushnil(http_client_L);
    }
    lua_call(http_client_L, 2, 0); // With 2 arguments and 0 result
```

https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/modules/http.c#L32

The code that fills the buffer (in `http/httpclient.c http_receive_callback` ) appends a null character onto the end of the array, which may have an impact with binary data (i.e., the data won't have the same hash with the null character appended).

https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/http/httpclient.c#L251

**Comment by jfollas** [comment]
I have a solution for this that I'll prepare a PR for.

**Comment by TerryE** [comment]
`lua_pushstring()` should _never_ be used for user data, for this reason.  It should be limited to pusihing  known patterns and text which can't contain an embedded nullchar.  Having done a quick scan of `app/modules` this is the only case here.

**Comment by jfollas** [comment]
Little hiccup in the process of getting here, but the PR 1157 includes the fix for this issue.

**Comment by TerryE** [comment]
@jfollas  @vowstar, I've just had a look at this source and it has a lot of short comings, for example:
-  it requires you to build with SSL enabled even if you are only using HTTP in your app.
-  it reimplements standard functions for no clear reason
-  it's memory allocation / freeing is flaky so it will generate memory leaks
-  it doesn't handle records which span IP packets.

Nothing to do with this PR but a lot more work is really needed on this.

**Comment by jfollas** [comment]
@TerryE: Having spent time in the code to troubleshoot/fix the issue, I'd agree that the http module could really use more effort. My PR focused on the tasks at hand (i.e., all of the things that you mentioned exist in the current module's code even without the corrective parts of my PR).

Oh, and I think it does handle the scenario where the payload arrives in different packets (`http_receive_callback`). The finalization work isn't until the socket disconnect callback.
