### ISSUE TITLE
BME280 module wrong temp Humi reading

### ISSUE THREAD

**Issue by lorenz24** [nodemcu/nodemcu-firmware#1158]
BME280 readings with the BME280 module from vsky279 shows me wrong data.
Messured with a DHT22  shows me 
23.0 degrees Celsius and Humidity of 36.3%.
A DHT22 shows me 
23.2 degree Celsius.
BME280 shows me
QNH=1023.994 
T=25.41
humidity=16.759%
The Air pressure is very accurate but the temperature and the humidity is wrong.
I used 3 BME280 sensors but almost same wrong result.
Can anybody help me.

**Comment by TerryE** [comment]
Sorry not on this issues list.  This is for firmware development, not applications support.  You need one of the application forums.  See #719 for the links to StackOverflow and esp8266.com.
