### ISSUE TITLE
SPI - CPHA is inverted when CPOL=1

### ISSUE THREAD

**Issue by jfollas** [nodemcu/nodemcu-firmware#1161]
NodeMCU received CPOL=1 support a few months ago (before then, we were stuck with only CPOL=0, or low-idle clock). Today I scoped out one of our SPI interfaces that was misbehaving while using CPOL=1,CPHA=1, and it was showing the wrong waveform. I have not checked CPOL=0 yet.

The CPHA=1 waveform looked like what CPHA=0 should, and vice versa (it was one of those "How did this ever work in the first place?" situations).

CPOL=1, CHPA=1
![CPOL=1](http://i.imgur.com/LrNB9M3.png)

CPOL=1, CPHA=0
![CPOL=0](http://i.imgur.com/SZEmwsL.png)

Example of what it's supposed to look like:

![SPI Waveforms](https://abieneman.files.wordpress.com/2010/04/atmega-spi-modes.gif)

I'm going to make the correction that I think, and then scope out the new waveforms. If they are correct, then I'll submit the PR.

**Comment by TerryE** [comment]
@jfollas much appreciated.  I await your analysis with interest.  Regards Terry

**Comment by jfollas** [comment]
Submitting a PR on this. I've verified the waveforms for all four modes.

*Mode 3*
![Mode 3](http://i.imgur.com/1O4gAt2.png)

*Mode 2*
![Mode 2](http://i.imgur.com/Mvdflpy.png)

*Mode 1*
![Mode 1](http://i.imgur.com/TBQ6JYf.png)

*Mode 0*
![Mode 0](http://i.imgur.com/HXQuXPj.png)

**Comment by jfollas** [comment]
#1162 has been merged.
