### ISSUE TITLE
unsubscribe a mqtt topic

### ISSUE THREAD

**Issue by wuyuanyi135** [nodemcu/nodemcu-firmware#1172]
Hello,

The mqtt library does not provide unsubscribe feature. Will it be implemented?

**Comment by marcelstoer** [comment]
We're always happy to see pull requests created by the community. It's true if there's `subscribe` you'd expect `unsubscribe` but I don't actually see the need for it. What's the use case?

**Comment by pjsg** [comment]
Actually, the project that I am working on needs the unsubscribe functionality as well. I had assumed that it was present as well. 

My particular project is a dial which shows a value (such as electricity consumed/generated). It uses the rotary switch module (that I committed) to choose which parameter to display. It then subscribes to that parameter and then drives a stepper motor to drive the needle (once we get past the current dev->master merge, I'll submit that). Of course, I need to unsubscribe the old topic.....

**Comment by marcelstoer** [comment]
@pjsg thanks for the PR
