### ISSUE TITLE
Customizable Enduser-Setup webpage

### ISSUE THREAD

**Issue by skycoders** [nodemcu/nodemcu-firmware#1187]
I just tried the enduser setup module for the first time. It worked great. Nevertheless, I was wondering if anyone agrees that handing over a file name from where to load the html file in the start call would be cool. The html page could be provided as a template in git or wherever. This file would then replace the website inlined into the c module file. 
Additionally, providing a custom base name of the created WIFI network would allow the next step of customization. This should be fairly easy to do.
Any comments?

**Comment by robertfoss** [comment]
That feature already exists. Place a file named index.html in the filesystem, and it will be served by EUS.

**Comment by skycoders** [comment]
uh, sorry... but that is not documented in the module docs, isn't it? I could find that in the module code now. 
Besides this, changing the AP name from SetupGadget... to something else is not included, correct? What do you think about this extension?

**Comment by robertfoss** [comment]
It's possible in manual mode or while compiling NodeMCU.

**Comment by charudatt** [comment]
Hi Robert. 
I tried your code along with a non customized bin file and it worked the first time, but again it just goes in a loop, It does not connect to the accesspoint nor does it show up the HTML page.

When I used the compiled NODE MCU bin file, the NodeMCU board just goes into a endless loop showing junk characters in the serial screen.

Can you please explain how to use it with an example.

**Comment by robertfoss** [comment]
@charudatt this isn't the place for this discussion. hit me up at dev@memcpy.io

Buuut, have a look at building a module with @marcelstoer fantastic service: https://nodemcu-build.com/
Build a module with the enduser_setup module compiled in.

Run a an init.lua file with something along the lines of:

    function on_connect()
      print("Connected to wifi as: " .. wifi.sta.getip())
      ssid,password,bssid_set,bssid = wifi.sta.getconfig()
      print(
          "\nCurrent Station configuration:"
        .."\nSSID : "..ssid
        .."\nPassword  : "..password
        .."\nBSSID_set  : "..bssid_set
        .."\nBSSID: "..bssid.."\n"
      )
      -- add more stuff here
    end
    
    enduser_setup.start(on_connect)`

**Comment by marcelstoer** [comment]
> this isn't the place for this discussion. hit me up at dev@memcpy.io

True, but I'd much rather if you guys could discuss in public so others could profit as well 😉 @charudatt also see https://nodemcu.readthedocs.io/en/latest/en/support/

**Comment by gusarov** [comment]
Sorry, is there a way to call and configure enduser-setup on C (using Visual Studio / Atmel Studio / Arduino Studio)? I like ESP & Nodemcu but have no intention to learn one more new language.

**Comment by robertfoss** [comment]
The module is written in C.

So you can do whatever you like with it in your editor of choice.
