### ISSUE TITLE
SPI to fast

### ISSUE THREAD

**Issue by Phando** [nodemcu/nodemcu-firmware#1189]
SORRY... saw posting to git issues is the wrong place for support. I will post elsewhere. I couldn't figure out how to delete this, feel free to close.

Hello,
I really want to make use of this SPI module on my nodemcu. SPI keeps my code clean and frees up some of my gpio pins. I feel it is sending data too fast for my 74HC595 to keep up with. It was working for a bit, then stopped. It seemed like there was a lot of noise on the line so I hooked up the logic analyzer and saw that when I was sending data, bits were flying across the line at almost 6ns (which is awesome). My driving a 595 and ultimately a stepper needs data at a way slower rate. I have tried using the clock parameter in the setup call, but I feel it never slows the SPI clock. Is there any way to set the clock speed to something that would be more 595+stepper friendly? 

Thanks!

**Comment by TerryE** [comment]
@Phando This is the wrong place to ask "How do I" Qs.  See #719 for appropriate forums.
