### ISSUE TITLE
Method names longer than LUA_MAX_ROTABLE_NAME should not fail silently

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#1193]
#1191 threw this on up. We should pick this up during initialisation, rather than with some difficult to diagnose runtime side-effect.

This is low priority, but still an issue.

**Comment by jmattsson** [comment]
Is this a lack of compiler warnings that is biting us here?

**Comment by TerryE** [comment]
No, it's just that I forgot to do this when I did the change :sob:

**Comment by TerryE** [comment]
Add to TODO and bundle with #929
