### ISSUE TITLE
Dump the HTTP server example

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1196]
Terry says:
> Having said that the current http_server example is just terrible.

We should just dump it because a full HTTP server IMO is beyond the scope of even our "examples". Instead we can link to https://github.com/marcoskirsch/nodemcu-httpserver.

If we want to keep it then someone needs to clean up https://github.com/nodemcu/nodemcu-firmware/blob/dev/lua_examples/http_server.lua.

**Comment by jmattsson** [comment]
Bad examples are worse than no examples I think.

**Comment by ID453543435** [comment]
I HAVE OK HTTP SERVER BUT IT EXPENSIVE!
