### ISSUE TITLE
mqtt branch - Unable to initialize mqtt client

### ISSUE THREAD

**Issue by MrBalonio** [nodemcu/nodemcu-firmware#121]
Hello, 

I am running the lastest bin and after connecting to wireless I am unable to initialize the MQTT client

Here's what I get

> m = mqtt.Client("clientid", 120, "user", "password")
stdin:1: attempt to call field 'Client' (a nil value)

I also tried 
 m=mqtt.Client()
stdin:1: attempt to call field 'Client' (a nil value)

**Comment by robb-aker** [comment]
Hey,

I hit the same problem. The old method for creation still works.

rob

**Comment by nodemcu** [comment]
in the branch mqtt， you have to compile the code yourself。

**Comment by tuanpmt** [comment]
Binary file can be downloaded here: http://www.esp8266.com/viewtopic.php?f=19&t=1278

**Comment by MrBalonio** [comment]
@tuanpmt  thanks. I will try the new binary with the new example

**Comment by nodemcu** [comment]
mqtt branch merged to master, pre_build bin included.

**Comment by robb-aker** [comment]
Works lovely. Thanks for the great work guys!

**Comment by MrBalonio** [comment]
Thanks it works great
