### ISSUE TITLE
enduser_setup can cause wdt reset

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#1224]
The following code causes a wdt reset and restart

```
enduser_setup.start(function() enduser_setup.stop() end)
```

**Comment by jmattsson** [comment]
Hmm, is this something that got introduced when there was a delay added before the automatic shutdown?

I've never seen this problem, but we always run in manual mode here.

**Comment by marcelstoer** [comment]
Philip, wasn't that fixed a while ago?

**Comment by pjsg** [comment]
I'll check it and see
