### ISSUE TITLE
HX711 module.

### ISSUE THREAD

**Issue by Rishi99es** [nodemcu/nodemcu-firmware#1227]
I generated a custom build firmware that includes HX711 and ADC modules along with other default modules and uploaded the firmware(float) into my nodeMCU 1.0

I would like to know how can I use the hx711.init() and hx711.read() functions in my lua script.

Below is a simple script to just measure the load cells.

'clk = 1 --pin D5
dout = 2 --pin D4

gpio.mode(clk, gpio.OUTPUT)
gpio.mode(dout, gpio.INPUT)

hx711.init(clk, dout)
rawData = hx711.read(0)`

Please let me know all the essentials in order to generate the right script for my application.
Thank you

**Comment by marcelstoer** [comment]
See http://nodemcu.readthedocs.org/en/dev/en/support/ and http://nodemcu.readthedocs.org/en/dev/en/modules/hx711/.
