### ISSUE TITLE
tmr.alarm() with ns or us, pwm >= 200 kHz

### ISSUE THREAD

**Issue by matzl** [nodemcu/nodemcu-firmware#1234]
Will there be some way to generate an interrupt with < 1ms delay or to speed up PWM to >= 200kHz?
I would like to generate a toggling pin for a LED PWM controller with f=204800 Hz...

**Comment by pjsg** [comment]
The existing PWM code will not be able to do this. However the I2S interface might be able to do what you want. However, the nodemcu code doesn't really have any support yet for the i2s.....

**Comment by devsaurus** [comment]
There's a PWM-like mode for the [sigma-delta](http://nodemcu.readthedocs.org/en/dev/en/modules/sigma-delta/) module: 8&nbsp;bit resolution at fixed 312.5&nbsp;kHz. That's >200&nbsp;kHz but not 2^11-ish.
