### ISSUE TITLE
UART Bug

### ISSUE THREAD

**Issue by pretcorr** [nodemcu/nodemcu-firmware#1241]
I found a bug that makes the serial data in the UART not transmit back to the port. I send data to the unit via wifi and do not get back the data unless I say how many bytes I need. I got the code working on one unit but cannot get it going on the later ones.

Im using these files

NodeMCU custom build by frightanic.com
	branch: master
	commit: c8037568571edb5c568c2f8231e4f8ce0683b883
	SSL: false
	modules: file,gpio,net,node,ow,tmr,uart,wifi
 build built on: 2016-04-13 11:14
 powered by Lua 5.1.4 on SDK 1.4.0

The code I use is

 uart.on("data", 0, function(data)
 conn:send(data)
 end, 0) 

I send 4 bytes then need to get 2 back
I send 4 bytes then 18 comes back
I send 4 bytes then 82 comes back.

Its circular comms with variable bytes being received.

According to the spec the bytes in buffer should be transmitted ie if there is 10 its sent regardless but it does not do that. If I change the value to the value of bytes I expect then it fine. Cannot make it 100 because variable data being send and received.

Thanx!

**Comment by TerryE** [comment]
Use a `dev` build, and post your complete code to a gist, so we can review.

**Comment by pretcorr** [comment]
Thank you fro responding!

must say the could build service is great!

I used ESplorer to write the code. The implementation is to run serial petrol pump communication through the wifi system at a site and have the pos just connected to the network. It worked on one module but then it stopped I could duplicate the success.

use the build off the could site in dev mode and its doing the same!

NodeMCU custom build by frightanic.com
	branch: dev
	commit: a33f5868551000d6f8e06def540bc5755b2146f0
	SSL: false
	modules: file,gpio,net,node,ow,tmr,uart,wifi
 build 	built on: 2016-04-14 08:15
 powered by Lua 5.1.4 on SDK 1.5.1(e67da894)


--variables
strresult = '';
dummy = 0;
mycount = 1
txdata = 0
----tag reader pins
TAGONETAG = 2  
--TAGTWOTAG = 1
----tag led pins
TAGTONELED = 5
--TAGTWOLED = 13
--TAGTWOLED = 14
mytagnumber=0
--onboard led
onboardled=4
gpio.mode(onboardled,gpio.OUTPUT)
gpio.write(onboardled,gpio.HIGH) --OFF
--gpio.write(onboardled,gpio.LOW)   --ON
tmr.alarm(0,2000,0,function()end) -- run after a delay//200
--setup wifi
--Number: current mode after setup. 
-- 1 for wifi.STATION; 
-- 2 for wifi.SOFTAP; 
-- 3 for wifi.STATIONAP; 
wifi.setmode(wifi.STATION)
--wifi.setmode(wifi.SOFTAP)
--wifi.setmode(wifi.STATIONAP)
--wifi.sta.config("TotalGlencoe","Lerm7861")
wifi.sta.config("PRETCORR","AA122448FF")
--wifi.sta.connect()
wifi.sta.autoconnect(1)
--wifi.sta.setip({ip="10.0.0.201",netmask="255.255.255.0",gateway="10.0.0.2"})
wifi.sta.setip({ip="192.168.1.201",netmask="255.255.255.0",gateway="192.168.1.1"})

--cfg={}
--cfg.ssid="PRETCORR"
--cfg.pwd="AA122448FF"
--cfg.ip="192.168.1.2011"
--cfg.netmask="255.255.255.0"
--cfg.gateway="192.168.1.1"
--set the settings
--wifi.ap.setip(cfg)
--wifi.ap.config(cfg)
--do the connect
tmr.alarm(1, 1000, 1, function() 
    --if wifi.sta.getip()== nil then 
    --if wifi.sta.status() >> 5 then 
        --0: STATION_IDLE, 
        --1: STATION_CONNECTING, 
        --2: STATION_WRONG_PASSWORD, 
        --3: STATION_NO_AP_FOUND, 
        --4: STATION_CONNECT_FAIL, 
        --5: STATION_GOT_IP.
        mystatus = wifi.sta.status()
        --print("IP unavaiable, Waiting..."..mycount..".."..mystatus) 
   ---     print(wifi.sta.status()) 
        --if lighton==0 then
        --   lighton=1
        --   gpio.write(tagledpin,gpio.HIGH)
        --else   
        --   lighton=0
        --   gpio.write(tagledpin,gpio.LOW)
        --end
        --mycount = mycount + 1
        --if mycount > 6 then tmr.stop(1) end
        if mystatus == 5 then 
           gpio.write(onboardled,gpio.LOW)
           gpio.write(TAGTONELED,gpio.HIGH)
           tmr.stop(1)
        else   
           if lighton == 1 then 
              gpio.write(onboardled,gpio.HIGH)
              gpio.write(TAGTONELED,gpio.LOW)
              lighton = 0 
           else
              gpio.write(onboardled,gpio.LOW)
              gpio.write(TAGTONELED,gpio.HIGH)
              lighton = 1 
           end      
        end
       
    --else 
    --    tmr.stop(1)
    --    print("Config done, IP is "..wifi.sta.getip())
        --dofile("yourfile.lua")
    --end 
 end)
--------------------UART----------------------------------
--id = 0, only 1 uart supported.
-- baud = 9600, 19200, 38400, 57600, 74880, 115200, 230400, 460800, 921600. not tested more than 115200
-- databits = 5, 6, 7, 8. 
-- parity = 0(none).
-- stopbits = 1(1 stopbit), 2(2 stopbit).
-- echo = 0(close echo back).
--uart.setup( id, baud, databits, parity, stopbits, echo )
--?????uart.setup(0, 9600, 8, 0, 1, 0)
-------------------TIMER------------------------------------
--tmr.alarm(id, interval, repeat, function do())
-- id: 0~6, alarmer id. 
-- Interval: alarm time, unit: millisecond
-- repeat: 0 - one time alarm, 1 - repeat
-- function do(): callback function for alarm timed out
--tmr.alarm(0,200,0,function() -- run after a delay//200
--tmr.alarm(0,200,0,function() -- run after a delay//200
-----------------SERVER START-----------------------------------
-- net.createServer(type, timeout)
-- type: net.TCP or net.UDP
-- timeout: for a TCP server, timeout is 1~28800 seconds, 
-- for a inactive client to disconnected.
--srv=net.createServer(net.TCP, 60)
------------------SERVER LISTEN-------------------------------------
--net.server.listen(port,[ip],function(net.socket))
-- port: port number
-- ip:ip address string, can be omitted
-- function(net.socket): callback function, 
-- pass to Caller function as param if a 
-- connection is created successfully
---srv:listen(80,function(conn)
--  conn:on("receive",function(conn,payload) 
--    print(payload) 
--  end)
--end) 
--end) 

--msg = "F00FA25D" 

--tmr.alarm(1, 1000, 1, function()

--   mycount = mycount + 1
--   if mycount > 10 then tmr.stop(1) end
        
--   for i = 1,string.len(msg),2 do
--     byte =("0x"..string.sub(msg,0+i,1+i)) 
 --    uart.write(0,tonumber(byte))
--   end
   
 --  tmr.alarm(0,50,0,function() end) -- run after a delay//200
   
 --  uart.on("data", 0, function(data)
 --       print(data) 
--  end, 0)
--end)
function DEC_HEX(IN)
    local B,K,OUT,I,D=16,"0123456789ABCDEF","",0
    while IN>0 do
        I=I+1
        IN,D=math.floor(IN/B),math.mod(IN,B)+1
        OUT=string.sub(K,D,D)..OUT
    end
    return OUT
end

--CRC calc
function bxor(a,b)
   local r = 0
   for i = 0, 31 do
      if ( a % 2 + b % 2 == 1 ) then
         r = r + 2^i
      end
      a = a / 2
      b = b / 2
   end
   return rs
end
--tag start
function readthetag()
    addr = ow.reset_search(TAGONETAG)
    repeat
        tmr.wdclr()
      
    if (addr ~= nil) then
       crc = ow.crc8(string.sub(addr,1,7)) 
       mytagnumber = addr
       --mytagnumber=string.format("%02X%02X%02X%02X%02X%02X", 
       --                          addr:byte(7),addr:byte(6),
       --                          addr:byte(5),addr:byte(4), 
       --                          addr:byte(3),addr:byte(2))
                                 --crc)
       --for i = 1,string.len(addr),1 do       
       --   mytagnumber = mytagnumber..string.format("%02X",addr:byte(i)) 
       --end
       --mytagnumber = encoder.toHex(addr)                   
       --mytagnumber=string.format("%02X",addr)
       --mytagnumber = tonumber(data, 16)
    end
    addr = ow.search(TAGONETAG)
    until(addr == nil)
end  
--start of main procedure

function myserverrunning() --start of the procedue
tmr.alarm(0,200,0,function() -- run after a delay//200
    --setup variables
    global_c = nil 
    intrecbyes = 0 
    --setup serial 
    uart.setup(0, 9600, 8, 0, 1, 0)
    --setup tcp server
    srv=net.createServer(net.TCP, 60) 
    --listen what happens
    srv:listen(5001,function(conn)
        --receive data
        conn:on("receive",function(conn,payload) 
           for i = 1,string.len(payload),1 do
               if (payload:byte(i) == 0xA1) then 
                   intrecbyes=18 
                   --print(18)  
                   --print(intrecbyes) 
               end
               if (payload:byte(i) == 0xA2) then 
                   intrecbyes=2 
                   --print(2)  
                   --print(intrecbyes) 
               end
               if (payload:byte(i) == 0xA9) then 
                   intrecbyes=82 
                   --print(82)  
                   ---print(intrecbyes) 
               end
           end
           if string.find(payload, "T") then
              gpio.write(TAGTONELED,gpio.LOW)
              tmr.alarm(1,50,0,function()end) -- run after a delay//200
              mytagnumber = ""
              readthetag()
              if mytagnumber > "" then 
                 conn:send(mytagnumber) 
                 mytagnumber = ""
                 payload = ""
                 intrecbyes = 0
                 datareceiveok = 0
              end
               gpio.write(TAGTONELED,gpio.HIGH)   
           end
           --send the datab
           if payload > "" then 
              uart.write(0,payload) 
              tmr.alarm(1,50,0,function()end) -- run after a delay//200
           end
           --tmr.alarm(2,100,0,function()end) -- run after a delay//200
           --read the data
           --uart.on("data", intrecbyes, function(data)
           --   conn:send(data)
           --end, 0)   
        end)  
        
        --conn:on("disconnection",function(c) 
        --    uart.on("data")
        --end) 
        --send data back from serial
        uart.on("data", intrecbyes, function(data)
             conn:send(data)
        end, 0) 
    
        
        --uart.on("data", 0, function(data)
        --     conn:send(data)
        --end, 0)
        --if ((addr:byte(1) == 0x10) or (addr:byte(1) == 0x28)) then
        --conn:on("receive",function(conn,payload) 
            --if string.find(payload, "T") then
            --   gpio.write(TAGTONELED,gpio.LOW)
            --   mytagnumber = ""
            --   readthetag()
            --   if mytagnumber > "" then conn:send(mytagnumber) end
               --if mytagnumber > "" then print(mytagnumber) end
            --   gpio.write(TAGTONELED,gpio.HIGH)
            --   mytagnumber = ""
            --   payload = ""
            --end   
            --if payload > "" then
               --for i = 1,string.len(payload),2 do
               --     byte =("0x"..string.sub(payload,0+i,1+i)) 
               --    uart.write(0,tonumber(byte))
               --end  
               -- uart.write(0,payload)
            
            --end
         --   if payload > "" then
         --      for i = 1,string.len(payload),2 do
         --          byte =("0x"..string.sub(payload,0+i,1+i)) 
         --          txdata = txdata..tonumber(byte)
         --      end
         --      print(txdata)  
         --   end   
       -- end)  
        
      --  conn:on("disconnection",function(c) 
        --    uart.on("data")
       -- end)
        
    end)
end)
--gpio.write(TAGTONELED,gpio.LOW)
--gpio.write(onboardled,gpio.HIGH) --OFF
end;--end of the procedure
--loop back
function myloopback()
tmr.alarm(0,200,0,function() -- run after a delay//200
srv=net.createServer(net.TCP, 60) 
        
        srv:listen(5001,function(conn)
        
        conn:on("receive",function(conn,payload) 
               for i = 1,60 do
               end
               if string.find(payload, "ST") then
                  print(string.len(payload))
                  strresult = payload
                  --for i = 1,string.len(payload),1 do
                  --    print(DEC_HEX(tonumber(string.sub(payload,i))))
                  --end
                  --print(payload)
                  --print(string.len(payload))
                  
               --conn:send(payload) 
               --for i = 1,string.len(payload),2 do
               --   byte =("0x"..string.sub(payload,0+i,1+i)) 
               --    sending = uart.write(0,tonumber(byte))
                   --conn:send(payload) 
                   --conn:send(tonumber(byte))
               end 
               --conn:send(sending)  
               --print(strresult)
               --strresult = ''
        end)
        end)
               
end)
end
--new server procedurer
function myservernew()
  uart.setup(0,9600,8,0,1,0) 
  sv=net.createServer(net.TCP, 60) 
  global_c = nil 
  sv:listen(5001, function(c) 
      if global_c~=nil then 
         global_c:close() 
      end 
     global_c=c 
     c:on("receive",function(sck,pl) uart.write(0,pl) end) 
  end) 
 
  uart.on("data",2, function(data) 
     if global_c~=nil then 
        global_c:send(data) 
     end 
  end, 0) 

end
function myservernewnew()
  -- 30s time out for a inactive client
  sv = net.createServer(net.TCP, 30)
  -- server listens on 80, if data received, print data to console and send "hello world" back to caller
  sv:listen(5001, function(c)
    c:on("receive", function(c, pl) 
      print(pl)
    end)
  c:send("hello world")
end)

end
myserverrunning()
--myloopback()
--myservernew()
--myservernewnew()

firmware programmer

C:\Users\Gerhard\Desktop\ESP8266\esp_iot_sdk_v1.4.0\bin\esp_init_data_default.bin 0xFC000
C:\Users\Gerhard\Desktop\ESP8266\esp_iot_sdk_v1.4.0\bin\blank.bin 0x7E000
C:\Users\Gerhard\Desktop\ESP8266\esp_iot_sdk_v1.4.0\bin\blank.bin 0X1FE00
C:\Users\Gerhard\Desktop\ESP8266\LUA Firmware\13042016\nodemcu-dev-8-modules-2016-04-14-08-16-29-float.bin 0x00000

Dont mind the code to be shared! All of it is copied off the web!

**Comment by pretcorr** [comment]
Sorry abot the code some parts is commented out! its a work in progress

**Comment by pretcorr** [comment]
I run the following baud rates:
4800, 8, N, 1
4800, 8, E, 1
4800, 8, O, 1
9600, 8, N, 1
9600, 8, E, 1
9600, 8, O, 1
14400, 8, N, 1

Are they all supported? I use 9600, 8, N, 1

**Comment by TerryE** [comment]
See #719, what we do here is to fix bugs in the firmware; other forums provide general user support. My only Q here is: is there evidence of a bug? We aren't to provide teaching support.  I did ask for a gist rather than an inline post, but I will take a quick look.

**Comment by pretcorr** [comment]
Yes, If I use uart.on("data",0, function(data) I get no data back. According to the wiki "if n=0, will receive every char in buffer." If I use this then I get nothing back so yes I consider it a bug. A function that the wiki says works does not work. My code, as send to you, works if I make n=the bytes that I need. 

A previous unit works on this code but subsequent units and firmware upgrades does not work. This is the main key section of the code to send data back to me and because it does this it doesn't work. Isnt that the whole idea of the ESP8266?

**Comment by pretcorr** [comment]
Ok read the 719 and understand what it means but I am firmly assured that the new upgrade stopped sending buffer data back

**Comment by TerryE** [comment]
The core of your code does the following:
```Lua
do
  tmr.alarm(0,200,0,function()
    global_c = nil
    intrecbyes = 0
    uart.setup(0, 9600, 8, 0, 1, 0)
    local function some_random_stuff_and_set_intrecbyes( conn, payload)
      -- ...
    end
    srv=net.createServer(net.TCP, 60)
    srv:listen(5001,function(conn)
      conn:on("receive",some_random_stuff_and_set_intrecbyes)
      uart.on("data", intrecbyes, function(data)
           conn:send(data)
      end, 0)
    end)
  end)
end
```
The `uart.on()` is executed as part of the listen callback using the `intrecbyes` value at the connection which is typically zero or whatever was left over from the last connection.  The `conn:on("receive")` callback doesn't come into this.  Programming error, not a firmware bug.

**Comment by pretcorr** [comment]
Ok Terry, Thank you for your help! I apologise blaming your code if my code was wrong!

**Comment by TerryE** [comment]
No apologies needed :)

**Comment by ymxcc** [comment]
@TerryE  

Hi, All!

Now I am facing a very hard problem, even make the whole day confusion on my mind, as folllows:

I want to read CO2 and PM2.5 value from sensors which are connected with UART. But I found that the received data were sometimes right and sometimes wrong, e.g. PM2.5 received data: 22 17 11 0 0 2 245 0 0 2 249 0 0 2 240 2 0 0 3 229
In my code, I just judged the existing "22" in the received data, then the pm2.5 could be calculated using the formulation. However, the data absolutely were wrong, PM2.5 = 757. 
The correct data were: received data: 22 17 11 0 0 0 28 0 0 0 28 0 0 0 25 0 0 0 3 122, the reasonable value is PM2.5 = 28. The bold numbers above made a big difference in some time, especially I downloaded the code into me device with plugging off the USB, making it operation under the battery.

Maybe some guys could help me to find my code where I made a big mistake to make it happen.

function measure(num, switch)

local tem = switch
uart.on("data", num, function(data)
switch = 0
uart.on("data")
uart.alt(0)
uart.setup(0, 115200, 8, uart.PARITY_NONE, uart.STOPBITS_1, 1)

        print("receive from uart:", data)
        print("received data:", string.byte(data, 1, num))
        print("tem", tem)
        if num == 20 then
        pm25_i = 1
        while(pm25_i < num)
        do
            pm25_a = string.byte(data, pm25_i)
            if pm25_a == tonumber('16', 16) then
                pm25_b = tonumber(string.byte(data, pm25_i - 1 + 7), '10') --+ string.byte(data,5) * math.pow(2,8) + string.byte(data,4) * * math.pow(2,16) + string.byte(data,5) * * math.pow(2,24)
                pm25_c = tonumber(string.byte(data, pm25_i - 1 + 6), '10')
                pm25_e = tonumber(string.byte(data, pm25_i - 1 + 5), '10')
                pm25_f = tonumber(string.byte(data, pm25_i - 1 + 4), '10')
                qiaqia_pm25 = pm25_b + bit.lshift(pm25_c, 8) + bit.lshift(pm25_e, 16) + bit.lshift(pm25_f, 24)
                m:valuechange("4", qiaqia_pm25)
                print(qiaqia_pm25)
                break
            end
            pm25_i = pm25_i + 1
        end
        end


        if num == 9 then
        co2_i = 1
        while(co2_i < num)
        do
            co2_a = string.byte(data, co2_i)
            co2_b = string.byte(data, co2_i + 1)
            if co2_a == tonumber('ff', 16) and co2_b == tonumber('86', 16) then
                co2_c = tonumber(string.byte(data, co2_i + 2), '10')
                co2_d = tonumber(string.byte(data, co2_i + 1), '10')
                qiaqia_co2 = bit.lshift(co2_c, 8) + co2_d
                m:valuechange("3", qiaqia_co2)
                print(qiaqia_co2)
                break
            end
            co2_i = co2_i + 1
        end
        end

end, 0)

if switch == 1 then
uart.alt(1)
uart.setup(0, 9600, 8, uart.PARITY_NONE, uart.STOPBITS_1, 0)
pin = 10
gpio.mode(pin,gpio.OUTPUT)
gpio.write(pin,gpio.LOW)
uart.write(0, 0xff, 0x01, 0x86, 0, 0, 0, 0, 0, 0x79)
end

if switch == 2 then
uart.alt(1)
uart.setup(0, 9600, 8, uart.PARITY_NONE, uart.STOPBITS_1, 0)
pin = 10
gpio.mode(pin,gpio.OUTPUT)
gpio.write(pin,gpio.HIGH)
uart.write(0, 0x11, 0x02, 0x0B, 0x01, 0xE1)
end
end
awp = 1
tmr.alarm(1, 2000, 1, function()
if awp == 1 then

measure(9, 1)
awp = 0
elseif awp == 0 then
measure(20, 2)
awp = 1 
end
end)

Thanks so much!
