### ISSUE TITLE
enduser-setup() not working with wemos D1

### ISSUE THREAD

**Issue by vcchm** [nodemcu/nodemcu-firmware#1248]
Hi !

-I installed a firmware using enduser_setup on a wemos D1 mini (http://www.wemos.cc/Products/d1_mini.html)

-enduser_setup does not seem to work. When i start it using the example provided in the nodemcu documentation, nothing happens.

-I had a similar issue when trying to GET a web page - i finally had it work by sending the HTTP header in one net:send("xxx") operation rather than many (which worked for nodemcu, but not for wemos).

I dont know if it is a bug in the firmware, or an incompatibility between the firmware and wemos but it is unfortunate because wemos d1 mini price & form factor a really great !

**Comment by marcelstoer** [comment]
You seem to confuse a few things but this is something for http://nodemcu.readthedocs.org/en/dev/en/support/.
