### ISSUE TITLE
Decimal literals don't seem to work

### ISSUE THREAD

**Issue by mkarliner** [nodemcu/nodemcu-firmware#125]
=19.5 gives me...

stdin:1: malformed number near '19.5'

**Comment by nodemcu** [comment]
float number not supported.

**Comment by vowstar** [comment]
You can use only integer.

**Comment by mkarliner** [comment]
Could you state that in the docs somewhere, as the eLua project does support floats.

**Comment by vowstar** [comment]
https://github.com/nodemcu/nodemcu-firmware/pull/136
We support floating point just now, please enjoy yourself.
