### ISSUE TITLE
Connect to AP with specific MAC

### ISSUE THREAD

**Issue by goran-mahovlic** [nodemcu/nodemcu-firmware#126]
I have network with more then one AP with the same SSID, it is connected in mesh.
I would like to connect to specified AP that is closest to me, but I do not know how to connect to specified MAC.

**Comment by MarsTechHAN** [comment]
OK, we will discuss about it...

**Comment by devsaurus** [comment]
Please check whether #404 resolves your request and comment or close this issue accordingly.

**Comment by devsaurus** [comment]
Closed due to inactivity. Feel free to reopen in case the issue persists.
