### ISSUE TITLE
Rotary Module documentation error

### ISSUE THREAD

**Issue by NicolSpies** [nodemcu/nodemcu-firmware#1264]
@pjsg 

- 1. Documentation for **rotary.on()** callback applies.
- 2. The following is stated:

> The first argument is the current position of the rotary switch, the second is the eventtype,..

-   I have tested the **first argument** returned with the callback to be **"eventtype"** rather than "pos" as stated and,
- the **second argument** returned with the callback to be **"pos"** rather than "eventtype" as stated

**Comment by jmattsson** [comment]
Fix merged, thanks for reporting!
