### ISSUE TITLE
New NodeMCU-D-duino

### ISSUE THREAD

**Issue by lspoplove** [nodemcu/nodemcu-firmware#1266]
I made this type of NodeMCU. Anybody want to use it make something? 
Refer to this link  https://www.tindie.com/products/lspoplove/d-duino-esp8266-and-nodemcu-and-096-oled/

**Comment by jmattsson** [comment]
Neat hardware, but this is the issue list for the NodeMCU firmware and not the place for such an announcement. Please see [the docs](https://nodemcu.readthedocs.org/en/dev/en/support/) in case of confusion.
