### ISSUE TITLE
Support for ESP8285?

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1269]
Can we support ESP8285 with little effort?

https://espressif.com/en/media_overview/news/espressif-announces-esp8285-wi-fi-chip-wearable-devices

http://imgur.com/M0uVrqT

**Comment by vowstar** [comment]
ESP8285 is same as ESP8266, and only use DOUT mode. So we should change esptool.py to DOUT by default. NodeMCU dev0.9, 1.0, ESP-12, ESP-12-E, ESP-12-F all support DOUT.

**Comment by marcelstoer** [comment]
Just found this chip in the wild on a nice dev board at https://www.tindie.com/products/onehorse/esp8285-development-board/.

**Comment by eku** [comment]
@marcelstoer nice board, but expensive.

**Comment by marcelstoer** [comment]
The board is real nice and NodeMCU just works out-of-the-box: http://frightanic.com/iot/nodemcu-esp8285-perfect-match/ .
