### ISSUE TITLE
add lua script to run on boot in firmware

### ISSUE THREAD

**Issue by danlu01** [nodemcu/nodemcu-firmware#1274]
Hi, Recently I start playing with building my own firmware with docker.  Is there a way to add some lua code in the firmware so that on boot up it would run that lua code then init.lua?

Basically, I would like it to run some lua code that is read only.  This way in case init.lua gets corrupted, it still have fall back code.  thanks.

**Comment by TerryE** [comment]
>  Is there a way to add some lua code in the firmware so that on boot up it would run that lua code then init.lua?

No, this is what init.lua does.
