### ISSUE TITLE
GPIO Pins goes "HIGH" during startup

### ISSUE THREAD

**Issue by metehanemlik** [nodemcu/nodemcu-firmware#1275]
Hi,

I am working on esp12e project which has four motors. When ı connected energy to circuit. Gpıo pins goes high and esp did not start because motors will use whole enegy. Whatever ı do to fix this ?

**Comment by dnc40085** [comment]
This sort of question is better asked on [esp8266.com](http://www.esp8266.com/viewforum.php?f=17) or [stackoverflow.com](http://stackoverflow.com). please see http://nodemcu.readthedocs.io/en/dev/en/support/.

**Comment by TheoHarbers** [comment]
I have had the same problem and i just set the pins low first line in the init.lua
