### ISSUE TITLE
lua database access

### ISSUE THREAD

**Issue by goran-mahovlic** [nodemcu/nodemcu-firmware#129]
Is it posible to implement lua database access
http://www.tutorialspoint.com/lua/lua_database_access.htm
so ESP can write directly to database

**Comment by NeiroNx** [comment]
mysql is TCP connection. Client lib can be writed on lua from C lib https://launchpad.net/mysql-arduino
it simple and commented in soure.

**Comment by sej7278** [comment]
think i'd rather have an app (tcp server, webserver etc.) on my db server handle a request from the esp rather than the esp directly writing to the db

**Comment by nodemcu** [comment]
no plan to add database support.
maybe you can make connect to internet, and let other app do this, pass info to nodemcu board.
