### ISSUE TITLE
node.dsleep option 4 with wifi connect command

### ISSUE THREAD

**Issue by GelirDurum** [nodemcu/nodemcu-firmware#1290]
I am using developer branch firmware and i am working on deepsleep mode. I use node.dsleep function with option 4. With this option after timer wake up there is no rf functionalty. My project is about temperature control  and i want connect wifi only when temperature data pass some limit. So I want use deepsleep mode option 4 with my control on wifi connection. Are there any command for connect wifi after wakeup deespsleep option 4.

**Comment by marcelstoer** [comment]
You obviously know about http://nodemcu.readthedocs.io/en/dev/en/support/. No need to post on SO and here (http://stackoverflow.com/q/37162932/131929).
