### ISSUE TITLE
Unable to create multiple server

### ISSUE THREAD

**Issue by ench4nt3r** [nodemcu/nodemcu-firmware#1296]
When my second call net.createServer(), it prompts "only one tcp server allowed"？thanks.

**Comment by marcelstoer** [comment]
This is by design, you need to [close](http://nodemcu.readthedocs.io/en/dev/en/modules/net/#netserverclose) the existing server first.

**Comment by ench4nt3r** [comment]
Why this need to do?

**Comment by dnc40085** [comment]
@ench4nt3r the current version of the net module only allows one TCP server to be open at any given time
