### ISSUE TITLE
Will espconn_disconnect() release memory?

### ISSUE THREAD

**Issue by ench4nt3r** [nodemcu/nodemcu-firmware#1299]
example:

    struct espconn *temp = (struct espconn *) os_zalloc(sizeof(struct espconn));
    temp->proto.tcp = (esp_tcp *) os_zalloc(sizeof(esp_tcp));
    espconn_disconnect(temp);

It will release them?thanks.

**Comment by ench4nt3r** [comment]
release temp and temp->proto.tcp?

**Comment by dnc40085** [comment]
You haven't given enough details, what are you trying to accomplish here? Are you trying to report a bug?

**Comment by marcelstoer** [comment]
No more feedback -> closing.
