### ISSUE TITLE
Are there any method to disable serial echo?

### ISSUE THREAD

**Issue by zzxxtt** [nodemcu/nodemcu-firmware#1301]
I want to connect the esp8266 with arduino,but I faced with a problem. I want to disable the serial echo.
For example, when the arduino send "print(123)" to the esp8266 through serial, I received ">print("123")\n123" on the arduino. But I only want to receive "123".
Is there any method? thank you.

**Comment by devsaurus** [comment]
For sure: [uart.setup()](http://nodemcu.readthedocs.io/en/dev/en/modules/uart/#uartsetup)

**Comment by zzxxtt** [comment]
Thank you very much.

**Comment by marcelstoer** [comment]
Speaking of which, it'd be nice if we had the defaults for `uart.setup()` documented 😦 (or a function to _get_ the current settings)
