### ISSUE TITLE
Add assigned IP address to enduser_setup web interface

### ISSUE THREAD

**Issue by FrankX0** [nodemcu/nodemcu-firmware#1309]
Can someone add the assigned IP address to the status information of the enduser_setup web interface, after successful connection to the WiFi network? This would make it easier to get to e.g. the webserver of the connected device.So something like:
_Status: Connected to "WiFi network" (192.168.1.101)_
Maybe for you @robertfoss ?

**Comment by FrankX0** [comment]
It turned out to be not so difficult.
I gave it a try: #1313 
Might need (coding) improvement, but it works.

**Comment by marcelstoer** [comment]
Thanks for the PR.
