### ISSUE TITLE
Issue with enduser_setup

### ISSUE THREAD

**Issue by tejaswigowda** [nodemcu/nodemcu-firmware#1314]
Hi I am getting the following error:

> [NodeMCU custom build by frightanic.com
>         branch: master
>         commit: c8037568571edb5c568c2f8231e4f8ce0683b883
>         SSL: true
>         modules: crypto,enduser_setup,file,gpio,net,node,spi,tmr,uart,wifi
>  build  built on: 2016-05-26 02:21
>  powered by Lua 5.1.4 on SDK 1.4.0
> lua: init.lua:3: attempt to call field 'manual' (a nil value)
> stack traceback:
>         init.lua:3: in main chunk
>         [C]: ?
> 

All from this line of code:

`enduser_setup.manual(true)
`
Please help!

**Comment by marcelstoer** [comment]
See http://nodemcu.readthedocs.io/en/dev/en/support/ and #719. `manual()` is not available in the [`master` branch](https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/enduser_setup.c#L933).
