### ISSUE TITLE
enduser_setup for other params

### ISSUE THREAD

**Issue by davehun** [nodemcu/nodemcu-firmware#1318]
The current enduser_setup is great for setting the wifi but it would be handy to allow custom params to be set at the same time e.g. for mqtt.

**Comment by robertfoss** [comment]
While functionality like that would be neat, there is very little infrastructure in EUS currently for supporting a feature like that.

**Comment by asofta** [comment]
Yes, this will be great feature. I also think about this.

Till now, there are feature to serve custom html page from spifs. New form fields can be added here, but there are no lua callback handler with all form parameters parsed on form submit. 
Maybe the only improvement must be adding such handler.

**Comment by marcelstoer** [comment]
That's a dup of #1302.
