### ISSUE TITLE
WPA Enterprise Encryption

### ISSUE THREAD

**Issue by Flole998** [nodemcu/nodemcu-firmware#1320]
As WPA2 Enterprise is now supported by the SDK it should be added to nodemcu. Issue #366 should be reopened.

**Comment by JaapBraam** [comment]
+1

**Comment by vshakhlin** [comment]
+1

**Comment by szogi** [comment]
+1

**Comment by mrmax1** [comment]
+1

**Comment by ziotibia81** [comment]
+1

**Comment by tolean** [comment]
++1

**Comment by Flole998** [comment]
To everyone waiting for those feature: Just don't use nodemcu, use C in Arduino, they have WPA Enterprise support (even with PEAP if I am not mistaken). Since I created the first issue which was closed I have switched to Arduino and it's working way better than nodemcu ever did. Still someone should invest time to implement this in nodemcu.

**Comment by ds2k5** [comment]
Hi Flole998,
can you share sample Code please ?
Thanks

**Comment by tolean** [comment]
I have developed branch for enterprise wifi, if you want I share it

**Comment by b08Walls** [comment]
tolean please, share my friend :)

**Comment by Flole998** [comment]
Instead of closing the issue someone should fix it....... While fixing means open the other issue again in this case. Until someone has done so, this one should stay open.
