### ISSUE TITLE
Update u8glib to version 1.19.1

### ISSUE THREAD

**Issue by devsaurus** [nodemcu/nodemcu-firmware#1335]
U8glib had an upstream [release 1.19.1](https://github.com/olikraus/U8glib_Arduino/releases/tag/1.19.1) which added contrast control for the popular SSD1306 displays.
Reminder to update our [u8glib integration](http://nodemcu.readthedocs.io/en/dev/en/modules/u8g/#u8g-module) after master snap.

**Comment by pjsg** [comment]
For the SPIFFS update, I ended up making a script that would checkout the spiffs repo and then copy over the files into the nodemcu tree. This will make it easy to do future upgrades as well...
