### ISSUE TITLE
Extend ws2812 module with shift feature

### ISSUE THREAD

**Issue by skycoders** [nodemcu/nodemcu-firmware#1342]
### Missing feature
The ws2812 module was recently updated and the buffer concept was introduced. It also added a fade() method to fade out the buffer. As another extension I have implemented a shift method, which allows you to circulate the buffer forward (positive parameter) and backwards (negative parameter). This way you can quickly achieve animations, or move the buffer and overwrite the new first/last pixel afterwards.   
I have further extended the module to support fadeIn and fadeOut (fade method kept for backwards compatibility). I can provide a pull request for this, if this is seen as useful.

### Justification
fadeIn completes the already provided fadeOut. It will of course only work if the initial set of bytes allows to scale up, but nice animations will still be possible. 
The shift method is very useful to perform this task on e.g. LED circular modules or to do any other LED chasing features.

### Workarounds
This can be done in LUA, but it is runtime critical and not as memory efficient. For fast animations, it is better to have this in native code.

**Comment by marcelstoer** [comment]
> I can provide a pull request for this, if this is seen as useful.

👍

**Comment by devsaurus** [comment]
Also a go from my side. Please check pending #1310 for any interdependence.

**Comment by skycoders** [comment]
As I have only changed buffer behavior but not the actual write command, this should not cause any issues with #1310

**Comment by skycoders** [comment]
as this is my first time ever, I hope this pull request is OK :)
