### ISSUE TITLE
add a general RGB LED library

### ISSUE THREAD

**Issue by skycoders** [nodemcu/nodemcu-firmware#1352]
### Missing feature

After working a lot with RGB LEDs together with NodeMCU, I was wondering if it makes sense and is of interest to create some native code LED library supporting cross-LED-type functionality. 
### Justification

There are several modules for digital RGB LEDs (tm1829,ws2801,ws2812) as well as the possibility to drive analog RGB LEDs with pwm. All of them need to do similiar stuff, especially color manipulation. For color fade or gradient effects, the HSV color model provides much easier ways than doing this in RGB space. Also keeping a color while completely dimming it down is not possible with RGB. Value conversion between HSV and RGB could be done in lua, but this is inherently inefficient. A LED library  module providing such things could help here. I have read that e.g. the [fastled.io](http://fastled.io/) library is successfully running on ESP8266 already, so maybe porting it or parts of it could do the job. I am only wondering how we can make it available natively within the single LED driver modules, because performing transformations native, returning all the values to lua and then sending them back to the LED module does not sound that great to me as well. 
One idea is to build a HSV-based buffer similar to the ws2812.buffer, but again, that would be limited to this one module.
### Workarounds

Do all the work in lua is possible, though probably inefficient and more memory consuming.

Any comments from the LED fans?

**Comment by eku** [comment]
https://github.com/FastLED/FastLED
https://github.com/patrickjahns/RGBWWLed
