### ISSUE TITLE
Feature Request: Date/time conversion for rtctime.get()

### ISSUE THREAD

**Issue by devsaurus** [nodemcu/nodemcu-firmware#1370]
### Missing feature
Conversion of a timestamp "seconds since Unix epoch" into calendar items year/month/day/hour/min/sec.

### Justification
Seconds since epoch can't be handled easily in a human readable way.

### Workarounds
Hour & second components can be calculated by simple formulas in Lua land. Date is more complex and less efficient but error prone.

### Proposal
A respective conversion routine (gmtime_r) is available from [dietlibc](http://www.fefe.de/dietlibc/) and I would add it with a Lua binding to the code base.
`tm = xxx.unix2date(stamp, timezone)`
Returns a table with entries
- `year`
- `month`
- `day`
- `hour`
- `minute`
- `second`

Should this function go into rtctime, node or a dedicated module?

**Comment by marcelstoer** [comment]
Only rtctime has a meaningful representation for "seconds since Unix epoch", right (unless queried from external service)? If so, then it should be added to that module IMO.

**Comment by pastukhov** [comment]
This issue has been discused here #603
