### ISSUE TITLE
before load init.lua all GPIO are OUTPUT HIGH

### ISSUE THREAD

**Issue by ozyart** [nodemcu/nodemcu-firmware#1375]
8<------------------------ BUG REPORT -----------------------------------------

Before init.lua load, all GPIO OUTPUT are HIGH.
I need all GPIO in LOW before load init.lua

I hope one solution, thanks

### NodeMCU version
NodeMCU 0.9.5 build 20150318  powered by Lua 5.1.4

### Hardware
ESP8266 12E

8<------------------------ END BUG REPORT -------------------------------------

**Comment by devsaurus** [comment]
My guess would be that all GPIOs power-up with their pull-up resistors enabled for safe operation. Even though GPIOs could be set to drive LOW quite early in the start-up process, there would be always this initial phase.

How long can your use case tolerate that all GPIOs are HIGH before they're driven LOW by software?

**Comment by ozyart** [comment]
I test it with diferent resistors and diodes.

When I turn the esp12 UP, All GPIO are HIGH during 1 second.
When read init.lua everyone go to LOW.
I need  this always start in LOW.



________________________________
De: Arnim Läuger <notifications@github.com>
Enviado: 27 de junho de 2016 21:04
Para: nodemcu/nodemcu-firmware
Cc: ozyart; Author
Assunto: Re: [nodemcu/nodemcu-firmware] before load init.lua all GPIO are OUTPUT HIGH (#1375)


My guess would be that all GPIOs power-up with their pull-up resistors enabled for safe operation. Even though GPIOs could be set to drive LOW quite early in the start-up process, there would be always this initial phase.

How long can your use case tolerate that all GPIOs are HIGH before they're driven LOW by software?

-

**Comment by ozyart** [comment]
I test it with diferent resistors and diodes. 

When I turn the esp12 UP, All GPIO are HIGH during 1 second. 
When read init.lua everyone go to LOW. 
I need  this always start in LOW.

**Comment by ozyart** [comment]
All GPIO load with 1.73V, and if I don't define GPIO to OUTPUT this doesn't go to 0V

**Comment by marcelstoer** [comment]
We had this a few times before e.g. #897. It's down to the hardware specs and the Espressif SDK. NodeMCU 0.9.x is no longer supported.

**Comment by ozyart** [comment]
how I resolve that?

**Comment by nickandrew** [comment]
Perhaps you could invert the logic in your hardware so starting high is OK.

**Comment by ozyart** [comment]
I will invert the logic with software, I go try this with C code

**Comment by ozyart** [comment]
last version work fine!

**Comment by SupotSaeEa** [comment]
Use last version 1.5.4.1. The problem still occurred.
