### ISSUE TITLE
Docs don't seem to state how to remove callbacks from net.socket()

### ISSUE THREAD

**Issue by jaggzh** [nodemcu/nodemcu-firmware#1382]
Prior to net.socket.close(), how can one remove a callback set with net.socket.on()?
I can examine the source to find out -- but I'm learning how to handle contributions / pull requests.

**Comment by devsaurus** [comment]
> how can one remove a callback set with net.socket.on()?

@jaggzh as far as I can see, there's no method to remove callbacks which were registered with `net.socket.on()`. They're implicitly unregistered when the socket object is reaped during automatic garbage collection.

You should see a respective effect with
```lua
sck:close()
sck = nil   -- allows garbage collection to delete the object
```

**Comment by marcelstoer** [comment]
IIRC some of our modules/methods allow you to pass `nil` for the callback to reset it. Assuming I understand `socket:on()` code correctly this won't work here, though.

**Comment by devsaurus** [comment]
> IIRC some of our modules/methods allow you to pass nil for the callback to reset it.

Agree, the logic in `socket:on()` will only allow to set a callback but not to unregister an existing one.

Is this a use case? It could be added without breaking backwards compatibility IMO.

**Comment by marcelstoer** [comment]
No feedback from the OP in a month -> closing.

**Comment by jaggzh** [comment]
Sorry, I didn't know there was a question for me.  I didn't understand, "is this a use case?"  It's just that I registered some debug info for the connection, but didn't want it on an ongoing basis; however, when trying to find how to un-register it, I found it didn't seem possible.

**Comment by jaggzh** [comment]
That is -- I didn't want to close the socket, and didn't want further connections to call my debug routine (and didn't want to register a separate dummy function to override it (if that works -- I've not checked if the events are added, or replaced).

**Comment by devsaurus** [comment]
I wanted to figure out whether the missing unregister restricts you and other users in using the `net` module.
Is it worth the effort to add a way to unregister callbacks or is it just nice to have?
