### ISSUE TITLE
TCP Server with SSL

### ISSUE THREAD

**Issue by jackasses** [nodemcu/nodemcu-firmware#1384]
The API from Espressif support a TCP-Server with SSL connection.

Is it possible or implemented to run this with nodemcu? 
I only see the options for the tcp-client.

**Comment by djphoenix** [comment]
espconn layer is deprecated since announce of ESP-32 and RTOS-SDK. After migration (and integration of `mbedtls`) this functionality may be provided.

**Comment by jackasses** [comment]
i found mbedtls that is working on the ESP-8266. The performance is not the best but i have to try it.

**Comment by tdotu** [comment]
so, does this mean that the non RTOS-SDK version of nodemcu-firmware is "depricated"?

**Comment by djphoenix** [comment]
Nope. Just espconn. Mbedtls can be used in NONOS SDK. But after first release of RTOS-based NodeMCU, NONOS versions will become outdated, so.

**Comment by georeb** [comment]
Are there any advances on this? @marcelstoer 
Including secure connections for net.createServer() is a very high priority in my opinion.
It would open up a whole new world of usage for the ESP!

**Comment by jmattsson** [comment]
There is a PR in the works to move the `net` module over to native lwIP, and after that I believe the plan is to switch over to mbedTLS to give us a newer/better SSL/TLS stack, which should hopefully allow us to do secure servers.

**Comment by smcmurray** [comment]
v2.0 doesn't seem to allow tls server. Am I misunderstanding the docs?

**Comment by HHHartmann** [comment]
It world be really great to have secured TCP comminucation from ESP8266 to ESP8266.
