### ISSUE TITLE
I want to make a hook to send an instruction or file to the nodemcu in a wireless way.

### ISSUE THREAD

**Issue by jack888yang** [nodemcu/nodemcu-firmware#1389]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
When the module is connected to the AP, I want to send an instruction or file to the nodemcu in a wireless way. So I have to find nodemcu debug io's throat, so that I can make a hook. Where is the throat? I need help. Thank you very much!
### Test code
Provide a minimal and isolated test which will reproduce the problem.
```Lua
-- add code here
```
### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.

8<------------------------ END BUG REPORT -------------------------------------

8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
https://nodemcu.readthedocs.io/en/latest/en/support/ -> closing.
