### ISSUE TITLE
builded  NodeMcu firmware with modules of http,mqtt,net,gpio,file,node,wifi,uart using custom build , After flashing the bin file to ESP-12E module using ESPFLASHER tool . after restarting the module contentiously giving below error message 

### ISSUE THREAD

**Issue by Anudeep09** [nodemcu/nodemcu-firmware#1393]
ets Jan 8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 28740, room 16 
tail 4
chksum 0xe7
load 0x3ffe8000, len 2888, room 4 
tail 4
chksum 0xd6
load 0x3ffe8b50, len 15536, room 4 
tail 12
chksum 0x39
csum 0x39
R	)DÐBÄPPŒ€I
øè - See more at: http://www.esp8266.com/viewtopic.php?f=23&t=6571#sthash.EPvpsZRS.dpuf

**Comment by marcelstoer** [comment]
This is not a support forum, see http://nodemcu.readthedocs.io/en/latest/en/support/.
