### ISSUE TITLE
string.format not working since 0127(float version)

### ISSUE THREAD

**Issue by nodemcu** [nodemcu/nodemcu-firmware#140]
from esp8266.com
```lua
t=1
= string.format("%i, ",t)
```

**Comment by nodemcu** [comment]
update, fixed.
pls test.

**Comment by unwin** [comment]
I think the behavior of string.format's handling of '-' has changed.  string.format("%-10s",k) produces 10s as output. Removing the '-' produces the contents of the string formatted to 10 spaces, right justified.

**Comment by dvv** [comment]
optimized printf in 0.9.5?

**Comment by vowstar** [comment]
Because SDK's printf not support floating number, we write one but not beautiful yet.

**Comment by vowstar** [comment]
![qq 20150212014623](https://cloud.githubusercontent.com/assets/394260/6152676/02aec992-b25a-11e4-9187-eecebf2cc6d5.png)

**Comment by GeoNomad** [comment]
Can you please try string.format("%-10s",'this')

That is the part that has been breaking LuaLoader's file.list and Survey buttons.

It has been printing 

-10s

Thanks.

**Comment by vowstar** [comment]
![qq 20150212105141](https://cloud.githubusercontent.com/assets/394260/6161000/627cf2d6-b2a5-11e4-930e-6b5da770c76e.png)
It out put this. Is it right?

**Comment by nodemcu** [comment]
I got this, I think it is right! well done
```lua
> i=-1
> =string.format("%-10f,end", i)
-1.000000 ,end
> =string.format("%-10d,end", i)
-1        ,end
>
```

**Comment by GeoNomad** [comment]
Yes, it is fixed. Thanks guys!
