### ISSUE TITLE
http: specified header does not override the default one

### ISSUE THREAD

**Issue by Arnie97** [nodemcu/nodemcu-firmware#1410]
### Version
Introduced in 88bae3e, first reported in #962.
`Connection` and `User-Agent` are hard-coded into `httpclient.c` (see [master](https://github.com/nodemcu/nodemcu-firmware/blob/master/app/http/httpclient.c#L203-L211), [dev](https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/http/httpclient.c#L204-L225)).
### Test code
```Lua
http.get(
    'http://httpbin.org/user-agent',
    'User-Agent: curl/7.49.1\r\n',
    function(status, body) print(body) end
)
```
### Expected behavior
```
{
  "user-agent": "curl/7.49.1"
}
```
### Actual behavior
```
{
  "user-agent": "ESP8266,curl/7.49.1"
}
```
### Work-around
Remove [`User-Agent` from `httpclient.c`](https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/http/httpclient.c#L207).

**Comment by marcelstoer** [comment]
I don't see why you'd want to override the host header.  After all it is derived from the HTTP URL the request is sent to.
