### ISSUE TITLE
Lua interpreter - Sqr() Function 

### ISSUE THREAD

**Issue by VictorDika** [nodemcu/nodemcu-firmware#1420]
Please add sqr function. Thxks
http://stackoverflow.com/questions/38558499/nodemcu-lua-sqr-function
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior

Sqr() function
### Actual behavior
not avaible
8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
As I said on SO, this is a dup of #1280.

**Comment by VictorDika** [comment]
Oh sry, thanks.
Have a nice day
