### ISSUE TITLE
Expose json

### ISSUE THREAD

**Issue by dvv** [nodemcu/nodemcu-firmware#144]
Please, consider exposing `str = json.stringify(tbl)` and `tbl = json.parse(str)`, or alike.
TIA

**Comment by vowstar** [comment]
Yes, with json, eveything comes easy.

**Comment by marcoskirsch** [comment]
There's plenty of example code floating around to go from lua table to JSON and back. Why not use that?

**Comment by dvv** [comment]
json stuff already in sdk, needs mostly only proper exposing

**Comment by pastukhov** [comment]
+1

**Comment by iMarvinS** [comment]
Is someone here able to expose the json API?

**Comment by alex-march** [comment]
Agree, would be a neat way to handle json in nodemcu, otherwise there are some lightweight options in pure lua.

**Comment by crapthings** [comment]
+1

**Comment by zhivko** [comment]
Would be nice to have json exposed as module.
Which existing module would be most apropriate candidate for rework, so we could have json module?

**Comment by nodemcu** [comment]
cjson ported to nodemcu, currently in json branch. please fork and test.
cjson manual is [here](https://github.com/mpx/lua-cjson).
and also download latest build for cjson to test [download](https://github.com/nodemcu/nodemcu-firmware/releases/latest), maybe need some time for travis-ci to build?

**Comment by dvv** [comment]
great!

**Comment by robotiko** [comment]
+1

**Comment by alex-march** [comment]
Good stuff, thank you!

**Comment by marcoskirsch** [comment]
It's great to have this. But some applications don't need JSON and the firmware as is makes for an extremely memory constrained environment. Please make it so it's easy to compile in/out based on a single #define. That request holds for most non essential functionality... thanks!

**Comment by dvv** [comment]
We should definitely stab the knife to exploring loadable c modules support.
This may be of concern even for intrinic bit/table modules.

**Comment by nodemcu** [comment]
@marcoskirsch 
[/app/include/user_modules.h](https://github.com/nodemcu/nodemcu-firmware/blob/json/app/include/user_modules.h)
one line #define for each module.
