### ISSUE TITLE
 HTTPS POST making no answer and returning -1 code

### ISSUE THREAD

**Issue by vcchm** [nodemcu/nodemcu-firmware#1440]
Trying to feed sensor data through JSON coded HTTPS POST request.
When i'm using HTTP it works perfectly, but when i'm turning to HTTPs i'm getting a -1 code
I have the same issue when i'm trying to build the request directly with net:socket - seems to be related with SSL/HTTPS implementation.

### Expected behavior
I'm expecting what i get with a http request using the code provided in the last section of this post

```
{
	"args": {},
	"data": "[{\"temp\":123},{\"ozone\":123},{\"light\":426426}]",
	"files": {},
	"form": {},
	"headers": {
		"Content-Length": "45",
		"Content-Type": "application/json",
		"Host": "httpbin.org",
		"User-Agent": "ESP8266"
	},
	"json": [{
		"temp": 123
	}, {
		"ozone": 123
	}, {
		"light": 426426
	}],
	"origin": "xxxxx",
	"url": "https://httpbin.org/post"
}
```

### Actual behavior
-1 error code

### Test code
```lua
temp=123
light=426
ozone=123
po_string='[{"temp":'..temp..'},{"ozone":'..ozone..'},{"light":'..light..'426}]'

http.post("https://httpbin.org/post",
  'Content-Type: application/json\r\n',
  po_string,
  function(code, data)
    if (code < 0) then
      print("HTTP request failed"..code)
    else
      print(code, data)
    end
  end)
```

### NodeMCU version
I used a custom-build firmware build yesterday using Marcel's online tool. I tried both master & dev, using http, crypt, net modules.

### Hardware
Wemos D1 mini. But again works perfectly with HTTP so dont think this is an hardware issue.

**Comment by marcelstoer** [comment]
We had this before, it's not a firmware bug. See http://nodemcu.readthedocs.io/en/latest/en/support/.
