### ISSUE TITLE
node.readvdd33() causes reboot while wifi is connected

### ISSUE THREAD

**Issue by Mehrius** [nodemcu/nodemcu-firmware#145]
Hello everybody,

My module reboots if I run node.readvdd33() while wifi is connected.
It runs fine when wifi is not connected.

Do any of you also have this problem?

**Comment by vowstar** [comment]
In sta mode when connect wifi it will reboot , in ap or stationap or not connect wifi it will have no problem. It is SDK 0.9.5's bug.

**Comment by Mehrius** [comment]
Thank you,

Not being nodeMCU related I guess I should close this issue.

**Comment by vowstar** [comment]
The 0.9.6_b1 SDK import a new API system_get_vdd33(), but it always return 65535.
May be espressif want fix it, we are waiting 0.9.6 finish beta.

**Comment by vowstar** [comment]
https://github.com/nodemcu/nodemcu-firmware/commit/fc8fa2cc915aea3687b068eb0355bb84b2fc113d
