### ISSUE TITLE
Enable TimeToLive for net/UDP 

### ISSUE THREAD

**Issue by mikep01** [nodemcu/nodemcu-firmware#1455]
8<------------------------ FEATURE REQUEST ------------------------------------
### Justification

TTL tells routers when to forward IP multicast packets.  A TTL of 0 or 1 restricts UDP to the same subnet; allowing a configurable TTL, or at least a value of 32 would support LUA apps running in on premise in more complicated networks.
Ref: [http://searchnetworking.techtarget.com/definition/time-to-live](url)
### Workarounds

Are there any workarounds you currently have in place because the feature is missing?
no

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by jmattsson** [comment]
This is something that could probably be done easily once we have the `net` module moved onto native LWIP (#1379), by adding a hook to adjust `udp_pcb->ttl`.
