### ISSUE TITLE
Unable to boot new Firmware

### ISSUE THREAD

**Issue by ludovicterrier** [nodemcu/nodemcu-firmware#1468]
Hello,

I'm unable to boot new firmware built from https://nodemcu-build.com/

The one built built on: 2016-07-09 08:33 works, but ones built today and yesterday don't. (I did many attempts with master/dev and 10, 11, 13, modules...)

I use esptool.py and I have no errors. But when I restart the module (Wemos D1 V2 or Huzzah Feather) the LED blinks very quickly. And that's all.

### NodeMCU version that's working
NodeMCU custom build by frightanic.com
        branch: master
        commit: b580bfe79e6e73020c2bd7cd92a6afe01a8bc867
        SSL: false
        modules: adc,bme280,file,gpio,mqtt,net,node,ow,pwm,tmr,uart,wifi,ws2812l.

### Hardware
Wemos D1 V2
& Huzzah Feather Adafruit

**Comment by hwmland** [comment]
Sounds like mantra: did you flash new esp_init_data_default.bin as well? See [http://nodemcu.readthedocs.io/en/master/en/flash/](url)

**Comment by marcelstoer** [comment]
See https://nodemcu.readthedocs.io/en/latest/en/support/ (also referenced on https://nodemcu-build.com/faq.php#get-help) and #1010.
