### ISSUE TITLE
String:format Floating point,  width.precision not working

### ISSUE THREAD

**Issue by Rotma** [nodemcu/nodemcu-firmware#148]
> t=2.345
> = string.format("%02f",t)
2.345
> = string.format("%02.2f",t)
2f
> = string.format("%02d",t)
02
>

**Comment by sej7278** [comment]
isn't this fixed since https://github.com/nodemcu/nodemcu-firmware/commit/1346cbbc38976ea49076755969710bfea75dbf55 ?

**Comment by Rotma** [comment]
Example was with build 20150126
Latest bin 20150127 string.format("%02f",t) returns nothing.

**Comment by vowstar** [comment]
![qq 20150212014623](https://cloud.githubusercontent.com/assets/394260/6152676/02aec992-b25a-11e4-9187-eecebf2cc6d5.png)

**Comment by willd** [comment]
Works like a charm, thanks!

**Comment by Rotma** [comment]
Still one small problem, %03.2f should produce 002.04... (preceding zero's) like %03d 
For the rest it's working ok.

NodeMCU 0.9.5 build 20150213  powered by Lua 5.1.4
> a=2.045
> print(string.format("%03.2f\n",a))
2.04
> print(string.format("%03d",a))
002

**Comment by TheoHarbers** [comment]
Not entirely true it should be:
> a=2.045
> print(string.format("%03.2f\n",a))
> 2.05

**Comment by vowstar** [comment]
Hi Rotma, it is not bug. please test it use C 's printf and read c99's field width definition of printf in floating case.
If you want 0.002.04, please use print(string.format("%06.2f\n",a))
![qq 20150215110431](https://cloud.githubusercontent.com/assets/394260/6201928/8e437c28-b502-11e4-8207-d44c2bbd733d.png)

**Comment by Rotma** [comment]
Vowstar, you are right my mistake.
But another thing i noticed  after the comment of Theo is that roundig up starts at 6.
This should be normally at 5 i tought.

> a=2.045
> b=2.046
> print(string.format("%05.2f - %05.2f",a,b))

02.04 - 02.05

**Comment by vowstar** [comment]
I think it is not an error.
"For the GNU C library, the rounding rule used by printf() is "bankers rounding" or "round to even". This is more correct than some other C libraries, as the C99 specification says that conversion to decimal should use the currently selected IEEE rounding mode (default bankers rounding)."
See also:
http://stackoverflow.com/questions/10357192/printf-rounding-behavior-for-doubles
http://linuxgazette.net/144/misc/lg/a_question_of_rounding_in_issue_143.html
http://www.gnu.org/software/libc/manual/html_node/Rounding.html
And  "bankers rounding" or "round to even" in Wikipedia:
http://en.wikipedia.org/wiki/Rounding
Please read it carefully.

The result on build 20150213 NodeMCU:
![lua-nodemcu](https://cloud.githubusercontent.com/assets/394260/6206479/d00f09d8-b5c5-11e4-9588-b37aecbab387.PNG)

I have tested this behavior on my debian sid, it have same results:
![lua-rouding](https://cloud.githubusercontent.com/assets/394260/6206474/a36cd572-b5c5-11e4-83ed-15a6ab921fb7.png)

I have tested this behavior on my centos, it have same results:
![lua-centos](https://cloud.githubusercontent.com/assets/394260/6206483/ea254b16-b5c5-11e4-957b-7ddab3f3b19b.PNG)

```
> a=2.045
> print(string.format("%05.2f",a))
02.04
> a=2.055
> print(string.format("%05.2f",a))
02.06
>
```
