### ISSUE TITLE
Doc link for master points to dev.

### ISSUE THREAD

**Issue by devsaurus** [nodemcu/nodemcu-firmware#1490]
### Expected behavior 
Link in master's README.md points to docs consistent with master branch.

### Actual behavior
Link points to latest which shows dev-related content atm. Eg. the new sdcard chapter.
I thought up to now that latest is an alias for master, but apparently not.

### NodeMCU version
Current repo.

**Comment by marcelstoer** [comment]
`latest` is an alias for `dev`. The default, however, is `master`.
- http://nodemcu.readthedocs.io/ -> master
- http://nodemcu.readthedocs.io/en/latest/ -> dev
- the rest is obvious
Invalid or misleading internal links such as "Edit on GitHub" are bugs with either MkDocs or Read the Docs.

**Comment by marcelstoer** [comment]
`latest` is an alias for `dev`. The default, however, is `master`.
- http://nodemcu.readthedocs.io/ -> master
- http://nodemcu.readthedocs.io/en/latest/ -> dev
- the rest is obvious
Invalid or misleading internal links such as "Edit on GitHub" are bugs with either MkDocs or Read the Docs.

**Comment by marcelstoer** [comment]
`latest` is an alias for `dev`. The default, however, is `master`.
- http://nodemcu.readthedocs.io/ -> master
- http://nodemcu.readthedocs.io/en/latest/ -> dev
- the rest is obvious
Invalid or misleading internal links such as "Edit on GitHub" are bugs with either MkDocs or Read the Docs.

**Comment by devsaurus** [comment]
> Alternatives?

Would an intended & static difference in `README.md` on the two branches be enough? Or does this generate merge conflicts?

**Comment by marcelstoer** [comment]
I could live with that if there actually _were_ merge conflicts 😉 It would remind us at every master drop that we need to keep the URLs different. What I'm worried about is a silent merge/replacement. However, it'd be worth a try. Can't be worse than the status quo.
