### ISSUE TITLE
float exponentiation of negative values gives wrong result

### ISSUE THREAD

**Issue by sibbi77** [nodemcu/nodemcu-firmware#1491]
### Expected behavior
(-0.5)^3 should result in -0.125

### Actual behavior
(-0.5)^3 results in +0.125

### Test code
```Lua
=(-0.5)^3
=(-0.5)*(-0.5)*(-0.5)
```
### NodeMCU version
branch: master
commit: 95e85c74e7310a595aa6bd57dbbc69ec3516e9c6
powered by Lua 5.1.4 on SDK 1.5.4.1(39cb9a32)

### Hardware
NodeMCU v2 - Lua based ESP8266

**Comment by devsaurus** [comment]
Same result here on a float build from `dev`.

**Comment by luismfonseca** [comment]
More data (float build from `dev`):

```
> = -0.5 ^ 3
-0.125
> = (-0.5) ^ 3
0.125
```

**Comment by luismfonseca** [comment]
Ok, I've found the problem.

I'll make a MR with my attempt to fix it.

**Comment by devsaurus** [comment]
Fix was merged to `dev`.
