### ISSUE TITLE
FR Please add ucglib font selector to nodemcu cloud builder

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#1493]
### Justification
Please add font selector similar to u8glib

**Comment by marcelstoer** [comment]
- The cloud builder is my private project, unrelated to the NodeMCU team. -> closing
- There are only a total of 8 fonts available anyway: https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/include/ucg_config.h
- I have currently no intention to build  selector for those.
