### ISSUE TITLE
Dump the stack on exception in DEVELOP_VERSION

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#1495]
### Missing feature

When DEVELOP_VERSION is enabled, the firmware should dump out the contents of the stack on an exception (rather than just restarting the platform).
### Justification

This will make debugging much easier. The ESP8266 version of the Arduino code has this capability (https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_esp8266_postmortem.c) but it looks as though it needs lots of other components as well.....
### Workarounds

Nope. I'm beating my head against a brick wall. It is nice when I stop.

**Comment by jmattsson** [comment]
Looks like it's relying on some of the gdb_stub stuff?

Also, the stack frame decoding looks rather primitive, but I guess that's a lot better than what we currently have!

**Comment by pjsg** [comment]
Maybe I should just integrate https://github.com/espressif/esp-gdbstub first (obviously under a config define). Thoughts? Or has someone else already done it?

**Comment by pjsg** [comment]
See #1505 to integrate the gdbstub....
