### ISSUE TITLE
Documentation for RC module missing

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1498]
RC is still the only module [w/o proper documentation](http://nodemcu.readthedocs.io/en/latest/en/modules/rc/). @mikewen can we ask you to document the module and its `send` function in https://github.com/nodemcu/nodemcu-firmware/blob/dev/docs/en/modules/rc.md.

**Comment by sonaux** [comment]
This module has same functionality as rfswitch module. I made simple documentation page, but does this module is even needed?
