### ISSUE TITLE
Feature Request: mDNS

### ISSUE THREAD

**Issue by dereulenspiegel** [nodemcu/nodemcu-firmware#150]
Hello,

nodeMCU is a great firmware to quickly realize small IoT projects. To make this even easier it would be nice to be able to respond to mDNS requests, so we can discover nodeMCU devices in the network.

**Comment by ersinpw** [comment]
I totally agree

**Comment by sej7278** [comment]
i'd certainly want an option to disable this if someone does implement it, yuck multicast!

**Comment by dereulenspiegel** [comment]
I would have expected that this is a feature which can enabled and disabled via the user_config.h or has to be explicitly called via a LUA API call and if you don't call this API the node doesn't react to multicast packages.
It would also be nice to be able to announce services and not only an A record, so protocol and port can be discovered.

**Comment by mkarliner** [comment]
+1 from me, although I'm still learning about zeroconf
Looking at the last couple of days of issues, with lots
of conversations about features, a good config system
would seem to be a good idea, so we can all build our
own 'perfect' nodemcu

**Comment by sej7278** [comment]
@mkarliner you bring up a good point, all of these macro's should really be compile-time flags in the Makefile, so we don't have to edit a bunch of header files

**Comment by morlac** [comment]
+1

**Comment by pastukhov** [comment]
Any news?

**Comment by LucasG2000** [comment]
+1

**Comment by rolimat** [comment]
+1

**Comment by marcelstoer** [comment]
> a good config system would seem to be a good idea, so we can all build our own 'perfect' nodemcu

@mkarliner I developed http://frightanic.com/nodemcu-custom-build/ for that. It might be useful for your needs, too.

**Comment by aguaviva** [comment]
any updates on this one?

**Comment by saeugetier** [comment]
Issue is still open. Is there any progress implementing mDNS for nodemcu?

**Comment by DesperateProgrammer** [comment]
I am working on a user module for mDNS/Bonjour/ZeroConf welk at least in my sparse sparetime.

Progress can ne found at http://desperate-programmers.com/2016/01/24/name-resolving-demo-mdns-reponder/

When the LUA Interface is set i'll try to get it into this git (dont know git as much as svn yet.

**Comment by saeugetier** [comment]
Thanks. I ported your bonjour.c into my fork of nodemcu. It is working now...

**Comment by pjsg** [comment]
I have a mdns lua module that acts as a server and can advertise the name of the board and a single service. Needs a bit more testing, but appears to work.

I'll submit a PR in the next couple of days.   

The documentation is at https://github.com/pjsg/nodemcu-firmware/blob/mdns/docs/en/modules/mdns.md -- let me know if it does what you need. This is a pretty thin layer over the Espressif provided mdns implementation, so there is not a lot of room for enhancement without significant work. However it does provide the basic capabilities.

**Comment by pjsg** [comment]
I've submitted PR #988 to provide this implementation.

**Comment by ersinpw** [comment]
@pjsg thanks!

**Comment by pjsg** [comment]
This has now been merged and is now in the dev branch.
