### ISSUE TITLE
device not connect to esp8266 in ap mode while running while loop

### ISSUE THREAD

**Issue by rinturaj** [nodemcu/nodemcu-firmware#1512]
wifi.setmode(wifi.SOFTAP)
	-----------------------------------------------------------------------------
	print("Starting Web Server...")
	-- Create a server object with 30 second timeout
	srv = net.createServer(net.TCP, 80)

	-- server listen on 80, 
		srv:listen ( 80,function(conn) 
		conn:on( "receive",function(conn,payload)
			if(receive_flag ~= true ) then
				decode(payload)
				conn:send(ack_data)
				ack_data="nope";
			else
				
				file.open("frame/data.rin","w")
				file.writeline(payload);
				file.close();
				conn:send("FR complete");
				receive_flag = false;
			end
		end)     
	end)

 while true do
     
      file.open("frame/data.rin","r")
      file.readline();
      file.close();
      if(new == true ) then
      --print("r")

            todmd();  --
        
     else
      gpio_toggle(j)
        if(j==3)then
            j=0;
            
            if(c==60) then
            c=0;
            new = true;
            else
            c=c+4;
            end
        else
         j=j+1;
        end  
      end
      tmr.wdclr()
end
function todmd() 

        for row=0,3,1 do
                  gpio_toggle(row)
                  spi.send(1,0xf0,0xf0,0xf0,0xf0,0xf0,0xf1,0xf1,0xf1,0xf1,0xf1,0xf1,0xf1,0xf1,0xf1,0xf1,0xf1)
                  gpio.write(6, gpio.LOW) 
                  gpio.write(6, gpio.HIGH)
                  gpio.write(6, gpio.LOW) 
                  tmr.wdclr()

        end
end
while running the above code the mobile not connected to esp8266  ,when i remove the while loop
there is no problem to connect devices. what is the actual problem here i cant fix it ,i try different firmware but the result is same. any solution to solve this

**Comment by marcelstoer** [comment]
See #1010 and http://nodemcu.readthedocs.io/en/latest/en/support/.
