### ISSUE TITLE
how to enabled by setting WIFI_SMART_ENABLE in user_config.h 

### ISSUE THREAD

**Issue by jackccchen1** [nodemcu/nodemcu-firmware#1542]
i want to use wifi.startsmart but the note told that must set enable .but what can i do after open and firmware

**Comment by jackccchen1** [comment]
who can i help me please......very thankssss

**Comment by antal0126** [comment]
you'd better build the firmware yourself with "#define WIFI_SMART_ENABLE" line uncomment in user_config.h, see https://nodemcu.readthedocs.io/en/master/en/build/

**Comment by marcelstoer** [comment]
See #1010.
