### ISSUE TITLE
gpio.trig() not same performance as doc

### ISSUE THREAD

**Issue by trailsandtribulations** [nodemcu/nodemcu-firmware#1544]
### Expected behavior
gpio.trig( 8, 'both' ) would remove trigger for 'both' if exists 

### Actual behavior
gpio.trig( 8, 'both' ) raises error

### Test code
```Lua
gpio.mode( 8, gpio.INT )
gpio.trig( 8 )          -- this works
gpio.trig( 8, 'both' )  -- this bombs
-- ERROR: stdin:1: bad argument #3 to 'trig' (invalid callback type)s
```

**Comment by marcelstoer** [comment]
Our GitHub issues template asks you to provide the NodeMCU version you use. Which one is it?

Does it work if you leave out the first `gpio.trig` call?

```lua
gpio.mode( 8, gpio.INT )
gpio.trig( 8, 'both' )  -- what happens?
```

**Comment by pjsg** [comment]
The documentation seems to indicate that 

```
gpio.trig(8, 'both')
```

should enable both interrupts on pin 8 using the previously specified callback, The error indicates that there is no previously specified callback.

If you want to clear the interrupt, then you do

```
gpio.trig(8)
```

I think that the behaviour is 'works as designed'

**Comment by marcelstoer** [comment]
Philip's right, sorry I missed it.

> `type`: If the type is "none" or omitted then the callback function is removed and the interrupt is disabled.

> `callback`: The previous callback function will be used if the function is omitted.

**Comment by trailsandtribulations** [comment]
> =node.info()
1 5 4 2358765 1458415 4096 2 40000000

interesting:
> gpio.mode( 8, gpio.INT )
> gpio.trig( 8, 'both' )  => OK
> gpio.trig( 8 ) => OK
> gpio.trig( 8, 'both' ) => ERROR bad arg #3
