### ISSUE TITLE
rtcmem cannot be included to firmware using NodeMCU custom builds service

### ISSUE THREAD

**Issue by alexgts** [nodemcu/nodemcu-firmware#1547]
### Actual behavior
The module RTCMEM missed in [NodeMCU custom builds service](https://nodemcu-build.com/index.php)
Tested 3 times with different packages (including rtcmem)

### Test code
```Lua
require("rtcmem")
```
### Result
```Lua
lua: init.lua:2: module 'rtcmem' not found:
	no field package.preload['rtcmem']
	no file 'rtcmem.lc'
	no file 'rtcmem.lua'

```

### NodeMCU version
NodeMCU 0.9.5 build 20150318  powered by Lua 5.1.4
> You successfully commissioned a NodeMCU custom build from the master branch. You selected the following 8 modules: adc file gpio node rtcmem tmr uart wifi.

`=node.info()
0	9	5	357502	1458400	4096	2	40000000
`

### Hardware
Wemos D1 mini 4 MB flash

**Comment by devsaurus** [comment]
> NodeMCU 0.9.5 build 20150318 powered by Lua 5.1.4

Version 0.9.5 didn't contain `rtcmem` module, thus the error message. You obviously did not flash the image from custom build service. A successful upgrade reports version `NodeMCU 1.5.4.1`.
