### ISSUE TITLE
WPS support

### ISSUE THREAD

**Issue by ksrm** [nodemcu/nodemcu-firmware#1556]
Is there any plan to add support for WPS (auth via button)? This is crucial for applications where you have no other method of getting an SSID/password onto a device, so I am a little bit surprised that there is no support for it. The ESP8266 Arduino core (https://github.com/esp8266/Arduino) has support for it.

If nobody else is working on this I will make a start, but I'm interested to know if there is some reason that this hasn't been added yet.

**Comment by karrots** [comment]
I can't speak for official reasons but [end user setup](https://nodemcu.readthedocs.io/en/master/en/modules/enduser-setup/) is one way to get an SSID programmed into a device without using WPS.

Additionally, WPS is [severely broken](https://www.us-cert.gov/ncas/alerts/TA12-006A) from a security perspective.

**Comment by marcelstoer** [comment]
Even if we wanted to support WPS, there are good reasons not to (https://github.com/nodemcu/nodemcu-firmware/issues/778#issuecomment-158203376), I feel the support should be in the Espressif SDK.
