### ISSUE TITLE
Why is the U8G reference for SSD1306 128x32 missing in u8g_config.h

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1567]
There's no mention of [SSD1306 128x32](https://github.com/olikraus/u8glib/wiki/device#ssd1306-128x32) in [`u8g_config.h`](https://github.com/nodemcu/nodemcu-firmware/blob/master/app/include/u8g_config.h) but the driver seems to be there: `app/u8glib/u8g_dev_ssd1306_128x32.c`.

Is this an oversight or missing on purpose?

**Comment by devsaurus** [comment]
Hm, there's no good reason why it's not in - it was probably just forgotten.

**Comment by marcelstoer** [comment]
Do you have time to create a PR for that?
