### ISSUE TITLE
ds18b20 module can't get negative temperature.

### ISSUE THREAD

**Issue by vowstar** [nodemcu/nodemcu-firmware#157]
ds18b20 module can't get negative temperature, need to fix it.

**Comment by dvv** [comment]
-- kinda so, may be can be redone in pure arithmetics
if bit.isset(t, 15) then
  t = bit.bxor(t, 0xffff) + 1
end

**Comment by sej7278** [comment]
isn't this fixed now since https://github.com/nodemcu/nodemcu-firmware/commit/169699b93acf37ac2f486dd3acadc3fb85b6c881 ?

**Comment by TheoHarbers** [comment]
I am using this to get the right negative values:

if bit.isset(t, 15) then t = 0 - (bit.bxor(t, 0xffff) + 1) end

**Comment by nodemcu** [comment]
ref #222
