### ISSUE TITLE
Add support to ws2812.buffer to allow mixing...

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#1574]
### Missing feature

Easier operations on ws2812 buffers -- such as mixing
### Justification

In lighting, you often want to crossfade from one lighting setup to another. Having a builtin function can make this very efficient.
### Workarounds

No.

**Comment by pjsg** [comment]
This was the result

![image](https://cloud.githubusercontent.com/assets/1508813/20030570/58793c3c-a33e-11e6-9f1d-46730f8d390e.png)

It was a glowing orb that presented network security data -- animated.

**Comment by marcelstoer** [comment]
Woah, impressive! If you find the time to write up the details somewhere please share that with us.
