### ISSUE TITLE
showing a QR code on OLED screen? 

### ISSUE THREAD

**Issue by helxsz** [nodemcu/nodemcu-firmware#1600]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
showing a QR code on the OLED screen.

just see a project [ESP8266 Nodemcu ](https://github.com/anunpanya/ESP8266_QRcode), wonder can we modify it to be a nodemcu package? 

### Justification
Tell us why you would like to see this feature added.

The QR code is a interesting feature to link the device with the mobile application. 

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
QRcode would be nice but it falls under item 2 of #1010 -> closing. A workaround could be to do [QRcode handling in Lua](https://speedata.github.io/luaqrcode/).
