### ISSUE TITLE
Switch to Espressif's new download center

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1604]
Espressif created a new "download center" at https://espressif.com/en/support/download/sdks-demos a while ago. While the old BBS file hosting still works, you don't even get a redirect response, it's my understanding that we should probably adjust our setup and fetch SDKs from the new location.

At the moment http://bbs.espressif.com/download/file.php?id=1572 and https://espressif.com/sites/default/files/sdks/esp8266_nonos_sdk_v1.5.4.1_patch_20160704.zip return the same file. Switching to the new URLs will also allow us to get rid off `SDK_FILE_ID` and `SDK_PATCH_ID` in `Makefile`.

**Comment by djphoenix** [comment]
Done in `sdk200` branch.
