### ISSUE TITLE
How is the Lua C integration of the current apps done? 

### ISSUE THREAD

**Issue by joakimeriksson** [nodemcu/nodemcu-firmware#1607]
### Missing feature
Documentation on how to add a C-module - or rather some examples of how the current apps are integrated into LuA. How do Lua understand how to use CoAP? I did not find any Lua binding information in the CoAP code - just some bits and pieces in endpoint.c but nothing else. Is there more
files that are not part of the app directory or is there a magic auto-wrapper that does it?

### Justification
I am considering to add some of our app from Contiki OS into NodeMCU such as LWM2M client and I feel that I need to understand this better first.

**Comment by marcelstoer** [comment]
We have some information in https://github.com/nodemcu/nodemcu-firmware/wiki/%5BDRAFT%5D-How-to-write-a-C-module

**Comment by joakimeriksson** [comment]
Yes I did read that one and then I tried to use that knowledge to figure out how for example the CoAP module was supported in Lua - but I did fail to find the binding information in the coap code. Is it developed in the same way or is there another principle that was used for the coap app?

**Comment by marcelstoer** [comment]
Not sure I can really help you as I'm not a firmware programmer but I'll try anyway. The Lua binding is in [`/app/modules/coap.c`](https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/coap.c). The heavy-lifting is done in [`/app/coap`](https://github.com/nodemcu/nodemcu-firmware/tree/master/app/coap). Lots of modules have their own subfolder in `/app` and then refer to that from within `/app/modules/<module>.c`.

**Comment by joakimeriksson** [comment]
Yes, that is absolutely the help I needed - I was obviously a bit blind! Thanks!
