### ISSUE TITLE
[feature] raw spi slave mode

### ISSUE THREAD

**Issue by aep** [nodemcu/nodemcu-firmware#161]
current spi slave mode appears to require using the obscure 'command phase' and 'address phase'. there is no way to just transfer raw bytes full duplex as most applications would require.

What i figured out so far is that you can switch off all the phases, except 'address phase'. It will ignore the flag and still eat the first byte into SPI_ADDR.  At least that way there is a way to do up to 24 bits of raw mosi, but no miso, since the miso line is dead during 'address phase'.

**Comment by devsaurus** [comment]
SPI slave mode is not supported at the moment and there's no indication that it will change sometime soon. Closed per #719.
