### ISSUE TITLE
ESP32: improve node module

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#1614]
**Rationale:**
The `node` module lacks some things, such as reset reason and output redirection.

Note that `node.restore()` should *not* be reintroduced, as in the IDF the corresponding action is a WiFi-only restore, so if anything it should go into the wifi module.

`node.osprint()` should probably be moved into its own `log` module, and expanded to match the features provided by the IDF logging framework.

**Priority:** Low/Medium

**Dependencies:**
  - CPU over-/under-clocking not yet supported by the IDF.

**Comment by mdeneen** [comment]
Is there any desire to maintain compatibility with the esp8266's node.bootreason() ?  Would reset reason and wakeup reason be good enough?

It looks like this information is available from the RTC peripheral and could easily be mapped into the node module.  However, there is some added complexity given that there can be a reset reason _per cpu_.  Thoughts?
