### ISSUE TITLE
ESP32: spi module

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#1617]
**Rationale:**
We need to support the SPI bus(es). Hoping @devsaurus might sign on for this ;)

- [ ] Basic SPI bus support.
- [ ] SPI DMA support.

**Priority:**
  - High for basic support
  - Low for DMA version?

**Dependencies:**
  - IDF 1.0 released. SPI driver released (last comment from Espressif was that this wouldn't make it into the 1.0 release).

---

### spi.master(bus, config)
Initializes a bus in master mode.
- `bus` id, one of
  - `spi.SPI1`, not supported by driver
  - `spi.HSPI`
  - `spi.VSPI`
- `config` table listing the assigned GPIOs. All signal assignment are optional.
  - `sclk`
  - `mosi`
  - `miso`
  - `quadwp`
  - `quadhd`

Returns an SPI master object.

### spi.master:device(config)
Adds a device on the given master bus. Up to three devices per bus are supported.
`config` table describing the device parameters.
- `cs` GPIO connected to device's chip-select pin, mandatory
- `mode` SPI mode used for this device (0-3), mandatory
- `freq` clock frequency used for this device [Hz], mandatory
- `command_bits` amount of bits in command phase (0-16), defaults to 0 if omitted
- `address_bits` amount of bits in address phase (0-64), defaults to 0 if omitted
- `dummy_bits` amount of dummy bits to insert address and data phase, defaults to 0 if omitted
- `cs_ena_pretrans`, optional
- `cs_ena_posttrans`, optional
- `duty_cycle_pos`, optional
- `tx_lsb_first` transmit command/address/data LSB first if `true`, MSB first otherwise
- `rx_lsb_first` receive data LSB first if `true`, MSB first otherwise
- `wire3` use spiq for both transmit and receive if `true`, use mosi and miso otherwise
- `positive_cs` chip-select is active high during a transaction if `true`, cs is active low otherwise
- `halfduplex` transmit data before receiving data if `true`, transmit and receive simultaneously otherwise
- `clk_as_cs` output clock on cs line when cs is active if `true`

Returns an SPI device object.

### spi.master():device():transaction(trans)
Initiate an SPI transaction consisting of
1. assertion of cs signal
2. optional sending of command bits
3. optional sending of address bits
4. optional sending of dummy bits
5. sending of tx data
6. concurrent or appended reception of rx data, optional
7. de-assertion of cs signal

`trans` table containing the elements of the transaction:
- `command` data for command phase, amount of bits was defined during device creation, optional
- `address` data for address phase, amount of bits was defined during device creation, optional
- `txdata` string of data to be sent to the device
- `rxlen` number of bytes to be received, optional
- `mode` optional, one of
  - `sio` transmit in SIO mode, default if omitted
  - `dio` transmit in DIO mode
  - `qio` transmit in QIO mode
- `addr_mode` transmit address also in selected `mode` if `true`, transmit address in SIO otherwise.

Returns string of `rxlen` bytes, or `#txdata` bytes if `rxlen` omitted.

---

### spi.slave(bus, config)
Initializes a bus in slave mode.
- `bus` id, one of
  - `spi.SPI1`, not supported by driver
  - `spi.HSPI`
  - `spi.VSPI`
- `config` configuration table for the slave device:
  - `sclk` gpio number, optional
  - `mosi` gpio number, optional
  - `miso` gpio number, optional
  - `cs` GPIO connected to ESP's chip-select pin, mandatory
  - `mode` SPI mode used for this device (0-3), mandatory
  - `tx_lsb_first` transmit command/address/data LSB first if `true`, MSB first otherwise
  - `rx_lsb_first` receive data LSB first if `true`, MSB first otherwise

Returns an SPI slave object.

### spi.slave():on(event[, cb_fn])
Registers or unregisters an event callback handler.
- `event` one of
  - "receive" data received from master
- `cb_fn(err, data)` function to be called when data was received from the master. Unregisters previous callback for `event` when omitted.

### spi.slave():send(data1[, data2[, ..., datan]])
Writes send data for the master into the transmit buffer. This function returns immediately if there's enough room left in the buffer. It blocks if the buffer is doesn't provide enough space.

Data items can be multiple numbers, strings or lua tables.

**Comment by devsaurus** [comment]
I'd be on board, for sure 👍
Though the lack of ESP32 hardware will be blocking any heavy duty work for (quite) some time.

**Comment by devsaurus** [comment]
I've started to sketch an API description in the original post. ATM this seems to evolve closely along the IDF concept, meaning:
- host/bus configuration with `spi.init(bus, bus_config)`
- add up to 3 devices to a bus with `spidev = spi.device(bus, dev_config)`
- run transactions on a device with `spidev:transaction()`

Transactions are synchronous by default in the basic implementation. Asynchronous operation can be added later by means of an optional callback (DMA is used by the driver in any case).

This is quite different from the Lua API on esp8266 and I tend to *not* be compatible with that but focus on exposing all of the hardware/driver functionality instead. I expect that backward compatibility can be retro-fitted with a Lua module up to a basic extent (to be proven).

Everybody feel free to feed back.

**Comment by devsaurus** [comment]
Updated API to support SPI slave mode with latest esp-idf.

**Comment by devsaurus** [comment]
Implementation started @ https://github.com/devsaurus/nodemcu-firmware/tree/esp32-spi.

**Comment by devsaurus** [comment]
I've pushed initial SPI master support to `dev-esp32` branch (819284530e550d5343e6a0f9dd9bdd607c911299). Slave mode to follow.
NB there are 2 pending issues with the underlying IDF driver: Espressif/esp-idf#574 and Espressif/esp-idf#598.

**Comment by devsaurus** [comment]
Closing this. SPI slave functionality should be handled as a new issue.
