### ISSUE TITLE
ESP32: [wall]clock module

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#1620]
**Rationale:**
The ESP32 finally has the capability of keeping wallclock/real time, even when deep sleeping. The IDF provides wallclock time access via the standard C interface `[gs]ettimeofday()`. This should be exposed in some user-friendly manner. If we're feeling particularly brave, we could even pull in timezone data... Or, we could just stick with UTC and save our sanity.

- [ ] Implement basic get/set time function.
- [ ] Implement `gmtime()` access for nice, easy (but UTC-only) calendar info.
- [ ] Implement timezone support and `localtime()` access.

**Priority:** Medium/Low

**Dependencies:**
None?

**Comment by djphoenix** [comment]
I think this should be in both 8266 and 32 branches. About local times, I propose to just expose `[gs]ettimezone` to userspace, I think this is enough for most cases. TimeZone database is very huge for controllers.

**Comment by igrr** [comment]
I was thinking that could add an option to bundle (limited amount of) timezone data with the firmware. Selection could be done in menuconfig, for instance. Oddly enough, I haven't found an existing way to convert entries from tzdata database into the [TZ variable format](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html).

**Comment by pjsg** [comment]
In my app, I have some lua code that handles the binary timezone files. In my case, I just upload the single required file (and call it "timezone") and then it just works.

**Comment by LDmitryL** [comment]
@jmattsson There is progress in the development module?

**Comment by jmattsson** [comment]
Alas, no progress on my end - work has me off on two different projects that aren't ESP32 related :(

**Comment by HHHartmann** [comment]
Seems to be fixed already

**Comment by HHHartmann** [comment]
Seems to be fixed already
