### ISSUE TITLE
ESP32: tls module

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#1622]
**Rationale:**
The IDF comes with mbedTLS included out of the box, and we should be making use of it. The old espconn stuff is not supported (though it *might* be in the future). Either way, we should be including @djphoenix's work/planned-work on the `tls` module. 

Given the resources available on the ESP32, we should aim at making the `tls` module do the right/most-secure thing by default, and making it easy to do so. All certs should be possible to pass via filename reference, and file access via standard C API (not our old VFS).

For NodeMCU32 I'd be tempted to not provide any hooks in the `net` module for "secure" connections, as they're really not secure without setting up at least CA verification first.

- [ ] `tls` module basics matching `net` where possible
- [ ] CA verification
- [ ] Client authentication via cert

**Priority:** High

**Dependencies:**
  - Main filesystem changed to use IDF VFS (see #1613)

**Comment by djphoenix** [comment]
Thumbs up for all of this.
Unfortunately I haven't ESP32 module right now, so code support may be provided only for ESP8266-branch. Of course, it *may* be portable at most.

About TLS module - it should be limited to secure connections (and similar stuff), but I also will work on crypto module to add most of mbedTLS stuff to lua-level.

Also, about verification - I prefer public-key-based certificate verification, so I also will work on common routines for it. But CA is first (and simpliest) way.

All TLS things are depends (for me) at SDK2.0 and LWIP patches on 8266 branch.
