### ISSUE TITLE
bme280.init() is ambiguous

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#1631]
### Missing feature
`bme280.init()` initialises the driver and the chip. We need to separate the two actions.

### Justification
In a battery operated setup the esp deep sleeps and on wakeup needs to initialise the driver (the `bme280.c` module). The chip was kept powered (sleeping too) and is holding the latest reading that should be fetched quickly before another reading starts in the background (`bme280.startreadout()`).

A chip init is not required and actually is detrimental in this context (which I consider common use).

### Workarounds
As always I can fiddle with the module and add an option to the `init()` routine to indicate if the chip needs to be initialised too.

**Comment by vsky279** [comment]
When coding the module I have not thought about optimizing it for battery usage. But I agree it makes sense to do it.
I would suggest to add another optional parameter `cold_start` to `bme280.init()` which would be `true` by default. When `false` it would skip the unnecessary parts of the code.
