### ISSUE TITLE
bug in bme280.c

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#1636]
When converting the module to use i2c bust reads I noticed a mismatch from the doco in `bme280_lua_init()`.
I wonder if the doco is known to be wrong? After all a bad extraction of the parameters should produce wrong result from `bme280_compensate_H()` and I did not see a complaint.
### Expected behavior
The data-sheet says (**6.2.2 Trimming parameter readout**)
```
0xE4 / 0xE5[3:0]  -> dig_H4 [11:4] / [3:0]  signed short
0xE5[7:4] / 0xE6  -> dig_H5 [3:0] / [11:4]  signed short
0xE7              -> dig_H6                 signed char
```
### Actual behavior
The code for extracting the humidity parameters  does
```
bme280_data.dig_H4 = ((int16_t)r8u(reg) << 4 | (r8u(reg+1) & 0xF)); reg+=2;
bme280_data.dig_H5 = ((int16_t)r8u(reg+1) << 4 | (r8u(reg) >> 4)); reg+=2; 
bme280_data.dig_H6 = (int8_t)r8u(reg);
```
Note the `reg+=2` after extracting `H4`. `0xE5` should be split between `H4` and `H5`. The current code seems to extract `H5` from `0xE7/0xE6` then `H6` from `0xE8` (out of range). A `++reg` should be done instead.
Do I read this correctly? I am looking at the doco from Bosch dated
```
BME280: Final data sheet
Document revision            1.2
Document release date        October 26th, 2015
Document number              BST-BME280-DS001-11
Technical reference code(s)  0 273 141 185
```
### Test code
None, this is what I find looking at the code.
### NodeMCU version
Latest dev branch
### Hardware
None, this is what I find looking at the code.
### Notes
[Here](http://members.iinet.net.au/~eyaleb/bme280.c) is a version of `bme280` where I changed:
1 - Fixed the above bug
2 - improved registers read by using burst more
3 - Added `bme280_lua_read()` to efficiently read `T, P & H` (and optionally return QNH) in one call.

**Comment by vsky279** [comment]
Thanks for spotting this bug. I have posted a PR https://github.com/nodemcu/nodemcu-firmware/pull/1652 to fix it based on your suggestion.

Please give me more time to study your other suggestions.
