### ISSUE TITLE
FR: add  ability to store custom configs  to enduser setup

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#1650]
### Missing feature
Neduser setup is able to use custom html page, but not able to store anything, except SSID and password.
### Justification
The idea is: to be able to store additional fields of eunduser setup form. For example with wifi_ssid=blablabla&wifi_password=123&custom_config={option1:1,option2:2}, urlencoded and stringifyed. Then the module should save it to custom_config.json or similar.

**Comment by marcelstoer** [comment]
To me this looks a close duplicate of #1302.
