### ISSUE TITLE
Modify firmware in order to discard deauthentication packets

### ISSUE THREAD

**Issue by scazzomatto** [nodemcu/nodemcu-firmware#1651]
Hello, I'm doing my master thesis in IoT cyber-security and I'm looking to modify the firmware in order to discard deauthentication packets that come from outside. My idea is to discard all the packets that have a 0x000c in their structure but I don't know which files I have to edit. Do any of you guys know?
Thanks a lot

**Comment by djphoenix** [comment]
In fact, you can't. Espressif released their SDK with only binary libraries for WiFi-related functionality. You may try to edit them at binary-level, but I think this is very huge work.
