### ISSUE TITLE
Is there a way to determine the SSID of the connected AP (except callback tracking?)

### ISSUE THREAD

**Issue by neilyoung** [nodemcu/nodemcu-firmware#1654]
As subject says

**Comment by Jonathan411** [comment]
I don't think this is a bug/feature request so this question is probably better asked in StackOverflow.com (but I'm just a noob, so maybe someone not-so-nooby could weigh in on this).

That said,  have you looked at:  wifi.sta.getapinfo()

**Comment by djphoenix** [comment]
wifi.sta.getconfig is enough (you maybe also need to check status according to docs)

**Comment by marcelstoer** [comment]
See #1010

**Comment by neilyoung** [comment]
Thanks. For some reasons I don't get notifications by mail, so sorry for the late reply

**Comment by marcelstoer** [comment]
> For some reasons I don't get notifications by mail

Check the "Watch" setting for this repo. Top of any page, slightly right of the center.

**Comment by neilyoung** [comment]
Too stupid, was set to "Not watching". Sorry
