### ISSUE TITLE
ESP32: i2c master module

### ISSUE THREAD

**Issue by devsaurus** [nodemcu/nodemcu-firmware#1663]
**Rationale:**
I2C master mode is a key feature to attach many external components like sensors or displays.

- [x] Basic synchronous I2C master support.
  - Lua: The API for basic mode shall maintain back-ward compatibility with existing scripts.
  - Platform: Functions provided to perform init, read & write operations.
- [x] Asynchronous I2C master support.
  - Lua: API extensions with (optional) callback functions. Lua command finishes immediately and calls back the provided function once transfer terminated.
  - Platform: Expected to establish an interrupt handler with C-callback registration. Synchronous variants for basic support encapsulate IRQ registration and busy wait for the callback.

**Priority:**
  - High for basic support
  - Low for async version

**Dependencies:**
✅ I2C driver released with future IDF.

---

**C API:**

The approach to use IDF's i2c driver in the way sketched below didn't work due to espressif/esp-idf#241. Instead, the sw-based i2c master implementation was ported over from the master branch. Documentation (and platform code) is kept here for future reference.

#### platform_i2c_setup(id, sda, scl, speed)
- prepare configuration with `i2c_param_config()` using provided params
- activate driver `i2c_driver_install()`

#### platform_i2c_send_start(id)
- create link
- queue start command
- exec & discard link

#### platform_i2c_send_stop(id)
- create link
- queue stop command
- exec & discard link

#### platform_i2c_send_address(id, address, direction, ack_check_en)
- create link
- queue write_byte command for address
- exec & discard link

#### platform_i2c_send_byte(id, data, ack_check_en)
- create link
- queue write_byte command
- exec & discard link

#### platform_i2c_recv_byte(id, ack_val)
- create link
- queue read_byte command
- exec & discard link

---

**Lua API:**

Same like for ESP8266 in basic version.

Async version:
- Module IDs 1 and 2 are assigned to the queued implementation based on the IDF driver.
- Functions shared with basic version but they append start / address / write / read / stop commands instead.
- New function `i2c.transfer()` that triggers `i2c_master_cmd_begin()`.
- Asynchronous (i.e. non-blocking) use indicated by presence of callback function parameter to `i2c.transfer()`.
- Will post to a FreeRTOS task that actually calls blocking `i2c_master_cmd_begin()` and posts a task back to the main firmware once the transfer completed.

**Comment by devsaurus** [comment]
Implementation blocked by espressif/esp-idf#241.

**Comment by devsaurus** [comment]
@jmattsson if the issue with the I2C hardware driver isn't fixed anytime soon, I would have to port the software-based master driver as workaround.
Where does a "user driver" go into? E.g. `components/driver` doesn't exist yet.

**Comment by jmattsson** [comment]
I'd suggest `components/driver_i2c` in that case. I put the console driver in `components/driver_console` to avoid potential name conflicts with the IDF's `driver` component.

**Comment by devsaurus** [comment]
I've ported the sw i2c driver:
https://github.com/devsaurus/nodemcu-firmware/tree/dev-esp32-i2c

Things appear to work on the LA, but I need to check more thoroughly against a real slave.

**Comment by devsaurus** [comment]
The basic version is now available in [`dev-esp32` branch](https://github.com/nodemcu/nodemcu-firmware/commit/381726f103b677b81c4b3dfb32e716b1d45aeeda). Feel free to give it a try.

**Comment by devsaurus** [comment]
Support for additional 2 hardware channels in synchronous and asynchronous operation is now available as well with https://github.com/nodemcu/nodemcu-firmware/commit/f5632f41f94df2aa1dd72a7cdef9fd454839e64b.
I'm considering this issues as done.
