### ISSUE TITLE
crypto.mask() only support 4bytes mask

### ISSUE THREAD

**Issue by kicer** [nodemcu/nodemcu-firmware#1677]
### Expected behavior
According to the documentation crypto.mask() should:

> Applies an XOR mask to a Lua string

> - **message** message to mask
> - **mask** the mask to apply, repeated if shorter than the message

### Actual behavior
Return the right string only when use 4bytes mask.

### Test code
```Lua
> print(crypto.toHex(crypto.mask("some message to obscure","X0Y7")))  --right
2b5f3452785d3c442b513e527844361737522a542d423c
> print(crypto.toHex(crypto.mask("some message to obscure","X0Y7otherMaskStrings"))) --error!
2b5f3452785d3c442b513e527844361737522a542d423c
```

```C
/*  app/modules/crypto.c, L122  */
static int crypto_mask( lua_State* L )
{
  int len, mask_len;
  const char* msg = luaL_checklstring(L, 1, &len);
  const char* mask = luaL_checklstring(L, 2, &mask_len);
  int i;
  char* copy = (char*)c_malloc(len);
  for (i = 0; i < len; i++) {
    copy[i] = msg[i] ^ mask[i % 4];    /* if(mask_len> 0) i%mask_len ? */
  }
  lua_pushlstring(L, copy, len);
  c_free(copy);
  return 1;
}
```

### NodeMCU version
master & dev branch

### Hardware
ESP-12S module

**Comment by pjsg** [comment]
Can you make a pull request for this change. Also, either a mask_len of 0 should be illegal and throw an error, or it should leave the input string unaltered.
