### ISSUE TITLE
socket client doesn't connect to node.js server

### ISSUE THREAD

**Issue by ibramn** [nodemcu/nodemcu-firmware#1684]
lua code:
`ip = wifi.sta.getip()`
`print("your IP is "..ip)`
`srv = net.createConnection(net.TCP, 0)`
`srv:on("receive", function(sck, c) print(c) end)`
`srv:connect(3000,"192.168.1.4")`
`srv:on("connection", function(sck, c)`
  `sck:send("GET / HTTP/1.1\r\nHost: 192.168.1.4\r\nConnection: keep-alive\r\nAccept: */*\r\n\r\n")`
`end)`

node.js code:
`var app = require('http').createServer();`
`var io = require('socket.io')(app);`

`io.on('connection', function(socket){`
	`console.log('someone is connected');`
`});`
`app.listen(3000);`

connecting to wifi works well and gets the ip.
node.js server works well with other clients.

**Comment by marcelstoer** [comment]
See #1010.
