### ISSUE TITLE
ping -f crashes NodeMCU immediately

### ISSUE THREAD

**Issue by hisnameishb** [nodemcu/nodemcu-firmware#1686]
### Expected behavior
Not rebooting

### Actual behavior
Rebooting in under one second, sometimes it keeps up the ping storm a few more seconds.

### Test code
On NodeMCU: only connect to an AP, no further software is running. NodeMCU must be reachable in the net.

```shell
ping -f ipaddress of nodeMCU
```
### NodeMCU version
1.5.4.1

### Hardware
NodeMCU

### Missing feature
Configurable behavior on receiving pings: ping back or ignore pings

### Justification
Because of the above behavior.

### Workarounds
none

**Comment by marcelstoer** [comment]
I can't confirm that. I tested on macOS against an old 1.5.4.1 from April and the latest `dev` and both withstand the ping flood.

```
~/Data/NodeMCU/nodemcu-firmware (dev) > sudo ping -f 192.168.0.46
PING 192.168.0.46 (192.168.0.46): 56 data bytes
..Request timeout for icmp_seq 1562
..Request timeout for icmp_seq 8811
..Request timeout for icmp_seq 19651
.^C
--- 192.168.0.46 ping statistics ---
29514 packets transmitted, 29510 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.297/2.620/14.798/1.135 ms
```

**Comment by hisnameishb** [comment]
It was a power problem. With good power supply theres no rebooting or packet loss.
