### ISSUE TITLE
How to obtain the “Probe Request” SSID/BSSID/channel？

### ISSUE THREAD

**Issue by onesecurity** [nodemcu/nodemcu-firmware#1692]
For esp8266 nodemcu firmware how could I obtain the "Probe Request" SSID / BSSID / channel? I can only use the "Probe Request" to obtain Client MAC and RSSI.

![wifi](https://i.stack.imgur.com/O80hG.jpg)

**Comment by onesecurity** [comment]
No one answered the question? @marcelstoer

**Comment by Keshav2136** [comment]
What is the name of this program? Is it for windows too?
