### ISSUE TITLE
Uart.On data event encode/decode problem

### ISSUE THREAD

**Issue by young310** [nodemcu/nodemcu-firmware#1693]
### Expected behavior
The same data print by CH340G usb2serial  1B C3 C4 DB 00 1B 1B FF FF 

### Actual behavior

But nodemcu out 4 unreadable something like diamonds
### Test code
```Lua
uart.on("data", 8,
  function(data)
    print("receive from uart:", data)
```
### NodeMCU version
branch: master
commit: 7b83bbb2ea134cd85ac9d63108603cc02c4e20f7
	
### Hardware
n/a

**Comment by devsaurus** [comment]
What is the output of
```lua
function (data)
  print("receive from uart:", data)
  print(data:byte(1))
  print(data:byte(2))
  ...
  print(data:byte(8))
end
```
Does it match the input from the terminal?

**Comment by young310** [comment]
Thanks! It works now, prints the dec value.
But how can I use the feature: end_char? 
ex: uart.on("data", "??", function(data)

**Comment by devsaurus** [comment]
Refer to the docs http://nodemcu.readthedocs.io/en/dev/en/modules/uart/#uarton for flavours of `uart.on()`.
Furthermore, please consider #1010 for support questions.

**Comment by young310** [comment]
Hi, because the data can be delivered in diverse data types, how the comparison will work if I pass digit/byte in?
