### ISSUE TITLE
dht22 example doesn't workin with 20150127 firmware

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#171]
> dofile('dht22test.lua')
Error reading from DHT22
with 20150127
But 
> dofile('dht22test.lua')
Temperature: 28.4 deg C
Humidity: 24.7%
with 20150126

**Comment by MarsTechHAN** [comment]
Please past the content of 'dht22test.lua' here. please.

**Comment by pastukhov** [comment]
it's happened  because of floating point math implemented in latest firmware. I find fixed dh22 lua lib https://github.com/javieryanez/nodemcu-modules/tree/master/dht22
