### ISSUE TITLE
How can I create Date Object from Date and Time Strings in Lua NodeMCU?

### ISSUE THREAD

**Issue by zhangke0504** [nodemcu/nodemcu-firmware#1713]
I am playing around with NodeMCU on an ESP8266. I have a Date String and a Time String from a Web Request like this:

15.07.16 (German format DD.MM.YY)

19:50 (24 hours format)

These DateTimes lay usually a little bit in the future. I want to get the number of minutes from the current time to the time from my strings above.

I guess I have to create a time object from the strings and then compare it to the current time. But how can I do that with Lua?

Unfortunately there is no os Library on NodeMCU (or I might have missed how to enable it).

Calculating the difference manually would be a huge pain which I would like to avoid. Does anyone know a way to compute that with available or external libraries?

Thanks for any support!

**Comment by marcelstoer** [comment]
See #1010
