### ISSUE TITLE
MDNS query

### ISSUE THREAD

**Issue by reejinbouk** [nodemcu/nodemcu-firmware#1723]
nodemcu firmware stil can't connect to devices with avahi-daemon service.
for example it can't connect to "raspberrypi.local" 
propose need to add port 5353 to "net" module, then connect to multicast, set dnsserver and it will work?

**Comment by djphoenix** [comment]
Not sure this may be intergated in `net` module (or elsewhere) because MDNS is not part of LWIP.
But I think that MDNS resolution may (and should) be implemented in `mdns` module.
Tagging @pjsg as maintainer of `mdns` module

**Comment by pjsg** [comment]
I don't have any experience with using nodemcu as a mdns client. The approach outlined by @reejinbouk ought to work.

**Comment by dwery** [comment]
@pjsg @djphoenix just found this: http://desperate-programmers.com/2016/02/02/an-update-to-mdns-querries-yay/

the .c file provides the parsing routines, while the lua code has the high level stuff

**Comment by iShift** [comment]
+1 add mDNS resolving function to firmware
