### ISSUE TITLE
Bug in wifi.c, line 740

### ISSUE THREAD

**Issue by neilyoung** [nodemcu/nodemcu-firmware#1726]
### Expected behavior
Wifi password of 64 byte length is accepted
### Actual behavior
Wifi password of length 64 is rejected in line 740, because the comparison is done with '<' instead of '<=' . Corrected code:

``` 
luaL_argcheck(L, (pl==0||(pl>=8 && pl<=sizeof(sta_conf.password)) ), 2, "length:0 or 8-64");
```
### Test code
```Lua
wifi.sta.config("SSID", "0123456789012345678901234567890123456789012345678001234567890123")

```
This will be rejected in line 740, although valid.

### NodeMCU version
master, 1.5.4.1

### Hardware
NodeMCUv2

**Comment by neilyoung** [comment]
Hmm.. Nobody? I thought it would be an easy issue...

**Comment by neilyoung** [comment]
Thanks for fixing it

**Comment by marcelstoer** [comment]
> I thought it would be an easy issue...

It is...and we do accept PRs 😉 

\<banging-the-marketing-drum\>
Building NodeMCU on your own machine is actually [fairly easy using Docker](http://nodemcu.readthedocs.io/en/latest/en/build/#docker-image) - regardless of OS.
\</banging-the-marketing-drum\>
