### ISSUE TITLE
How to enable SmartConfig with Cloud Build Service Website ?

### ISSUE THREAD

**Issue by LiweiDong** [nodemcu/nodemcu-firmware#1728]
> SmartConfig is disabled by default and can be enabled by setting WIFI_SMART_ENABLE in  user_config.h before you build the firmware.

I can't find this options  on Cloud Build Service Website .

**Comment by marcelstoer** [comment]
You currently can't, that feature is not implemented. Also note that the cloud builder is not operated by the NodeMCU firmware team. I'm doing that as an individual.
