### ISSUE TITLE
enduser Setup: is it possible to provide a way to upload a file like "config.lua" ?

### ISSUE THREAD

**Issue by sivix** [nodemcu/nodemcu-firmware#1733]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior

Being able to send a configuration file (config.lua) using the enduser_setup webserver module.
is enough to have an API method on the webserver.

My short term need would be to have additional parameters like the MQTT Server and Topic;

a similar implementation is already available for Arduino IDE: https://github.com/tzapu/WiFiManager

I'll take care of saving that parameters, but the captive portal should be able to read it and pass them

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
-- add code here
```
### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.
Master branch 2017-Jan 

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.
ESP8266-12E "Amica" NodeMCU v1.0

8<------------------------ END BUG REPORT -------------------------------------

8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
> ### Expected behavior
>
> Being able to send a configuration file (config.lua) using the enduser_setup webserver module.
is enough to have an API method on the webserver.

Why is that expected behavior? The EUS documentation doesn't mention this be feature.

Your feature request is similar to #1302. Also take note of #1010.
