### ISSUE TITLE
How many requests nodemcu can handle at a time

### ISSUE THREAD

**Issue by Akriti-S** [nodemcu/nodemcu-firmware#1740]
If we have 4 connections to a nodemcu (esp 8266 nodemcu 12E board) and all of the connections are sending voluminous traffic to it, then in this case will it be able to handle such condition.

**Comment by marcelstoer** [comment]
A related comment: https://github.com/nodemcu/nodemcu-firmware/issues/1737#issuecomment-273480908

**Comment by Akriti-S** [comment]
Thank you for your response. My query is bit different, I want to know about the ideal load of traffic(number of requests from clients) a nodemcu web server can handle at a time.

**Comment by marcelstoer** [comment]
If a system is single-threaded: 1 concurrent request. Also see https://github.com/nodemcu/nodemcu-firmware/pull/1757#issuecomment-275877454
