### ISSUE TITLE
希望作者增加点中文资料支持，让更国人参与进来！

### ISSUE THREAD

**Issue by xwlyjj** [nodemcu/nodemcu-firmware#1741]
**# _希望作者增加点中文资料支持，让更国人参与进来！或者建一个中文官方discuz论坛_**

**Comment by marcelstoer** [comment]
According to Google this translates to

> Hope that the authors increase the point of Chinese data support, so that more people involved in! Or to build a Chinese official discuz forum

Sorry to say but none of the current maintainers speak Chinese. I guess this also relates to #1732.
