### ISSUE TITLE
When I flash the node mcu firmware (I have tried all version available) to my nodemcu devkit 1.0 i get the following error:  Writing 41435136 @ 0x0... 4194304 (10 %) A fatal error occurred: Write failure, status: 35 .When i flash  version 0.96 everything works fine

### ISSUE THREAD

**Issue by LucaSfragara** [nodemcu/nodemcu-firmware#1750]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
-- add code here
```
### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.

8<------------------------ END BUG REPORT -------------------------------------

8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
See #1010.
