### ISSUE TITLE
Please push PR to branch "dev" instead of master.

### ISSUE THREAD

**Issue by nodemcu** [nodemcu/nodemcu-firmware#176]
Thank you everyone for contributing to this project.
I have made branch "dev" up-to-date with master branch.
new features or some major fixes can first push to this "dev" branch.
note that pre_build bin in this "dev" branch is never up-to-date.
for ones want to test new features, please pull "dev" branch and compile.

**Comment by Suxsem** [comment]
thanks! :) please don't forget to build new pre_build! :)

**Comment by vowstar** [comment]
Ok, I agree with it =)

**Comment by funshine** [comment]
I would like to open this issue again.
there's many PRs in master ahead of dev branch. we are now going to sort things out.

**Comment by nodemcu** [comment]
I would like to open this issue again.
there's many PRs in master ahead of dev branch. we are now going to sort things out.

**Comment by karrots** [comment]
#575 & #675 were cherry picked over to 'dev'.

**Comment by nodemcu** [comment]
great, once all done, we will add this to guideline and can be closed.

**Comment by TerryE** [comment]
I'll sort out any residual manual merges tomorrow.

**Comment by marcelstoer** [comment]
@karrots Thanks for checking.
@nodemcu It already _is_ in the guidelines, see https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md.

**Comment by TerryE** [comment]
We now have this as a contribution guideline which is being actively enforced by the committers so we can close this as an issue.
