### ISSUE TITLE
Unable to load tls module

### ISSUE THREAD

**Issue by Lir10** [nodemcu/nodemcu-firmware#1760]
I've built latest nodemcu-firmware (Master branch) with SSL/TLS support . 
But when i run : 

`srv = tls.createConnection()`
i get : `attempt to index global 'tls' (a nil value)`

I've built the firmware from the cloud.

Thanks

**Comment by Lir10** [comment]
I can confirm by the mail i got that tls has been added to the build: 

> This was built against the master branch and includes the following modules: cjson, crypto, encoder, file, gpio, mqtt, net, node, tmr, uart, wifi, **tls**

**Comment by Lir10** [comment]
Looks like it's working only on the dev branch

**Comment by djphoenix** [comment]
@marcelstoer is there a bug in cloud builder?

**Comment by marcelstoer** [comment]
It's notoriously difficult to prove the absence of bugs 😉 

However, this ain't a bug. The TLS module will only be available on `master` after the [next `dev`-to-`master` merge](https://github.com/nodemcu/nodemcu-firmware/milestone/4).

**Comment by Lir10** [comment]
@marcelstoer Thanks for lettings us know :)

@djphoenix Few questions:
A. Is it possible to connect to tls server from esp8266 with this tls module using client certificate  ?

B. In the docs it says something about saving the certificate inside 

> tls.cert.verify()

, is it possible to store  all the certificate chain ?

**Comment by marcelstoer** [comment]
@Lir10 our documentation is bound to a specific branch since we keep it in the same repo as the code, there's a difference between http://nodemcu.readthedocs.io/en/dev/en/modules/net/ and http://nodemcu.readthedocs.io/en/master/en/modules/net/

**Comment by Lir10** [comment]
@marcelstoer As i can see from the docs (dev branch) `net.cert` Module has gone to the TLS module, but it's not clear from tls docs how can we add all the certificate chain to tls.cert.verify() as a string.

**Comment by djphoenix** [comment]
@Lir10, I totally not understand how (and why) tls module works right now. This is a remaining part of my `net` module rework (#1379). And we will completely rewrite it sooner or later (#1700).

About certificate verification - it goes to old `espconn` layer, and, so, passed through it to new mbed TLS layer (since 2.0.0 - #1435). `espconn` is a mess at all...

**Comment by Lir10** [comment]
@djphoenix What do you suggest to use for the meantime for secured connection untill tls module will be completed (or it's not possible for now to create secured connection with the current stable version) ?

As for now , it's not clear to me how to create simple client ssl connection even without client certificate

**Comment by djphoenix** [comment]
As in current `dev` docs, you can use both old-style [`net.createConnection(net.TCP, 1)`](http://nodemcu.readthedocs.io/en/dev/en/modules/net/#netcreateconnection) and new-style [`tls.createConnection()`](http://nodemcu.readthedocs.io/en/dev/en/modules/tls/#tlscreateconnection) API. Please note that old-style API is kept for backward compatibility and will be deprecated.

So after creating connection you may [`:connect`](http://nodemcu.readthedocs.io/en/dev/en/modules/tls/#tlssocketconnect) it to remote server. And it works.
I never used certificate validation with nodeMCU (old SSL or even mbedTLS), but you can see [example](http://nodemcu.readthedocs.io/en/dev/en/modules/tls/#tlscertverify) of passing your root CA cert to nodeMCU. I think it should work.

**Comment by Lir10** [comment]
@djphoenix Thanks , will try to test it with CA cert only. 
It would be great if we would be able to add client certificate to tls module api in the near future !

**Comment by tcpipchip** [comment]
hi, how to enable the TSL module on LUA BUILD (ESP32)
attempt to index global 'tls' (a nil value)
Thanks!
