### ISSUE TITLE
Old-style net API deprecation

### ISSUE THREAD

**Issue by djphoenix** [nodemcu/nodemcu-firmware#1762]
Now we have new APIs for creation TLS connections and UDP sockets, and so old APIs that kept only for backward compatibility (just convenience calls):

- `net.createConnection(net.UDP)` -> `net.createUDPSocket()`
- `net.createServer(net.UDP)` -> `net.createUDPSocket()`
- `net.createConnection(net.TCP, 1)` -> `tls.createConnection()`

I propose to:

- [x] After upcoming master drop, set `net.createConnection()` behaviour to create **plain tcp connection** by default (without options).
- [x] Add deprecation message to the docs
- [x] Add deprecation message to the firmware (requires #1538).
- [ ] After (upcoming+1) master drop, completely remove deprecated feature, and keep only separated APIs.

**Comment by marcelstoer** [comment]
I basically agree but this

> Add deprecation message to docs

should be done _before_ the upcoming merge.

**Comment by jmattsson** [comment]
No objections from me.

**Comment by devsaurus** [comment]
For sure the way to go :+1:

**Comment by djphoenix** [comment]
@marcelstoer 
> I basically agree but this [deprecation message to docs] should be done before the upcoming merge.

Can you add right message by yourself? I have not excellent english, you see :)

**Comment by marcelstoer** [comment]
@djphoenix issue number 2 from your list above can be ticked off, see http://nodemcu.readthedocs.io/en/latest/en/modules/net/#netcreateconnection

**Comment by marcelstoer** [comment]
> Add deprecation message to the firmware (requires #1538).

That PR is now ready.

**Comment by marcelstoer** [comment]
This is fast reaching its 2nd birthday. @nwf retired the static timers in #2603. Maybe it would be a good time to finally close this one here as well.

**Comment by nwf** [comment]
Hey, more dead code to eliminate.  I'll  take this on, too, as part of my rampaging around the network stack.

**Comment by marcelstoer** [comment]
> more dead code

And dead _documentation_, too 😉

**Comment by HHHartmann** [comment]
I can`t see anything to do here anymore. Documentation looks good and the implementation also does not allow for options anymore.

Can we close this?
