### ISSUE TITLE
crypto.fhash() resets NodeMCU

### ISSUE THREAD

**Issue by joysfera** [nodemcu/nodemcu-firmware#1769]
### Expected behavior
crypto.fhash("md5", "main.lc") should compute the MD5 hash of main.lc file.

### Actual behavior
reboots the system

### Test code
```Lua
a=crypto.fhash("md5","main.lc")

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 25028, room 16 
tail 4
chksum 0xba
load 0x3ffe8000, len 2260, room 4 
tail 0
chksum 0xcc
load 0x3ffe88d4, len 8, room 8 
tail 0
chksum 0xc1
csum 0xc1

NodeMCU custom build by frightanic.com
	branch: master
	commit: 81ec3665cb5fe68eb8596612485cc206b65659c9
	SSL: false
	modules: bit,cjson,crypto,file,gpio,http,mdns,mqtt,net,node,ow,rtcmem,rtctime,sntp,tmr,uart,wifi
 build 	built on: 2017-01-28 20:56
 powered by Lua 5.1.4 on SDK 1.5.4.1(39cb9a32)
```
### NodeMCU version
see above in the output

### Hardware
Wemos-Mini

### Notes
Happens with SHA1 as well.
Does not happen with other files. Actually happens with certain files only. Cannot figure out what's so special about the files that cause the fhash to fail so horribly. Tried even to format whole filesystem but the problem persists. The main.lc file is 6912 bytes long. There are longer files than that and they don't crash in fhash(). Just this one.
No idea how to debug it. Please advise.
Getting sick of this constantly crashing Lua stuff. I thought a scripting language would make developing stuff easier than say plain C. Seems like I was very wrong.

### EDIT1
You're not going to believe this: the key factor is the file length. I have just created few empty (filled with stuff from /dev/zero) test files. 6911 and 6913 bytes long files are OK while the 6912 crashes the NodeMCU. 6912 = 6x1024 + 3x256 if this indicates anything.

### EDIT2
current -dev is not affected by this. Not sure if I can switch my production device to -dev branch, though. Any idea when the dev->master copy is planned so I could guess how stable the -dev is?

**Comment by djphoenix** [comment]
You can see "master drop" plans [here](https://github.com/nodemcu/nodemcu-firmware/milestones). Next one is planned on 1st Feb.
There are some fixes for fhash in `dev`, so...
