### ISSUE TITLE
Increase CPU frequency 

### ISSUE THREAD

**Issue by eliabieri** [nodemcu/nodemcu-firmware#178]
A method to increase CPU frequency would be nice.
Something like esp8266.cpu(160)

**Comment by MarsTechHAN** [comment]
We have dicussed it.
If enable the CUP-SPEED-ADJUST will cost extra ram . 
And you need to re-adjust the the SerialPort Setting(We can auto do this, but cost time.) 
The increaseing speed will lead to the increasing temp and walts.As a result, we decide to not to enable the feature now.

**Comment by raz123** [comment]
eliabieri, this fork does it: https://github.com/jrahlf/nodemcu-firmware/tree/master/bin
Command: node.set_cpu_freq(80) or node.set_cpu_freq(160)

More info: http://www.esp8266.com/viewtopic.php?f=21&t=1369

**Comment by nodemcu** [comment]
ref #289
