### ISSUE TITLE
weird gpio action

### ISSUE THREAD

**Issue by zenz** [nodemcu/nodemcu-firmware#1791]
NodeMCU custom build by frightanic.com
	branch: master
	commit: b96e31477ca1e207aa1c0cdc334539b1f7d3a7f0
	SSL: false
	modules: dht,file,gpio,mqtt,net,node,tmr,uart,wifi
 build 	built on: 2017-02-09 08:15
 powered by Lua 5.1.4 on SDK 2.0.0(656edbf)

I'm trying to use nodemcu to control a relay. if I do gpio.write(1, gpio.HIGH), then the relay is actived. but when I do gpio.write(1, gpio.LOW), the relay is still actived. until I do gpio.mode(1, gpio.INPUT), the relay goes deactived. Please test

**Comment by NicolSpies** [comment]
I assume you drive the relay via a transistor and with a flyback diode across the relay coil

**Comment by pjsg** [comment]
What is your drive circuit?

**Comment by zenz** [comment]
@NicolSpies is right, while I replace with different relay module, it's working fine.

**Comment by zenz** [comment]
Please close this issue.
