### ISSUE TITLE
Init.lua Example improvements

### ISSUE THREAD

**Issue by samuel-puschacher** [nodemcu/nodemcu-firmware#1796]
Currently the init.lua example in the Docs is using a tmr interval, which checks every second, if the ESP8266 got an IP.
It seems that the module needs very much time to get to the Point, where it gets the IP.
Since I use `wifi.sta.eventMonStart()` the ESP8266 neds just a few seconds to obtain the IP, instead of more than ten seconds, up to over a minute.
Could the init.lua example be updated, to this more effective way?

**Comment by marcelstoer** [comment]
> It seems that the module needs very much time to get to the Point, where it gets the IP.

That's not what I see here, takes 1-2s usually. Are you saying that `wifi.sta.getip()`-not-nil and the callback for `wifi.sta.eventMonReg(wifi.STA_GOTIP....` don't report the connected status at roughly the same time?

The good thing about the timer is that it prints something every seconds so you know what's going on. To achieve the same with the event monitor you'd register for both `wifi.STA_GOTIP` and `wifi.STA_CONNECTING` and act accordingly.
