### ISSUE TITLE
WS2812 Module - Random colour triggered on bootup/restart

### ISSUE THREAD

**Issue by georeb** [nodemcu/nodemcu-firmware#1799]
### Expected behaviour
WS2812 LED to remain off (0,0,0) during reboot/start up.

### Actual behaviour
On soft restart, using `node.restart()`, garbage data is produced on GPIO2 which causes the WS2812 LED to display a random colour.

This can be overridden by issuing
```Lua
ws2812.init()
ws2812.write(string.char(0, 0, 0)) 
```
but there is always an undesierable delay.

### NodeMCU version
Master branch - 2.0.0

### Hardware
ESP8266-12F with a single WS2812 LED connected on GPIO2.
The data connection has an inline 0.1K resistor.

@dereulenspiegel @Alkorin

**Comment by Alkorin** [comment]
Not sure we can do anything for it. I'll take a look but I think that this "garbage" is outputted by the bootloader :/

**Comment by georeb** [comment]
@Alkorin Yes, I think so. It is also the pin connected to the blue indication LED. Do you know of any electrical tricks that work, for example, holding the data line low??

**Comment by Alkorin** [comment]
Yes, you could use another pin of your ESP8266 to controle some kind of buffering, like the 74HCT245 which is often used with WS2812 to boost the data line to 5V. With the `OE` pin you can control if the data can go through or not.

**Comment by georeb** [comment]
Okay, fair enough, it's a shame the bitstream cannot be generated on a non-uart gpio :(
It appears to only happen occasionally on a soft-restart, and is always green!

**Comment by Alkorin** [comment]
It's a trade-off. I use the UART to generate de bitstream (leaving the CPU doing whatever it needs). Else you should do bit-banging and use 100% resources of the CPU because WS2812 protocol is very timing-critical...

Personally, I control hundreds of WS2812-like LEDs via Wifi at ~100fps without any crash, which wasn't really the case when the code used a bit-banging style version ;-)

**Comment by georeb** [comment]
Yes, I understand. It's a small price to pay for less CPU usage :)

**Comment by devsaurus** [comment]
>  think that this "garbage" is outputted by the bootloader

Appears to be correct - there's a related statement in the [esptool.py wiki](https://github.com/espressif/esptool/wiki/ESP8266-Boot-Mode-Selection#required-pins):

> GPIO2 should always use a pullup resistor to VCC, not a direct connection. This is because it is configured as an output by the boot ROM.

And in https://github.com/esp8266/esp8266-wiki/wiki/Pin-definition:

> GPIO2 	UART Tx during flash progamming

Would be interesting to see what the bootloader sends on GPIO2...

**Comment by FrankX0** [comment]
> Would be interesting to see what the bootloader sends on GPIO2...

Well, this (at 74880 bps):
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 26892, room 16 
tail 12
chksum 0x79
ho 0 tail 12 room 4
load 0x3ffe8000, len 2228, room 12 
tail 8
chksum 0x27
load 0x3ffe88b4, len 136, room 0 
tail 8
chksum 0xd0
csum 0xd0
```

**Comment by georeb** [comment]
@devsaurus What value pull-up resistor would you suggest?

**Comment by devsaurus** [comment]
@georeb the [NodeMCU Devkit](https://github.com/nodemcu/nodemcu-devkit-v1.0/blob/master/NODEMCU_DEVKIT_V1.0.PDF) uses 12k for the pull-ups.

**Comment by georeb** [comment]
Unfortunately the 12k pull-up doesn't fix the problem :(

**Comment by georeb** [comment]
Is there any way to disable the bootloader spool on GPIO2 before build @marcelstoer ??

**Comment by devsaurus** [comment]
@georeb no pull-up will fix the problem of course. I just quoted the statement from the wiki to have another source that confirms that UART is outputting information on GPIO2.

**Comment by Alkorin** [comment]
If it's the bootloader, in ROM, nothing can be done ... :/

Put your code in init.lua to disable the leds as soon as possible.
