### ISSUE TITLE
A .disconnect() before .dsleep() leads to a longer .connect() after wakeup

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#1819]
At this time I want to understand how this works, so not a bug or a request yet.

### Expected behaviour
When waking up from deep sleep the wifi (station) connection does not depend on the state before the sleep.
### Actual behaviour
If I `wifi.sta.disconnect()` before the `dsleep` then it takes about 2s longer to get a connection. If I do not issue the `.disconnect()` then a connection takes a very short time (less than 90ms from the `setip()`).

### Test code
N/A
### NodeMCU version
latest dev.
### Hardware
Any. I use esp-07, esp-12* and more.

### Rational
I was not issuing a `.disconnect()` (never needed it). When my a/p died recently I started using a loaner and it could only associate with a small number of stations (I think 14). Issuing a `.disconnect()` frees an entry immediately, thus allowing more stations to connect.

My app takes less than 500ms every 1 or 5 minutes so it is rare to overflow the limit of concurrent connections. A rare failure is not a problem.

The cost of the extra 2s connection means the app takes 5 times as long to run, thus draining the battery 5 times faster.

This may be an issue with the SDK (not the NodeMCU firmware) or maybe it even is how station association is supposed to work (if the a/p remembers a station then it associates quicker?).

TIA

**Comment by jmattsson** [comment]
I *believe* this expected, and related to regeneration of keying material on a fresh join. I don't have evidence to back this belief up properly, however.
