### ISSUE TITLE
How to send string from ِِArduino to NodeMCU esp8266??

### ISSUE THREAD

**Issue by 00matrix95** [nodemcu/nodemcu-firmware#1824]
Hello guys
I'm working on a small project i'm using nodeMCU esp 8266 and arduino uno 
i want to send string data like "abcd" or values like "1234" from arduino to NodeMCU through wires
How can i do  it?
I'm beginner so please support me with examples i'm working on Arduino IDE

**Comment by jmattsson** [comment]
Please see the link in #1010 for the right place to ask this question.
