### ISSUE TITLE
adc.readvdd33() on wemos d1 mini pro always gives 65535

### ISSUE THREAD

**Issue by Tuxdiver** [nodemcu/nodemcu-firmware#1826]
### Expected behavior
Calling `adc.readvdd33()` should return the voltage after setting `adc.force_init_mode(adc.INIT_VDD33)` and possibly restarting

### Actual behavior
Call of `adc.readvdd33()` always returns 65535, `adc.read(0)` returns analog value around 7.

### Test code
```Lua
print(adc.force_init_mode(adc.INIT_VDD33))
print(adc.readvdd33())
print(adc.read(0))
```

gives:
```
false
65535
7
```

### NodeMCU version
Current own build by docker image:
NodeMCU 2.0.0 build unspecified powered by Lua 5.1.4 on SDK 2.0.0(656edbf)

### Hardware
Wemos d1 mini Pro

### Possible reason
Could the changed memory layout for modules with more than 4MB flash cause the problem? Maybe the writing to memory position 107 is at the wrong position in the flash?
adc.c:
`  uint32 init_sector = flash_safe_get_sec_num () - 4;`
It does write something, because calling `adc.force_init_mode` with changing mode returns true in the first call and false after that. But maybe it is not in the right block.

**Comment by devsaurus** [comment]
Your analysis is most likely correct, thanks for reporting!
Seems I missed this instance - will have a look.

**Comment by devsaurus** [comment]
@Tuxdiver I was able to reproduce this issue. Fix is contained in the linked PR.

**Comment by jmattsson** [comment]
Fix merged into dev.
