### ISSUE TITLE
Transfer build options documentation from README to documentation

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1830]
The chapter at https://github.com/nodemcu/nodemcu-firmware/tree/dev#build-options feels totally out of place and is IMO not expected there.
-> transfer to documentation

A new FAQ entry? Or a chapter at http://nodemcu.readthedocs.io/en/latest/en/build/? Or both, a FAQ entry linking to the build page?

**Comment by jmattsson** [comment]
> both, a FAQ entry linking to the build page

...would be the ideal imho.
