### ISSUE TITLE
TIME_WAIT sockets issues

### ISSUE THREAD

**Issue by djphoenix** [nodemcu/nodemcu-firmware#1836]
Now we have two (*or more? Point me if I miss something*) critical issues related to sockets kept in TIME_WAIT state:
- Cannot open new `server` instance when any socket in `TIME_WAIT` state with matched target port is present
- "Memory leak" (actually high consumption that rolls back after time)

I think we have a several ways to go (or maybe mix them together):
- [x] Reduce `TIME_WAIT` state timeout for socket, so them will be closed earlier
- [x] ~Kill blocking `TIME_WAIT` sockets when calling `listen` method~. Enable `SO_REUSEADDR` flag.
- [ ] Kill `TIME_WAIT` sockets somewhere in Lua GC (I not so familiar with lua-level, anyone can explain this?)

Objections? I think we should resolve this ASAP (**before** upcoming master drop).
/cc @marcelstoer @devsaurus

**Comment by luismfonseca** [comment]
>  Kill blocking TIME_WAIT sockets when calling listen method (maybe it will require some LWIP code patching)

I suppose you can do this without code patching lwIP. By changing the net module and killing off `TIME_WAIT` sockets when a new connection is about to be made. Although, that means each module that uses lwIP needs to do the same thing. This is were something espconn could be of use - an intermediate layer to make lwIP more tailored to the nodemcu/esp8266 use case and capabilities :o.

**Comment by djphoenix** [comment]
> Although, that means each module that uses lwIP needs to do the same thing
Yes and no - this is required feature only for TCP server sockets, TCP clients and UDP sockets haven't this requirement.

**Comment by djphoenix** [comment]
So there are first "good news everyone" - I managed `SO_REUSEADDR` to work, and its the simpliest patch I wrote for nodemcu ever. *facepalm*
See 06c8a47f7d9bc709b8c50ff16984b5ae23905f5e

I will work on it some more and prepare PR.

**Comment by luismfonseca** [comment]
Oh cool!

Is there any known downside for using `SO_REUSEADDR`?

**Comment by djphoenix** [comment]
Not sure but now I can't reproduce memory leaks... So, *what?* o_O
@luismfonseca you have initially caught leakage, so, can I ask you to try it again and (if it reproduced) get a sample code with client-side reference?

**Comment by djphoenix** [comment]
And it fixed. `TIME_WAIT` sockets are being free after `2*TCP_MSL` inactivity time frame, so for 60s MSL heap stability time is 120s. I reduced it to 5s, and stable time now is 10s. I think it is enough (unless anyone try to DDoS someone by TCP from ESP).
See 8c8947aeb35f3c249c741bd6f4cf1e73be844b87

**Comment by georeb** [comment]
Will this change be available in the DEV branch soon?

**Comment by djphoenix** [comment]
@georeb I promise, track #1838 for progress :)

**Comment by pjsg** [comment]
One approach to dealing with time_wait is to reset the connection -- I don't know if this is possible with lwip.  (this is actually the trick that Internet Explorer uses on windows)

What happened before in the old sdk?
