### ISSUE TITLE
init.lua main script

### ISSUE THREAD

**Issue by aignaciors** [nodemcu/nodemcu-firmware#184]
Is there a problem to describe all the code in the "init.lua" file and flash the uC just with this script on luatool? I've noted that many uses two files, init and main.lua, but what is the difference between them?

**Comment by MarsTechHAN** [comment]
```init.lua```As the name, is used to initiate the ESP8266(Like to connect to WiFi).And When the ESP8266 start working, it will run ```init.lua```first.(Name cannot change!)
 If you put too much code inside, may cause hard to edit it. (Also everybody's WiFi Code is different )

As for``` main.lua ```The name means nothing, you can choose your own one, for example ``` what_a_good_lua_program.lua```(How ever that's not a good idea).People like to put the functional program here, like to updata the temp to a website...
