### ISSUE TITLE
Duplicate lua examples for DS18b20

### ISSUE THREAD

**Issue by karrots** [nodemcu/nodemcu-firmware#1841]
### Expected behavior
One library for DS18b20 in code base.

### Actual behavior
New async library and examples in `lua_modules\ds18b20` as well as two basically identical old style example files in `lua_examples`. 

### NodeMCU version
Current `dev` be2a9df1b0fafa6b8822c24faf2a6ee5f334c676

**Comment by marcelstoer** [comment]
Are you willing and motivated to help us clean up here? Proposal:
- Merge https://github.com/nodemcu/nodemcu-firmware/blob/master/lua_modules/ds18b20/ds18b20-example.lua and https://github.com/nodemcu/nodemcu-firmware/blob/master/lua_modules/ds18b20/ds18b20-web.lua into a single up-to-date example
- Move that one to https://github.com/nodemcu/nodemcu-firmware/tree/master/lua_examples
- Delete the existing DS18b20 examples there
- Rename ds18b20.EN.md to README.md so GitHub would display that by default
- Correct that documentation if necessary

**Comment by karrots** [comment]
Happy to create a PR. Mostly started the issue to create conversation. The issue isn't the code in `lua_modules` it's the old code in `lua_examples`.

I'll create a PR to do the following:

1. Rename `ds18b20.EN.md` to `README.md` so GitHub would display that by default.
2. Remove old examples in `lua_examples`.
3. Convert `toBase64` that I missed earlier to `toHex`
4. Fix formatting and spelling issues in `README.md`

You mention splitting the examples from the actual module. It seems like other Lua modules have examples in the folder while the examples folder is where general examples go.
