### ISSUE TITLE
enduser_setup: Show obtained IP address to user after connected to WiFi

### ISSUE THREAD

**Issue by tricoos** [nodemcu/nodemcu-firmware#1856]
### Missing feature
WiFi IP not shown to user in captive portal after successful connection

### Justification
The user cannot find out the IP address of the device easily except via NMAP or DHCP server logs. But the IP address is important if you have a web server running on the device as the user needs to know the IP to connect to it.

### Workarounds
Not using enduser_setup and writing it from scratch in LUA.

**Comment by FrankX0** [comment]
This feature used to be in there ( #1313).
I'll see what I can do.

**Comment by pjsg** [comment]
Another approach is to use mdns to advertise the name of the device and then you can connect by name. On Mar 11, 2017 06:55, tricoos <notifications@github.com> wrote:Missing feature
WiFi IP not shown to user in captive portal after successful connection
Justification
The user cannot find out the IP address of the device easily except via NMAP or DHCP server logs. But the IP address is important if you have a web server running on the device as the user needs to know the IP to connect to it.
Workarounds
Not using enduser_setup and writing it from scratch in LUA.

**Comment by FrankX0** [comment]
I'm also using mdns for my applications.
But note that this works in Windows and iOS, but not (AFAIK) in Android.

**Comment by pjsg** [comment]
Argh! I just starred https://bugs.chromium.org/p/chromium/issues/detail?id=405925

I did install the 'Pea Finder' app (https://play.google.com/store/apps/details?id=com.ersteheimat.peafinder) which shows the local mdns servers which support web access and then allows you to click on them.

**Comment by FrankX0** [comment]
I also just installed ' Pea Finder', which indeed finds device with mdns enabled.
But I don't think this is always a convenient way to first having to install this app to find the device in question.

**Comment by pjsg** [comment]
I think that the best approach is to get Chrome to support mdns on Android.... But I don't know how to get them to do it....

**Comment by tricoos** [comment]
Well, just including the mdns module to connect to the module once and then never use it again when the IP address is readily available is something I don't want to do because of memory reasons. In addition, to be able to use mDNS you need to have Bonjour/Avahi installed on the host system. But then again even if I would use mDNS how do I show the user the hostname he's supposed to connect to? I can't, right? So I don't have any advantage over showing the IP address that's readily available.
I have multiple devices of the same type in the same network so knowing the IP or the hostname is required to know which of them is the new one I have to connect to to configure/control it.
And mDNS is no solution as I don't have any memory left and was able to get the code running with some heavy optimizations to save RAM. So showing the IP address that's readily available is the only solution for me with this implementation.

**Comment by FrankX0** [comment]
I agree that mDNS is not always the solution.
Please have a look at the referenced pull request.
After connecting to the AP it will show the assigned IP address.

**Comment by FrankX0** [comment]
Propose to close: with the merge the request to show the IP address has been implemented.
