### ISSUE TITLE
ESP32: NET module Issue

### ISSUE THREAD

**Issue by michan18** [nodemcu/nodemcu-firmware#1864]
Hello, I was trying to implement a TCP server on ESP32 and listing via a port a Panic issue is thrown out ..This is my sample....code 

srv=net.createServer(net.TCP,0)
srv:listen(80,function(conn)
conn:on("receive",function(conn,payload) end)
print(payload)
end)

Whenever I execute the code i am getting PANIC: unprotected error in call to Lua API (attempt to call a nil value)

Now someone to take over to actually fix it or a possible solution?

**Comment by FrankX0** [comment]
Shouldn't the `print(payload)` not be part of the `conn:on` callback (incorrect position of the first end)?
Like this:
```lua
srv=net.createServer(net.TCP,0)
srv:listen(80,function(conn)
  conn:on("receive",function(conn,payload)
    print(payload)
  end)
end)
```

**Comment by michan18** [comment]
Thank you but the issue is on port listening ...
srv:listen... will always showing a panic issues.....only in esp 32

**Comment by FrankX0** [comment]
To me it sounds there is an issue with the callback mechanism of the `listen` function.
Can you try the following:
```lua
srv=net.createServer(net.TCP,0)
srv:on("receive",function(conn,payload)
  print(payload)
end)
srv:listen(80)
```

**Comment by michan18** [comment]
Yes tried it but its returning with  an error 
 attempt to call method 'on' (a nil value)

**Comment by michan18** [comment]
Yes ...Thanks its fixed now........:)

**Comment by FrankX0** [comment]
@michan18: can be closed I guess?

**Comment by michan18** [comment]
Yes
