### ISSUE TITLE
Document that file.mount() requires #define BUILD_FATFS

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1881]
http://nodemcu.readthedocs.io/en/latest/en/modules/file/#filemount needs to tell that it requires`#define BUILD_FATFS` in `user_config.h`.

-> http://www.esp8266.com/viewtopic.php?f=23&t=14247

Also, fix the typo in this sentence:

> Besides the SPIFFS file system on internal flash, this module can also access FAT partitions on an external SD card is FatFS is enabled.

Aaaand fix the TOC at the top of the page for functions like `file.close()`.

**Comment by marcelstoer** [comment]
@devsaurus your documentation states explicitly that FatFS is at R0.12a. How relevant is it to keep it up to date? Does the low version number imply anything wrt to stability or maturity? http://elm-chan.org/fsw/ff/updates.txt

**Comment by devsaurus** [comment]
> How relevant is it to keep it up to date?

Most incremental fixes were related to exFat, so I check once in a while. Could be a good opportunity to update sometime soon again.

**Comment by devsaurus** [comment]
PR was merged, closing.
