### ISSUE TITLE
Remove deprecated i2c init()

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1888]
Follow-up to #1887...

Remove `init` from adxl345, am2320, bme280, bmp085, hmc5883l, l3g4200d and hdc1080.

**Comment by devsaurus** [comment]
...and from lua_modules as well.

**Comment by marcelstoer** [comment]
Any chance to get this done before the 2.2 release?

**Comment by devsaurus** [comment]
Will have a look.
