### ISSUE TITLE
Remove wifi.sta.eventmonreg

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1893]
#1889 deprecated `wifi.sta.eventmonreg`. Remove the function after the next master drop.

**Comment by marcelstoer** [comment]
@dnc40085 I tried to assign this issue to you but GitHub wouldn't let me because you're not an official maintainer 😞 Still, we'd be happy if you could take care of this once the next master drop is completed.

**Comment by dnc40085** [comment]
@marcelstoer yeah, no problem. I can do that.
