### ISSUE TITLE
DNS TXT Record Lookup Support

### ISSUE THREAD

**Issue by greglangford** [nodemcu/nodemcu-firmware#1898]
8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
It would be a really good feature to be able to perform DNS TXT lookups using the NodeMCU firmware. By doing so would allow tunnelling of data over DNS packets. Most open networks with captive portals still allow DNS traffic which means IoT devices could be in the wild with no supporting network infrastructure. All of the communication is performed using DNS queries and responses.

### Workarounds
I am looking at sending hand crafted UDP packets to achieve this functionality but it is very messy.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
It'd be a nice feature that's true but in line with #1010 I want to close this unless you can resource the development yourself.
