### ISSUE TITLE
Not support SPI slave

### ISSUE THREAD

**Issue by iFish85** [nodemcu/nodemcu-firmware#1922]
I can see there are some slave-related codes in app/driver/spi.c, but why platform_spi_setup() hardcode spi_master_init() ?
Also the document shows that "spi.SLAVE - not supported currently"
Is there any known serious issues on spi slave implementation?

Thanks

**Comment by djphoenix** [comment]
> Is there any known serious issues on spi slave implementation?

Yes - this is still undone :) And noone who need it and have time+skill to implement.

**Comment by iFish85** [comment]
> Yes - this is still undone :) And noone who need it and have time+skill to implement.
Fortunately, we need this slave function on our production...
I find the esp8266 SDK (NONOS and RTOS) already include SPISlaveSendData/SPISlaveRecvData, if these functions can works well, Lua api also can be implemented, right?
Anyway, I will try to implement it.

Thanks.
