### ISSUE TITLE
Captive Portal

### ISSUE THREAD

**Issue by inversesandwich** [nodemcu/nodemcu-firmware#193]
Would it be possible to have a captive portal function for when the ESP8266 is being used as an AP

**Comment by raz123** [comment]
See: https://github.com/hamishcunningham/fishy-wifi/tree/master/joinme

**Comment by inversesandwich** [comment]
@raz123 That is not a captive portal, I still have to browse to 192.168.4.1

**Comment by slaff** [comment]
Such a functionality would be great! Is EPS8266 providing its own DNS server? May be a fake DNS server can be written that redirects all  hosts to 192.168.4.1 when the "captive" mode is activated.

**Comment by layerzerolabs** [comment]
Hiya - fishy-wifi people here - we're still working on exactly that 'fake' dns server idea to achieve a true captive portal. If you'd like to collaborate to speed this feature up then pls ping us a message. Cheers!

**Comment by marcelstoer** [comment]
See http://www.areresearch.net/2015/09/new-captiveintraweb-release-v3-esp8266.html.
