### ISSUE TITLE
No rule to make target  - Problem in compiling the esp32 branch.

### ISSUE THREAD

**Issue by helxsz** [nodemcu/nodemcu-firmware#1931]
Problem in compiling the esp32 branch.

### NodeMCU version
esp32 branch

### Hardware
esp32 supported development board

### Environment
My environment is MAC

 it works for the first time, however the second time I tried to compile the code, I encountered a error: 

```
Setting IDF_PATH and re-invoking...
GENCONFIG
make[2]: *** No rule to make target `/Users/helxsz/Documents/projects/nodemcu-firmware-esp32/build/bootloader/bootloader.bin'.  Stop.
make[1]: *** [/Users/helxsz/Documents/projects/nodemcu-firmware-esp32/build/bootloader/bootloader.bin] Error 2
make: *** [all] Error 2
```

**Comment by marcelstoer** [comment]
Likely related to #1932, update `make` to >= 4.0?
