### ISSUE TITLE
ESP32 How to use wifi?

### ISSUE THREAD

**Issue by kevinlovejia** [nodemcu/nodemcu-firmware#1935]
### Expected behavior
I want to use wifi.sta.status and  wifi.STA_GOTIP these two function. I  saw #1615 in the TO DO list, are these two function are deprecated? If these are, how can I know nodemcu module got IP?

### Actual behavior
Serial Terminal print these all the time:
I(2125) wifi: n:11 2, o:1 0, ap: 255 255, sta:11 2, prof:1
I(3115) wifi: state: init  -> auth(b0)
I(3115) wifi: state: auth -> init(0)
I(3415) wifi: n:11 2, o:11 2, ap: 255 255, sta: 11 2, prof:1
I(3535) wifi: n:11 2, o:11 2, ap: 255 255, sta: 11 2, prof:1
I(3535) wifi: state: init  -> auth(b0)
I(3535) wifi: state: auth -> init(0)

### Test code
```Lua
local function getwifistatus() 
   -- status = wifi.sta.status() 
    print_wifi_status(status)
    if (status == wifi.STA_WRONGPWD or status == wifi.STA_APNOTFOUND) then
        tmr.unregister(timer_wifi)
        node.restart()
    end
    if status ~= wifi.STA_GOTIP then    
        onReconectedWIFI()
    else
        tmr.unregister(timer_wifi)        
        onWIFIConnected() 
    end 
end

function module.start()  
    wifi.mode(wifi.STATION, true)
    wifi.start()
    wifi.sta.config({ssid="TP-LINKA", pwd="1234565789", auto=true}, true)
    timer_wifi = tmr.create(); 
    timer_wifi:register(10000, tmr.ALARM_AUTO,getwifistatus); 
    timer_wifi:interval(1000); 
   timer_wifi:start();
end
```
### NodeMCU version
Nodemcu : dev-esp32
ESP-IDF v2.0-rc1-597-gf73c6f87 2nd stage bootloader
NodeMCU ESP32 build unspecified powered by Lua 5.1.4

### Hardware
ESP32S

**Comment by FrankBuss** [comment]
This script works with the firmware from today and loads another script init2.lua from a webserver and executes it:

```
collectgarbage("setmemlimit", 64)

function executeString(s)
	local fun = loadstring(s)
	fun()
end

function stripHeader(s)
	local pos = string.find(s, "\r\n\r\n")
	return s:sub(pos + 4)
end

function runScript(host, url)
	receivedPage = ""
	conn = net.createConnection(net.TCP, 0) 
	conn:on("receive", function(conn, data) receivedPage = receivedPage .. data end)
	conn:on("disconnection", function(conn, data) pcall(function() executeString(stripHeader(receivedPage)) end) end)
	conn:on("connection", function() pcall(function() conn:send("GET /" .. url .. " HTTP/1.1\r\nHost: " .. host .. "\r\nConnection: close\r\n\r\n") end) end)
	conn:connect(80, host)
end

wifi.sta.on("got_ip", function(ev, info)
	wifi.sta.on("got_ip", nil)
	print("NodeMCU IP config:", info.ip, "netmask", info.netmask, "gw", info.gw)
	runScript("192.168.11.27","init2.lua")
end)

wifi.mode(wifi.STATION)
wifi.start()
station_cfg={}
station_cfg.ssid="ssid"
station_cfg.pwd="password"
wifi.sta.config(station_cfg)
```

The collectgarbage command is useful, if you need to load bigger scripts, because it increases the limit for strings to 64 kB.
