### ISSUE TITLE
ESP32: CAN module

### ISSUE THREAD

**Issue by zelll** [nodemcu/nodemcu-firmware#1948]
### Missing feature
ESP32 has a built-in CAN controller. We need a module for it in nodemcu ~

### Justification
Why not? :)

### Workarounds
MCP2515 + SPI ? 

---------
https://esp32.com/viewtopic.php?f=12&t=380 Discussion
https://github.com/eerimoq/simba/commit/46778af636a4fe58773753b5ed9da83916cfaa06 Driver
https://github.com/ThomasBarth/ESP32-CAN-Driver/ ESP-IDF based driver

**Comment by zelll** [comment]
And here is a feature branch [dev-esp32-can](https://github.com/zelll/nodemcu-firmware/tree/dev-esp32-can/) ,based on @ThomasBarth 's driver.
Checked on an oscilloscope. I'll test it on a real CAN bus when I get my CAN device next week.

**Comment by jmattsson** [comment]
Cool! I can't test it, but I'd certainly like to see it added when you've tested it!
