### ISSUE TITLE
init.lua uses old WiFi code

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1951]
When @dnc40085 updated the `wifi.sta.config()` implementation to use the table notation we forgot to update https://nodemcu.readthedocs.io/en/latest/en/upload/#initlua accordingly.

**Comment by dnc40085** [comment]
I knew I forgot something, I can submit a PR to fix this.

Concerning issue #1940, should I include an update for `wifi.sta.config()` to be persistent in the PR?

**Comment by marcelstoer** [comment]
You added `save=true` explicitly which I believe is the right thing to dol
