### ISSUE TITLE
write large file , esp auto reboot

### ISSUE THREAD

**Issue by etimes2008** [nodemcu/nodemcu-firmware#1963]
nodemcu-firmware-2.0.0-master_20170202`

```
spi.setup(1, spi.MASTER, spi.CPOL_LOW, spi.CPHA_LOW, 8, 8)

vol = file.mount("/SD0")
if not vol then
  print("retry mounting")
  vol = file.mount("/SD0")
  if not vol then
    error("mount failed")
  end
end

if file.open("/SD0/test.txt", "a+") then
  for i=0, 10000, 1 do
     if not file.write('etimes2008 etimes2008 etimes2008 etimes2008 etimes2008\n') then
          print("write err")
     end
     file.flush()
     tmr.delay(1000)
  end
  file.close()
else
     print("open file fail")
end
```

print:
NodeMCU 2.0.0 build unspecified powered by Lua 5.1.4 on SDK 2.0.0(656edbf)
lua: cannot open init.lua
> spi.setup(1, spi.MASTER, spi.CPOL_LOW, spi.CPHA_LOW, 8, 8)
> vol = file.mount("/SD0")
> if not vol then
print("retry mounting")
vol = file.mount("/SD0")
if not vol then
error("mount failed")
end
end
> --print(file.rename("200KB","/SD/200KB"))
> --
> --l = file.list();
> --for k,v in pairs(l) do
> --  print("name:"..k..", size:"..v)
> --end
> if file.open("/SD0/test.txt", "a+") then
for i=0, 10000, 1 do
if not file.write('etimes2008 etimes2008 etimes2008 etimes2008 etimes2008\n') then
--          print("write err")
end
--     file.flush()
--     tmr.delay(1000)
end
file.close()
else
print("open file fail")
end

 ets Jan  8 2013,rst cause:2, boot mode:(3,3)

load 0x40100000, len 26844, room 16 
tail 12
chksum 0x5c
ho 0 tail 12 room 4
load 0x3ffe8000, len 2236, room 12 
tail 0
chksum 0x20
load 0x3ffe88bc, len 136, room 8 
tail 0
chksum 0x17
csum 0x17

**Comment by etimes2008** [comment]
2g tf card is ok

**Comment by pastukhov** [comment]
Try to feed the watch dog with [tmr.wdclr()](https://nodemcu.readthedocs.io/en/dev/en/modules/tmr/#tmrwdclr)
