### ISSUE TITLE
sjson should trim trailing null bytes

### ISSUE THREAD

**Issue by rtahiry** [nodemcu/nodemcu-firmware#1989]
### Expected behavior
sjson.decode() (and possibly encode()) should trim trailing null bytes. This is particularly important when the json string was encrypted and usually terminated by a null byte. (Null bytes in-between characters may be another issue since they are allowed in lua strings)
### Actual behavior
sjson.decode() throws a FOUND_NULL_BYTE exception when string has trailing null bytes. The following snippet shows this behavour and confirms that decoding goes through when trailing null bytes are removed.
### Test code

```Lua
=sjson.decode('{}')
table: 3fff0408
> cypher=crypto.encrypt("AES-ECB","1234567891234567", '{}')
> text=crypto.decrypt("AES-ECB","1234567891234567", cypher)
> =text
{}
> =sjson.decode(text)
stdin:1: JSON parse error: FOUND_NULL_BYTE
stack traceback:
	[C]: in function 'decode'
	stdin:1: in main chunk
> text=text:gsub('%z.*','')
> =sjson.decode(text)
table: 3fff0408
> 
```
### NodeMCU version
Nodemcu dev branch built from nodemcu-build.com with sjson and crypto libraries.

**Comment by adoconnection** [comment]
+1 because its breaking change.
sjson.decode is not compatible with cjson.decode because of this

**Comment by pjsg** [comment]
I can certainly change the default behavior so that it ignores data after the end of the decoded object. I think that the padding done by the crypto.encrypt is probably wrong in this case (padding with nulls is not recommended). The most commonly used padding is to fill out the block with repeated bytes indicating how many bytes are pads. See RFC 5652, RFC 1423.

**Comment by adoconnection** [comment]
> the padding done by the crypto.encrypt is probably wrong 

You are absolutely right. Yet, old implementation in cjson.decode handled this case correcly.

**Comment by marcelstoer** [comment]
> Yet, old implementation in cjson.decode handled this case correcly.

It's never too late to correct old issues...
