### ISSUE TITLE
wifi.ap.setip() does not set ip address

### ISSUE THREAD

**Issue by SpaceTeddy** [nodemcu/nodemcu-firmware#199]
can not set IP address in SOFTAP mode. 
any idea?

-------------snip------------------------
> wifi.sta.disconnect()
> print(wifi.sta.getip())
nil
> wifi.setmode(wifi.SOFTAP)
> wifi.ap.config({ssid="myssid",pwd="12345678"})
> print(wifi.ap.getip())
192.168.4.1.255.255.255.0.192.168.4.1
> wifi.ap.setip({ip="10.10.10.1",netmask="255.255.255.0",gateway="10.10.10.1"})
> print(wifi.ap.getip())
192.168.4.1.255.255.255.0.192.168.4.1
> 

Node: 0.9.5

**Comment by vowstar** [comment]
![qq 20150212223923](https://cloud.githubusercontent.com/assets/394260/6169511/f27ea290-b308-11e4-867b-76777f460e1f.png)
