### ISSUE TITLE
I2C driver module for CAP1298

### ISSUE THREAD

**Issue by krishnakumar93** [nodemcu/nodemcu-firmware#2001]
Please provide i2c driver module for CAP1298 capacitive touch sensor IC.

**Comment by marcelstoer** [comment]
As per point 2 of #1010 I'm closing this.

**Comment by rahulms12** [comment]
Please provide the CAP1298 driver

**Comment by FrankX0** [comment]
First of all: #1010
This does not require a driver in the firmware: just implement in Lua.
