### ISSUE TITLE
When restart the esp8266 in several times,may cause cannot boot to nodemcu

### ISSUE THREAD

**Issue by hoxcape** [nodemcu/nodemcu-firmware#2002]
When the hardware be restarted in several times,or the power is not so steady,it will cause a insure that cannot boot to nodemcu.

When we flash again,the insure is disappeared,but this insure is not actually solved.

Is there any similar situation to this?
Thanks for any advice.

### NodeMCU version
1.5.4.1

### Hardware
ESP-12f

**Comment by marcelstoer** [comment]
Definitely looks like a hardware issue to me -> closing
