### ISSUE TITLE
Where are the bin firmware files for flashing with NodeMCU Flasher?

### ISSUE THREAD

**Issue by HermanLacuna** [nodemcu/nodemcu-firmware#2004]
Hi

This is my first time working with ESP and NodeMCU. I want to flash on your latest firmware using the NodeMCU Flasher. I can't seem the bin files however to do so. Could you please direct me as to where I can find the actual bin files.

Regards,

Herman

**Comment by hanfengcan** [comment]
look at here
http://www.jianshu.com/p/78b1400aa56e

Chinese only

**Comment by devsaurus** [comment]
See the docs for building the firmware at http://nodemcu.readthedocs.io/en/master/en/build/. I recommend the could build service.

Closing according #1010.
