### ISSUE TITLE
sjson fails decoding multiline json with number or bool

### ISSUE THREAD

**Issue by HHHartmann** [nodemcu/nodemcu-firmware#2005]
### Expected behavior
these exampled should be decodable (note the multiline)

{"number": 12
} 

{"bool": false
} 

### Actual behavior
errors are thrown:
stdin:1: JSON parse error: INVALID_NUMBER
stdin:1: JSON parse error: SPECIAL_EXPECTED

Without the \n it works like a charm
Also strings have no problem

### Test code
s = "{\"number\": 12\n}" 
o = sjson.decode(s)
s = "{\"bool\": false\n}" 
o = sjson.decode(s)

### NodeMCU version
NodeMCU custom build by frightanic.com
	branch: master
	commit: c8ac5cfb912ff206b03dd7c60ffbb2dafb83fe5e
	SSL: true
	modules: bit,file,gpio,http,i2c,net,node,ow,pwm,rtctime,sjson,sntp,tmr,uart,wifi,tls
 build 	built on: 2017-06-17 17:53
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

### Hardware
standard esp8266 E12 DEV Board

**Comment by pjsg** [comment]
This was my bad. I only tested with spaces and I had a typo.....
