### ISSUE TITLE
mdns not responding properly in STATIONAP mode

### ISSUE THREAD

**Issue by RadianM** [nodemcu/nodemcu-firmware#2022]
mdns should respond to both local AP requests (e.g. browsers connecting to our default IP 192.168.4.1) and LAN requests to DHCP allocated IP (e.g. 192.168.1.100) - as evidenced by this Arduino ESP8266 issue [here](https://github.com/esp8266/Arduino/commit/3e19c6e4b73fa51fa921e3a329a160732503a85d)

Actual behavior is that initially on setting STATIONAP mode and registering a hostname with mdns, only requests from devices connected direct to AP are resolved. When a DHCP IP is obtained, mdns requests from browsers across the LAN receive no reply.

Once mode is changed to STATION, without even re-registering the mdns module, it begins to  respond to browsers across the LAN. The SDK would seem to be able to handle zeroconfig requests simultaneously in both modes so it appears to be an issue that could be fixed.

Test code:
```
host="ESP-"..node.chipid()

wifi.eventmon.register(wifi.eventmon.STA_GOT_IP, function(T)
print("\n\tSTA - GOT IP".."\n\tStation IP: "..T.IP.."\n\tSubnet mask: "..T.netmask.."\n\tGateway IP: "..T.gateway)
--mdns.register(host) --apparently unnecessary even though we have only just got our IP from LAN gateway
--mdns only starts responding over LAN when AP mode turned off (after 1 minute here)...
tmr.alarm(0, 60000, tmr.ALARM_SINGLE, function() wifi.setmode(wifi.STATION) print("AP Down") end)
end)

--to begin with mdns only responds to requests over our local AP when in STATIONAP mode
wifi.setmode(wifi.STATIONAP) --IP presumably obtained from our AP (192.168.4.1)
mdns.register(host)
local cfg={}
cfg.ssid="ssid"
cfg.pwd="password"
wifi.sta.config(cfg)
```
Tested using a zeroconfig (Bonjour) browser e.g. Android app  [ZeroConf](https://play.google.com/store/apps/details?id=com.melloware.zeroconf&hl=en_GB)
NodeMCU cloud build Dev version Lua 5.1.4 on SDK 2.1.0(116b762) ESP8266-12E

**Comment by pradeepshankara** [comment]
Any updates here? We are also stuck with the same issue.
