### ISSUE TITLE
sjson module causes unresolved symbols

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#2023]
### Expected behavior
 - No unresolved symbols after linking the firmware ELF.
 - Firmware build should fail if there are unresolved symbols.

Initially observed by @dnc40085 over in #1755. Historically `esptool.py` has bailed out if there are undefined symbols, but clearly the current version we have in our tree does not.

I have no idea why this wasn't failing horribly for @pjsg during testing...

### Actual behavior
```
../tools/esptool.py elf2image --flash_mode dio --flash_freq 40m .output/eagle/debug/image/eagle.app.v6.out -o ../bin/
esptool.py v1.2-dev
Warning: ELF binary has undefined symbol calloc
Warning: ELF binary has undefined symbol free
```
### Test code
Include the SJSON module in the build.

### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.
`dev`

### Hardware
n/a

**Comment by jmattsson** [comment]
So it seems none of the functions which use `calloc`/`free` aren't actually used by the Lua module, and thus haven't caused actual problems. Now to work out why those functions are even included in the ELF after the linking...

**Comment by jmattsson** [comment]
Erk, why did we end up `#include`ing a .c file here?

**Comment by jmattsson** [comment]
Okay, I'm getting an appreciation for why a harsh `#include` was picked... curse the NON-OS SDK's non-standard include files to Hel and back **sigh**

**Comment by jmattsson** [comment]
Fascinating. If I build jsonsl.c into a library like everything else, things break at runtime.

**Comment by gbox3d** [comment]
resut = sjson.encode({code="print(\"hello\")"})
result is
"{\"code\":\"print(\"hello\")\"}"
it may be wrong

right result is "{\"code\":\"print(\\\"hello\\\")\"}" 

it is bug?
