### ISSUE TITLE
Keyboard Emulation Support

### ISSUE THREAD

**Issue by nilsbrychzy** [nodemcu/nodemcu-firmware#2029]
### Missing feature
HID.h so https://github.com/arduino-libraries/Keyboard could be used

### Justification
The NodeMCU has a mcro usb plug so you can connect to pc and complete automated tasks.

### Workarounds
- Remote Keyboard Control (like remote shutdown)
- Smart Home (like "Hey Alexa, start netflix")

**Comment by marcelstoer** [comment]
From what I understand this is essentially a dup of #1917.

**Comment by ccxx72** [comment]
I think it's the opposite of #1917.
In the #1917 they need to connect some HID periferals to the board and use the periferal as input.
In this case we need to use NodeMcu, or others devboard with an USB port, as a HID keyboard. 
Shortly, it's a keyboard emulation. I don't know if it's possible. Teensy can do that.

**Comment by pjsg** [comment]
It isn't possible on Nodemcu as the USB chip is a dedicated serial port USB chip. There is a software USB implementation: http://hackaday.com/2016/09/03/software-usb-on-the-esp8266/ but I have no information about it. It *might* be able to do what you want -- but it certainly isn't integrated into the lua firmware.

**Comment by nilsbrychzy** [comment]
Thanks! I'm new in that stuff so yeah
