### ISSUE TITLE
Trigonometric functions

### ISSUE THREAD

**Issue by KOT-KOCMOCMOHABT** [nodemcu/nodemcu-firmware#2036]
How to enable Trigonometric functions in
https://github.com/nodemcu/nodemcu-firmware
before
docker run --rm -ti -v pwd:/opt/nodemcu-firmware marcelstoer/nodemcu-build ?
need math.sin(), math.cos(), math.tang() and more

**Comment by marcelstoer** [comment]
See #1280.
