### ISSUE TITLE
ESP32: node.output - missing

### ISSUE THREAD

**Issue by Beckett2000** [nodemcu/nodemcu-firmware#2045]
8<------------------------ FEATURE REQUEST -----------------------------------------
### Missing feature

The node.output function from the node romtable does not seem to be included.

```Lua
for k,v in pairs(node) do print(k) end
```

<strong> Returns: </strong>

chipid
compile
dsleep
egc
heap
input
osprint
restart
stripdebug
task

### Justification

The node.ouput function is useful for redirecting the print function, and is used in the <strong>telnet.lua</strong> example for server output. 

### Workarounds

Redefine <strong>print </strong>:

```Lua
local _oldPrint = print

function print(...)
 -- Do something with the print output ...
 return _oldPrint(...)
end
```
or 

```Lua

local _oldPrint = print

function nodeOutput(func,serial_output)
   if func == nil then 
      print = _oldPrint return
   elseif serial_output == nil or serial_output == 1 then
      print = function(...) func(...)  _oldPrint(...) end
   elseif serial_output == 0 then
      print = function(...) func(...) end 
   end
end
   
```

### NodeMCU version

NodeMCU on ESP32
Branch: dev-esp32
Commit: c8ac5cfb912ff206b03dd7c60ffbb2dafb83fe5e

8<------------------------ END FEATURE REQUEST -------------------------------------

**Comment by jpeletier** [comment]
Fixed in #2637
