### ISSUE TITLE
Redirect to captive portal after connect to AP

### ISSUE THREAD

**Issue by metraport** [nodemcu/nodemcu-firmware#2051]
How is it possible to open a browser in Android / IOS after connect to AP in endusersetup with IP 192.168.4.1 ?

I've setted up a Fake DNS Response returning 192.168.4.1, but there will be no browser window opened after connection.

**Comment by djphoenix** [comment]
For iOS Captive Portal (not sure for Android) you need to also handle *all* incoming HTTP request and redirect them to EUS.

**Comment by marcelstoer** [comment]
Not in line with #1010 -> closing
