### ISSUE TITLE
Can't run more than once. Can't print anything.

### ISSUE THREAD

**Issue by zszen** [nodemcu/nodemcu-firmware#2083]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
1.print words.
2.Can repeat save and run again.

### Actual behavior
1.Don't display print words. 
2.Save again don't run again.  "Waiting answer from ESP - Timeout reached. Command aborted."

### Test code
connection info  :
NodeMCU custom build by frightanic.com
	branch: master
	commit: b62fae918b3627209fe434950cffb2506cee9a31
	SSL: false
	modules: adc,ads1115,am2320,bit,cron,crypto,encoder,file,gpio,i2c,net,node,ow,pcm,pwm,rtctime,sjson,spi,struct,switec,tmr,u8g,uart
 build 	built on: 2017-08-22 00:26
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

**Comment by zszen** [comment]
I use it control 12-pin digital display. It maybe convert tx/rx to gpio control. So each test I must reset the chipboard. And luck I don't run it as init.lua. It will never be written in. Other wise format it.
![100014621159_14286419627799](https://user-images.githubusercontent.com/1890538/29580763-b5ac7e50-87a9-11e7-97cc-0cfdaf5ef0f7.jpg)

**Comment by marcelstoer** [comment]
See #1010
