### ISSUE TITLE
ESP32: Missing feature for wifi setip/sethostname

### ISSUE THREAD

**Issue by LDmitryL** [nodemcu/nodemcu-firmware#2085]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
wifi.sta.sethostname() 
wifi.sta.setip()
wifi.sta.setmac()

### Justification
Really miss this functionality in ESP32

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by devsaurus** [comment]
Not stale, but resolved by related PR.
