### ISSUE TITLE
sjson encode function bug

### ISSUE THREAD

**Issue by gbox3d** [nodemcu/nodemcu-firmware#2099]
resut = sjson.encode({code="print(\\"hello\\")"})
result is
"{\\"code\\":\\"print(\\"hello\\")\\"}"
it may be wrong

right result is "{\\"code\\":\\"print(\\\\\\"hello\\\\\\")\\"}"

is it bug?

**Comment by TerryE** [comment]
PC cjson:  `{"code":"print(\"hello\")"}`
NodeMCU sjson:  `{"code":"print("hello")"}`

So yes it is a bug.
