### ISSUE TITLE
Loosing WiFi (station) connection

### ISSUE THREAD

**Issue by iMarvinS** [nodemcu/nodemcu-firmware#210]
I'm using NodeMCU 0.9.5 build 20150212 on the ESP-07 and ESP-12.
Both are loosing WiFi connection to my accesspoint (WD MyNet N600) after some minutes (I can´t really measure it).
The connection only gets lost after some minutes of inactivity (no TCP socket is connected).
If I continuously ping the IP the connection does not get lost and I can send requests to it every time.
The @nodeMCU support on Twitter already told me to use a external antenna with the ESP-07 but it also does not work (also isn´t applicable on the ESP-12 ).

Does anyone have advice for this issue?

**Comment by vowstar** [comment]
Is this ap?
![qq 20150213134015](https://cloud.githubusercontent.com/assets/394260/6182808/2ba64ef6-b386-11e4-90fc-9e049d6ef361.png)
![t2gq8 x2fxxxxxxxxx-31125042](https://cloud.githubusercontent.com/assets/394260/6182811/41072e32-b386-11e4-8ef6-642d5a78e374.jpg)

I think WD MyNet N600 is special, it is may a SDK bug. I'll send this issue to espressif and they will test how to support this ap.

**Comment by iMarvinS** [comment]
That´s the right one.
I´ll try it with a FRITZ!Box 7362 provided by my ISP.

**Comment by vowstar** [comment]
This issue have replied by espressif. Some ap will kick station during sometime have no communication, it is normal.

**Comment by iMarvinS** [comment]
This is indeed a problem with the N600 Accesspoint. With a FRITZ!Box both modules work just fine. 
After analyzing some logs of the N600 I saw the issue described by espressif.

Maybe a DD-WRT installation on the N600 can help to solve the issue.

For now this issue can be closed.
