### ISSUE TITLE
wifi.ap.setip doesn't work sometimes

### ISSUE THREAD

**Issue by gridnow** [nodemcu/nodemcu-firmware#2100]
hi guys:
  i am using esp8266 in softap mode, and called wifi.ap.setip with:

wifi.setmode(wifi.SOFTAP, true)
cfgTemp 		= {}
cfgTemp.ip      = "192.168.1.1"
cfgTemp.netmask = "255.255.255.0"
cfgTemp.gateway = "192.168.1.1"
wifi.ap.setip(cfgTemp)

and connect with iphone, but sometimes I got the ip with 192.168.4.x ( gateway is 192.168.4.1) in iphone's wifi detail page.
and sometimes is correct.  I have updated my fireware to newest code:
2e67ff5a639a13260fd4fb3c3b627ccdc2845616
but it still happens. any suggest is appreciated,  thanks a lot!

**Comment by tc1989tc** [comment]
I also meet this issue.
