### ISSUE TITLE
how to turn off high frequency clock

### ISSUE THREAD

**Issue by zhao007z4** [nodemcu/nodemcu-firmware#2106]
Now esp8266 run in deep sleep. but i will consume 1.8mA. too much.

i find some info. it tell to turn off high frequency clock. it will consume 88uA。

so i want to know how to turn off 

https://www.hackster.io/fablabeu/esp8266-thing-by-sparkfun-982bc6
Current Optimization:
As the ESP8266 has a combined HF and application processing on a single MCU the Wifi operation take most of the 100+ mA during normal operation, even it is not transmitting any data. Two reduce the power there are two options: switching off the HF part (yes there is LUA command) or putting the ESP8266 (like the lander on the comet) into a deep sleep mode - switching off all components except a timer for waking up the ESP8266: roughly 88uA is the current consumption during deep sleep. A huge difference!

**Comment by TerryE** [comment]
This is really a Q for StackOVerflow, not here, but please read [node.setcpufreq](https://nodemcu.readthedocs.io/en/master/en/modules/node/#nodesetcpufreq).
