### ISSUE TITLE
should be rmt_get_ringbuf_handler ?

### ISSUE THREAD

**Issue by kostousov-ds** [nodemcu/nodemcu-firmware#2110]
https://github.com/nodemcu/nodemcu-firmware/blob/7448d21afa6d05b58c51717b030fc33d2ab59ebc/components/platform/onewire.c#L144

**Comment by kostousov-ds** [comment]
https://github.com/nodemcu/nodemcu-firmware/blob/7448d21afa6d05b58c51717b030fc33d2ab59ebc/components/platform/dht.c#L96

**Comment by devsaurus** [comment]
Espressif changes the API recently. You're probably missing an update of the esp-idf submodule.
