### ISSUE TITLE
Error "open a file first". Issue on file systems?

### ISSUE THREAD

**Issue by LoveDaisy** [nodemcu/nodemcu-firmware#2118]
My codes ran well on my ESP device but suddenly cannot be connected and stopped. I tried to write new scripts to the device but failed. Neither can I run any existed script on the device. It just kept showing error "open a file first". Seems there's something wrong with file systems?

Does anyone has any idea?

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
1. Any normal codes that run properly. or
2. Write a script via ESPlorer

### Actual behavior
Show "open a file first" error. Something like follows:
```shell
NodeMCU 2.1.0 build 2017/06/20 powered by Lua 5.1.4 on SDK 2.1.0(116b762)
do file init.lua
do file flashmod.lua
lua: flashmod.lua:11: open a file first
stack traceback:
	[C]: in function 'write'
	flashmod.lua:11: in function 'flashMod'
	flashmod.lua:24: in main chunk
	[C]: in function 'dofile'
	init.lua:3: in main chunk
	[C]: ?
```

### Test code
```Lua
-- any codes that run properly before
```
### NodeMCU version
at master branch

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.

8<------------------------ END BUG REPORT -------------------------------------

**Comment by TerryE** [comment]
Closed because of timeout.
