### ISSUE TITLE
Two servers on two different ports

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2124]
Is it possible to run two different servers on two different ports in same IP?

**Comment by eku** [comment]
Yes, one UDP and one TCP.

**Comment by chathurangawijetunge** [comment]
I have managed to successfully run two TOP servers.
E.g. 192.168.1.20:80 and
        192.168.1.20:3030

**Comment by chathurangawijetunge** [comment]
I have managed to successfully run two TCP servers.
E.g. 192.168.1.20:80 and
192.168.1.20:3030
