### ISSUE TITLE
enduser setup doesn't connect, most of the time (failed password)

### ISSUE THREAD

**Issue by Inigovd** [nodemcu/nodemcu-firmware#2131]
### Expected behavior
enduser_setup.start() starts AP, allows user to connect, shows html page, and allows to connect to Wi-Fi network

### Actual behavior
Everything works up until the selection of my Wi-Fi network. Mostly returns 'Failed - wrong password'. Sometimes it will connect, after many reboots and retries. 100% certain the password is correct and working, and is the entered the same time every time.

Console keeps spamming the following from the moment I enter my wifi credentials:
```
state: 5 -> 2 (fc0)
rm 0
reconnect
state: 2 -> 0 (0)
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
```

### Test code
```
enduser_setup.start(
            function()
                print("connected!")
            end,
            function(err, str)
                print("Err #" .. err .. ": " .. str) 
            end,
            function(message)
                print(message)
            end
        )
```
 
### NodeMCU version
master branch, tested both float and integer .bins I built myself with docker, and a .bin file from https://nodemcu-build.com/ using "This was built against the master branch and includes the following modules: bit, crypto, enduser_setup, file, gpio, http, i2c, net, node, sjson, tmr, uart, wifi.".

### Hardware
WiFi ESP8266, USB-TTLCH340, WeMos branded

**Comment by marcelstoer** [comment]
No confirmation from anyone else that this is indeed a bug -> closing
