### ISSUE TITLE
KRACK vulnerability

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2138]
I see that Espressif has announced that they have resolved this issue -- so we should probably do a release with the new SDK:

http://espressif.com/en/media_overview/news/espressif-releases-patches-wifi-vulnerabilities-cert-vu228519#.WeVJ91XhAqE.twitter

**Comment by heythisisnate** [comment]
Thank you for raising the issue. I came here looking for a discussion on this vulnerability.

**Comment by marcelstoer** [comment]
Waiting for https://github.com/espressif/ESP8266_NONOS_SDK/issues/46

**Comment by marcelstoer** [comment]
If I interpret @FayeY's and @wujiangang's comments on espressif/ESP8266_NONOS_SDK#46 correctly then there won't ever be an official 2.1.x release with just the KRACK fix but a 2.2 later this month.

**Comment by marcelstoer** [comment]
Superseded by #2225.
