### ISSUE TITLE
Use of tmr.suspend() or tmr.resume() with tmr.alarm() Throws an Error

### ISSUE THREAD

**Issue by jmd13391** [nodemcu/nodemcu-firmware#2140]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
As per NodeMCU Read the Docs:

https://nodemcu.readthedocs.io/en/master/en/modules/tmr/#tmrsuspend
tmr.suspend()
Suspend an armed timer.
Example
--suspend timer mytimer
mytimer:suspend()

https://nodemcu.readthedocs.io/en/master/en/modules/tmr/#tmrresume
tmr.resume()
Resume an individual timer.
Example
--resume timer mytimer
mytimer:resume()

### Actual behavior

Use of either method throws an error:
attempt to call method 'suspend' (a nil value)
attempt to call method 'resume' (a nil value)

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
mytimer = tmr.create()
mytimer:alarm(60000,tmr.ALARM_AUTO,function() print("test") end)
mytimer:suspend()  -- mytimer:resume() will also fail here
```
### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.

2.1.0-master_20170824

NodeMCU custom build by frightanic.com
	branch: master
	commit: 2e67ff5a639a13260fd4fb3c3b627ccdc2845616
	SSL: false
	modules: file,gpio,net,node,tmr,uart,websocket,wifi
 build 	built on: 2017-08-26 23:08
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.

Amica ESP8266
=node.info(): 2	1	0	1183817	1458400	4096	2	40000000
=node.chipid(): 1183817
=node.flashid(): 1458400

8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
Those functions are not compiled into the firmware by default: http://nodemcu.readthedocs.io/en/latest/en/modules/tmr/#tmrsuspend. Sorry, the docs didn't mention this until now (PR #2107 was idle for a month).
