### ISSUE TITLE
rtc time not kept through deep sleep

### ISSUE THREAD

**Issue by mkresse** [nodemcu/nodemcu-firmware#2144]
### Expected behavior

Setting the rtc time using `rtctime.set(0,0)` enables the realtime clock so that after a deep sleep, a call to `rtctime.get()` returns the curren (up-) time. This works on a version build from master on 2017-06-17. 
The example code outputs "phase 1", goes to deepsleep and then prints "phase 2".

### Actual behavior

Using a current master build (2017-10-12), reading the time using `rtctime.get()` always returns 0.
The example code outputs "phase 1" in an endless loop. I suppose that the changes of commit d93465c have something to do with the changed behaviour?

### Test code
```Lua
    local sec, usec = rtctime.get()
    if (sec == 0) then
        print("phase 1, initializing time + sleeping 2s");
        rtctime.set(0, 0)

        tmr.create():alarm(100, tmr.ALARM_SINGLE, function()
            rtctime.dsleep(2 * 1000 * 1000)
        end)
        
    else
        print(string.format("phase 2, uptime: %ds", sec));
    end
```
### NodeMCU version

Working version:
````
NodeMCU custom build by frightanic.com
	branch: master
	commit: c8ac5cfb912ff206b03dd7c60ffbb2dafb83fe5e
	SSL: false
	modules: adc,bit,cron,file,gpio,mqtt,net,node,rtcmem,rtctime,sntp,tmr,uart,wifi,ws2812
 build 	built on: 2017-06-17 20:54
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)
````

Broken version:
```
NodeMCU custom build by frightanic.com
	branch: master
	commit: 2e67ff5a639a13260fd4fb3c3b627ccdc2845616
	SSL: false
	modules: adc,bit,cron,ds18b20,file,gpio,mqtt,net,node,rtcmem,rtctime,sntp,tmr,uart,wifi,ws2812
 build 	built on: 2017-10-12 19:32
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

```

### Hardware

ESP8266 ESP-12F on custom adapter board (http://www.mikrocontroller-elektronik.de/esp12e-tutorial-einstieg-mit-dem-esp8266-modul/)

**Comment by marcelstoer** [comment]
> I suppose that the changes of commit d93465c have something to do with the changed behaviour?

One for @pjsg then?

**Comment by pjsg** [comment]
I'll take a look -- the first thing that occurrs to me is that it is entirely possible that the RTC now doesn't count if it is set to zero (it may treat this as 'unset').

**Comment by mkresse** [comment]
@pjsg Thanks for looking into it. I just tried to set it to a different value - same behaviour.

**Comment by pjsg** [comment]
I'll take a look at the code.... On Oct 20, 2017 16:38, Martin Kresse <notifications@github.com> wrote:@pjsg Thanks for looking into it. I just tried to set it to a different value - same behaviour.

**Comment by pjsg** [comment]
Ugh. I borked it when I made those changes. I'm making progress towards fixing it. One of the challenges is that *some* of the code runs before the bss segment is initialized.

**Comment by pjsg** [comment]
I have a branch at https://github.com/pjsg/nodemcu-firmware/tree/fix-dsleep which (I think) fixes the problem. I'm going to do some more testing.....

**Comment by pjsg** [comment]
It appears that (currently) a 10 second deep sleep causes a 200millisecond clock skew, A 20 second deep sleep is a 600millisecond clock skew. This seems bad.... More investigation needed....
