### ISSUE TITLE
sht3x for nodemcu 

### ISSUE THREAD

**Issue by eric2chek** [nodemcu/nodemcu-firmware#2150]
hi All~
i'm used nodemcu Amica board and build fw on nodemcu-build.com.
i found on google that sht21 can work by si7021 module but it not working with my sht30 and sht31, any idea ?

NodeMCU custom build by frightanic.com
	branch: master
	commit: 443e8219527f5b2190324a969a4586f9d3d731bf
	SSL: false
	modules: adc,bit,coap,dht,enduser_setup,file,gpio,http,i2c,mdns,mqtt,net,node,pwm,rtctime,si7021,sjson,sntp,spi,tmr,uart,websocket,wifi
 build 	built on: 2017-10-23 07:49
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)
lua: cannot open init.lua

**Comment by marcelstoer** [comment]
Another one for #1010
