### ISSUE TITLE
req: NET.SOCKET.GETPEER() to get client IP from socket connection

### ISSUE THREAD

**Issue by SpaceTeddy** [nodemcu/nodemcu-firmware#216]
one nice guy worked out a solution for getting the client IP of a socket connection.
he, and also myself is not able to generate a PR. 
can you add it in the /dev branch please?
thx

info:
http://www.esp8266.com/viewtopic.php?f=21&t=1245#p7261

**Comment by nodemcu** [comment]
now it is in dev branch source code.
will be pre_build bin in next build.
currently please pull and build it from source.
