### ISSUE TITLE
ESP32  I2C read error

### ISSUE THREAD

**Issue by marcel12bell** [nodemcu/nodemcu-firmware#2162]
### Expected behavior
I connected a Si70xx sensor
Reading w/o error

### Actual behavior
error after Reading: /esp-idf/components/driver/./i2c.c:930 (i2c_master_cmd_begin):i2c number error
getting a value back, but i don't understand the Message

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
sensor = i2c.attach(i2c.I2C1, i2c.MASTER, 400000)
sensor:start()
sensor:address(0x40, false)
sensor:write(0xF3)
sensor:start()
sensor:address(0x40, true)
data = sensor:read()
```
### NodeMCU version
dev-ESP32

### Hardware
https://www.silabs.com/documents/public/data-sheets/Si7006-A20.pdf

**Comment by devsaurus** [comment]
Your test code doesn't match the [NodeMCU API for I2C on ESP32](http://nodemcu.readthedocs.io/en/dev-esp32/en/modules/i2c/#i2c-module): There's no `i2c.attach()` function.
I suspect you posted this in the wrong project.
