### ISSUE TITLE
Add API to set WiFi RF power

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#2164]
### Missing feature
Add API to set WiFi RF power

### Justification
When power supply is not a problem you might want to crank up the volume on the WiFi to reach that AP. It's available in Arduino: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp#L285
There's `	system_phy_set_max_tpw` in the SDK: http://espressif.com/sites/default/files/documentation/2c-esp8266_non_os_sdk_api_reference_en.pdf#page=31 -> chapter 3.1.13

@dnc40085 whadayathink?

### Workarounds
Move the device closer to the AP...

**Comment by volatile666** [comment]
push
Shouldnt this be implementable easily?

**Comment by paulblondeau** [comment]
I could really use this feature too.

**Comment by marcelstoer** [comment]
> Shouldnt this be implementable easily?

Tell us once you tried 😜

**Comment by volatile666** [comment]
I did. I failed (not having worked on node mcu before) :D
