### ISSUE TITLE
Feature request: mDns client

### ISSUE THREAD

**Issue by Schwenkner** [nodemcu/nodemcu-firmware#2168]
Is it possible to add mDns client support to the firmware?

My use case is to locate ip of the MQTT broker in my network. The broker is running in the local net and the nodemcu clients have to determine the ip of the broker. The device where the broker is running I can implement the mdns server.

**Comment by marcelstoer** [comment]
> Is it possible to add mDns client support to the firmware?

I'm sure it is (not being a firmware programmer) but basically this is one for #1010. @pjsg wrote the [NodeMCU mDNS _server_ module](https://nodemcu.readthedocs.io/en/latest/en/modules/mdns/). So, if at all he'd be a likely candidate to add mDNS _client_ support to NodeMCU.

**Comment by SimoGira** [comment]
maybe [this](https://github.com/udaygin/nodemcu-mdns-client) can help you
