### ISSUE TITLE
Feature request: upgrade to u8g2 from u8glib

### ISSUE THREAD

**Issue by v1993** [nodemcu/nodemcu-firmware#2169]
### Missing feature
Use u8g2 instead of u8glib.

### Justification
Old library no more develops, new one may contain new fonts, displays, features, fixes.

### Workarounds
Binding it by youself? No another ideas.

**Comment by v1993** [comment]
Link to current repository: https://github.com/olikraus/u8g2.

**Comment by v1993** [comment]
Guide to porting: https://github.com/olikraus/u8g2/wiki/u8gvsu8g2

**Comment by marcelstoer** [comment]
Obviously a dup of #2169

**Comment by v1993** [comment]
Dup of itself?!

**Comment by marcelstoer** [comment]
Sorry, meant #1904. Just search for 'u8g2' in the issues list.
