### ISSUE TITLE
wifi.sta is a nil value

### ISSUE THREAD

**Issue by aj22r** [nodemcu/nodemcu-firmware#2170]
### Expected behavior
The ESP8266 will connect to a wifi access point
### Actual behavior
"stdin:1: attempt to index field 'sta' (a nil value)"
### Test code
```Lua
> wifi.setmode(wifi.STATION)
> wifi.sta.config("ssid", "pass")
stdin:1: attempt to index field 'sta' (a nil value)
> print(wifi.sta.status())
stdin:1: attempt to index field 'sta' (a nil value)
>
```
### NodeMCU version
1.0.20150120

### Hardware
Wemos D1 mini

**Comment by marcelstoer** [comment]
We don't support ancient versions, see #1010

**Comment by aj22r** [comment]
But this is the newest version according to [http://nodelua.org/doc/download_firmware/](http://nodelua.org/doc/download_firmware/)

**Comment by djphoenix** [comment]
@aj22r [NodeLua](https://github.com/haroldmars/nodelua) is another project, and seems like it's not updated in last 3 years.

**Comment by marcelstoer** [comment]
@haroldmars hasn't been active on GitHub in a long time and the last entry on his blog is from April 2014, I guess it's save to assume that NodeLua is dead.
