### ISSUE TITLE
Buy esp8266 noce mcu 1.0 Genuine

### ISSUE THREAD

**Issue by kakaducsy** [nodemcu/nodemcu-firmware#2182]
Hi all
I'm bought esp8266 nodemcu, but it fake. ( have 2 pin D2)
I want bought esp8266 nodemcu v1.0 Genuine. Have you address?

**Comment by TerryE** [comment]
Sorry but this list is for issues  relating to the Lua firmware.

**Comment by marcelstoer** [comment]
https://frightanic.com/iot/comparison-of-esp8266-nodemcu-development-boards/#official-vs-unofficial, it's hard to get these days. This looks genuine but it's expensive: https://www.seeedstudio.com/NodeMCU-v2-Lua-based-ESP8266-development-kit-p-2415.html
