### ISSUE TITLE
timers can only be started once

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2183]
### Expected behavior

The code should print out 'on' and then 'off' whenever the pulse() method is invoked. From my reading of the documentation, the timer should remain registered and it should be startable multiple times. 

### Actual behavior

The first time it works fine, and the second time it never prints 'off'

### Test code

```Lua
pulsetimer = tmr.create()
pulsetimer:register(100, 0, function() 
    print('off')
  end)

function pulse()
  print ('on')
  pulsetimer:stop()
  pulsetimer:start()
end
```

### NodeMCU version
Current dev branch
### Hardware
wemos d1 mini

**Comment by devsaurus** [comment]
Isn't mode 0 actually `tmr.ALARM_SINGLE`? That would explain the observed behavior. 
You probably want mode `tmr.ALARM_SEMI`.

**Comment by pjsg** [comment]
Indeed. It is probably a bug that the :start() method doesn't throw an exception if it doesn't actually start a timer!

**Comment by stefan-muc** [comment]
Documentation of tmr.start() says: https://nodemcu.readthedocs.io/en/latest/en/modules/tmr/#returns_9

> Returns true if the timer was started, false on error

So I guess it's up to you to check the return code.

**Comment by marcelstoer** [comment]
@pjsg do you intend to change the `:start()` behavior or can this be closed?

**Comment by pjsg** [comment]
Thanks for reminding me. I was thinking that the failure to start a timer should be an exception, but I wonder if that will break anybody's code....

**Comment by pjsg** [comment]
Actually, after looking at the tmr code, I think that it just makes sense to leave the code the way that it is.
