### ISSUE TITLE
Docs say modules can be in C++, but .CPP missing from Makefile

### ISSUE THREAD

**Issue by darkain** [nodemcu/nodemcu-firmware#2193]
https://github.com/nodemcu/nodemcu-firmware/wiki/%5BDRAFT%5D-How-to-write-a-C-module

The very first line on the page:
> This short tutorial will show you how to enhance the NodeMCU firmware with your own module written in C/C++. 

https://github.com/nodemcu/nodemcu-firmware/blob/master/Makefile
This file contains no actual build targets for CPP files. It has partial configuration for them at the beginning, but no reference on how to build .CPP files or track their dependencies. Adding this support to the Makefile should in theory be trivial without bothering any of the existing code.

**Comment by marcelstoer** [comment]
The fact that in theory you could write a module in C++ doesn't necessarily mean everything is prepared and ready for that already. The first one doing so should include changes to the Makefile in the PR. No need for action here IMHO.
