### ISSUE TITLE
Allow arbitrary sleep time [edited]

### ISSUE THREAD

**Issue by jrahlf** [nodemcu/nodemcu-firmware#221]
Based on:
https://github.com/nodemcu/nodemcu-firmware/issues/219

1. If desired sleep time is greater than limit (~35min), store excess sleep time in rtc timer. Then go to sleep. Set deep_sleep_option appropiately (wifi on/off on next start).
2. Check that value at startup before the lua virtual machine is started, if a value is set, goto 1).

**Comment by vowstar** [comment]
This is a good idea. 
https://github.com/nodemcu/nodemcu-firmware/commit/5894df1da68460c9bf136023262c7da662a5a4fe
This update can use indefinite sleep, but can not use >~35min sleep.

**Comment by jrahlf** [comment]
Oh, my bad. I meant indefinite as in very long, but not forever.^^
