### ISSUE TITLE
http.post NULL body check

### ISSUE THREAD

**Issue by Arhorn** [nodemcu/nodemcu-firmware#2221]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Correct execution of the post-request
### Actual behavior
An error occurs: HTTP client: Body shouldn't be NULL
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
http.post('http://httpbin.org/post',
  'Content-Type: application/json\r\n',
  '{"hello":"world"}',
  function(code, data)
    if (code < 0) then
      print("HTTP request failed")
    else
      print(code, data)
    end
  end)
```
### NodeMCU version
latest

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.

WeMos D1 mini
8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
Handled here: https://stackoverflow.com/q/48117813/131929
