### ISSUE TITLE
Possible memory leak in PCM module

### ISSUE THREAD

**Issue by redliquid** [nodemcu/nodemcu-firmware#2227]
### Expected behavior
The same memory amount available after destroying the object.

### Actual behavior
Free memory amount decreased by 16 bytes (not always), see https://pastebin.com/gEAWD5YZ

### Test code
```Lua
function play()
  drv = pcm.new(pcm.SD, 5)
  drv = nil
  print("[" .. tmr.time() .. "], HEAP: " .. node.heap())
end

tmr.create():alarm(1000, tmr.ALARM_AUTO, play)
```
### NodeMCU version
This issue appears to be in `nodemcu:master` and `nodemcu:dev` branch.

Currently testing on:
NodeMCU custom build by frightanic.com
	branch: dev
	commit: df930c2d031bad8ab1d47ef4c06173d111e29e4f
	SSL: false
	modules: adc,bit,bme280,enduser_setup,file,gpio,http,i2c,net,node,pcm,sigma_delta,sjson,tmr,tsl2561,uart,wifi
 build 	built on: 2018-01-14 10:25
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

**Comment by devsaurus** [comment]
Thanks for reporting! I'll have a look.

**Comment by devsaurus** [comment]
@redliquid the leak highlighted by your test code gets fixed with the referenced PR .
