### ISSUE TITLE
64Mbit and 128Mbit flash size not support yet.

### ISSUE THREAD

**Issue by vowstar** [nodemcu/nodemcu-firmware#224]
64Mbit and 128Mbit have supported by hardware, but not supported by this SDK 0.9.5. Waiting for SDK update.
Flasher is OK to burn with 64Mbit and 128Mbit flash if some one hacked the SDK.
 https://github.com/nodemcu/nodemcu-flasher

**Comment by nodemcu** [comment]
done in 20150318
