### ISSUE TITLE
enduser_setup new feature

### ISSUE THREAD

**Issue by davidcbittner** [nodemcu/nodemcu-firmware#2263]
### Missing feature
Displaying IP address assigned after succesful AP configuration and IP address assigned.

### Justification
For ease of setup and use without having to rummage around to find out what the IP address of the unit is after you have gone through a successful AP configuration and connected to a WIFI network. Currently without having the hostname additionally as a parameter to set during the AP configuration a user has to search their wifi router to find out what has been assigned. This is time consuming and a nuisance. Having the IP address appear on the "Success!" screen once it connects would be a trememdous benefit. It's impossible to write instructions to an end user on how they can obtain their IP address on so many brands, makes and models of wifi routers and AP point forget it you can't do it and give screen shots.

### Workarounds
I am not sure there is one.
![wifi](https://user-images.githubusercontent.com/36071328/36163525-8bff21a4-10e1-11e8-8ecd-9dcdfdf4cbe0.jpg)

**Comment by FrankX0** [comment]
That's what I had implemented almost a year ago: #1867

**Comment by davidcbittner** [comment]
This is probably a dumb question however I just flashed my unit with the latest 1.5.4.1 should I not see it in there?

**Comment by davidcbittner** [comment]
sorry I closed this by mistake

**Comment by FrankX0** [comment]
Firmware version 1.5.4.1 is old.
Please generate either a current master or dev build, using https://nodemcu-build.com

**Comment by davidcbittner** [comment]
perfect thanks very much.
