### ISSUE TITLE
esp32 make flash error:patition data subtypes 'rf' is not valid

### ISSUE THREAD

**Issue by 361790160** [nodemcu/nodemcu-firmware#2270]
esp32 make flash error:patition data subtypes 'rf' is not valid
![12345](https://user-images.githubusercontent.com/18511592/36514605-2d15c2a8-17b0-11e8-983d-3fc0683f2de6.png)
![tim 20180221180252](https://user-images.githubusercontent.com/18511592/36514617-3c53620c-17b0-11e8-9b2c-689f72a369a7.png)
![20180222091202](https://user-images.githubusercontent.com/18511592/36514706-bc4bb860-17b0-11e8-9900-afd77f1f3ec3.png)

**Comment by devsaurus** [comment]
@jmattsson there's still the custom partition table around at `components/platform/partitions-2MB.csv`. As far as I can see it's outdated as stated above and not used anywhere. I can't remember what the initial purpose of this was. So far I understood that spiffs searches for partition type 0xC2 and appends a new partition for spiffs if it can't find one.
Should we update it to match current IDF format or should we get rid of it?

**Comment by jmattsson** [comment]
Oh gosh, I haven't been in ESP32-land for so long now!

Umm... I think we had the custom table to get the rfdata into a known spot? I'm very much not across the changes to the IDF, so if that's no longer an issue I think we could probably get rid of the custom partition table. Just remember to remove any reference to it from the idf-default overrides.

**Comment by devsaurus** [comment]
I've fixed and documented the template partition table with https://github.com/nodemcu/nodemcu-firmware/commit/45be28cf60901513ed8ec72bb66bd8db36240d7a.
