### ISSUE TITLE
Crash with node.sleep and some other question

### ISSUE THREAD

**Issue by grey-yibu** [nodemcu/nodemcu-firmware#2272]
These days I'm keep going with my low power solution.After some try with function ' node.sleep()  ', I find it doesn't shows good as the api documentation said.

I use the 'D1 mini' for nodemcu developing and mainly use the ' node.sleep()' parameter 'duration' to let the chip wake up.When I use the ' node.sleep()  ' and set the 'resume_cb'  callback, the  'resume_cb' callback always execute immediately.Besides,probability the chip might not wake up after the second ' node.sleep()'.

I'm not familiar with all those project so if i have any misunderstanding please help me figure it out.

In my opinion ,the ' node.sleep()' function is a light sleep mode corresponding the esp8266 hardware level.However ,I check the 'www.espressif.com' official document and flash their low power solution bin and  I find that in official the light sleep only use 1mA (has Verified).But the same chip with ' node.sleep()  ' use 10mA~20mA.I think i might got something wrong.
URL : 'http://download.espressif.com/FB/EvaKit/Power_Consumption_Tests_EN.zip'

It seems that using the 'node.dsleep()' can be better.Is there a way to identify whether the Nodemcu is restart or awake from  'node.dsleep()' ?

**Comment by TerryE** [comment]
@grey-yibu, think of deep sleep as a restart triggered by a timer or a GPIO interrupt.  Very little of the chip is powered during deep sleep -- mainly just some GPIO interrupt logic, the RTC including some RAM in the RTC.  So your app effectively cold starts, but you can keep sleep->start context in the RTC RAM or SPIFFS.

The documentation does explain all of this :smile: but unfortunately this list isn't to help posters navigate the documentation.
