### ISSUE TITLE
enduser_setup module doesn't capture https

### ISSUE THREAD

**Issue by and7ey** [nodemcu/nodemcu-firmware#2290]
### Expected behavior
`enduser_setup.start()` has been run, user connected to a wireless network "SetupGadget_XXXXXX",  and navigated to the root of **any** website (e.g., http**s**://example.com/), a web page `enduser_setup.html` is displayed.

### Actual behavior
The webpage is not displayed. User should choose HTTP site, not HTTP**S**.

### Test code
n/a

### NodeMCU version
2.1.0-master_20170824

### Hardware
n/a

**Comment by HHHartmann** [comment]
This can't be done since the gadget would have to sully a valid certificate to the client for whatever host the user choosed to enter as URL.
The Browser would then show a certificate error.
