### ISSUE TITLE
HTTP Basic authentication issue

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2291]
username & password = username:password
base 64 encode val = dXNlcm5hbWU6cGFzc3dvcmQ=

code
-----------
add="http://dXNlcm5hbWU6cGFzc3dvcmQ=@members.dyndns.org/nic/update?hostname=scwhome.dyndns.org&myip=11.11.11.11&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG"

function DDNS_Updatex()              
           #print("Updating DDNS....")
  http.get(add, nil, function(code, data)
       if (code < 0) then
          print("'DDNS Update failed'") 
       else 
          print("'DDNS Updated OK- "..code.." "..data) 
       end 
  end)    
end

i get onlly

HTTP client: DNS failed for dXNlcm5hbWU6cGFzc3dvcmQ=@members.dyndns.org
---
even if i use my real user name and password. but it works in normal browser.

even if i do with encoder.toBase64("username:password") i get the same result. is it somthing wrong with the Freeware or am i doing something wrong

**Comment by marcelstoer** [comment]
This is a user support request, see #1010 -> closing
