### ISSUE TITLE
getpeer() return do not reflect a valid TCP connection

### ISSUE THREAD

**Issue by devloperbra** [nodemcu/nodemcu-firmware#2294]
### Expected behavior
_net.socket:getpeer()_ should not return ip and port while no TCP connection. It should return _nil_, as explained on documentation:
[Returns](https://nodemcu.readthedocs.io/en/dev/en/modules/net/#returns_11)
port, ip (or nil, nil if not connected)

### Actual behavior
net.socket:getpeer() returns ip/port while its trying to connect to a TCP server.

_net.socket:getpeer()_ returns same **ip/port** , as specified on net.socket:connect(**port, ip**).
net.socket:getpeer() return IP and PORT for arround 5 seconds after net.socket:connect(port, ip) is executed.

After that, it returns nil,nil, as expected.

I would like to use getpeer() to determine if TCP is connected or not.

### NodeMCU version
NodeMCU custom build by frightanic.com
	branch: dev
	commit: 5c8af3c452574448d471e271231b36ac3fff6b1b
	SSL: false
	modules: adc,bit,bme280,bmp085,dht,encoder,file,gpio,http,i2c,mdns,mqtt,net,node,pwm,sntp,spi,tmr,uart,ucg,websocket,wifi,wifi_monitor,ws2801
 build 	built on: 2018-03-06 20:43
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

### Hardware
Lolin V3

**Comment by TerryE** [comment]
> I would like to use getpeer() to determine if TCP is connected or not.

What you would like and what it does are two different issues.  This returns nil if the associated internal socket userdata `pcb`  isn't defined and the `remote_port` and `remote_ip` fields if it is.  These are initialised during socket connection and cleared when the userdata is garbage collected, which is not necessarily the same as when it is disconnected because of Lua GC algos.

**Comment by devloperbra** [comment]
>  This returns nil if the associated internal socket userdata pcb isn't defined and the remote_port and remote_ip fields if it is

I see its working that way. I tested. It´s clear for me 

... but the doc says :
Returns
port, ip (or nil, **NIL IF NOT CONNECTED**)

Using your own words, "This returns nil if the associated internal socket userdata pcb isn't defined", what is different of docs, " **NIL IF NOT CONNECTED** "

**Comment by TerryE** [comment]
@devloperbra, we all do this work pro bono.  Why don't you propose a change to the document wording and issue a PR?

**Comment by devloperbra** [comment]
@TerryE I understand and appreciate your work. I work pro bono too on other job...

This is my first issue and very early development  stage with all these environment.

I am not sure where to propose this kind of PR.
