### ISSUE TITLE
sntp dns lookups maybe incorrect behavior

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2296]
### Expected behavior

I'm not sure -- I'm conflicted.

### Actual behavior

If you give a list of dns names to the sntp.sync method, then the call fails if *any* of them cannot be looked up. This seems bad. In my case, I had provided a couple of IP address and a couple of dns names, and the call failed because the internet was not reachable. [We got hit by the big storm in the north-eaast, and I was running on generator power for a couple of days and no internet.] My internal NTP servers continued to operate on generator power. 

### Solutions

1. The current behavior is correct

2. The sync operation should happen if *any* of the dns names or addresses can be converted into an ip address. There are then two sub cases: (a) at least one of the failed lookups should be reported on the error callback; (b) no error should be reported unless *all* of the lookups fails. 

I'm conflicted over which of the two subcases is better.

### NodeMCU version
dev

**Comment by ritesht93** [comment]
I as the end user app developer would vouch for Solution 2, case b

**Comment by pjsg** [comment]
I'm inclined to agree with you....

**Comment by TerryE** [comment]
I vote for B also.
