### ISSUE TITLE
Minor doc fix for node.stripdebug()

### ISSUE THREAD

**Issue by cwrseck** [nodemcu/nodemcu-firmware#2302]
The Lua Developer FAQ states:

> How do I reduce the size of my compiled code?...
> ...
> The memory footprint of the bytecode created by method (2) is the same as
> when executing source files directly, but the footprint of bytecode created
> by method (1) is typically 10% smaller than a dump with the stripdebug level
> of 2 or 60% smaller than a dump with a stripdebug level of 0, because the
> debug information is almost as large as the code itself.

The node.stripdebug() module docs state:

> Syntax
> node.stripdebug([level[, function]])
> 
> Parameters
>   level
>     1, don't discard debug info
>     2, discard Local and Upvalue debug info
>     3, discard Local, Upvalue and line-number debug info
>   function
>     a compiled function to be stripped per setfenv except 0 is not permitted.

As far as I can tell, node.stripdebug() won't accept a level of 0.  It might
be worth updating the docs when it's next convenient to do so.

C W Rose

**Comment by TerryE** [comment]
Yup it should read 1,2,3. Lua and not C indices.
