### ISSUE TITLE
uart.on: wrong arg range

### ISSUE THREAD

**Issue by ZaXk** [nodemcu/nodemcu-firmware#2306]
From page: https://nodemcu.readthedocs.io/en/dev-esp32/en/modules/uart/#uartstart

Syntax
uart.on([id], method, [number/end_char], [function], [run_input])

When I run this code:
`uart.on(1,"data", "\r",
  function(data)
    print("receive from uart:", data)
    if data=="quit" then
      uart.on("data") -- unregister callback function
    end
end, 0)`

error output:

> uart.lua:4: wrong arg range
stack traceback:
	[C]: in function 'on'
	uart.lua:4: in main chunk
	[C]: in function 'dofile'
	stdin:1: in main chunk

**Comment by FrankX0** [comment]
Unlike the documentation suggests, `uart.on()` does not support an (optional) uart id number.

**Comment by ZaXk** [comment]
It's my fault. It's esp32 doc. My board is esp8266.

**Comment by devsaurus** [comment]
Doc confirms that on ESP32 `uart` module has an additional optional input parameter which is not present on ESP8266 API.
