### ISSUE TITLE
Strange rounding issue

### ISSUE THREAD

**Issue by marconfus** [nodemcu/nodemcu-firmware#231]
While playing with the dht22 library I encountered a strange problem:

```
> PIN = 3
> dht22 = require("dht22")
> dht22.read(PIN)
> t = dht22.getTemperature()
> print (t)
220
> print(t / 10)
22
> print(t % 10)
8.5265128291212e-14
> print(220 % 10)
0
```
Am I missing something, or is 220 not equal to 220? :-)

**Comment by marconfus** [comment]
Disabling floating point support everything works as expected.

**Comment by TerryE** [comment]
This is a floating point facet.  we can't fix this in the firmware.
