### ISSUE TITLE
mqtt:connect failure function does not work on SDK 2.0.0(656edbf) 

### ISSUE THREAD

**Issue by jwmeyer** [nodemcu/nodemcu-firmware#2314]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
failure function runs if mqtt:connect fails
### Actual behavior
The function does not run most of the time. Sometimes I have seen it run once.
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
--this code works on SDK 2.1.0(116b762)
-- add code here
m = mqtt.Client("1", 0, "xxxxxx", "xxx")
function connect()
m:connect("192.168.1.xx",1883,0,0,function()
  print("Mqtt Connected to: 192.168.1.33") 
  --m:close()
end, function(client, reason)     print ("Mqtt Reconnecting...") 
     tmr.create():alarm(2 * 1000, tmr.ALARM_SINGLE, connect)
print("failed reason: "..reason) end)
end
connect()
```
### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.
NodeMCU custom build by frightanic.com
	branch: master
	commit: b96e31477ca1e207aa1c0cdc334539b1f7d3a7f0
	SSL: false
	modules: bit,dht,enduser_setup,file,gpio,mqtt,net,node,pwm,tmr,uart,wifi,ws2812
 build 	built on: 2017-02-28 17:04
 powered by Lua 5.1.4 on SDK 2.0.0(656edbf)

### Hardware
Wemos D1 mini
8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
We're only supporting the versions we have branches for. You seem to have tested against a supported version (indication: the comment `this code works on SDK 2.1.0(116b762)`).

-> closing
