### ISSUE TITLE
net socket documentation clarification

### ISSUE THREAD

**Issue by cwrseck** [nodemcu/nodemcu-firmware#2321]
The Lua Developer FAQ has the [following example of socket usage](https://nodemcu.readthedocs.io/en/latest/en/lua-developer-faq/#so-how-is-the-lua-registry-used-and-why-is-this-important):
> srv:on("connection", function(sck, c)
>     svr:send(reply)
> end)

As far as I can tell from the wording this is intended as an example
of memory leakage.  Could it please be annotated with an unambiguous
"This is how not to do it"?  Or a fuller working example added, such as:

> local udpskt
> udpskt = net.createUDPSocket()
> if udpskt ~= nil
> then
>     udpskt:on("sent", function(s, c) s:close() end)
>     udpskt:send(UDPPort, broadcast, "Message")
> end

Thanks - Will

**Comment by marcelstoer** [comment]
The FAQ should actually just link to the relevant documentation/example of the net module so that code doesn't have to be updated in two places. Looking forward to your PR.

**Comment by joysfera** [comment]
I believe it indeed documents how easy it is to create a memory leak, and also an example of a programmer's bug, not a Lua/NodeMCU bug. Linking to the net module documentation is not appropriate there. The "This is how not to do it" would be enough. Looking forward to my PR :)

**Comment by marcelstoer** [comment]
Sure, you can declare it as a bad example (good idea) but will also have to present how to do it properly. This can either be done by giving another example (that fixes the first one) or by linking to a good example in the respective module.

**Comment by marcelstoer** [comment]
> Looking forward to my PR :)

Would be cool if we got this before the next master drop, thanks.

**Comment by joysfera** [comment]
When is the next master drop going to happen?

**Comment by marcelstoer** [comment]
Monday evening if nothing unexpected happens.
