### ISSUE TITLE
how to transfer datas from one esp8266 to another esp8266 while both connected to a router

### ISSUE THREAD

**Issue by rasilkrishnan** [nodemcu/nodemcu-firmware#2324]
this is my client code

#include <ESP8266WiFi.h>
const char* ssid     = "CSIact.2G";    
const char* password = "csi@2018"; 

IPAddress ip(192,168,0,2);              

WiFiClient client;

void setup() {
  Serial.begin(115200);
  delay(10000);
  WiFi.begin(ssid, password);
  Serial.print("\n ............client...........");
  Serial.print("\nConnecting to "); 
  Serial.println(ssid);
  int i = 0;
  while (WiFi.status() != WL_CONNECTED && i++ < 43) 
  {
    delay(1000);
    Serial.print(i);
  }
  if (i == 44) 
  {
    Serial.print("\nCould not connect to"); 
    Serial.println(ssid);
    while (1) {
      delay(1000);
    }
  }
  
  Serial.print("\nconnected to ");Serial.println(ssid);
  
}

void loop() 
{
  client.connect(ip, 2323);  
      //find server
      if (! client.connected()) 
      {
        if (client) 
        {
          client.stop();
        }
//        if(client.connect(ip,2323));
//        {Serial.print("server connected ");}
    
     }

String answer = client.readString();   // receives the answer from the sever
  Serial.println("from server: " + answer);
  client.flush();

   
//  //check server for data
//    if (client.connected()) 
//    {// client.flush();
//      if (client.available()) 
//      {
//        //get data from the server and push it to the UART
//        while (client.available())
//        {
//          
//          int data = client.read();
//          Serial.write(data);
//        }
//      }
//    }
//    client.stop();
    delay(2000);
  
}

this is my server code

#include <ESP8266WiFi.h>
const char* ssid     = "CSIact.2G";    
const char* password = "csi@2018"; 

  IPAddress ip(192,168,0,2);              
  IPAddress gateway(192,168,0,1);         
  IPAddress subnet(255,255,255,0);

WiFiServer server(2323);

void setup() {
  Serial.begin(115200);
  delay(10000);
  //WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.print(".........server.......\n");
  WiFi.config(ip, gateway, subnet);
  Serial.print("\nConnecting to "); 
  Serial.println(ssid);
  int i = 0;
  while (WiFi.status() != WL_CONNECTED && i++ < 43) 
  {
    delay(1000);
    Serial.print(i);
  }
  if (i == 44) {
    Serial.print("\nCould not connect to"); Serial.println(ssid);
    while (1) {
      delay(1000);
    }
  }
  Serial.print("\nconnected ");
  server.begin();    ////start the server
  server.setNoDelay(true);

  Serial.print("clients can connect to static IP: ");
  Serial.print(WiFi.localIP());
}

//void loop() 
//{
//
//  //check if there are any new clients
//  if (server.hasClient()) 
//  {
//      //find free/disconnected spot
//      if (!serverClients[i] || !serverClients[i].connected()) {
//        if (serverClients[i]) 
//        {
//          serverClients[i].stop();
//        }
//        serverClients[i] = server.available();
//        Serial.print("New client: "); Serial.print(i);
//        break;
//      }
//    
//  }
  

void loop() {
  // listen for incoming clients
  WiFiClient client = server.available();
  if (client) {

    if (client.connected()) 
    {
      //Serial.println("Connected to client");
      
     // if (server.available()) 
      //{
        //Serial.println("Connected to client");
        //get data from the server and push it to the UART
        //while (server.available())
        //{
          client.println(Serial.read());
       // }
  //}
    
  
}
    }

    // close the connection:
    client.stop();
  }

please help me .

**Comment by marcelstoer** [comment]
If you have a problem with Arduino code you should ask in _that_ community -> closing
