### ISSUE TITLE
[net.TCP] Sometimes we receive concat messages

### ISSUE THREAD

**Issue by Lir10** [nodemcu/nodemcu-firmware#2328]
Testing with the latest firmware (master)

Looks like sometimes when we send JSON messages from the server to the ESP client they are not seperated for example:

python server sends the following JSONS one by one:
```

'{"test":1}\r\n'
'{"test":2}\r\n'
```

ESP Client code for receiving:

```
conn:on("receive",function(t,e)
  print("Received ", e)
end)
```

Results:
`Received '{"test":1}\r\n{"test":2}\r\n'`

Any ideas why ESP concat those messages?

**Comment by pjsg** [comment]
This is a characteristic of TCP. TCP does not have record boundaries and hence you should expect to see any TCP data delivered in one or more callbacks.

**Comment by Lir10** [comment]
@pjsg Thanks for the response. 
Any ideas how we should handle this to exract the JSON from it ? do we need to split the string on every packet we receive?
