### ISSUE TITLE
2.2 20180402 integer build.

### ISSUE THREAD

**Issue by cwrseck** [nodemcu/nodemcu-firmware#2344]
As is well-known luac.cross won't build under an integer version of
NodeMCU - a fix is expected RSN.  However, luac.cross built under a
floating-point version of NodeMCU will cross-compile lua files to code
which will run on an integer version, at least for the 2.1.0_20170824
release.  Pretty much a life-saver.

However, files built with the luac.cross of the 20180402 release fail,
with dofile() giving the "cross.lc: bad header in precompiled chunk"
error when the file is loaded onto a 20180402 NodeMCU. (The 20170824
luac.cross won't build files which run on 20180402 either.)

This is just a warning to those using an integer NodeMCU that they
should probably stick with 2.1 until the luac.cross patches are in,
unless they have files small enough to build on the actual device.

With the recent increases in available heap and memory the need
for an integer build is probably fading away anyway.

Will

**Comment by TerryE** [comment]
The latest dev version build integer luac.cross
