### ISSUE TITLE
Upgrade node.dsleep to SDK >=2.1

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#2351]
SDK 2.1 changed the parameter for `system_deep_sleep` from uint32 to uint64. This allows deep sleep intervals beyond the current 71min boundary. It would also be useful to have a `node.dsleepmax` like Arduino has to get the most out those extended deep sleep capabilities: https://github.com/esp8266/Arduino/blob/2.4.1/cores/esp8266/Esp.cpp#L119

https://nodemcu.readthedocs.io/en/latest/en/modules/node/#nodedsleep needs updating as well.

More details at https://thingpulse.com/2018/04/10/max-deep-sleep-for-esp8266/ (disclaimer: it's from yours truly)

**Comment by dtran123** [comment]
Looking forward to see this change implemented for my battery applications.
