### ISSUE TITLE
Wemos D1 Pro with NodeMCU

### ISSUE THREAD

**Issue by anton101101** [nodemcu/nodemcu-firmware#2355]
Just a quick question. I really want to use NodeMCU on the above board with the 16MB flash would that then mean I would have 16MB of memory to play with as in heap or is limited to something within the firmware which would mean 16MB is only used for the file storage?

Thanks in advance.
Anton

**Comment by joysfera** [comment]
It's not limited in firmware at all. The CPU still has just 80 kB of RAM as it's the same as in other Wemos variants.

**Comment by anton101101** [comment]
Thanks for the reply and clearing that up for me.
