### ISSUE TITLE
Compile error in app/pm/swtimer.c

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2356]
### Expected behavior
It should compile. I'm using a fairly recent docker build environment. As far as I can tell, task_handle_t is really a uint32. I found this after back-merging dev into @TerryE dev-LFS branch....

### Actual behavior
```
swtimer.c:86:40: error: initialization makes integer from pointer without a cast [-Werror]
 static task_handle_t cb_register_task_id = NULL; //variable to hold task id for task handler(process_cb_register_queue)
                                        ^
cc1: all warnings being treated as errors
```
### NodeMCU version
current dev

**Comment by TerryE** [comment]
Yup, I had also noticed this but hadn't tracked it down. It should be `= 0;`

**Comment by dnc40085** [comment]
Hmm, that error never showed up during local compilation or in the TravisCI log.  
I tried adding the below lines to `app/pm/swtimer.c` and got a bunch of other errors but not the one you found, how did you get the error to show up?

``` c 
#if defined(__GNUC__)
#pragma GCC diagnostic warning "-Wall"
#pragma GCC diagnostic warning "-Wextra"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif
```
I'll submit a fix for this and the other errors I found.

**Comment by pjsg** [comment]
Yeah -- I don't understand the difference between what travis is doing and what I'm doing. I did update my docker image fairly recently -- and it started to use ccache to make the build go faster. I wonder if the gcc version also changed....

**Comment by pjsg** [comment]
This was my command line to build swtimer.c:

```
/usr/bin/ccache xtensa-lx106-elf-gcc -I/opt/nodemcu-firmware/sdk-overrides/include -I/opt/nodemcu-firmware/app/include/lwip/app -I/opt/nodemcu-firmware/sdk/esp_iot_sdk_v2.2.0-f8f27ce/include -ggdb -O2 -ffunction-sections -fno-jump-tables -fdata-sections -g -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals  -D__ets__ -DICACHE_FLASH -DLUA_OPTIMIZE_MEMORY=2 -DMIN_OPT_LEVEL=2 -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP -DUSE_OPTIMIZE_PRINTF -DMBEDTLS_USER_CONFIG_FILE=\"user_mbedtls.h\"  -DLUA_NUMBER_INTEGRAL -std=gnu11 -Wimplicit  -I include -I ./ -I ./include -I ../include -I ../../include -I ../lua -I ../platform -I ../libc -I ../include -I ./ -include /opt/nodemcu-firmware/user_config.h -I ../../include -I ../../include/eagle  -o .output/eagle/debug/obj/swtimer.o -c swtimer.c
```

I don't know how that differs from yours.

**Comment by TerryE** [comment]
@dnc40085, IMO, using a per module set of pragmas to change the warning and error levels is the wrong way to go. For example, you shouldn't ignore unused parameters, but instead use the UNUSED() macro.

**Comment by dnc40085** [comment]
@TerryE My mistake, I forgot to take those lines out before pushing the commit, I copied that section from `app/modules/tmr.c` in hopes of reproducing the original error,  Instead I found different errors.

**Comment by dnc40085** [comment]
>I did update my docker image fairly recently -- and it started to use ccache to make the build go faster.

I compared the build commands for both the local build and docker build and found no difference between the two aside from the addition of `ccache`. 

I decided to check if the addition of `ccache` was causing the problem, so I modified the local makefile and added `/usr/bin/ccache` before `xtensa-lx106-elf-gcc` on line 83 and re-ran the build and the build hung on the `cb_register_task_id` warning just as it had on the docker build.

Why is the warning not being caught by the local `make all` and TravisCI builds?
The line at the beginning of [`app/modules/tmr.c`](https://github.com/nodemcu/nodemcu-firmware/blob/67027c0d05f7e8d1b97104e05a3715f6ebc8d07f/app/modules/tmr.c#L1) suggests that warnings are turned off in the makefile, shouldn't this be fixed?

**Comment by TerryE** [comment]
> The line at the beginning of app/modules/tmr.c suggests that warnings are turned off in the makefile, shouldn't this be fixed?

You are right. There is a lot of tidy up that needs to be done, but a job for another day.

**Comment by peturdainn** [comment]
It's a question of policy if it should fix everything or just a part of it, right?
(sorry, I couldn't let this double standard pass even if it doesn't make me any friends here)

**Comment by TerryE** [comment]
@dnc40085, it would be really good if the core committers could hook you into some of the more informal side conversations.

**Comment by dnc40085** [comment]
@TerryE I sent a PM to you on esp8266.com
