### ISSUE TITLE
PIN_FUNC_SELECT by lua?

### ISSUE THREAD

**Issue by anod221** [nodemcu/nodemcu-firmware#2371]
My problem is that I need a pin for clock out. I found that GPIO0 would be work. [pin func](https://www.esp8266.com/wiki/doku.php?id=esp8266_gpio_pin_allocations)
So I think I need to call PIN_FUNC_SELECT by lua. Is there any way to do that?

**Comment by devsaurus** [comment]
I'm not too comfortable with introducing a dedicated mode for just a single pin (and ensure that it fails when applied to all other pins). Though I don't have better proposal to abstract this.
Something like `gpio.FUNCTION4` would be more generic, but is really low-level and requires the user to select the matching function for the intended mode.

**Comment by anod221** [comment]
OK, I think I should do it myself. Thanks.
