### ISSUE TITLE
Could Filter more packets when using monitor

### ISSUE THREAD

**Issue by charlesld** [nodemcu/nodemcu-firmware#2373]
I'm focus on sniffering one STA, thus I can sensor the STA is here nearby ,  so I need to extract no more prob, but qos data even rts can be used.  
Could it support this filter style? thx。
![](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1526363480161&di=d72f9b6a912da3be6538e8a180d26e6d&imgtype=0&src=http%3A%2F%2Fe.hiphotos.baidu.com%2Fzhidao%2Fwh%253D450%252C600%2Fsign%3D2c478856fcf2b211e47b8d4affb0490e%2Fe824b899a9014c085279c6800d7b02087bf4f451.jpg)

**Comment by marcelstoer** [comment]
Sorry, don't get it. @pjsg "WiFi monitoring" could be one for you to comment on?
