### ISSUE TITLE
require() fails on compiled bytecode files when LUAL_BUFFERSIZE is less than 4096

### ISSUE THREAD

**Issue by Erant** [nodemcu/nodemcu-firmware#239]
When require-ing in compiled bytecode files produced with node.compile() on a system with a LUAL_BUFFERSIZE set to less than 4096, the require() fails and crashes the firmware.

**Comment by myplacedk** [comment]
Relevant commits:
6e840a4 (all branches) Add node.compile() and increase LUAL_BUFFERSIZE
fab1f95 (master and dev) Revert LUAL_BUFFERSIZE

**Comment by Erant** [comment]
a1be293 fixed this.
