### ISSUE TITLE
Soft WDT reset  Error

### ISSUE THREAD

**Issue by arghasen10** [nodemcu/nodemcu-firmware#2390]
I am unable to connect my nodemcu to a java WebSocket server.
My nodemcu gets connected to wifi and then it fails to connect to the server and then in my serial monitor, it is showing this error.--------->

Connection failed.

Soft WDT reset

ctx: cont 
sp: 3ffefbf0 end: 3ffefde0 offset: 01b0

>>>stack>>>
3ffefda0:  3ffe8510 3ffeeb28 3ffeed88 402021bd  
3ffefdb0:  401070a0 9d2ba8c0 feefeffe feefeffe  
3ffefdc0:  3fffdad0 00000000 3ffeedae 402047bc  
3ffefdd0:  feefeffe feefeffe 3ffeedc0 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

And then the wifi connection gets lost.

**Comment by marcelstoer** [comment]
This looks a stack from Arduino -> closing
