### ISSUE TITLE
Upgrade to SDK 2.2.1

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#2395]
https://github.com/espressif/ESP8266_NONOS_SDK/releases/tag/v2.2.1

@devsaurus and @nwf you did this last time. Would you have spare time to work on this?

**Comment by nwf** [comment]
From a quick glance through the deltas from v2.2.0, this should be real fast; almost all of the changes are in binary blobs rather than source.  I'll see if I have time this weekend.
