### ISSUE TITLE
Performance regression in WiFi connection since SDK 2.2

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#2397]
8<------------------------ BUG REPORT -----------------------------------------

In the last few months I noticed that my esp8266 devices run out of battery power sooner than before.
Looking at the timing data (which the devices include in each report) I see a consistent slowdown.

Most connections are fast at about 500ms, so my app sleeps after about 600. This did not change.

If the connection fails at first (there are over 10 devices on a 1m loop so they clash about 15% of the time) then the connection takes about 2s longer to establish.

Since the change to `SDK 2.2` this second case takes an extra 600ms.

The program just waits for a `GOT_IP` condition, having set a static IP, and using the a/p credentials stored internally.

BTW, if the 2s delay is due to a clash, is the timing controlled by the esp or by the a/p?

### Expected behavior

Connection time, when the fast path fails, takes about 2.6s.

### Actual behavior

Connection time, when the fast path fails, takes about 3.2s.

code using the last SDK 2.1:
```
NodeMCU 2.1.0 build dev-20180609-2330-4367e6e9e0-1m-all powered by Lua 5.1.4 on SDK 2.1.0(116b762)

0.187675 main: code 2 reason 5 cause 99
0.202800 main: using node.dsleep
0.223415 main: static IP set to '192.168.2.47' for 'esp-12f'
0.291979 read: reading 'ds18b20'
0.377738 read: read[1]=18.1250
0.395416 read: have Reading 18.1250
0.497170 wifi: GOT_IP after 0.061069 seconds, ip=192.168.2.47 status=5 channel=11

0.187977 main: code 2 reason 5 cause 99
0.203099 main: using node.dsleep
0.223724 main: static IP set to '192.168.2.47' for 'esp-12f'
0.290711 read: reading 'ds18b20'
0.376455 read: read[1]=17.8750
0.394129 read: have Reading 17.8750
2.586672 wifi: GOT_IP after 2.151689 seconds, ip=192.168.2.47 status=5 channel=11
```
code using the first SDK 2.2:
```
NodeMCU 2.2.0.0 build dev-20180910-1012-f3ebfa9bfe-1m-all powered by Lua 5.1.4 on SDK 2.2.0(f28eaf2)

0.188819 main: code 2 reason 5 cause 99
0.204287 main: using node.dsleep
0.225542 main: static IP set to '192.168.2.47' for 'esp-12f'
0.294239 read: reading 'ds18b20'
0.380305 read: read[1]=19.2500
0.398011 read: have Reading 19.2500
0.500400 wifi: GOT_IP after 0.061582 seconds, ip=192.168.2.47 status=5 channel=11

0.185920 main: code 2 reason 5 cause 99
0.201375 main: using node.dsleep
0.222637 main: static IP set to '192.168.2.47' for 'esp-12f'
0.288547 read: reading 'ds18b20'
0.374579 read: read[1]=19.0000
0.392287 read: have Reading 19.0000
3.152458 wifi: GOT_IP after 2.718079 seconds, ip=192.168.2.47 status=5 channel=11
```
Note how the ds18b20 reading time is practically identical for all cycles. It is then that the app waits for an IP:
```
eventmon.register(eventmon.STA_GOT_IP, function(T) have_connection("GOT_IP") end)
```
I checked and the latest dev timing is identical to the first SDK 2.2 commit. The above builds were made locally from a git commit tag (downloaded the zip file).

### NodeMCU version
I am on the dev branch, and the above two show the commits after the date-time.

### Hardware
Any, but the above examples use a naked esp-12f on a small breadboard.

**Comment by marcelstoer** [comment]
I'm quite certain the cause is in the SDK rather than in our firmware. However, did you try the new https://nodemcu.readthedocs.io/en/latest/en/modules/wifi/#wifisetcountry to limit the channels (related to espressif/ESP8266_NONOS_SDK#125)?

**Comment by eyaleb** [comment]
@marcelstoer , I just tried `wifi.setcountry()` and it made no difference. I see that the country is always set to `CN` on wakeup and my app needs to sets it to `AU` (first thing) every time.
```lua
    if nil == country then
            country = "AU"
    end
    if country ~= wifi.getcountry().country then
        wifi.setcountry({country=country, start_ch=1, end_ch=11, policy=wifi.COUNTRY_AUTO})
        Log ("wifi.country set to '%s'", country)
    end
```

I then tried to scan only channel 11, which is the one the a/p is using now:
```lua
wifi.setcountry({country=country, start_ch=11, end_ch=11, policy=wifi.COUNTRY_AUTO})
```

```
0.199375 main: code 2 reason 5 cause 99
0.214138 main: using node.dsleep
0.240205 main: wifi.country set to 'AU'
0.256760 main: static IP set to '192.168.2.47' for 'esp-12f'
0.325317 read: reading 'ds18b20'
0.410716 read: read[1]=16.1875
0.428108 read: have Reading 16.1875
0.530402 wifi: GOT_IP after 0.062844 seconds, ip=192.168.2.47 status=5 channel=11

0.199193 main: code 2 reason 5 cause 99
0.214007 main: using node.dsleep
0.240035 main: wifi.country set to 'AU'
0.256592 main: static IP set to '192.168.2.47' for 'esp-12f'
0.323579 read: reading 'ds18b20'
0.408974 read: read[1]=16.1875
0.426378 read: have Reading 16.1875
5.738205 wifi: GOT_IP after 5.272187 seconds, ip=192.168.2.47 status=5 channel=11
```

Unexpectedly, this time the connection actually increased by another 2.5 seconds.

**Comment by eyaleb** [comment]
While we are talking about `wifi.setcountry`, when should it be set?

I have `autoconnect` set, so the wifi negotiation is already in motion when my app starts.
`wifi.sta.setip` is the first wifi call the app issues, and it probably is OK to arrive while the association takes place, so I issue `wifi.setcountry` first. Does it take effect?

Also, the doco says
``
wifi.COUNTRY_MANUAL Country policy is manual, NodeMCU will use locally configured country info.
``
and I do not understand what `locally configured` means. Where is this set?
I see that the country code is not remembered and has to be set each time. Is it even related to the abovementioned configuration?
I also tested setting different start/end channels and saw no effect on performance.

Should mere mortals like me always use `COUNTRY_AUTO`?

**Comment by TerryE** [comment]
This API call implements the SDK `wifi_set_country()` API call.  See the section 3.5.74 of the Espressif SDK:
> -  The default WiFi country code is {.cc="CN", .schan=1, .nchan=13, policy = WIFI_COUNTRY_POLICY_AUTO}
>-  If policy = WIFI_COUNTRY_POLICY_AUTO, the country code of ESP8266 station will change automatically to be the same as the AP it connected to; and when the WiFi connection ends, its country configuration will change back to be the original one.
>-  If policy = WIFI_COUNTRY_POLICY_MANUAL, the country code of ESP8266 will always be the configured one.
>-  If the ESP8266 is in station+softAP mode, the softAP's country IE in the probe response/beacon will always be the same as the station's country info.
>-  The country configuration will not be saved into flash

The mess is described in [WP:List of WLAN channels](https://en.wikipedia.org/wiki/List_of_WLAN_channels), and the TL;DR is that not all channels work in all countries as some have statuary allocations that pre-date the introduction of WiFi. 

If the ESP running as a station, then the auto setting essentially assumes that the router/AP has been correctly configured, and is only advertising WiFi services that are valid in that country.   As the manual says, it picks up the CC from the AP once connected.  

One of the things on my long list of TODOs is to explore autoconnect vs manual connect performance.  The autoconnect mode latches Wifi credentials / channel, etc. into FLASH, so I would have thought that connection latencies would be reduced.    In terms of your explorations, have you found any differences?

**Comment by eyaleb** [comment]
Thanks @TerryE, I need to find the time to read the SDK doco, and learn more about the details of wifi connection. I expect `COUNTRY_AUTO` is what I should use.

I use autoconnect (I do not set any credentials). I do set static IP as it is not saved. The result is that I get a connection rather fast, often 100-200ms after the app starts (if it does not hog the CPU).

The app is simple:
- set IP
- read sensors
- wait for a connection (e.g. eventmon)

If I do manual connection then the process is very much longer, a few seconds. My understanding is that issuing manual connection requests restarts the whole wifi connection.

[As an aside, this discussion should really move elsewhere, the subject of this issue is the performance regression when we upgraded to SDK 2.2. I need to establish an SDK app that demonstrates the issue and submit it to espressif].
