### ISSUE TITLE
can't set uart bitrate and parity

### ISSUE THREAD

**Issue by Suxsem** [nodemcu/nodemcu-firmware#240]
Hi.
I'm trying to set uart with this configuration:
bitrate: 2400
data bits: 8
parity: even
stop bits: 2
echo: disabled

from documentation i tried:
uart.setup(0, 2400, 8, 1, 2, 0)

birate and data bits are successfully set, but parity and stop bits are not correct.
who know the correct syntax?

**Comment by devsaurus** [comment]
Even parity would require `0` for `uart.setup()`.
From a quick review of the driver code, I'd say that the parity configuration looks odd somehow :grin: Might be broken at the moment and requires further investigation.

**Comment by devsaurus** [comment]
Issue fixed, thanks for reporting.
