### ISSUE TITLE
Help flashing ESP12-e.

### ISSUE THREAD

**Issue by Leobute** [nodemcu/nodemcu-firmware#2402]
I have Esp8266 . ESP12-E with 4 Mb flash size.

Can anybody help me in understanding where to download the latest flash ?

I have downloaded the nodemcu flash utilities.
 Cannot find the 4 (?) files needed.
First of all how do i check the release i have ???

Thanks a lot to all.

**Comment by marcelstoer** [comment]
See #1010 and http://nodemcu.readthedocs.io/en/latest/en/#getting-started I guess
