### ISSUE TITLE
[ESP32] Handle json encode/decode 

### ISSUE THREAD

**Issue by Lir10** [nodemcu/nodemcu-firmware#2412]
Looks like sjson is not supported in esp32 nodemcu firmware

I'm trying to migrate an app from esp8266 to esp32 but without sjson module it's pretty much useless

Any ideas about this?

**Comment by x-logLT** [comment]
You can pretty much take the sjson module/lib from esp8266 branch and add it to ESP32 one without much trouble, have been using it as such close to a year now: https://github.com/x-logLT/nodemcu-firmware/commit/9b003b55b1355d12a9042227ddc8bea4d367575a.
Other way would be using included cjson lib and adapting old cjson module to it, don't know how straightforward that would, if memory serves right, its not even the same lib as was used in old esp8266 branch.

**Comment by marcelstoer** [comment]
>  have been using it as such close to a year now: x-logLT@9b003b5

Great, then why not put it up as a PR to help the community?

**Comment by x-logLT** [comment]
it's on my to-do list, at the moment I don't have time to do it the proper way.

**Comment by galenzhao** [comment]
by using this 
https://gist.github.com/tylerneylon/59f4bcf316be525b30ab

**Comment by x-logLT** [comment]
So which route are we taking;
1. Use masters SJSON lib/module
2. Use esp-idf's cjson lib and write module for it
3. Use LUA module based on lib pointed out by galenzhao
?

**Comment by devsaurus** [comment]
I'm unbiased here. Are there any pros or cons with either of the first 2 alternatives?

I understand that support for streaming JSON is essential, though.

**Comment by jmattsson** [comment]
I'd suggest going with the sjson option. Not only is it built for streaming support, it also means we're not diverging further from esp8266 nodemcu.

**Comment by devsaurus** [comment]
Related PR was merged.
