### ISSUE TITLE
Wording for README.md

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#2418]
Another issue that doesn't fit the templates.  This is a trivial one but worth discussing and reaching consensus before raising the PR.  There are a could of issues with the project README that deserve fixing.  \(Many thanks to @nailujx86 for raising this\).

-  The lede is just misleading and needs replacing.  For example: it majors on eLua, whilst in reality perhaps 85% of the Lua hierarchy is standard Lua. Of the remaining mods and new code, my and zeroday's mods / enhancements are a far larger portion than the eLua components (mainly ROTable handling).  To all intents the code is 100% c.  Also whilst the project started out a companion to the NodeMCU boards, it can be run on any ESP module.  So how about:

> NodeMCU is an open source [Lua](https://www.lua.org/) based firmware for the [ESP8266 WiFi SOC from Espressif](http://espressif.com/en/products/esp8266/) and uses an on-module flash-based [SPIFFS](https://github.com/pellepl/spiffs) file system. NodeMCU is implemented in C and is layered on the [Espressif NON-OS SDK 2.2.0](https://github.com/espressif/ESP8266_NONOS_SDK/releases/tag/v2.2.0).

-  We should also underline that the project is now run by community members and is vendor-neutral in terms of hardware: 
 
> The firmware was initially developed as is a companion project to the popular ESP8266-based NodeMCU development modules, but the project is now community-supported, and the firmware can now be run on _any_ ESP module.

>

**Comment by marcelstoer** [comment]
Fine for me, I like. Two issues:

- Don't mention the exact NON-OS SDK _version_. Would be one less place to edit with every SDK upgrade.
- "can now be run on any ESP module." - I don't think the term "ESP module" has any official meaning.

How about 

> ...nity-supported. The firmware can now be run on any ESP8266, ESP8285 and ESP32.

-> maybe mention something about the respective NodeMCU branches?

**Comment by cwrseck** [comment]
It would be helpful to add the release version (eg. 2,2,0-master_20180608) to the title of the README title.  I have several versions of NodeMCU, and it's tedious to have to check the source directory to find out which version's documentation I've found.

Will

**Comment by TerryE** [comment]
@cwrseck.  I can't follow your logic here.  The README is in the source directory.  How do you do your build? Via cloud builder or what?  From our PoV, having the version in the README is a PITA as you now have to update this file every release.

**Comment by cwrseck** [comment]
I have a docs link on the desktop, effectively (I'm building NodeMCU from a local directory).  With various versions in play, it's handy to know which version of the docs goes with which without scuffling through the file system.   In general I'd expect the version number to be updated automatically when each new release is built,  but there may well be difficulties I'm not aware of.

Will

**Comment by marcelstoer** [comment]
> worth discussing and reaching consensus before raising the PR

Ready for PR IMHO.

**Comment by marcelstoer** [comment]
Fixed in 8505362
