### ISSUE TITLE
Improving LFS documentation

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#2431]
This is a detailed spin-off of #2413.  We have now got LFS deployed in dev, but there are a number of rough edges, particularly in how it is documented and introduced to existing and new users

### What documentation current exists

-  ✅The [LFS whitepaper](http://nodemcu.readthedocs.io/en/dev/en/lfs/) is now included in the newly reorganised whitepapers section.  This goes into a lot of technical detail that is of no interest to Lua IoT developers who are only interested in what it can allow them to do, and not the magic behind it.
-  ✅[node.flashindex()](http://nodemcu.readthedocs.io/en/dev/en/modules/node/#nodeflashindex) and [node.flashreload()](http://nodemcu.readthedocs.io/en/dev/en/modules/node/#nodeflashreload) are properly documented in the **node** module but neither refer back to the LFS whitepaper :scream: 
- Some examples do exist, but more needs added here.

### Justification for extra work

LFS is the biggest change to NodeMCU since Johny's unaligned exception handler patch allowing most constant data to be moved into Flash. The use of LFS transforms the sort of applications that you can realistically develop for the ESP8266, yet it is in the "best kept secrets" category.   We should headline this somehow for users.
 
### Scope of documentation changes

-  ✅ The intro in the README.md should refer to the new LFS feature and link to the relevant documentation -> 4c6c9d3
-  ✅ The lead to the online documentation should do likewise.
-  ✅ The LFS whitepaper needs polishing.  I am probably to geeky and too close to the implementation to write this well for consumption by the average developer.  @vsky279 Lukáš has suggested a first cut in this draft commit c39891f9.  We need something like this.
-  The examples need expanding. 
-  (Out of scope but very important).  
    - ✅ Since a lot of developers use [esp8266.com](http://esp8266.com) and the [NodeMCU custom build service](https://nodemcu-build.com/), we should use these to advertise the new functionality, in the former by a sticky post, and the latter either by a news banner or a reference on the "your build is complete" email. 
    - ✅ Announce it on https://www.facebook.com/NodeMCU -> @marcelstoer

@vsky279 already has my email details;  unfortunately github doesn't offer PM, but @HHHartmann Gregor if you want to have a side chat then I still have an apache org mailbox from my committer days there (same userid); ping me an email and I'll reply on the mail address I usually use,

**Comment by vsky279** [comment]
As @TerryE said I have drafted a Quick Start guide to LFS. I have submitted a PR #2432 so everyone can comment and discuss.

**Comment by marcelstoer** [comment]
I'll now work on some of the issues (docs and communication).

> in the former by a sticky post, 

I'll contact an admin after posting to make it sticky.

> and the latter either by a news banner or a reference on the "your build is complete" email.

Should be a banner as the users will only see the email _after_ the build; "Dang, why didn't they tell me about LFS before...".

**Comment by marcelstoer** [comment]
I added ✅to the original description for tasks that are done.

As said elsewhere I'll start promoting LFS once @TerryE and @HHHartmann with the `luac.cross` stuff. Otherwise, we'd get flooded with people asking how to build/obtain the `luac.cross` binary necessary for LFS.

**Comment by TerryE** [comment]
@marcelstoer Marcel,

> Otherwise, we'd get flooded with people asking how to build/obtain the `luac.cross` binary necessary for LFS.

Or we can just point them at this blog post [A Lua Cross-Compile Web Service](https://blog.ellisons.org.uk/article/nodemcu/a-lua-cross-compile-web-service/).  Good enough to let Lua developers play with LFS.

Are you going to do the next dev->master cut?

**Comment by HHHartmann** [comment]
@TerryE Terry that is great news!
Just wanted to try it, but I get a login dialog first.
Also loocking at the code I see that you only allow .lua files in the zip. This will give Mac users a headache, as the default GUI zip will always add some Mac specific metafiles to the zip. Maybe just unpack it all and just compile lua files.

**Comment by HHHartmann** [comment]
And if you find some time you could use $zipName to generate the download name. But that would just be sugar.

**Comment by jmd13391** [comment]
@TerryE Terry, RE: https://github.com/nodemcu/nodemcu-firmware/issues/2431#issuecomment-415607693

This is outstanding! (and IMO I think it should be included in the NodeMCU docs)

One minor suggestion: On your [A Lua Cross-Compile Web Service](https://blog.ellisons.org.uk/article/nodemcu/a-lua-cross-compile-web-service/) page, consider adding a reference to [Compiling Lua on your PC for Uploading](https://nodemcu.readthedocs.io/en/master/en/upload/#compiling-lua-on-your-pc-for-uploading) that describes what "luac.cross" is, cross-compiling and why it's needed here.

Doing so may help to mitigate some of the complexity and confusion associated with "rolling your own" NodeMCU code. Ref: [Compiling of lua programs in PC-Windows](https://www.esp8266.com/viewtopic.php?f=22&t=16035) 

Keep in mind that newbies (and even some not-so-newbies) to NodeMCU may have no clue what you guys are talking about; to them, "luac.cross" might as well be an ancient Mayan glyph. :-) 

-Joe

**Comment by jyh29** [comment]
Why not setup a web service under pay for users to cross compile the Nodemcu-firmware according to users uploading include/user_config.h ?
