### ISSUE TITLE
https://nodemcu-build.com/ building ESP32 images

### ISSUE THREAD

**Issue by ildar** [nodemcu/nodemcu-firmware#2437]
https://nodemcu-build.com/ currently shows ESP32 branch as disabled for build

Is it possible to make it build ESP32 firmware and how?

**Comment by marcelstoer** [comment]
It says there "not yet". So, no you can't build for ESP32.

I run that service as an individual: https://nodemcu-build.com/faq.php#who -> close issue

**Comment by ildar** [comment]
I see on "who" and that's appreciated.

But "not yet" isn't really informative, can you expand? No plans or maybe
in Autumn or next year or need some assistance or ... ?

**Comment by TerryE** [comment]
@ildar, we welcome any capable developers to work on contributing to the project, so long as they offer a net benefit.
