### ISSUE TITLE
node.key() broken?

### ISSUE THREAD

**Issue by emsi** [nodemcu/nodemcu-firmware#244]
When I try the example I get:

```
> node.key("long", function() print('hello world') end)
stdin:1: attempt to call field 'key' (a nil value)
```

**Comment by raz123** [comment]
Read the changelog.

2015-02-12
remove node.led() and node.key() api.

**Comment by emsi** [comment]
Since gpio.trig() does not work on GPIO16 how I cen reimplement that feature back?

**Comment by nodemcu** [comment]
uncomment line 12 in /app/include/user_config.h
```c
// #define DEVKIT_VERSION_0_9 1 	// define this only if you use NodeMCU devkit v0.9
```
rebuild firmware

**Comment by emsi** [comment]
That's what I did. 
Thank you.
