### ISSUE TITLE
node.sleep() is not working for interrupt wakeups

### ISSUE THREAD

**Issue by mikep01** [nodemcu/nodemcu-firmware#2445]
### Expected behavior
`node.sleep()` should wake up when the desired pin level occurs.

BTW, `node.sleep()` will only work for LOW or HIGH levels, the SDK "ESP Low Power Solutions" indicates "The GPIO wake-up function can only be enabled by level triggers".

### Actual behavior
`node.sleep` does not wake up on the requested level, but instead wakes on the opposite level.

### Test code

When `init.lua` starts, trigger the interrupt button low/high a few times to confirm it's working.  Once you stop triggering, leave it for 5s and the device will go to sleep.

It will take a double transition to trigger the resume_cb.

You should also notice that the interrupt handler stops working and no longer reports both transitions.
```Lua
-- init.lua:

button_pin = 3

gpio.trig(button_pin, "both", function(level)
  print("Interrupt: level = " .. tostring(level))
  tmr.stop(0)
  tmr.alarm(0,5000,tmr.ALARM_SINGLE,
    function()
      sleep()
    end)
end)
print("installed interrupt handler, press interrupt button")

wifi.setmode(wifi.STATION,false)

function sleep()

  print("going to sleep...")

  local interruptMode = node.INT_HIGH
  if (gpio.read(button_pin) ~= 0) then
    interruptMode = node.INT_LOW
  end

  print("Pin=" .. tostring(gpio.read(button_pin)) .. " Using mode=" .. interruptMode)

  local parms = {
    int_type=interruptMode,
    preserve_mode=false,
    resume_cb = function()
      wifi.setmode(wifi.STATION,false)
      print("Resume callback!")
    end,
    wake_pin=button_pin}
  local s,err = pcall(function()
    node.sleep(parms)
  end)
  if (not s) then
    print("Error trying to sleep: " .. err)
  end
end
```
### NodeMCU version

2.2 DEV

### Hardware
a NodeMCU board is handy for this, using the flash button to trigger the interrupt.

**Comment by mikep01** [comment]
The bug seems to be related to the gpio pin interrupt handler.  
If pmSleep.c null_mode_check_timer_cb is changed to add this:
         platform_gpio_intr_init(current_config.wake_pin, GPIO_PIN_INTR_DISABLE); 
         wifi_enable_gpio_wakeup(pin_num[current_config.wake_pin], current_config.int_type);
just before:
        wifi_fpm_do_sleep(current_config.sleep_duration);
         
everything seems to wake up ok.  Interrupts can be re-enabled and things work properly.

I wonder if something gets out of sync in the interrupt handler/counters in platform.c because the state change is not reported there as an interrupt when handling wifi wakeup?

**Comment by TerryE** [comment]
@mikep01, totally off issue (sorry :disappointed:) but in Lua esp on the ESPs, you want to make use of locals as these are faster and take up less RAM. So a good trick is to do `for k,v in pairs(_G) do print(k,v) at the end of a run and ask yourself d you really need to use globals?  Unlike JS, Lua doesn't do any scope hoisting, but when using CBs you can use the assignment forms just as effectively, e.g. 
```Lua
-- init.lua:
local sleep, resume_cb
local button_pin = 3

gpio.trig(button_pin, "both", function(level)
  print("Interrupt: level = ",level)
  tmr.alarm(0,5000,tmr.ALARM_SINGLE, sleep) -- previous stop not needed
end)

print("installed interrupt handler, press interrupt button")

wifi.setmode(wifi.STATION,false)

sleep = function()
  local button_state  = gpio.read(button_pin)
  local interruptMode = (button_state == 0) and node.INT_HIGH or node.INT_LOW

  print(("Pin=%u, Using mode=%u"):format(button_state,interruptMode))
  print("going to sleep...")

  local s,err = pcall(node.sleep, {
    int_type      = interruptMode,
    preserve_mode = false,
    resume_cb     = resume_cb,
    wake_pin      = button_pin,
  })

  if (not s) then
    print("Error trying to sleep: " .. err)
  end
end

resume_cb = function()
  wifi.setmode(wifi.STATION,false)
  print("Resume callback!")
end
```
Just a few coding hints.  Ignore if you wish.

**Comment by mikep01** [comment]
Understood - usually I code a little cleaner (out of necessity that I hope starts to go away with LFS :)!), in this case I was playing with different combinations so I wanted my functions available from the command prompt.

**Comment by jmd13391** [comment]
@TerryE... Now that you strayed... LOL Question related to your coding tips snip above:

"if (not s) then..."

Are the parenthesis really needed in this case?

**Comment by TerryE** [comment]
> Are the parenthesis really needed in this case?

:scream: I've been out-Terry'ed

@jmd13391, fancy giving your critical eye to the Developer FAQ?
