### ISSUE TITLE
ESP_PARTITION_TABLE_ADDR undeclared in file flash_api.c

### ISSUE THREAD

**Issue by chairongzhen** [nodemcu/nodemcu-firmware#2464]
when i try to compile , an error occured. 
/nodemcu-firmware/components/platform/flash_api.c:50:25: error: 'ESP_PARTITION_TABLE_ADDR' undeclared (first use in this function)    const uint32_t offs = ESP_PARTITION_TABLE_ADDR;

any help

**Comment by syntroniks** [comment]
I am curious about this identifier too. It came up as undefined/undeclared when I upgraded the esp32 esp-idf to `master` (I think it happens on 3.1 as well)

For my hacky purposes, I hardcoded it to 0x8000. It seems to be present in `make menuconfig` -- maybe it isn't available to the dependent files.

**Comment by devsaurus** [comment]
I've updated the repo to latest esp-idf. This issue is fixed.
