### ISSUE TITLE
how to use IR Community(1838) recive singal?

### ISSUE THREAD

**Issue by godchenmeng** [nodemcu/nodemcu-firmware#2466]
how to use IR Community(1838) recive singal?pwm?adc?or other?

**Comment by marcelstoer** [comment]
See #1010 -> closing

**Comment by FrankX0** [comment]
Like @marcelstoer commented, this is not the place for these kind of questions.
But maybe this helps (no personal experience though): https://github.com/mykh/ESP8266-IR-Remote-Receiver
