### ISSUE TITLE
Provide an API for SPIFFS on external SPI flash devices

### ISSUE THREAD

**Issue by JohnMH** [nodemcu/nodemcu-firmware#2474]
### Missing feature
API for SPIFFS on external SPI flash devices

### Justification
This would allow some pretty obvious projects which may be able to use temporary files on the initial run, for example.

### Workarounds
No, but users could definitely hard-code regions to be loaded or something like that.

**Comment by marcelstoer** [comment]
Maybe you're looking for this: https://nodemcu.readthedocs.io/en/latest/en/sdcard/

**Comment by JohnMH** [comment]
@marcelstoer I'm under the impression that that only works for FAT formatted devices. I'm specifically referring to, for example, external SPI EEPROM.
