### ISSUE TITLE
Updateing Its Driver

### ISSUE THREAD

**Issue by UrafikiTheFluff** [nodemcu/nodemcu-firmware#2498]
ok so I got mine on wish.com but when I try to update its driver software and flashing it but when I go on to my phone it still says "ESP_21374" it doesn't say pawned I have discord and an email please get a hold of me

**Comment by nwf** [comment]
This is not a support forum, and moreover this is not the right place to discuss https://github.com/spacehuhn/esp8266_deauther as you seem to want.  If you still wish help, likely one of us can be hired at reasonable contracting rates.

**Comment by marcelstoer** [comment]
See #1010 -> closing
