### ISSUE TITLE
node.restart() - hangs

### ISSUE THREAD

**Issue by Toshik** [nodemcu/nodemcu-firmware#25]
```
NodeMcu 0.9.2 build 20141209  powered by Lua 5.1.4

> node.restart();
> bB
```

MCU hangs, power off/on helps.

**Comment by gorec2005** [comment]
may be here hardware issue? - try pullup reset pin... for me this help....

**Comment by topherCantrell** [comment]
I tied the reset to VCC. I still get about 30% failed power-ups. I have to turn the power off. Wait a minute, and try again. Sometimes it takes two retries. Very frustrating.

**Comment by gorec2005** [comment]
power source is good? check it.... i try about 20-30 power cycles - all ok!

**Comment by Suxsem** [comment]
Hi....there are multiple reports about failed power up with nodemcu while 100% successfull powerup with AT firmware... You can find theme here: http://www.esp8266.com/viewtopic.php?f=13&t=1287&start=20
Can you check please?

**Comment by topherCantrell** [comment]
Thanks for the link. This seems to be exactly what I am seeing. I have
tried different power supplies. I have tried some light and some heavy caps
on the power rails. Same behavior.

Note that toggling the RESET line produces a clean restart every time. It
is only at cold power-up that I see failures. I was thinking about putting
a cap on the reset line to delay its release.

**Comment by TerryE** [comment]
This is not a nodeNCU firmware issue.

**Comment by kbeckmann** [comment]
In case @Toshik still has problems: You should connect RST with GPIO16
