### ISSUE TITLE
any rotary encoder lib for esp32?

### ISSUE THREAD

**Issue by galenzhao** [nodemcu/nodemcu-firmware#2506]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature\
rotary encoder lib for esp32-dev

### Justification
the lib in esp8266 was wonderful,
I found a pure Lua version for esp8266, and port to esp32,
but always show some CW when I rote CCW, 

### Workarounds
https://github.com/FredThx/nodemcu_iot/blob/master/rotary.lua

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
Closing as per #1010
