### ISSUE TITLE
Object-based file API missing in dev-esp32 branch

### ISSUE THREAD

**Issue by tomsci** [nodemcu/nodemcu-firmware#2521]
The object-based file API appears to be missing in the dev-esp32 branch, is re-adding that blocked on #1613? Or was the esp32 code simply forked before the object-based API was added? Either way I have a lot of code written for the esp8266 which will need some major rewrites.

Happy to attempt bringing the esp32 file.c up to date but will only do so if it's not completely doomed or if there isn't a rewrite dropping imminently.

**Comment by tomsci** [comment]
Merging master in seems to have worked ok. PR to follow.

**Comment by devsaurus** [comment]
IIRC, the ESP32 branch forked before, and just the vfs layer was cherry-picked but not the object-based file API. Probably for reasons Johny @jmattsson described in #1613.
IMO the points there are still valid and maybe we tackle such restructuring at some point in the future. But for the time being: +1 from my side for aligning with the esp8266 API.

**Comment by tomsci** [comment]
Definitely don't want to stand in the way of future cleanup refactors. Thanks for the background info, coming into the ESP32 port from fresh it can be quite tricky to work out what's what!

**Comment by devsaurus** [comment]
Guess this one is resolved.
Note that I ported additional commits from dev branch to fully support the new API. SPIFFS integration and vfs layer were missing bits and pieces.
