### ISSUE TITLE
Memory leak for MQTT reconnect

### ISSUE THREAD

**Issue by abhignair** [nodemcu/nodemcu-firmware#2522]
### Expected behavior
Heap memory should not reduce at every mqtt reconnect.

### Actual behavior
MQTT: Trying to connect. Heap:40784 Uptime:30
MQTT: Connected
MQTT: Broker going to offline
MQTT: Trying to connect. Heap:38856 Uptime:81
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:38696 Uptime:91
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:38696 Uptime:101
MQTT: Connected
MQTT: Broker going to offline
MQTT: Trying to connect. Heap:37064 Uptime:152
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:36904 Uptime:162
MQTT: Connected
MQTT: Broker going to offline
MQTT: Trying to connect. Heap:35272 Uptime:215
MQTT: Connecting failed. Reason:-5

### Test code
```Lua
local timer_mqtt_connect = tmr.create()

local m = mqtt.Client("nodemcu-test", 20, "", "", 1)

m:on("offline", function(client)
    print ("MQTT: Broker going to offline")
    client:close()
    timer_mqtt_connect:start()
end)

local function mqtt_connected(client)
    print("MQTT: Connected")
end

local function mqtt_error(client, reason)
    print("MQTT: Connecting failed. Reason:"..reason)
    client:close()
    timer_mqtt_connect:start()
end

local function do_mqtt_connect()
    print("MQTT: Trying to connect. Heap:"..node.heap().." Uptime:"..tmr.time())
    m:connect("146.148.70.212", 1883, mqtt_connected, mqtt_error)
end

timer_mqtt_connect:register(5*1000, tmr.ALARM_SEMI, function()
    do_mqtt_connect()
end)

timer_mqtt_connect:start()
```
### NodeMCU version
Branch: Master
Build from cloud build service taken on 10/16/2018. 

### Hardware
D1 Mini

**Comment by sonaux** [comment]
I tried now on master and dev branches with empty and not empty user/pass and clean install of mosquitto server with default config:

NodeMCU 2.2.0.0 build unspecified powered by Lua 5.1.4 on SDK 2.2.1(6ab97e9)
> MQTT: Trying to connect. Heap:36440 Uptime:8
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:38232 Uptime:13
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:36
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37720 Uptime:41
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37720 Uptime:46
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:65
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:75
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37720 Uptime:80
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:89
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37720 Uptime:94
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:107
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:115
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:120
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:125
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:135
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:152
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:157
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:167
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:192
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:197
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:207
MQTT: Connected
MQTT: Broker going offline
MQTT: Trying to connect. Heap:37784 Uptime:248
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:253
MQTT: Connecting failed. Reason:-5
MQTT: Trying to connect. Heap:37712 Uptime:268
MQTT: Connected

It's fluctuating, but I could not get a steady memory leak 
Similar issues #2364, #1349
