### ISSUE TITLE
I2C and deepsleep

### ISSUE THREAD

**Issue by vahooz** [nodemcu/nodemcu-firmware#2530]
**Use case:**
To be able to perform the communication after returning from "deepSleep". When 20 seconds pass, and **setup()** procedure is executing nodemcu hangs on **Wire.begin()** .
**Question:** How to close  down the I2C hardware?

`#define D1 5 // I2C Bus SCL (clock)
#define D2 4 // I2C Bus SDA (data)
#include <Wire.h>
#include <VL53L1X.h>

VL53L1X sensor;

void setup()
{
  Serial.begin(19200);  
  Wire.begin(D2, D1);  
  Wire.setClock(400000); // use 400 kHz I2C  
  sensor.setTimeout(500);
  if (!sensor.init())
  {
    Serial.println("Failed to detect and initialize sensor!");
    while (1);
  }  
  sensor.setDistanceMode(VL53L1X::Long);
  sensor.setMeasurementTimingBudget(50000);
  sensor.startContinuous(50);
}

void loop()
{
  Serial.print(sensor.read());
  if (sensor.timeoutOccurred()) { Serial.print(" TIMEOUT"); }
  unsigned int sleep_secs = 20;
  ESP.deepSleep(sleep_secs*1000000, WAKE_RF_DEFAULT);
  delay(100);
}`

**Comment by nwf** [comment]
You've found the wrong project; this is for the Lua-based NodeMCU work, not the C++-based/Arduino ESP8266 environment.
