### ISSUE TITLE
MODBUS protocol

### ISSUE THREAD

**Issue by US4LKW** [nodemcu/nodemcu-firmware#2532]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
[MODBUS](https://en.wikipedia.org/wiki/Modbus)
### Justification
With the advent of new industrial controllers as well as various industrial measuring devices with the MODBUS protocol and their availability, developers and I, more and more, began to use MODBUS to integrate their own developments with industrial controllers and other industrial measuring devices that work only according to the MODBUS protocol. We can not influence the manufacturers of industrial controllers and measuring devices, so that they give us the choice of which protocol to work, so developers have to adjust to them, including me.
Some of my familiar developers claim that the MQTT protocol is very slow compared to the MODBUS protocol and rework their projects to the MODBUS protocol. I see that in your firmware there is support for the MQTT protocol. Why don't you add support for the MODBUS protocol?
This will cause a great interest of many industrial developers to the NODEMCU LUA project, which is also interesting to me, but I have difficulty writing a program to work with the MODBUS protocol at the LUA.

### Workarounds
I could not find examples of the implementation of the MODBUS protocol at the LUA and therefore I have to use the ARDUINO IDE to solve this problem, for ARDUINO IDE there are libraries and examples of the implementation of MODBUS:
http://en.trialcommand.com/blog/esp8266-slave-modbus-tcpip-no-libraries/
http://pdacontrolen.com/update-esp8266-industrial-modbus-tcp-ip/
http://pdacontroles.com/actualizacion-esp8266-industrial-modbus/
http://domoticx.com/esp8266-wifi-modbus-tcp-ip-slave/
https://github.com/andresarmento/modbus-esp8266
https://github.com/MaxKravt/WiFi-Modbus-TCPtoRTU
https://github.com/JhonControl/ESP8266_Industrial_ModbusTCP_V2
8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by devsaurus** [comment]
Do I understand correctly that the MODBUS protocol can be implemented with Lua code on top of `net` module? If yes, this could go into `lua_examples` or `lua_modules` in case you intend to set up a PR.
