### ISSUE TITLE
I bought a GY-39 board (including bme280 and max44009). What can I do to support the construction of max44009 module?

### ISSUE THREAD

**Issue by p99993** [nodemcu/nodemcu-firmware#2539]
I bought a GY-39 board (including bme280 and max44009). What can I do to support the construction of max44009 module?

**Comment by TerryE** [comment]
Hi. I use a few I²C modules, and as @nwf comments, I just use the l2C library and code the drivers in Lua.  Just download and read the relevant datasheets.  It's pretty straightforward.

**Comment by nwf** [comment]
@p99993 Despite that this issue is closed, please feel free to open a PR to land your new driver in the `lua_modules` directory if you like!
