### ISSUE TITLE
Align documentation for 1.5.4.1/ESP32 branches?

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#2542]
The 1.5.4.1 & ESP32 branches don't automatically profit from improvements we add to the documentation. A couple of examples:

- Start page: https://nodemcu.readthedocs.io/en/latest/ vs. https://nodemcu.readthedocs.io/en/dev-esp32/
- Navigation structure: current is Basics, FAQs, Whitepapers
- RC module: the _content_ of https://nodemcu.readthedocs.io/en/latest/en/modules/rc/ is missing in the 1.5.4.1 branch
- FAQ: https://nodemcu.readthedocs.io/en/latest/en/lua-developer-faq/ has evolved only in the master & dev branch

Is is worth manually pulling over these changes to the 1.5.4.1 & ESP32 branches?

**Comment by devsaurus** [comment]
> Is is worth manually pulling over these changes to the 1.5.4.1 & ESP32 branches?

For 1.5.4.1 I'm not sure about the dependencies of the FAQs to actual features/functionality in the firmware. It might turn out that updating FAQ content in 1.5.4.1 requires a selective approach along based on whether items are applicable to 1.5.4.1 or not. But I might be too pessimistic on this.

For ESP32 the benefit is clearly evident IMO. Though it's just yet another item of asking whether we can support continuous manual synchronization between the branches? I don't see any such indication yet.

Best would be to follow up on #1657 and finally work out a strategy how to deal with the two forks.
