### ISSUE TITLE
Example server code freezes the ESP8266

### ISSUE THREAD

**Issue by marcoschwartz** [nodemcu/nodemcu-firmware#255]
Hi, I am using the example code to run a server on the ES8266:

srv=net.createServer(net.TCP) 
    srv:listen(80,function(conn) 
      conn:on("receive",function(conn,payload) 
        print(payload) 
        conn:send("<h1> Hello, NodeMcu.</h1>")
      end) 
      conn:on("sent",function(conn) conn:close() end)
    end)

It works fine once, but freezes on the second request. I am using the latest version of the 0.9.5 firmware. Can you help on this issue? Thanks!

**Comment by mikewen** [comment]
Could be the problem of browser keep connection open. (Think your server is http 1.1)
And the second time, it just send the data without sending headers, and your code already close the connection.

**Comment by marcoschwartz** [comment]
Thanks! I've been thinking about something like that, but how can I solve it? I mean, this is 100% the example code from the README file, so it should work right?

**Comment by MarsTechHAN** [comment]
If we put http-head inside... The whole things will be very complex, because most the browser won;t act like that, so we think it is a trade-off that we like to see.

**Comment by nodemcu** [comment]
Hi, I am using Chrome. the example works fine. could you test more?

**Comment by marcoschwartz** [comment]
It works fine for me as well, but as I said it freezes the ESP8266 after the first request. Does that part works fine for you? Thanks

**Comment by nodemcu** [comment]
yes, can do many requests, I press re-fresh button in Chrome.

**Comment by dvv** [comment]
you should try responding with minimum correct HTTP response (see 1.0 for client to not keep the connection open):
```lua
conn:send("HTTP/1.0 200 OK\r\n\r\n<h1>Hello, NodeMcu.</h1>")
```

**Comment by mercury123456** [comment]
I have the exact same problem.
I found that setting STATIONAP insted of STATION at the beginning the connection is always alive, I know is not the right way but it works fine. I will find a better solution in the future.

**Comment by mercury123456** [comment]
found here:
http://www.esp8266.com/viewtopic.php?f=6&t=1946

**Comment by TerryE** [comment]
See #719
