### ISSUE TITLE
 PANIC: unprotected error in call to Lua API (error loading module ..from file)

### ISSUE THREAD

**Issue by Fatihalparslan** [nodemcu/nodemcu-firmware#2563]
HI everyone 
I use ESPLorerv0.2.0 for programing NodeMCU Lolin. When I upload my program with have two lua module files i take this error:
 E:M 520
PANIC: unprotected error in call to Lua API (error loading module 'StaMod' from file 'StaMod.lua':
	not enough memory)

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 29564, room 16 
tail 12
chksum 0x86
ho 0 tail 12 room 4
load 0x3ffe8000, len 2212, room 12 
tail 8
chksum 0x7b
load 0x3ffe88a4, len 8, room 0 
tail 8
chksum 0xa6
csum 0xa6
don't use rtc mem data
Can anyone help me?

**Comment by marcelstoer** [comment]
See #1010 -> http://nodemcu.readthedocs.io/en/latest/en/support/
