### ISSUE TITLE
Travis decommissions container based builds

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#2568]
We need to remove the `sudo:false` flag from our `.travis.yml` file.

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

**Comment by TerryE** [comment]
@marcelstoer, as far as I read it, there is nothing in the build that will break with `sudo:false` so this is a cased of "just do it" :smile:

**Comment by marcelstoer** [comment]
That was my intention, indeed (therefore assigned to me). Had I just committed w/o creating this issue first others might have missed this important(?) Travis development. So its primary intention is to notify our community.
