### ISSUE TITLE
Gitter chat for nodemcu

### ISSUE THREAD

**Issue by kireevco** [nodemcu/nodemcu-firmware#257]
Please add gitter to this repository
https://gitter.im

This will allow to chat about the firmware and minimize issues creation

**Comment by GeorgeHahn** [comment]
+1

**Comment by inversesandwich** [comment]
+1

**Comment by MarsTechHAN** [comment]
+1

**Comment by nodemcu** [comment]
[chat here](https://gitter.im/nodemcu/nodemcu-firmware)

**Comment by kireevco** [comment]
awesome,thank you
