### ISSUE TITLE
tls.cert.auth should be exposed in the documentation

### ISSUE THREAD

**Issue by dtran123** [nodemcu/nodemcu-firmware#2578]
### Expected behavior

Documentation to include tls.cert.auth as an available function.
As indicated by issue #2576, I was able to apply both auth & ca certs to tls
in my connection to mqtt broker (which requires both) using:

tls.cert.auth(true)
tls.cert.verify(true)

### Actual behavior

Documentation excludes mention of tls.cert.auth

### Test code

The following code will work:

tls.cert.auth(true)
tls.cert.verify(true)

### NodeMCU version

Both dev and master branches don't mention  tls.cert.auth.

### Hardware

N/A

**Comment by marcelstoer** [comment]
Could you support NodeMCU by providing a PR with the necessary additions to the documentation?

**Comment by dtran123** [comment]
More characterization needs to be done before we expose tls.cert.auth because there are many scenarios beyond mqtt (my usecase) such as https, etc. As such, more testing needs to be done first to determine the usecases where this function is reliably applicable.

**Comment by HHHartmann** [comment]
We should either document this properly or remove the functionality.
@pjsg  could you as the original author (#1125) shed some light on this so it can be documented?
If there is a consensus I can also remove this functionality.

**Comment by dtran123** [comment]
Please don't remove the functionality as it works fine. It just needs proper documentation. This feature is absolutely needed for a complete TLS secured connection.

**Comment by dtran123** [comment]
To use this feature, you configure the cert and RSA key:

tls.cert.auth(
    [[
    -----BEGIN CERTIFICATE-----
    CLIENT CERTIFICATE String (PEM file)
    -----END CERTIFICATE-----
    ]]
    ,
    [[
    -----BEGIN RSA PRIVATE KEY-----
    CLIENT PRIVATE KEY String (PEM file)
    -----END RSA PRIVATE KEY-----
    ]]
    )

Then, enable verification:
tls.cert.auth(true)
