### ISSUE TITLE
[FR] module for sending data to monitoring system(s)

### ISSUE THREAD

**Issue by ildar** [nodemcu/nodemcu-firmware#2589]
### Missing feature
A module to send data to monitoring systems

### Justification
Some guys have their ESPs acting as a (IoT) Zabbix agent:
https://www.youtube.com/watch?v=DwjTAvn0Ymo
https://github.com/intellitrend/zabbix-iot
Guess it would be great to have features from both worlds.

**Comment by HHHartmann** [comment]
The protocol seems to be pretty straight forward and IMHO could be easily implemented in Lua.

**Comment by marcelstoer** [comment]
@ildar did you consider #1010? Are you willing to contribute a Lua module for that?

**Comment by ildar** [comment]
I see.
I'm definitely not ready as still learning both Zabbix and NodeMCU. Should
I close then? Or you?
