### ISSUE TITLE
net.server.listen does not closes after server closed

### ISSUE THREAD

**Issue by Toshik** [nodemcu/nodemcu-firmware#26]
```
a=net.createServer(net.TCP)
a:listen(8080,function(fc) ... end)
...
a:close()
b=net.createServer(net.TCP)
b:listen(80,function(fc) ... end)
```
Then NodeMCU answers at ports 8080 and 80, but should only 80

**Comment by layerzerolabs** [comment]
This bug also reported by ThomasW here: http://www.esp8266.com/posting.php?mode=reply&f=24&t=1285#pr7590
"Interestingly, i just learned that if you stop a server as described above and start another one on a different port the module keeps listening on the previous port too (I think this is a bug) but uses the callbacks of the active one."
If this bug can be reproduced and then fixed, we might be able to create a dns server, respond to a request, close down the server and then start a http server process.
Even better would be the ability to run two server processes (on different ports) at the same time?

**Comment by acalatrava** [comment]
Call me crazy but couldn't be this used as a feature? If we have a way to know what TCP port was connected we can use this "bug" to open two ports and use them... Something like this:

a=net.createServer(net.TCP)
a:listen(53, nil)
a:close()
b=net.createServer(net.TCP)
b:listen(80,function(conn)
  conn:on("receive",function(conn,payload)
     if conn.destport == 53 then
        ...
     elseif conn.destport == 80 then
        ...
     end
  end)
end)

**Comment by acalatrava** [comment]
And another thing that comes to my mind, it seems you can start a TCP server AND a UDP server. You can set the DNS server in UDP since the client will use UDP (unless the request or the response is too large)

**Comment by dwery** [comment]
bug confirmed as of today, version 0.9.6

**Comment by TerryE** [comment]
See #719
