### ISSUE TITLE
ESP32: Long Range Wi-Fi Protocol Mode

### ISSUE THREAD

**Issue by LDmitryL** [nodemcu/nodemcu-firmware#2611]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
We really need support for switching Wi-Fi Protocol mode **802.11 LR** in NodeMCU. 

### Justification
According to the manufacturer communication distance in **one-kilometre** is very much helped in the attraction device on the basis of ESP32
8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by nwf** [comment]
Please see #1010 and note that
- the attainable bandwidth for this 802.11 LR is likely to be quite small and
- it requires that both endpoints of the communication be ESP32 devices.

**Comment by marcelstoer** [comment]
@LDmitryL are you proposing to resource the development yourself?

**Comment by LDmitryL** [comment]
@marcelstoer No. I can't. I ask for help from outside to implement this feature! I think this functionality is very important in the area where we use NodeMCU.

**Comment by marcelstoer** [comment]
> in the area where **we** use NodeMCU

That's the point that #1010 is trying to make. If you need a feature, how ever useful it might be (like this one), that the volunteers here haven't implemented yet then you should be prepared to fund it yourself - time- or otherwise.

**Comment by LDmitryL** [comment]
@marcelstoer The existance of the switching protocols function is needed not only for me. But the existance of such function in LUA for NodeMCU makes it more attractive and useful for other developers of automation at home. Maybe that will push other developers to the nodemcu-firmware issue

**Comment by x-logLT** [comment]
For now I have implemented this functionality in my "[work in progress](https://github.com/x-logLT/nodemcu-firmware/tree/esp32-working)" branch, if it works as intended I'll make a PR some time later.
mode can be set then calling config for ap or sta and setting phymode in cfg table, available values are:
```
wifi.PHYMODE_B
wifi.PHYMODE_BG
wifi.PHYMODE_BGN
wifi.PHYMODE_BGNLR
wifi.PHYMODE_LR
```
