### ISSUE TITLE
ESP32: huge memory leak in http one-shot requests

### ISSUE THREAD

**Issue by jpeletier** [nodemcu/nodemcu-firmware#2614]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
All memory is released when using `http.get(url, callback)`
### Actual behavior
Around 2k of memory is retained every time you call `http.get(url, callback)`
### Test code
```Lua
collectgarbage()
a=node.heap()
count=0
function finish()
    collectgarbage()
    b=node.heap()
    print(string.format("\n\n\n\n\n\ndiff %d-%d=%d\n\n\n", a,b,a-b))
    a=b
    count=count+1
    if count < 200 then
       tmr.create():alarm(50, tmr.ALARM_SINGLE, herewegoagain)
    end 
end


function herewegoagain()
    http.get("SOME_URL", function(code, body, headers)
        tmr.create():alarm(100, tmr.ALARM_SINGLE, finish)
    end)
end

herewegoagain()
```
Executing the above will quickly exhaust your heap. At some point you'll get an error saying "cannot create rtos task", or other memory related issues.

### NodeMCU version
`dev-esp32`, `1adbc791062563aa99a6a010dfff384b6299b0d9`

### Hardware
ESP-32
8<------------------------ END BUG REPORT -------------------------------------

**Comment by TerryE** [comment]
@jpeletier Javier nothing to do with this issue, but you should read my FAQ on the use of locals :stuck_out_tongue_winking_eye:
