### ISSUE TITLE
I get a bug of fireware

### ISSUE THREAD

**Issue by UFU123** [nodemcu/nodemcu-firmware#2616]
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and **DELETE THE REST**.

8<------------------------ BUG REPORT -----------------------------------------
Today i get a fireware from your web but it flashing flashing flashing ... when i end the update and reset.
It can't work!

I had this bug twice before, maybe I do something wrong, but where? 
Anyone help me , thank u!

This was built against the master branch and includes the following modules: adc, bit, crypto, enduser_setup, file, gpio, http, i2c, net, node, ow, pwm, spi, tmr, uart, websocket, wifi, wps, tls.

### Hardware
12E
8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
> Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
