### ISSUE TITLE
Memory saving in mbedtls

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2620]
### Missing feature
We should set the MBEDTLS_SSL_OUT_CONTENT_LEN config variable to 1024 which will save a bunch of memory. The incoming buffer still has to be large to deal with legacy systems that don't support the max fragment length extension.

### Justification
Saves a bunch of RAM

**Comment by marcelstoer** [comment]
There's some wisdom collected in https://github.com/espressif/ESP8266_NONOS_SDK/issues/219
