### ISSUE TITLE
Removing / clearing a static IP

### ISSUE THREAD

**Issue by Timmiej93** [nodemcu/nodemcu-firmware#2624]
-------------------------- FEATURE REQUEST ------------------------------------
### Missing feature
Removing a static IP (static IP being set by wifi.sta.setip())

### Justification
Since it's possible to set a static IP, I think it should be possible to clear it as well, and have the IP revert to an automatically assigned one.

### Workarounds
I have not been able to come up with a workaround, since I can't clear the set IP in any way.

**Comment by dariuski** [comment]
In module **wifi.c** there is only **wifi_station_dhcpc_stop()** but no **wifi_station_dhcpc_start()** which is the only way to disable static IP and start DHCPc.
It means there is no other way at the moment to remove static IP as only to restart the device.
