### ISSUE TITLE
endusersetup clarification needed

### ISSUE THREAD

**Issue by IDispose** [nodemcu/nodemcu-firmware#2630]
Enduser setup docs [here](https://nodemcu.readthedocs.io/en/master/en/modules/enduser-setup/) states /setwifi is an Endpoint intended for services to use for setting the wifi credentials.

What does "indented for services" mean? Can I create a service that'll receive the form post data? Or does it mean the wifi_name and password is just set as variables in memory and magically configure the wifi connection?

**Comment by hmil** [comment]
Seems pretty straightforward to me.
It just means you can make a program that will configure the device using this endpoint.

For instance, connect to the Setup_Gadget network, open a web page to show the login portal and then write the following command in your terminal.

```

curl 'http://example.com/setwifi?wifi_ssid=YOUR_SSID&wifi_password=YOUR_PASSWORD'
```

A few seconds later, you will see in your browser that your nodemcu has successfully connected to the wifi.

**Comment by IDispose** [comment]
@hmil Thanks for your response. I understand that part and it works as expected. However the statement "intended for services" implies I can write a service (dont know what that is) that will listen to the post and the service can then process the post message and data. In addition to `wifi_ssid` and `wifi_password` can I pass additional query string parameters?

**Comment by HHHartmann** [comment]
It is intended for a service to call. Its meant for automatically setting up (many) gadgets without user Interaction where some kind of a service can scan for WIFIs, connect and set the credentials.
