### ISSUE TITLE
DNS resolution failure when using tls.socket:dns() 

### ISSUE THREAD

**Issue by NicolSpies** [nodemcu/nodemcu-firmware#2640]
### Expected behavior
It is expected that tls.socket:dns() provides a DNS resolution for a hostname.
### Actual behavior
Callback function never fires indicating no resolving. Resolving of domain was confirmed with `net.dns.resolve(host, function(sk, ip))`
### Test code
```Lua
sk = tls.createConnection()
sk:dns("google.com", function(conn, ip) print(ip) end)
```
### NodeMCU version
```Lua
 NodeMCU 2.2.0.0 built with Docker provided by frightanic.com
	branch: dev
	commit: 0e89fb24bae3c3dcd446b64f9bbc6d9581c08632
	SSL: true
	Build type: float
	LFS: Size: 0x10000
	modules: adxl345,cron,file,gpio,http,i2c,net,node,rtcmem,rtctime,sjson,tls,tmr,uart,wifi
 build created on 2019-01-23 10:59
 powered by Lua 5.1.4 on SDK 2.2.1(6ab97e9)
```
### Hardware
Standard ESP12 hardware configuration.

**Comment by nwf** [comment]
Why do we have separate `net.dns` and `tls.dns` functions, anyway?

**Comment by NicolSpies** [comment]
I believe it might be related to the fact that when you create a `tls.createConnection` the tls.socket sub module returned have a number of methods of which dns is one of them.

**Comment by nwf** [comment]
That's not the right kind of answer to a "why" question.

**Comment by marcelstoer** [comment]
👍 for dumping `tls.dns` unless @djphoenix who wrote that (or anyone else) comes forward with good reasons for keeping it.
