### ISSUE TITLE
Please cleanup trailing spaces

### ISSUE THREAD

**Issue by 532910** [nodemcu/nodemcu-firmware#2648]
There are a lot of trailing spaces that reduces readability and should be cleaned up.

**Comment by c-e-p-x-u-o** [comment]
fixed via #2649

**Comment by ziggurat29** [comment]
and in some cases, trailing spaces can break things.  e.g. trailing spaces after a backslash that is a line continuation character in a multi-line #define, at least if the compiler strictly adheres to the standard.  E.g. C++ standard section 2.2:

> "Each instance of a backslash character () **immediately** followed by a new-line character is deleted,
> splicing physical source lines to form logical source lines."

(emphasis added)

**Comment by TerryE** [comment]
In principle, doing this and any tab expansion cleanup is good house keeping and it makes sense to do this. 

However, the converse to @ziggurat29's point is also true: it is possible that in rare cases trailing blanks might have semantic significance and should not be removed.  So we should just present this as a PR without at least doing the static analysis and reviewing this first.
