### ISSUE TITLE
Add support for DHCP NTP server

### ISSUE THREAD

**Issue by 532910** [nodemcu/nodemcu-firmware#2651]
Please add support for ntp server over dhcp.

**Comment by nwf** [comment]
See #1010.  Also you should be more clear what you mean; NTP does not run over DHCP, so either you mean for setting the DHCP option identifying the NTP host in DHCP offers (relatively easy) or for the ESP8266 to be a NTP server (way harder).  But for either one, see #1010 or contact one of us out of band for contracting rates.

**Comment by c-e-p-x-u-o** [comment]
I mean dhcp option 42.
I have the working patch, that I'll PR tomorrow.

**Comment by marcelstoer** [comment]
@nwf the author included the patch for this by mistake in the (now closed) PR #2649.

**Comment by nwf** [comment]
Sorry, the issue text made it sound like this was another request for development effort.  I look forward to the PR.
