### ISSUE TITLE
Not flashing at all 

### ISSUE THREAD

**Issue by UrafikiTheFluff** [nodemcu/nodemcu-firmware#2652]
ok so i got the Ämica"one and i got 4 others from a differnet company they all have the cp2012 driver and stuff i have used the "nodemcu firmware programmer"and ive used audrinoide i just dont know what the heck to do i need some help can someone lead me to the right direction please a actual youtube help video im just not getting like uk the wifi thing were i get on my android phone it still shows like ""ESP_212374" this is becoming annoying please help me

**Comment by nwf** [comment]
Please see #1010; this is not a general nodemcu support forum.

**Comment by UrafikiTheFluff** [comment]
where do i get help then?

**Comment by nwf** [comment]
As per #1010, please see our support page, https://nodemcu.readthedocs.io/en/latest/support/
