### ISSUE TITLE
Please add support for tftp client.

### ISSUE THREAD

**Issue by 532910** [nodemcu/nodemcu-firmware#2663]
Please add support for tftp client.
 I'll try to make a pr, but not sure I can implement it.

The good one that I know is tftp-hpa https://git.kernel.org/pub/scm/network/tftp/tftp-hpa.git

Also it will be nice to receive server's ip over dhcp.

**Comment by TerryE** [comment]
> Please add support for tftp client

We already have a Lua module to a minimal FTP server in our lua_examples folder.  I can't see any advantage in slimming this down to TFTP, but you are welcome to try this for yourself.

>  it will be nice to receive server's ip over dhcp.

This is not an ESP function, but rather a DHCP one.  In station mode the DHCP look is a standard DHCP service function.  In AP mode, the ESP acts as the gateway.  IN both cases the IP address is available.

**Comment by c-e-p-x-u-o** [comment]
How "FTP server" is relate to "tftp client"?
Please reopen!

**Comment by c-e-p-x-u-o** [comment]
tftp has nothing common with ftp!

**Comment by c-e-p-x-u-o** [comment]
http client is ESP function: https://nodemcu.readthedocs.io/en/master/en/modules/http/
mqtt client is ESP function: https://nodemcu.readthedocs.io/en/master/en/modules/mqtt/
tftp client is also ESP function!

**Comment by nwf** [comment]
@c-e-p-x-u-o I agree a TFTP client could be of some utility for NodeMCU, but as per #1010, just open a PR with your contribution when it's ready.

**Comment by c-e-p-x-u-o** [comment]
Issue should be left opened as it's not fixed.

**Comment by c-e-p-x-u-o** [comment]
I'd like to updated lua scripts from external TFTP server.
The next step is OTA over TFTP offered by DHCP.

**Comment by nwf** [comment]
@c-e-p-x-u-o For the love of my inbox, type longer comments rather than splitting thoughts across several.  I understand why you might want TFTP support, but none of us are, AFAIK, likely to work on it; we'll review a PR when you open one.

**Comment by c-e-p-x-u-o** [comment]
Sorry.

**Comment by TerryE** [comment]
@c-e-p-x-u-o, as Nathaniel suggests, please follow our contribution guidelines and GitHub issues etiquette when posting to an issue.  If you want to use an IRC paradigm then we also have a gitter thread.  I've merged some of your fragment posts. 

I reopened the issue temporarily since as you point out this is about _client_ not server functionality.  It would be very straightforward implementing this as an LFS-style Lua module.  See my `lua_examples/lfs/HTTP_OTA.lua` as a starting point.  Feel free to raise a PR when you've got this working.

**Comment by marcelstoer** [comment]
> I'll try to make a pr

Great, that's the right spirit!

Thanks for following [our guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/master/CONTRIBUTING.md) by first creating an issue before raising a PR. We appreciate that.

**Comment by TerryE** [comment]
@532910 Sergio, TFTP is a nice keep-it-simple protocal for local LAN and Wifi deployments and as I said above, it should be straightforward to implement this as an LFS compatible Lua module.  As Marcel says: have a go and upload it to your own github fork.  We will constructively support you in this :smile:

**Comment by 532910** [comment]
Dear bot, please don't close it, I'll try to implement it, I promiss (:
