### ISSUE TITLE
ntp timezone over dhcp tcode pcode options 100 101

### ISSUE THREAD

**Issue by 532910** [nodemcu/nodemcu-firmware#2664]
Please add support for ntp timezone over dhcp tcode/pcode options 100 101
I'll try to make a pr, but not sure I can implement it.

Related RFC: https://tools.ietf.org/html/rfc4833

pcode -> tcode in lua:
https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/sys/zoneinfo/tzdata.lua

**Comment by pjsg** [comment]
I think that it would make sense to save the option 100 and 101 values, and then provide a LUA api to be able to get those values. The actual timezone conversion should probably be done in LUA code.... I have some code that interprets a compiled tzinfo file.....

**Comment by c-e-p-x-u-o** [comment]
agree!

**Comment by marcelstoer** [comment]
> [I have some code](https://github.com/nodemcu/nodemcu-firmware/tree/master/lua_examples/timezone) that interprets a compiled tzinfo file

I wonder why have this in `/lua_examples` rather than in `/lua_modules`?

**Comment by pjsg** [comment]
Probably because lua_modules didn't exist at that time.

**Comment by marcelstoer** [comment]
More OT, sorry: that folder goes way back to Dec 2014 😉

**Comment by 532910** [comment]
Not sure if it's clear for me how to implement it.

**Comment by HHHartmann** [comment]
Maybe we shoud at least move the timezone example to modules then
