### ISSUE TITLE
new pwm module (pwm2)

### ISSUE THREAD

**Issue by fikin** [nodemcu/nodemcu-firmware#2667]
### Justification
I guess there is no need to justify why 1kHZ limit of current SDK provided PWM is not good enough.

Lately I've played with https://github.com/StefanBruens/ESP8266_new_pwm. 
Its theoretical limit is 5MHz but I don't have equipment to confirm it. 
With my (cheap) oscilloscope I can observe up to 50kHz and it seems correct. 
Playing in smaller 1-5kHz range I haven't seen any duty cycle side effects either.
It would be great if someone can test it with better hw thought.
And I haven't tested with many pins, but that probably is only matter of time ;)

Stefan's library is for Arduino. I've adopted it as "pwm2" module for nodemcu.
https://github.com/fikin/nodemcu-firmware/tree/pwm2

The implementation is based around a driver, a header and lua bindings. Documentation has an example how that is programmed from lua pov.

Feedback is welcome! 

### Workarounds
Are there any? ;)

**Comment by nwf** [comment]
Please open a PR rather than an issue for review!
