### ISSUE TITLE
How to create a binary image containing custom LUA files (e.g. init.lua)

### ISSUE THREAD

**Issue by LanFly** [nodemcu/nodemcu-firmware#2676]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Create a binary image containing custom LUA files (e.g. init.lua).

I can build the firmware using docker-nodemcu-build, but I want to containing custom LUA files. I tried to find the information on the docs and google but could not find it. I don't know how to do this.

### Justification
I am trying to create a firmware containing Lua files so that I can upload Lua files to nodemcu while burning the firmware.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
You might want to read up on LFS in our documentation.

https://nodemcu.readthedocs.io/en/latest/getting-started/#upload-lfs-image
https://nodemcu.readthedocs.io/en/latest/lfs/
