### ISSUE TITLE
luac msvc build broken

### ISSUE THREAD

**Issue by ziggurat29** [nodemcu/nodemcu-firmware#2677]
### Expected behavior
hosttools will build with MSVC
### Actual behavior
hosttools does not build MSVC
### Test code
try to build with MSVC; syntax errors are emitted from lrotable.h, and linit.c
### NodeMCU version
dev
### Details
minor syntax errors; I am submitting this bug report really just to generate an issue number to associate with the PR that I will be submitting immediately afterwards.

**Comment by TerryE** [comment]
Thanks @ziggurat29, @marcelstoer :sob:
