### ISSUE TITLE
Add Ultrasonic sensor driver

### ISSUE THREAD

**Issue by mikewen** [nodemcu/nodemcu-firmware#268]
How about add Ultrasonic sensor driver ?

EAD Fritz already wrote C code:
https://github.com/eadf/esp8266_ping

**Comment by MarsTechHAN** [comment]
Too many block will make the whole program get bigger and bigger which is what we don't want to see. 
Can you rewrite that in Lua ? Or wait we add the ‘block select’ feature.
(Also... We highly recommend you to just pull for our people are always in busy...)

**Comment by mikewen** [comment]
I wrote the function in Lua , but because Ultra Sound sensor need very accurate timing, it was not working well.

**Comment by nodemcu** [comment]
you can make a PR to dev branch, 
and currently disable the module. for those who need this module, pull and rebuild it.

**Comment by dvv** [comment]
Wonder if we can load binary modules like big Lua does with  .so files?

**Comment by inversesandwich** [comment]
@dvv You can compile a Lua script into a binary, however it often doesn't make it much smaller, it just reduces the RAM usage.

**Comment by dvv** [comment]
I meant namelt binary modules not compiled scripts. That resembles
intrinsic modules like bit e.g.

**Comment by TerryE** [comment]
This falls into the won't fix unless we can get a contributor to develop this and open a PR.
