### ISSUE TITLE
Can't use Keyboard.h

### ISSUE THREAD

**Issue by N2Network** [nodemcu/nodemcu-firmware#2685]
I want to prefix this by saying I'm not an expert Arduino programmer. I'm trying to use a mini USB shield to connect a keyboard to my NODEMCU and load an Arduino script that uses some HID keyboard libraries. I'm getting the following errors and hoping someone can assist. The original Arduino program was written for an Arduino Pro Micro with an ESP8266. I assumed it would run on this NODEMCU. But perhaps I'm wrong.

HID.h: No such file or directory
#include "HID.h"

#include <Keyboard.h>
#include <hidboot.h>
#include <usbhub.h>

8<------------------------ BUG REPORT -----------------------------------------
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
-- add code here
```
### NodeMCU version
Which branch are you on? If you know the Git revision then add it here as well.

### Hardware
Describe which ESP8266 device you use and document any special hardware setup 
required to reproduce the problem.

8<------------------------ END BUG REPORT -------------------------------------

**Comment by nwf** [comment]
This is not the correct project for you; this is about a nodemcu board programmed in Lua.
