### ISSUE TITLE
node.heap show 4MB on esp32 with 64Mbit psram?

### ISSUE THREAD

**Issue by chk-jxcn** [nodemcu/nodemcu-firmware#2706]
I found node.heap show only about 4M on board with 64Mbit psram, where is the other memory space?
Any option in menuconfig help?

**Comment by devsaurus** [comment]
The esp-idf can only handle 4MB transparently. The [`Himem API`](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/himem.html#the-himem-allocation-api) is not used by NodeMCU.

**Comment by chk-jxcn** [comment]
Thank you, have read the document and...4M is enough for me.:-)
