### ISSUE TITLE
wifi.suspend() suspend_cb function not called when suspending, resume_cb called when resuming

### ISSUE THREAD

**Issue by poorandunlucky** [nodemcu/nodemcu-firmware#2716]
### Expected behavior

`wifi.suspend()` returns -1 after being passed a call that might be too long.

### Actual behavior

The `resume_cb` function is called, and seems to be fine, but nothing was printed when I used `wifi.suspend()`, at least on the first call...  I don't know about subsequent calls.  as `suspend_cb` is part of an optional series of arguments.

### Test code
```Lua
wifi.suspend ( { 
    duration = 0, 
    resume_cb = function ( ) print ( 'resumed' ) end, 
    suspend_cb = function ( ) print ( 'suspended' ) end, 
    preserve_mode = false 
} )`
```

This particular code works, but my actual function call doesn't.

Function call: 

```Lua
wifi.suspend ( { 
    duration = 0, 
    resume_cb = function ( ) log ( 'Wi-Fi: Operation resuming, re-opening from last known state.', 'wifi.lua, wifi_switch ( )', 'INFO' ) end, 
    suspend_cb = function ( ) log ( 'Wi-Fi: Operation suspended, re-enable with wifi_resume ( ).', 'wifi.lua, wifi_switch ( )', 'INFO' ) end, 
    preserve_mode = true 
} )
```

`log()` is just a function that prints to `stdout`.

The above call yields: `stdin:1: '<name>' expected near '', ''`

I think it's just too long, but I don't know if that's important or not...  I just added two functions to my function that registers all the callback functions for `wifi`, probably shortening it enough...  There's nothing wring with my call to `log()`, I can copy/paste it and run it on its own.

### NodeMCU version

2.2.1 Master

### Hardware

ESP8266MOD

**Comment by poorandunlucky** [comment]
Actually there was a problem in my callback function...  : <

I just hooked a USB-UART thing to the RX/TX pins of the MCU and I got the error while calling the function, `wifi.suspend()` was returning -1...

Well done!  ^_^'

**Comment by TerryE** [comment]
There's a problem with your Lua syntax for a start.  I would expect something like:
```Lua
wifi.suspend ( 0, 
    function ( ) print ( 'resumed' ) end, 
    function ( ) print ( 'suspended' ) end, 
    false )`
```
An assignment staatement is not allowed to be embedded in an arglist in Lua.

**Comment by poorandunlucky** [comment]
@TerryE I'm sorry for the confusion...  I was working on too many things at the same time...

There is an actual problem with the wifi.suspend() function where it won't accept the call I was trying to pass, my guess for being too long...  wifi.suspend() actually takes a table as an argument, but my example code was missing brackets...

I edited my original post so everything is clear, and exact...  There shouldn't be any errors now.

**Comment by TerryE** [comment]
Yes, you are correct, suspend takes a hash, but it should only contain keyed entries:
```Lua
wifi.suspend ({
    duration = 0, 
    suspend_cb =  function ( ) print ( 'resumed' ) end, 
    resume_cb = function ( ) print ( 'suspended' ) end, 
    preserve_mode = false })
```
so for example omitting the `duration =` results in settiing the entry [1] to zero so the routine will report a missing duration, etc.

I am closing this for now.  Please reopen if needed -- once you've eliminated your own bug and are convinced that you are left with an underlying issue with the wifi module.
