### ISSUE TITLE
smartconfig

### ISSUE THREAD

**Issue by chenlugithub** [nodemcu/nodemcu-firmware#2719]
#使用手动编译nodemcu时加入u8g2模块提示缺少头文件u8x8.h怎么解决，以及一系列

8<------------------------ BUG REPORT -----------------------------------------
../include/user_config.h:251:2: error: #endif without #if
 #endif /* __USER_CONFIG_H__ */
  ^
In file included from ../modules/wifi_common.h:12:0,
                 from user_main.c:173:
../include/user_config.h:251:2: error: #endif without #if
 #endif /* __USER_CONFIG_H__ */
  ^
../../Makefile:366: recipe for target '.output/eagle/debug/obj/user_main.o' failed
make[2]: *** [.output/eagle/debug/obj/user_main.o] Error 1
make[2]: Leaving directory '/root/test/nodemcu-firmware/app/user'
../Makefile:327: recipe for target '.subdirs' failed
make[1]: *** [.subdirs] Error 2
make[1]: Leaving directory '/root/test/nodemcu-firmware/app'
Makefile:327: recipe for target '.subdirs' failed
make: *** [.subdirs] Error 2
make: Leaving directory '/root/test/nodemcu-firmware'

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
Maybe this https://nodemcu.readthedocs.io/en/master/build/#git but we don't understand this issue. See #1010.
