### ISSUE TITLE
Add u8g2's updateDisplayArea API

### ISSUE THREAD

**Issue by hmil** [nodemcu/nodemcu-firmware#2722]
### Missing feature

Upgrade the u8g2 dependency and add the lua bindings for [updateDisplayArea](https://github.com/olikraus/u8g2/wiki/u8g2reference#updatedisplayarea).

### Justification

Version [2.25.10 of u8g2 (released last february)](https://github.com/olikraus/u8g2/blob/master/ChangeLog) introduces the very valuable `updateDisplayArea` API. This API enables realtime graphics at framerates we couldn't dream of before. I'm able to run pong on the ESP8266 thanks to this API.

### Workarounds

I don't know any other way to get that kind of performance for graphics rendering (besides writing the low-level graphics routines directly...)

**Comment by devsaurus** [comment]
Proposed change was merged to `dev`.
