### ISSUE TITLE
Why do we install srecord in our Travis builds

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#2741]
@marcelstoer A quick question.

I am debugging a Travis build and I notice that we install **`srecord`** ([here](/nodemcu/nodemcu-firmware/blob/master/.travis.yml#L6)).  I can't see us using this, so is there any specific reason that I've missed?

**Comment by marcelstoer** [comment]
Line 21, `srec_cat` https://github.com/nodemcu/nodemcu-firmware/blob/master/.travis.yml#L21

**Comment by TerryE** [comment]
Yup, I twigged after I posted.  Seems a bit like over kill downloading an extra package when you could do this in bash using `dd | tr` to generate the 0xFF fill bytes, but this is a very low priority issue in my view.  I'll close this one now.  Thanks :smile:
