### ISSUE TITLE
Docs need update for 3.0

### ISSUE THREAD

**Issue by jmattsson** [nodemcu/nodemcu-firmware#2746]
We have an explicit link to the 2.2 SDK over at https://nodemcu.readthedocs.io/en/dev/flash/#sdk-init-data which I presume is no longer correct to use, and we also make mention of particular sectors for the init data, which again I believe is no longer correct with the new partition table support?

@TerryE @nwf  do either of you have time/knowledge to update this? Or dob in someone who can? :)

**Comment by TerryE** [comment]
Thanks for the prompt, Johny.  I'll pick this up on the next push.

**Comment by TerryE** [comment]
Fixed in #3193
