### ISSUE TITLE
GitHub abuse

### ISSUE THREAD

**Issue by cwrseck** [nodemcu/nodemcu-firmware#2748]
I've no idea where if anywhere this problem fits, and I can't see a fix apart from  changing the name of the project (which really isn't practical), but a search for "nodemcu-firmware" on GitHub gets  the reponse:
```
Whoa there!

You have triggered an abuse detection mechanism.
Please wait a few minutes before you try again.
Contact Support — GitHub Status — @githubstatus
```

Document this? Ignore this?? Or ???

C W Rose

**Comment by TerryE** [comment]
Hi.  If you google **github  You have triggered an abuse detection mechanism** then you will see that it is an intermittent general GitHub issue, so this falls into the "ignore and retry" category as far as this repo is concerned.  :smile:
