### ISSUE TITLE
FIrmware fails to build with #define PMSLEEP_ENABLE

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2754]
### Expected behavior
The firmware should build
### Actual behavior
It fails building app/modules/node.c

### NodeMCU version
Today's dev branch

The solution is to remove the extra comma......

Even then, I thought that the LROT stuff had to have the keys in alphabetical order -- which is vry much not the case for node.c

**Comment by TerryE** [comment]
> Even then, I thought that the LROT stuff had to have the keys in alphabetical order -- which is vry much not the case for node.c

There is a trade-off here: you need a minimum of maybe 6 entries in your ROTable before a binary chop is on average any faster than a simple linear search -- and the search only takes place now anyway where there is a cache miss -- for example where `__index` meta is used to chain ROTables.  So my current thinking is to make the binary chop optional, and only use it initially on the higher frequency long tables where this is the case -- for example the baselib ROTable.

As far as the comma goes -- Philip Is can do this on my next PR if you want.  Your call.

**Comment by pjsg** [comment]
Do it on your next pr

**Comment by TerryE** [comment]
Philip, thanks for the feedback and will do :smile:

**Comment by TerryE** [comment]
#2757 fixes this.
