### ISSUE TITLE
node.info() missing for ESP32

### ISSUE THREAD

**Issue by coolwolf** [nodemcu/nodemcu-firmware#2759]
on esp32
**=node.info()** command
returns:
**stdin:1: attempt to call field 'info' (a nil value)**

**Comment by marcelstoer** [comment]
Yep, [ain't implemented yet](https://github.com/nodemcu/nodemcu-firmware/blob/dev-esp32/components/modules/node.c#L393). Now you can argue whether it's a "bug" that it's included in the API documentation or that it's not implemented 😉 

One would need to port https://github.com/nodemcu/nodemcu-firmware/blob/4905381c004bdeaf744a60bb940c1906c2e052d4/app/modules/node.c#L125-L136 to ESP32.

**Comment by stuartpb** [comment]
For that matter, what about a field in node.info's returns that explicitly says whether the current chip is an ESP32 vs ESP8266, since there are a lot of divergent APIs between the two?

**Comment by ildar** [comment]
This is the current way to determine then )))

**Comment by marcelstoer** [comment]
@chilipeppr maybe something for you to tackle?

**Comment by chilipeppr** [comment]
That last few months I've had to dive back hard into the day job, so ruined
my ability to do much. Sorry. The tough nature of open source software and
real life.
