### ISSUE TITLE
lfs_fragments.lua: replace old static timer

### ISSUE THREAD

**Issue by alistairwitt** [nodemcu/nodemcu-firmware#2764]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Timer operates
### Actual behavior
Error as follows:
```
init.lua:1: attempt to call field 'alarm' (a nil value)
stack traceback:
	runlfs.lua:1: in main chunk
	[C]: in function 'dofile'
	stdin:1: in main chunk
```

### Test code
nodemcu-firmware/lua_examples/lfs/lfs_fragments.lua
lines 59 to 62 are using the old/removed static timer and need to be replaced with a dynamic one.

**Suggested replacement code:**
```
local initTimer = tmr.create()
initTimer:register(1000, tmr.ALARM_SINGLE,
    function()
        local fi=node.flashindex; return pcall(fi and fi'_init')
    end
    )
initTimer:start()
```

### NodeMCU version
master or dev branch

### Hardware
ESP8266, Wemos D1 Mini

8<------------------------ END BUG REPORT -------------------------------------

**Comment by marcelstoer** [comment]
Was recently fixed with #2752.

**Comment by alistairwitt** [comment]
I can only see changes in #2752 that relate to luaOTA, not lfs_fragments.lua. Am I missing something?
Cheers,
Alistair

On 21 May 2019, at 9:03 pm, Marcel Stör <notifications@github.com<mailto:notifications@github.com>> wrote:


Was recently fixed with #2752<https://github.com/nodemcu/nodemcu-firmware/pull/2752>.

**Comment by marcelstoer** [comment]
Argh...I spoke too soon, sorry 🤦‍♂

**Comment by HHHartmann** [comment]
@alistairwitt your suggested changes look good. 
Do you want to create a PR?

**Comment by alistairwitt** [comment]
@HHHartmann I'll give it a go. I should be able to get to this around 12 hours from now.
