### ISSUE TITLE
New command request: file.systemfree()

### ISSUE THREAD

**Issue by 4refr0nt** [nodemcu/nodemcu-firmware#277]
Return of NodeMCU filesystem free size in bytes (for modules with different flash size)

**Comment by nodemcu** [comment]
please try:
```
remain, used, total = file.fsinfo().
```
in the dev branch after 20150310, pre_built bin is here https://github.com/nodemcu/nodemcu-firmware/releases/latest

**Comment by 4refr0nt** [comment]
in file.fsinfo() "used" not equal files summary size (byte to byte)

**Comment by nodemcu** [comment]
yes, the file system is aligned to 256 bytes logical pages.
the used amount is times of ( log_page_size - page_header )
because one logical page can only be used by one file.
even if the real file size is 1, it use at least 1 pages.

**Comment by 4refr0nt** [comment]
Thanks! Work great!
