### ISSUE TITLE
Adding SPI module to Arduino IDE

### ISSUE THREAD

**Issue by javadhabibi1500** [nodemcu/nodemcu-firmware#2784]
Hi, I want to use nodemcu  using it's SPI interface. ButI can't find out how to add SPI Module as a library to my nodemcu  code on arduino IDE. I can't find spi.h beside spi.c [here](https://github.com/nodemcu/nodemcu-firmware/tree/master/app/modules)
Please help me.
Thanks

**Comment by nwf** [comment]
You are in the wrong place; this is for a Lua-based firmware for ESP8266 and ESP32 devices, not the Arduino system.

**Comment by HHHartmann** [comment]
This project allows you to program the esp8288 using lua. For more information see the [documentation](https://nodemcu.readthedocs.io/en/master/upload/)
