### ISSUE TITLE
Improve error handling for: "PANIC: unprotected error in call to Lua API (attempt to concatenate a nil value)"

### ISSUE THREAD

**Issue by maciejmiklas** [nodemcu/nodemcu-firmware#2792]
Sometimes my program crashes with such error (nothing more):
`PANIC: unprotected error in call to Lua API (attempt to concatenate a nil value)`

Since it's not a small application (https://github.com/maciejmiklas/NodeMCUUtils) finding a reason for it is really hard. It would be nice, if we could get some more info in such situation (file, line), or at least node would restart.

I'm on ESP32 latest Frimware. "Panic handler behaviour" is set to "Print registers and reboot"

**Comment by TerryE** [comment]
Maciej, I am currently writing this out with my Lua 5.3 and to simplify the migration, I am back-porting some of these fixes to ESP8266 Lua 5.1.  I am not sure whether we'll get around to doing the backport to the ESP32. If not then this will need to wait to the common 5.3 release. Sorry.

**Comment by maciejmiklas** [comment]
super and thank you :)

**Comment by TerryE** [comment]
@maciejmiklas, Maciej, BTW in general if you want robust applications then it is sensible to do protected calls using `pcall()` or `xpcall()` and then you won't get panics anyway.

**Comment by maciejmiklas** [comment]
I have a few timers each one executes method trough `pcall()`, but I'm still getting sometimes panic. It's hard to determine the cause for it.
