### ISSUE TITLE
for or while clause repeat a large number cause to reset device

### ISSUE THREAD

**Issue by zzjcfj** [nodemcu/nodemcu-firmware#2809]
with nodemcu or other esp8266-01, device will reset if  loop a large number  
j=1
while j<300000
do
   j=j+1
end
print(j)

**Comment by TerryE** [comment]
Sorry, but this a case of [read the manual](https://nodemcu.readthedocs.io/en/dev/lua-developer-faq/#so-how-does-the-sdk-event-tasking-system-work-in-lua).
