### ISSUE TITLE
Node restarts during an "endless" loop

### ISSUE THREAD

**Issue by evgenitznikolov** [nodemcu/nodemcu-firmware#286]
Hi, 

Obviously the code below doesn't make sense, but in order to simplify the description of the problem I have reduced it to the following:

```LUA
while (1~=0) do 
     print(".") 
end
```

The result is that the node restarts after 5 seconds:
```
.
.
7Ó_ÇÏRSöfJSúfJSúfîá

NodeMCU 0.9.5 build 20150213  powered by Lua 5.1.4
lua: cannot open init.lua
> 
```

Could this be a bug?

Regards,

Evgeni

**Comment by Trilexus** [comment]
try 

```
while (1~=0) do 
     print(".") 
     tmr.wdclr()
end
```

to reset the watchdog timer ?

**Comment by evgenitznikolov** [comment]
Thank you, this solved the problem!
