### ISSUE TITLE
LUA script file compilation error

### ISSUE THREAD

**Issue by GarMingLi** [nodemcu/nodemcu-firmware#2867]
### Expected behavior
In the docker environment, lua script files are compiled into the nodemcu firmware.
### Actual behavior
Compilation error, error information is as follows:
```
Segmentation fault
Makefile:74:recipe for target 'spiffsscript' failed
make[1]: *** [spiffsscript] Error 139
make[1]: Leaving directory '/opt/nodemcu-firmware/tools'
Makefile:348:recipe for target 'spiffs-image' failed
make: *** [spiffs-image] Error 2
```
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
#define BUILD_SPIFFS
#define SPIFFS_FIXED_LOCATION        0x100000
#define SPIFFS_MAX_FILESYSTEM_SIZE    0x20000
#define SPIFFS_SIZE_1M_BOUNDARY
```
### NodeMCU version
NodeMCU 2.2.1  commit:4905381c004bdeaf744a60bb940c1906c2e052d4 
tag: 2.2.1-master_20190405
branch: master
### Hardware
ESP8266,ESP12S

**Comment by TerryE** [comment]
@GarMingLi, sorry but the project is staffed by community contributors and by policy we normally apply fixes to the current (in this case SDK 3.0) `dev` and this will cascade into `master`on the next master drop.  We don't attempt to fix issues in old versions, so this falls into the "won't fix" category.  If you can recreate this on current `dev` then please feel free to reopen this issue.
