### ISSUE TITLE
add OSC module support

### ISSUE THREAD

**Issue by diegodorado** [nodemcu/nodemcu-firmware#2879]
This isn't a bug, but a feature request.
It would be very useful to have an OSC module, at least an OSC client, and hopefully, an OSC server.
It would be glad to help to develop it if someone throw me some guidelines!

**Comment by ildar** [comment]
You mean this OSC?  https://github.com/janfiess/NodeMCU_OSC

**Comment by diegodorado** [comment]
yes, but to work with lua
