### ISSUE TITLE
gpio.trig does not remove callback (dev-esp32)

### ISSUE THREAD

**Issue by stevemac00** [nodemcu/nodemcu-firmware#2880]
### Expected behavior
Documentation states "trigger is disabled when [callback] omitted"
### Actual behavior
Interrupt callback is still there. The way I worked around it was to have a dummy function (il1) to switch to but it is not omitted.
### Test code
```Lua
gpio.config({gpio={22},dir=gpio.IN, pull=gpio.PULL_UP})
function il1() end
function il0() print('low') gpio.trig(22,gpio.INTR_LOW) end
gpio.trig(22,gpio.INTR_LOW,il0)
```

### NodeMCU version
dev-esp32
powered by Lua 5.1.4 on ESP-IDF v3.3-beta1-791-g890a341 on ESP-IDF v3.3-beta1-791-g890a341 on SDK IDF

### Hardware
ESP-32

**Comment by joysfera** [comment]
Just FYI, that is wildly incompatible with the current ESP8266 implementation, where documentation says:

> The previous callback function will be used if the function is omitted.

For disabling the trigger there's a special "none" trigger type.

Couldn't we have the ESP32 gpio module more compatible with the ESP8266 one? Or perhaps it is already implemented so, just the documentation is behind?

**Comment by stevemac00** [comment]
I found this by looking at C code.
gpio.INTR_NONE
Yes, the ESP8266 and ESP32 code is quite different in places but I was told the goal was to unite them at some point.

**Comment by joysfera** [comment]
@stevemac00 there's a great chance the INTR_NONE will do what you need (and is almost compatible with "none" of NodeMCU for ESP8266).

**Comment by tomsci** [comment]
Passing in `gpio.INTR_NONE` does kindasorta work in that it prevents the callback from being called, but does not unref the existing callback (or call `gpio_isr_handler_remove`).

Will open a PR for this (and to update the docs) as I just got hit by this too :)
