### ISSUE TITLE
Node will never get IP address if lua script started emedialy after node.restart()

### ISSUE THREAD

**Issue by evgenitznikolov** [nodemcu/nodemcu-firmware#290]
Hi, 

While playing with the module I noticed quite inconsistent behavior - the node was not getting an IP quite often. After some experiments I am quite sure that the reason was that I was executing my test script too fast after the reset (using node.restart()). 

Here is my test script:

```LUA
print (wifi.sta.status())
print (wifi.sta.getip())

if (wifi.sta.getip()==nil) then 
  wifi.setmode(wifi.STATION)
  wifi.sta.config("my SSID","my Password")
  while (wifi.sta.status()~=5) do  tmr.wdclr() print(wifi.sta.status()) end
end
```

Obviously it is not a showstopper but I don't know what will happen if I put this in init.lua...

Regards, 

E.

EDIT: BTW, now I know what will happen if I put it in init.lua -> now I have a real problem! - is there a way to prevent init.lua to start? :-(
EDIT2: Reflashing alone does not help as apparently the files are not deleted. I had to reflash the AT-firmware and then to flash back the LUA firmware. Now it works!

Nice Idea how to avoid init.lua problems: http://www.esp8266.com/viewtopic.php?f=18&t=1705

**Comment by nodemcu** [comment]
1, getip will return nil if it is called immediately after ssid setup. because ap takes time to assign a ip to station.
2, 
```lua
while (wifi.sta.status()~=5) do  tmr.wdclr() print(wifi.sta.status()) end
```
this code will prevent other part(tcp/ip stack) from running, wifi.sta.status() will never change.  makes  this a forever loop.
3, use tmr.alarm() to check this periodically.

**Comment by evgenitznikolov** [comment]
Does tmr.delay() also prevent the tpc/ip stack to run? I assumed it is using an interrupt but apparently it doesn't?

**Comment by nodemcu** [comment]
yes.
tmr.delay() is same as while loop. for loop
it uses cpu all the time.

**Comment by evgenitznikolov** [comment]
Thanks!
