### ISSUE TITLE
node.setpartitiontable

### ISSUE THREAD

**Issue by danjohn** [nodemcu/nodemcu-firmware#2919]
Just discovered the new `node.*` abilities with V3.0, much appreachated! **TY!**

But:`node.setpartitiontable{lfs_size=0x20000}` just bricks the chip, it starts up with "l�|��l�b|������r�b�b" (wrong baud rate, obviousely crashes in the boot code). The only way to get back is reflashing.

Does someone have a working example, how to establish a 128k LFS partition on a ESP8266/4M device with `nodemcu-build.com`-builded firmware?
(Also, IMO there shouldn't be a way to render the chip into nirvana by just calling a simple function (data checks?) ;-))

(Issue originating from: <https://github.com/marcelstoer/nodemcu-custom-build/issues/35#issuecomment-533079667>)

**Comment by TerryE** [comment]
@danjohn, sorry but I can't repeat this with my current #3193 build so I have to assume that we've fixed this in the tidy.
