### ISSUE TITLE
restart without error message

### ISSUE THREAD

**Issue by kubi57** [nodemcu/nodemcu-firmware#292]
Lua retarts without any error message with the following example code:

s="%3F"
s = string.gsub(s, "%%(..)", function(a) return string.char(tonumber(a, 16)) end)
print(s)

Am I doing anything wrong, or is this a bug?

**Comment by nodemcu** [comment]
you are passing a function to string.gsub as the third parameter?

**Comment by kubi57** [comment]
Yes, that wors fine. If you put 65 insted of tonumber(a, 16) it replaces the found patterns with the letter A. So functions as third parameter do work, but another function in there is apparently too much.

**Comment by kmpm** [comment]
I have something similar...
```
> s='abc'
> -- this works
> print(s:gsub('.', function (c) return c:byte() end))
979899  3
> --this crashes shortly after the result is printed.
> print(s:gsub('.', function (c) return string.format('%02X', c:byte()) end))
616263  3
>�S�٦N�;;W���

NodeMCU 0.9.6 build 20150318  powered by Lua 5.1.4
...
```

**Comment by kmpm** [comment]
This fails as well..
```
> s='abc'
> print(s:gsub('.', function (c) return string.char(97) end))
aaa     3
> J�
    @�M�Ds9ɗ����
```

**Comment by kmpm** [comment]
The unhex function in https://github.com/nodemcu/nodemcu-firmware/issues/59#issuecomment-77480952 fails as well.

**Comment by model101** [comment]
Moin,

at least the given examples should be fixed in dev branch now.

Fix was reducing stack usage of string functions.

Carsten

**Comment by devsaurus** [comment]
No issues seen with the examples above on current firmware.
See #719.
