### ISSUE TITLE
build smartconfig frameware meet some error

### ISSUE THREAD

**Issue by BruceAKABear** [nodemcu/nodemcu-firmware#2923]
hi, I want to test smart config so I build the firameware by myself
but when I build the frameware I meet some problem ! 

<------------------------ BUG REPORT -----------------------------------------
### Expected behavior

CC app/modules/wifi.c
wifi.c:20:31: fatal error: smart/smartconfig.h: No such file or directory
 #include "smart/smartconfig.h"
                               ^
compilation terminated.
../../Makefile:422: recipe for target '.output/eagle/debug/obj/wifi.o' failed
make[2]: *** [.output/eagle/debug/obj/wifi.o] Error 1
make[2]: Leaving directory '/mnt/f/forwsl/nodemcu-firmware-3.0-master_20190907/app/modules'

**Comment by marcelstoer** [comment]
See #2928. The fix is now on `dev`.
