### ISSUE TITLE
ESPNOW

### ISSUE THREAD

**Issue by poorandunlucky** [nodemcu/nodemcu-firmware#2924]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature

ESPNOW

### Justification

Well it's one of the big selling points for the ESP MCUs...  Oftentimes wifi is just overkill, or you want to implement an ecosystem of devices that doesn't use wifi per se, or that communicate between each other, and only a base station connects to wifi...  idk, really, it's just one of the things I was hoping to be able to play with, and I wanted to know if there were any plans on implementing it in NodeMCU...

### Workarounds

Well you can use the SDK, but you have to learn a whole new firmware, and it's not as pleasant to use as NodeMCU...

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
https://stackoverflow.com/questions/63168628/is-there-a-way-to-use-esp-now-protocol-using-lua linking here.

**Comment by jmattsson** [comment]
@poorandunlucky This is "a bit" late for this issue, but I've just raised a PR with a new `espnow` module, if you're interested in testing it.

**Comment by poorandunlucky** [comment]
well that's very nice...

how hard was it to put the code in a module?

i really love the Lua firmware, I think it's very elegant...


Patrick Dorion
📱 +1 438 345-4575

**Comment by jmattsson** [comment]
It was pretty straight forward to map the API, it was mainly a matter of time and "grunt work".

**Comment by poorandunlucky** [comment]
Yeah, that's pretty much what I gathered...  When I saw the project hadn't
been updated in quite some time, I took another look at the codebase,
especially the modules to figure out if I wanted to keep using the
firmware, or move on to something else...  I really like the simplicity,
and elegance of it, and being able to run stuff from SPIFFS to save RAM, i
don't know if that's unique to this, or not, but when I saw how simple the
modules really were, I decided there was no harm in sticking with it, and
worst case it would just help transition me to the ESP Non-OS IDF framework
that I originally wanted to use, but that was too complicated, and still
is, to some extent...

Thanks for letting me know, and for helping the project along!  Nodemcu is
definitely the most elegant piece of software I ever came across...


Patrick Dorion
📱 +1 438 345-4575
