### ISSUE TITLE
less Heap with new 3.0-master

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2935]
Before version 3.0 (cloud Build) in my project  i had about 21000 Heap left.
But with the new version it has come down to 17496
huge loss of memory.
why is this...? 
Esp8266
(Modules =file/node/wifi/gpio/mqtt/sntp/rtctime/net/tmr)

**Comment by TerryE** [comment]
> why is this...?

Because the SDK components take up another 4Kb.  Out of our control.  If you've only got 17Kb of heap left then use LFS and then you will have around 42Kb to work with.  Sorry but this falls into the won't fix category.
