### ISSUE TITLE
Upload to LFS

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2937]
How to upload to LFS using esplorer

**Comment by HHHartmann** [comment]
On Windows?  Use the ftp Server in Lua

**Comment by chathurangawijetunge** [comment]
Can you please give more details....
Tks

**Comment by chathurangawijetunge** [comment]
Is there a way to upload to LFS using uart

**Comment by HHHartmann** [comment]
What do you mean exactly by LFS? 
You have to upload the LFS image to the esp8266 and then use node.flashreload() command to load it into flash

**Comment by chathurangawijetunge** [comment]
I have a example.lua file. I can compile with node.compile()
So how do I upload to LFS this file.

**Comment by HHHartmann** [comment]
You need to compile it with luac.cross on your computer or with the online service. Then upload it to your nodemcu. 
Please also read the documentation and for further assistance please see #1010
