### ISSUE TITLE
Having memory leak problems when using gpio pulse

### ISSUE THREAD

**Issue by peterdownunder** [nodemcu/nodemcu-firmware#2940]
### Expected behavior
Memory should not leak on successive call to pulse.build
### Actual behavior
Memory leaks about 4k for every 100 calls in the sample below
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```
local function IntervalTimerRestart (timer)
    return function()
        print ('done:' .. node.heap())
        timer:start()
    end
end

local function IntervalTimerAction (actions, timer)
    return function()
        for id, a in next, actions do
            actions[id] = nil
        end
        table.insert(actions, { [7] = gpio.LOW, delay=500 })
        table.insert(actions, { [7] = gpio.HIGH, delay=500, loop=1, count=10})
        pulsar = gpio.pulse.build(actions)
        pulsar:start(IntervalTimerRestart (timer))
    end
end

gpio.mode(1, gpio.OUTPUT, gpio.PULLUP)
gpio.mode(7, gpio.OUTPUT, gpio.PULLUP)

gpio.write(1, gpio.LOW)
gpio.write(7, gpio.LOW)

node.egc.setmode(node.egc.ALWAYS)
local stepAction = {}
mytimer = tmr.create()
mytimer:alarm(1000, tmr.ALARM_SEMI, IntervalTimerAction(stepAction, mytimer))
```
### NodeMCU version
Building a local version of NodeMcu off master version 2.2.1

### Hardware
Describe which ESP8266 device you use and document any special hardware setup
required to reproduce the problem.
Standard ESP 12 (Amica) dev board

**Comment by pjsg** [comment]
This is very odd -- I've stared at the implementation of gpio.pulse and it looks plausible to me. I'm going to have to dig deeper!

**Comment by peterdownunder** [comment]
I did notice that there has been work done on pulse in the dev branch, none releated to memory.

Is it worth me trying on the dev branch

**Comment by pjsg** [comment]
I doubt it -- the differences between the current dev and master are just a
rename of a library function.

**Comment by nwf** [comment]
This seems like it's still a bug.
