### ISSUE TITLE
wifi.c file have a bug

### ISSUE THREAD

**Issue by yangyongda** [nodemcu/nodemcu-firmware#2952]
when WIFI_SMART_ENABLE is uncomment,  #include "smart/smartconfig.h" will build error,  because smart directory found not smartconfig.h file.  
 you can try

**Comment by yangyongda** [comment]
#ifdef WIFI_SMART_ENABLE
#include "smart/smart.h"
#include "smart/smartconfig.h" 

static int wifi_smart_succeed = LUA_NOREF;
#endif

please check  #include "smart/smartconfig.h"

**Comment by TerryE** [comment]
Duplicate of #2928
