### ISSUE TITLE
u8g2/ucg: allow to get list of available fonts

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#2966]
### Missing feature
u8g2/ucg don't tell me which fonts are available i.e. which ones I compiled into the firmware. Something like `getAvailableFonts()` would be handy.

### Justification
It's easy to forget which fonts you selected at the time you built the firmware. If you built it yourself (rather than using the cloud builder) you maybe still find the relevant `.h` files on your system - and hope you didn't tinker with them in the meantime.

### Workarounds
None - at least not unless you build the firmware yourself.

@devsaurus is this feasible?

**Comment by Michal78S** [comment]
I dig into hex file for _Font_. It isn't wery comfortable, but works.
![Fonts](https://user-images.githubusercontent.com/38104951/72528717-15b49100-386c-11ea-8d36-dea616a12c4f.jpg)

**Comment by HHHartmann** [comment]
Still seems to be a good feature to me.
