### ISSUE TITLE
Issues with http module when accessing an HTTPS API endpoint.

### ISSUE THREAD

**Issue by dankirkham** [nodemcu/nodemcu-firmware#2970]
### Expected behavior
I was able to run a successful GET request exactly once. It hasn't worked again. I am getting two error codes, `E:M 544` and `46`, and cannot determine what they mean.

### Actual behavior
```
E:M 544
HTTP client: Disconnected with error: 46
HTTP client: Connection timeout
```

### Test code
```Lua
local http = require("http")

API_APP = "redacted"
API_ENDPOINT = "https://graph-na04-useast2.api.smartthings.com/api/smartapps/installations/" .. API_APP
API_TOKEN = "redacted"

headers = "Authorization: Bearer " .. API_TOKEN .. "\r\n"
http.get(API_ENDPOINT .. "/switches", headers, function (code, data)
    print(data)
end)
```

### NodeMCU version
```
NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 310faf7fcc9130a296f7f17021d48c6d717f5fb6
	release: 3.0-master_20190907
	release DTS: 201909070945
	SSL: true
	build type: integer
	LFS: 0x0
	modules: file,gpio,http,net,node,sjson,tmr,uart,wifi,tls
 build 2019-11-24 14:43 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
```

### Hardware
NodeMCU v2 (HiLetgo on Amazon)

**Comment by marcelstoer** [comment]
SSL and HTTP are an endless source of frustration. If look through the (closed) issues here you'll find numerous examples of constellations that don't work. It's either memory constraints or lack of support for certain TLS features (ciphers, SNI, etc.).

You can try using the lower-level TLS as per https://nodemcu.readthedocs.io/en/latest/modules/tls/#tlssocketon but there is some doubt you'll have better luck. According to https://www.ssllabs.com/ssltest/analyze.html?d=smartthings.com&s=54.183.45.39 smartthings.com uses SNI.
