### ISSUE TITLE
node.flashreload('lfs.img') geting stuck

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2973]
I have expressed (like 1 time out of 20) in node.flashreload("lfs.img") get stuck...
No error return I have to physically restart.
Is it a bug...?
Any way to reboot automatically...

**Comment by TerryE** [comment]
Chathuranga, please follow the templates, and read #1010.  Without a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve), I can't really do anything with this sort of issue.

**Comment by seregaxvm** [comment]
It might be a good idea to verify LFS image checksum.
