### ISSUE TITLE
SJSON should have a validate JSON method

### ISSUE THREAD

**Issue by alexandruantochi** [nodemcu/nodemcu-firmware#2980]
### Missing feature
There is no way to validate the JSON string

### Justification
Running sjson.decode(string) on an invalid JSON will panic and reset the MCU.

### Workarounds
Using Lua pcall()

**Comment by HHHartmann** [comment]
Workaround would be to use pcall.

**Comment by TerryE** [comment]
@alexandruantochi  Another way of phrasing this is that the decode function throws the appropriate Lua error, and that catching these with pcall is the Lua way.

**Comment by alexandruantochi** [comment]
So I guess using pcall() would be the way to do it and there is no need for a "validate" method.
