### ISSUE TITLE
Problem writing bin file to ESP8266 and different error message

### ISSUE THREAD

**Issue by JohnSmith-LT** [nodemcu/nodemcu-firmware#299]
Hi,

Most likely something I am doing but using esp8266_flasher to write the integer build binary nodemcu_integer_0.9.5_20150318.bin results in this message:

Writing at 0x00065c00... (100 %)
Failed to write to target Flash

Same thing happens with the floating point build. This is not the same message as when you write the ESP_8266_BIN0.92.bin and get:

Writing at 0x0007ec00... (99 %)
Leaving...
Failed to leave Flash mode

which seems to work fine...

Any thoughts? Is there another flasher that I should use?

**Comment by nodemcu** [comment]
https://github.com/nodemcu/nodemcu-flasher

**Comment by JohnSmith-LT** [comment]
Thank you. You know i've actually used that before as well but completely forgot about it! D'oh

**Comment by JohnSmith-LT** [comment]
Actually, upon just trying https://github.com/nodemcu/nodemcu-flasher it seems that the 64bit build doesn't work on my 64bit Win7... Anyone else seeing this with the latest version updated 3 days ago?

**Comment by nodemcu** [comment]
I pull it down, works ok
I'm using 64bit win7 too.

**Comment by JohnSmith-LT** [comment]
Hmm thats strange... Thanks for trying it though and confirming... I'm using Win7 virtualised on a mac but that shouldn't make any difference... i'll investigate.
