### ISSUE TITLE
GSM modules

### ISSUE THREAD

**Issue by GeorgeGkinis** [nodemcu/nodemcu-firmware#3019]
### Missing feature
It would be incredibly useful to be able to use a **cellular** **2G/3G/4G/NB-iot/LTE-catM** modem like **SIM7000** or **Quectel** equivalent.

The underlying network stack should be used.

On **ESP-IDF** this is achieved utilising **PPPoS** supported by **lwIP**.

Support for the [**CMUX GSM 07.10 protocol**](https://www.etsi.org/deliver/etsi_ts/101300_101399/101369/07.01.00_60/ts_101369v070100p.pdf) should be considered during design, as it could allow to simultaneously use **GPS**, **sending AT** commands/**SMS** e.t.c. without interrupting network traffic.

### Justification
Many **IoT** solutions rely on **cellular modems** for communication.

### Workarounds
No workarounds have been found.
Trying to implement using **UART** wit **AT** commands is cumbersome and libraries like **MQTT**, **HTTP** e.t.c. cannot be reused.

**Comment by lePereT** [comment]
Could we reopen this issue please? PPPoS would be an incredibly useful feature, not just for modems but also for getting internet access over UART connections, using much less power than ethernet magnetics eg https://www.instructables.com/Connect-the-Raspberry-Pi-to-network-using-UART/
