### ISSUE TITLE
tmr:start() does not restart started timer

### ISSUE THREAD

**Issue by 532910** [nodemcu/nodemcu-firmware#3020]
### Expected behavior
https://nodemcu.readthedocs.io/en/master/modules/tmr/#tobjstart
says that `tmr:start()` **restarts** timer. It's not true:

### Actual behavior
`tmr:start()` will **restart** timer (start it count from zero)

### Test code
```Lua
> t = tmr.create()
> t:register( 3000, tmr.ALARM_SEMI, function( t ) print( 'alarm' ) end)
> t:start()
> -- wait 2 seconds
> t:start()
> -- alarm message will be printed 3 seconds after the first t:start() call, not the second one as expected.
```

### Workaround
```Lua
t:stop()
t:start()
```

### NodeMCU startup banner
NodeMCU 3.0.1.0, build type: integer
modules: file,gpio,net,node,rtctime,sntp,tmr,uart,wifi
build 2020-01-27 17:39 powered by Lua 5.1.4 on SDK 3.0.2(824dc80)

### Hardware
ESP8266 wemos D1 (not mini)

**Comment by HHHartmann** [comment]
This seems to be an unclear documentation. 
The second start in your example should return false as the timer is already running.
To achieve what you want you will need to stop the timer, and then start it again.

**Comment by 532910** [comment]
So:
1. documentation should be corrected
2. tmr:restart() should be added

If there are no objections, I'm ready to PR. The question is: should it be two different pull requests or the one common will be fine?

**Comment by 532910** [comment]
@marcelstoer, @TerryE can I make one single PR for the two points above or it should be two separate pull requests?

**Comment by TerryE** [comment]
@532910, I that both you and Gregor make valid points on this one   We should thing about valid use cases where this should apply, for example if the application is resetting a watchdog.  Do we insist on stopping the old timer first?  Whatever, the code should not fail silently.  It should return an error if the usage in incorrect.

Let's agree this first.

**Comment by HHHartmann** [comment]
I could also imagine to change tmr.stop to restart the timer if it is already running. But that might break existing code.

**Comment by 532910** [comment]
you mean tmr.start, right?

**Comment by HHHartmann** [comment]
Yes. Must have been still half asleep

**Comment by fikin** [comment]
> documentation should be corrected
> tmr:restart() should be added
+1

imho clear api, clearer documentation and no visible backward compatibility risk.

**Comment by HHHartmann** [comment]
So should we go for tmr.restart() and better documentation of tmr.start() then?

**Comment by TerryE** [comment]
Or even one line Lua function to do the same stop / start, so I do think that adding an extra function to avoid this is a bit OTT.

Whatever, the code does need changing to return a correct error code.

**Comment by HHHartmann** [comment]
Start already returns a boolean to indicate an error. At least according to the documentation. So testing if  it works as documented and clarification in the documentation should suffice here.

**Comment by 532910** [comment]
I'm for bringing `start` to its documentation: restart timer if it's already started.

**Comment by marcelstoer** [comment]
@HHHartmann Is this still on your list?

**Comment by HHHartmann** [comment]
I'v been thinking of a good solution here to satisfy @532910 s needs and not to break existing code.

If we use an optional parameter for `tmr:start(bool restart)` which would be `false` by default. That will not blow up the interface (too much).
Also the code should return `false` if false/no_param is give and the timer is already running to match the documentation.

One PR should be fine for code and documentation.

**Comment by 532910** [comment]
sounds good
