### ISSUE TITLE
gpio.serout() doesn't seem to work for GPIO16

### ISSUE THREAD

**Issue by stuartpb** [nodemcu/nodemcu-firmware#3043]
### Expected behavior

I'm trying to use `gpio.serout` to flash an LED connected to GPIO16 (it turns on when GPIO16 is low).

### Actual behavior

Using calls to `gpio.write` and `tmr.create():alarm()` can toggle the LED state, but calls to `gpio.serout` seem to have no effect on the pin's state.

The documentation notes:

> D0(GPIO16) can only be used as gpio read/write. No support for open-drain/interrupt/pwm/i2c/ow. 

However, nothing suggests that GPIO16 shouldn't be able to handle a call from serout.

### Test code

```Lua
gpio.serout(0,0,{1000000,1000000,1000000,1000000},1,1)
```
Should blink the LED a couple times across four seconds: in practice, does nothing.

### NodeMCU startup banner

```
NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 71a182caa7841cbb478ed90ede526dc881943c80
	release: 
	release DTS: 202001061321
	SSL: true
	build type: float
	LFS: 0x0
	modules: bit,color_utils,crypto,encoder,file,gpio,http,mdns,net,node,rtctime,sjson,sntp,spi,tmr,uart,websocket,wifi,ws2812,tls
 build 2020-02-06 11:37 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

```

### Hardware

I'm using a Pocket 8266 clone from [here](https://www.amazon.com/gp/product/B075H8X7H2/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8).

**Comment by HHHartmann** [comment]
Should be documented at least
