### ISSUE TITLE
Inconsistent href links in docs

### ISSUE THREAD

**Issue by cerasmus** [nodemcu/nodemcu-firmware#3045]
### Expected behavior
The hrefs links in the docs appear to be inconsistent (or incorrect?). Consider the [Getting Started](https://github.com/nodemcu/nodemcu-firmware/blob/master/docs/getting-started.md#compile-lua-into-lfs-image) page where the links to the example code point to _tree/dev_. I would expect these hrefs to link to the _master_ branch.

### Actual behavior
The result of this is that _tree/master_ docs that are published point to code that is in the _dev_ branch. In the case of the [telnet example](https://github.com/nodemcu/nodemcu-firmware/tree/dev/lua_examples/telnet/telnet.lua) the file doesn't exist.

I can't tell if this intentional or an artifact of the automation tooling. I'm happy to help fix up some links as I find problems. Thanks.

**Comment by marcelstoer** [comment]
It's quite a challenge to produce links that relative/dynamic enough to work both here on GitHub and once the docs are deployed at https://nodemcu.readthedocs.io/en/latest/getting-started/ - and do so across branches. Fixes are certainly welcome.
