### ISSUE TITLE
Add MCP23017 port expander support as a lua module

### ISSUE THREAD

**Issue by plomi-net** [nodemcu/nodemcu-firmware#3057]
### Missing feature
Hello,
I would like to contribute a few things to this great project.

I saw that there are already issues for the MCP23017 Port Expander. Unfortunately I didn't find any Lua or C modules in the current dev branch.

Without looking into the issues, I just created a module in Lua for the MCP23017.
Now I would like to learn more and adapt the module to become part of this project.

### Justification
This module can help other IoT developers to easily provide more GPIO pins, for example to control a relays card. 

### Workarounds
I am not sure which workaround represents a good solution.

Kind regards,
Marcel

**Comment by marcelstoer** [comment]
Contributions are welcome. Consider #3034.

**Comment by jmd13391** [comment]
@plomi-net, Have you see this?

[MCP23008 Module](https://nodemcu.readthedocs.io/en/master/lua-modules/mcp23008/)

I am currently using this Lua Module to extend the ESP8266 GPIO with great success.

**Comment by plomi-net** [comment]
Hi @jmd13391, @marcelstoer 

Thank you very much for your comment.
I had seen the module for the MCP23008 chip and that inspired me to create a module for the MCP23017.

For my project I need 16 channels, theoretically 128 pins would be possible with 8 MCP23017. 
I could also have used two MCP23008.

I will refactor my module in the next few days and then provide it.

**Comment by plomi-net** [comment]
Hi,
now some time has passed.

I have attached the program code with a pull request.
I hope the refactor succeeded and helps someone to extend the nodemcu.
If anyone has any comments or feedback, please let me know.

thanks a lot
