### ISSUE TITLE
Timer get how many time left

### ISSUE THREAD

**Issue by shiwzhi** [nodemcu/nodemcu-firmware#3058]
### Missing feature
tmr.state() be able to return how many time left

### Justification
Be able to get this data without to manual calculate

### Workarounds
Use variable to hold starting time of timer, use it plus timer interval minus current system time.

**Comment by nwf** [comment]
That would be handy, but unfortunately we cannot easily provide it.  The Espressif SDK OS interface, which you can find at https://github.com/espressif/ESP8266_NONOS_SDK/blob/64efd239c152555cd64399b3c268ece76c80d65c/include/osapi.h, does not provide the required accessors into the `os_timer_t` (equivalently `ETSTimer`) structure.
