### ISSUE TITLE
I fixed the ping crash bug

### ISSUE THREAD

**Issue by clearisoft** [nodemcu/nodemcu-firmware#3073]
I test the ping function in dev branch. 
Random crash when ping. See #2854

Cause:
Call unregister_refs() too early.

Solution:
static void ping_received(void *arg, void *data) {
 ...
    (nip->count)--;
    ---if (!nip->count) { // is this a last call?
    ---  unregister_refs(L, nip);
    ---}
    
    lua_call(L, 4, 0);
}

+++static void ping_sent(void *arg, void *data) {
+++    ping_t nip  = (ping_t)arg;
+++    lua_State *L = lua_getstate();
+++    unregister_refs(L, nip);
+++}

....
 nip->ping_opt.recv_function = &ping_received;
+++nip->ping_opt.sent_function = &ping_sent;
....

**Comment by nwf** [comment]
Please keep such things in the PR #2854 rather than opening issues for things that are not yet in the tree.
