### ISSUE TITLE
how to get app all wifi list

### ISSUE THREAD

**Issue by sungerk** [nodemcu/nodemcu-firmware#3074]
wifi.sta.getap
any duplicate SSIDs will be discarded

i want to get all duplicate SSIDs

**Comment by nwf** [comment]
As per the documentation, you must call `wifi.sta.getip(nil, 1, function(t) ... end)` so that the result table is indexed by BSSID not SSID, as it was in format 0.

**Comment by sungerk** [comment]
Thank you
