### ISSUE TITLE
LiquidCrystal Lua module broke CI build (#2974)

### ISSUE THREAD

**Issue by HHHartmann** [nodemcu/nodemcu-firmware#3079]
All build steps pass

### Actual behavior
Build breaks due to Lua cheks and
since Lua 5.3  4 also the windows build breaks

### Test code
See https://travis-ci.org/github/nodemcu/nodemcu-firmware/builds/679883840

**Comment by marcelstoer** [comment]
Weird...I don't see any CI build info in #2974. I'm sure we would otherwise have asked @seregaxvm to address this prior to merging.

**Comment by seregaxvm** [comment]
Looks like there's a CI configuration issue. CI build is not run when submitting a new PR. At least when I do it.

**Comment by marcelstoer** [comment]
> Looks like there's a CI configuration issue.

Definitely, yes. We see all the CI builds at https://travis-ci.org/github/nodemcu/nodemcu-firmware/pull_requests (i.e. they do run) but GitHub doesn't show the results anymore in the respective PR view.

Thanks for the quick fix!

**Comment by marcelstoer** [comment]
@HHHartmann I created a separate issue for the Windows build: #3082
