### ISSUE TITLE
No way to get IP address of client

### ISSUE THREAD

**Issue by marcoskirsch** [nodemcu/nodemcu-firmware#308]
I expected some function on net.socket to get the remote IP address but API documentation doesn't show anything. Am I missing something? Thanks!

**Comment by nodemcu** [comment]
ip,port = conn:getpeer()

**Comment by marcoskirsch** [comment]
Got it, thanks.
I've renamed the issue so that it is a documentation bug.

**Comment by TerryE** [comment]
IIRC, this is a duplicate and I've got the other assigned to me.
