### ISSUE TITLE
error messages within telnet only printed to the serial console

### ISSUE THREAD

**Issue by pnkowl** [nodemcu/nodemcu-firmware#3110]
### Expected behavior
When telnet is active
- console Inputs sent to the Lua interpreter
- Lua interpreter Outputs sent to the telnet console

### Actual behavior
Various error messages are printed to the serial terminal and are not shown in the telnet console (e.g. putty window)

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

Of specific interest is the serial terminal error text "stdin:1: attempt to perform arithmetic on global 'a' (a string value)" that is not seen on the putty window.
 
```Lua
-- add code here
putty                                     ESPlorer
----------------------------------------  --------------------------------------------------------------------
Welcome to NodeMCU world192.168.1.17      stdin:1: unexpected symbol near 'ÿ'
> =node.heap()
22184
>                                        
> a="hello"
> b=a/55
                                          stdin:1: attempt to perform arithmetic on global 'a' (a string value)
                                          stack traceback:
                                          stdin:1: in main chunk
> =a
hello
>
```
### Notes
1. see attachment for 2 telnet versions that behave similarly.  One must run out of LFS, the other simple version does not.  Both have origins on Nodemcu website.
[stderr.zip](https://github.com/nodemcu/nodemcu-firmware/files/4637141/stderr.zip)

2. It may be that it is not possible to print these types of errors in the telnet window.  If that is the case, then the documentation should reflect the actual operation.  But, I also have a web ide module (not written by me either) that returns these types of errors as I would expect.  Both telnet and web ide use node.output()

node.output()
Redirects the Lua interpreter output to a callback function. Optionally also prints it to the serial console.  

### NodeMCU startup banner
You MUST include the firmware startup banner to describe the version you are using. We reserve the right to immediately close any bug that doesn't.

NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 3d917850180f67adc7f2c6b5d00f27c152e7194c
	release: 
	release DTS: 202002231746
	SSL: false
	build type: float
	LFS: 0x40000
	modules: adc,bit,cron,dht,enduser_setup,file,gpio,mqtt,net,node,ow,pwm2,rtcmem,rtctime,sntp,struct,tmr,uart,wifi
 build 2020-05-01 12:54 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
lua: cannot open init.lua

### Hardware
Describe which ESP8266/ESP32 device you use and document any special hardware setup
required to reproduce the problem.

- NodeMCU ver 0.9 (ESP-12, 4M byte ESP8266)
- no external connections besides usb

**Comment by TerryE** [comment]
Duplicate.  Already covered in #3078 :smile: 

It's worth searching the open issues (the help explains how), and also going to the issues list and resorting by most recent comment date.

I good spot, but already caught.  If you don't mind, then I will close this as a duplicate.
