### ISSUE TITLE
gpio.PULLUP and gpio.INT (trigger) at the same time

### ISSUE THREAD

**Issue by eliabieri** [nodemcu/nodemcu-firmware#312]
Is there a way to use the internal pullup (gpio.PULLUP) and gpio.INT at the same time, so I can use the internal pullup resistor and call a function whenever my button is pressed?

**Comment by ulabs-sgiroux** [comment]
I think tyou can -- just spec them as 2 calls. Right?

https://github.com/nodemcu/nodemcu-firmware/blob/1bd3f5669394f37f6dd1433e2a09c4db19c56d21/app/modules/gpio.c#L90-L119

**Comment by devsaurus** [comment]
See #719.
