### ISSUE TITLE
🙉 compile  error , 

### ISSUE THREAD

**Issue by jiaplee** [nodemcu/nodemcu-firmware#3129]
`
git clone https://github.com/nodemcu/nodemcu-firmware

`

 [root@VM_72_141_centos nodemcu-firmware]# make
make: Entering directory `/data/soft/nodemcu-firmware'
Files /tmp/buildinfo.h and app/include/buildinfo.h differ
make[1]: Entering directory `/data/soft/nodemcu-firmware/app'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/user'
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/user'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/crypto'
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/crypto'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/driver'
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/driver'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/mbedtls'
make[3]: Entering directory `/data/soft/nodemcu-firmware/app/mbedtls/app'
make[3]: Leaving directory `/data/soft/nodemcu-firmware/app/mbedtls/app'
make[3]: Entering directory `/data/soft/nodemcu-firmware/app/mbedtls/library'
make[3]: Leaving directory `/data/soft/nodemcu-firmware/app/mbedtls/library'
make[3]: Entering directory `/data/soft/nodemcu-firmware/app/mbedtls/platform'
make[3]: Leaving directory `/data/soft/nodemcu-firmware/app/mbedtls/platform'
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/mbedtls'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/platform'
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/platform'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/libc'
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/libc'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/lua'
DEPEND: CC app/lua/lua.c
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/lua'
make[2]: Entering directory `/data/soft/nodemcu-firmware/app/lua'
make[3]: Entering directory `/data/soft/nodemcu-firmware/app/lua/luac_cross'
HOSTCC /data/soft/nodemcu-firmware/app/lua/luac_cross/luac.c
In file included from ../ltm.h:12,
                 from ../lstate.h:13,
                 from ../ldo.h:12,
                 from luac.c:22:
../lrotable.h:58: 错误：typedef‘ROTable’重定义
../lobject.h:402: 附注：‘ROTable’的上一个声明在此
make[3]: *** [.output/host/release/obj/luac.o] 错误 1
make[3]: Leaving directory `/data/soft/nodemcu-firmware/app/lua/luac_cross'
make[2]: *** [.subdirs] 错误 2
make[2]: Leaving directory `/data/soft/nodemcu-firmware/app/lua'
make[1]: *** [.subdirs] 错误 2
make[1]: Leaving directory `/data/soft/nodemcu-firmware/app'
make: *** [.subdirs] 错误 2
make: Leaving directory `/data/soft/nodemcu-firmware'

**Comment by marcelstoer** [comment]
Not an issue with the firmware as our CI builds still pass -> closing
