### ISSUE TITLE
observe is present in coap stack

### ISSUE THREAD

**Issue by yogasuhas** [nodemcu/nodemcu-firmware#313]
in nodemcu, apis found only for get and post. observe is on best option in in coap. api is not present for it. or if its present can anyone please tell me.

**Comment by nodemcu** [comment]
not implemented.

**Comment by yogasuhas** [comment]
Does anybody working on observe option implementation for nodemcu firmware.

**Comment by yogasuhas** [comment]
when we call
cc = coap.Client()
which function in coap library get execute.
when we call
cc : get(coap.CON,"coap://some_addrs:5683/path")
i found coap_make_request() in coap.c get start, if i want one parameter to specify for the addition of observer option, how can i add.

**Comment by devsaurus** [comment]
See #719.
