### ISSUE TITLE
tmr.time makes sudden jump

### ISSUE THREAD

**Issue by markkuhu** [nodemcu/nodemcu-firmware#314]
tmr.times seems to make sudden jump when it reaches a value around 12000.

![screenhunter_01 mar 27 19 57](https://cloud.githubusercontent.com/assets/11684199/6874055/1fad3256-d4bd-11e4-917f-e611344bcf81.jpg)
![screenhunter_03 mar 27 20 08](https://cloud.githubusercontent.com/assets/11684199/6874056/1fb4f05e-d4bd-11e4-94fa-1429c9e88406.jpg)
![screenhunter_03 mar 27 20 08](https://cloud.githubusercontent.com/assets/11684199/6874059/25e152f6-d4bd-11e4-9d10-b84e108159a8.jpg)
![screenhunter_01 mar 27 19 57](https://cloud.githubusercontent.com/assets/11684199/6874060/2610886e-d4bd-11e4-8f8e-cb92b26bbe9b.jpg)

**Comment by frankexoo** [comment]
This issue has been resolved already: use a later firmware version (20150318)

**Comment by markkuhu** [comment]
Hi,
and thank you for the quick reply.

Two comments though.

I actually had updated the version - or so I thought. The control on
versions using the Nodemcu programmer is not that good. The version, or
better still the build date, could be made visible there.

The way I acquired the new version was to download the zip file and just
extract it to the same folder as the previous one. This was not a good idea.
Maybe something could be done to prevent the issues arising from my method
could be done?

________________________________
Markku Hukari
+ 358 (0)400 215 360
_______________________________ 


-----Original Message-----

**Comment by devsaurus** [comment]
Issue was considered resolved.
