### ISSUE TITLE
Long-term feature request: SparkFun Artemis support

### ISSUE THREAD

**Issue by nwf** [nodemcu/nodemcu-firmware#3146]
This is an ambition, not an immediate project, but I think it would be a good thing for us to consider branching out beyond the Espressif universe.  Hopefully as we merge the 8266 and 32 trees together, we will start to get more of a HAL view of the world that will let us sit on other modules, too.

The https://www.sparkfun.com/products/15484 looks like it could be an especially attractive target, in terms of connectivity, RAM, and processing power.

As per #1010, I am happy for this to nominally be my project, even if it advances at zero rate for the foreseeable future, until such a time as someone wants to claim it from me.  I'd like an open issue just to collect thoughts as they happen.

**Comment by TerryE** [comment]
> 1M Flash / 384k RAM

This would be tight.  It's got a lot of I/O capability, but without a decent RTOS implementation or the equivalent, I suspect that this will sadly remain an ambition.
