### ISSUE TITLE
FTP server for files operations via WiFi

### ISSUE THREAD

**Issue by 4refr0nt** [nodemcu/nodemcu-firmware#316]
Simple ftp server (running with lua interpreter at one time, but separatly) for files operations via WiFi
What do you think about this?

**Comment by sjfaustino** [comment]
You can always adapt this script http://imzyx.com/technology/ftp-server-written-in-lua.html and run it on the esp8266

**Comment by cal101** [comment]
You sure noticed the the source code is alone is bigger than the free heap space of nodemcu? ;-)

**Comment by TerryE** [comment]
Sorry but this falls into the not going to do in the near future.
