### ISSUE TITLE
ESP32: Bump ESP-IDF to 3.3.2 LTS

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#3173]
We should adopt the latest fixes in the ESP-IDF LTS branch: 3.3.2.

I prepared a branch at https://github.com/nodemcu/nodemcu-firmware/commits/chore/bump-esp-idf but it appears we also need to adjust code. The [CI build broke](https://travis-ci.org/github/nodemcu/nodemcu-firmware/builds/700442610) with a compile error:

```
/home/travis/build/nodemcu/nodemcu-firmware/components/modules/net.c:981:22: error: invalid initializer

   ip_addr_t ipaddr = dns_getserver(numdns);
```

**Comment by marcelstoer** [comment]
@landswipe  over at  #2779 you stated that you had successfully bumped ESP-IDF locally. Were you not getting the error I reported above?

**Comment by thornley-david** [comment]
@marcelstoer yes I did, on my side this was fixed by changing: -

ip_addr_t ipaddr = dns_getserver(numdns);

to

const ip_addr_t *ipaddr = dns_getserver(numdns);

and adjusting the usage references to the ipaddr variable as pointer.

**Comment by marcelstoer** [comment]
Oh, right. If you happen to have that ready would you mind creating a PR against our `chore/bump-esp-idf` branch?

**Comment by thornley-david** [comment]
Submitted the fix as requested, sorry it took a while; I had to setup my whole development environment again after a wayward attempt as using WSL1/2.
