### ISSUE TITLE
LCD16x2 display.

### ISSUE THREAD

**Issue by asm7100** [nodemcu/nodemcu-firmware#318]
Hi
Is it posebel to make somting to use a 16 x 2 LCD display, connectet to at MCP23017?

**Comment by kubi57** [comment]
Hi,

yes, that can be done in lua. If you operate the LCD in 4-bit mode, an MCP23008 is also working.

**Comment by asm7100** [comment]
Nice, has anyone don it in Lua code??

**Comment by clixx-io** [comment]
I've done it in python. Shouldn't take much to convert to LUA.

https://github.com/clixx-io/clixx.io/blob/master/source/python/clixxIO_CharLCD.py

**Comment by asm7100** [comment]
Sorry not that strong in python:-)

**Comment by dvv** [comment]
https://github.com/dvv/nodemcu-thingies/blob/master/lcd1602.lua but it's for I2C

**Comment by asm7100** [comment]
Hey dvv, MCP23017 is using i2c, its a 2 x 8 bit port extender, MCP23008 has only one.

**Comment by devsaurus** [comment]
No WIP, thus closing as per #719.
