### ISSUE TITLE
rst cause:1, boot mode:(3,6)

### ISSUE THREAD

**Issue by dmfhyjk** [nodemcu/nodemcu-firmware#3182]
Firmware information:
NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 8d091c476edf6ae2977a5f2a74bf5824d07d6183
	release: 3.0-master_20200610
	release DTS: 202006092026
	SSL: false
	build type: float
	LFS: 0x0 bytes total capacity
	modules: file,gpio,mqtt,net,node,tmr,uart,wifi
 build 2020-06-18 11:14 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

hi, I have some problems.When I burned the firmware automatically generated by the official website of esp-01, it can work normally at first, but it will crash after a while and the error code is rst cause: 1, boot mode: (3, 6).what can i do?

I use ams1117 as the power supply and a 1000μf capacitor in parallel on the power supply side

err code:

	function initWIFI()

		wifi.setmode(wifi.STATION)
		APConfig={}
		APConfig.ssid="DMFHYJK-Wifi-2.4G"
		APConfig.pwd="19970513"
		wifi.sta.config(APConfig)

		
	end --initWIFI

	function connectMQTT()

    	local tdete = tmr.create()
		tdete:alarm(2 * 1000, tmr.ALARM_AUTO, function ()
			if wifi.sta.getip() then
				tdete:unregister()
				print("Config done, IP is ", wifi.sta.getip())
				m:connect('10.0.0.103', 1883, 0)
			end
		end)
	end

	function initMQTT()
		
		m = mqtt.Client('Sensors1', 60, 'HASS', '123456')
		m:on('connect', function(client)
			print('connected!')
			mqttState = 1
		end)
		m:on('offline', function(client)
			print('offline mqtt, wait 10s reconnect.')
			mqttState = 0
			local twait = tmr.create()
			twait:alarm(10 * 1000, tmr.ALARM_SINGLE, function ()
				connectMQTT()
			end)
		end)
		connectMQTT()
	end

	function sendData(t1, t2, t3, t4, t5, t6, t7) --sendData(aqi1,pm25,pm10,pm01,hcho,temp,hum)
		
		if t1 ~= nil then
			m:publish('home/bedroom/aqi1', t1, 0, 0, function(client)
			end)
		end
		if t2 ~= nil then
			m:publish('home/bedroom/pm25', t2, 0, 0, function(client)
			end)
		end
		if t3 ~= nil then
			m:publish('home/bedroom/pm10', t3, 0, 0, function(client)
			end)
		end
		if t4 ~= nil then
			m:publish('home/bedroom/pm01', t4, 0, 0, function(client)
			end)
		end
		if t5 ~= nil then
			m:publish('home/bedroom/hcho', t5, 0, 0, function(client)
			end)
		end
		if t6 ~= nil then
			m:publish('home/bedroom/temp', t6, 0, 0, function(client)
			end)
		end
		if t7 ~= nil then
			m:publish('home/bedroom/hum', t7, 0, 0, function(client)
			end)
		end

	end --connect to MQTT server

	function decode(data)

		local bs = {}
		-- print('decoding...')
		for i = 1, #data do
			bs[i] = string.byte(data, i)
		end

		if (bs[1] ~= 0x42) or (bs[2] ~= 0x4d) then
			return nil
		end
		
		local d = {}

		d['pm1_0-CF1-ST'] = bs[5] * 256 + bs[6]
		d['pm2_5-CF1-ST'] = bs[7] * 256 + bs[8]
		d['pm10-CF1-ST']  = bs[9] * 256 + bs[10]
		d['pm1_0-AT']     = bs[11] * 256 + bs[12]
		d['pm2_5-AT']     = bs[13] * 256 + bs[14]
		d['pm10-AT']      = bs[15] * 256 + bs[16]
		d['0_3um-count']  = bs[17] * 256 + bs[18]
		d['0_5um-count']  = bs[19] * 256 + bs[20]
		d['1_0um-count']  = bs[21] * 256 + bs[22]
		d['2_5um-count']  = bs[23] * 256 + bs[24]
		d['5_0um-count']  = bs[25] * 256 + bs[26]
		d['10_0um-count']  = bs[27] * 256 + bs[28]
		d['formaldehyde']  = bs[29] * 256 + bs[30]
		d['temperature']  = bs[31] * 256 + bs[32]
		d['humidity']     = bs[33] * 256 + bs[34]
		return d
	end --parse

	function aqipm25(t)
		if (t <= 12) then return t * 50 / 12
		elseif (t <= 35) then return 50 + (t - 12) * 50 / 23
		elseif (t <= 55) then return 100 + (t - 35) * 5 / 2
		elseif (t <= 150) then return 150 + (t - 55) * 2
		elseif (t <= 350) then return 50 + t
		else return 400 + (t - 350) * 2 / 3
		end
	end --aqipm25

	function aqipm10(t)
		if (t <= 55) then return t * 50 / 55
		elseif (t <= 355) then return 50 + (t - 55) / 2
		elseif (t <= 425) then return 200 + (t - 355) * 10 / 7
		elseif (t <= 505) then return 300 + (t - 425) * 10 / 8
		else return t - 105
		end
	end --aqipm10

	function aqi(t25,t10)
		if (t25 > t10) then return math.ceil(t10)
		else return math.ceil(t25)
		end
	end --aqi

	function initUART()
		
		uart.alt(0)
		uart.setup(0, 9600, 8, 0, uart.STOPBITS_1, 0)
		uart.on('data', 0, function(data) end, 0)
		tmr.delay(1000)
		uart.write(0, 0x42, 0x4d, 0xe1, 0x00, 0x00, 0x01, 0x70) -- request sensor
		print('\ninit uart done.\n')
	end

	function main()

		initUART()
		local tmain = tmr.create()
		tmain:alarm(20 * 1000, tmr.ALARM_AUTO, function ()
			uart.on('data', 40, function(data)
				if mqttState == 1 then
					mdat = decode(data)
					collectgarbage()
					-- print("Memory Used:"..collectgarbage("count"))
					-- print("Available heap: "..node.heap())
					if (mdat ~= nil) then
						pm01 = mdat['pm1_0-AT']
						pm25 = mdat['pm2_5-AT']
						pm10 = mdat['pm10-AT']
						hcho = mdat['formaldehyde']
						temp = mdat['temperature'] / 10 + 5
						hum = mdat['humidity'] / 10
						aqi25 = aqipm25(pm25)
						aqi10 = aqipm10(pm10)
						aqi1  = aqi(aqi25,aqi10)
						sendData(aqi1,pm25,pm10,pm01,hcho,temp,hum)
						print('send DATA')
					else
						print('UART not get data.')
					end
				end
				uart.on('data', 0, function(data) end, 0)
			end, 0)
			uart.write(0, 0x42, 0x4d, 0xe2, 0x00, 0x00, 0x01, 0x71) -- request sensor
		end)
	end --main

	mqttState = 0
	mdat, pm01, pm25, pm10, hcho, temp, hum, aqi25, aqi10, aqi1 = nil
	initWIFI()
	initMQTT()
	local tmain = tmr.create()
	tmain:alarm(2 * 1000, tmr.ALARM_AUTO, function ()
		if (mqttState == 1) then
			tmain:unregister()
			print('runing main...')
			main()
		end
	end)

**Comment by marcelstoer** [comment]
-> #1010
