### ISSUE TITLE
Compiling the luac.cross on mingw error

### ISSUE THREAD

**Issue by wnoliveira** [nodemcu/nodemcu-firmware#3185]
In the mingw makefile, more specific at the line https://github.com/nodemcu/nodemcu-firmware/blob/master/app/lua/luac_cross/mingw32-Makefile.mak#L39 , the compiler expects for the file "lrotable.c". But this file isn't needed by the gnu make version of the makefile.

I was not able to compile at Windows ultil I remove the "lrotable.c" from this list. After that, the luac.cross compilation works fine.

**Comment by TerryE** [comment]
@wnoliveira, thanks for this.  Note: self: need to update keep the MinGW and MSC makefiles in sync with the Linux on.

**Comment by TerryE** [comment]
TBH, my 10 year old laptop that used to dual boot into Win7 has died so I am not sure how I can support this. 😒
