### ISSUE TITLE
tmr  attempt to call field 'alarm' (a nil value)

### ISSUE THREAD

**Issue by zhaochengwei** [nodemcu/nodemcu-firmware#3187]
### Expected behavior
make this lua run correctly
```
tmr.alarm(0,1000, 1, function()
     print("hello world")
  end)
tmr.start(0)
```
### Actual behavior
![image](https://user-images.githubusercontent.com/13081827/85952841-9987b300-b99e-11ea-98a3-d52fcb15fbed.png)

### Test code
```
tmr.alarm(0,1000, 1, function()
     print("hello world")
  end)
tmr.start(0)
```
this is my firmware
http://doudingcross.oss-cn-shanghai.aliyuncs.com/temp/nodemcu-master-10-modules-2020-06-26-04-40-16-float.bin

### NodeMCU startup banner

NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 8d091c476edf6ae2977a5f2a74bf5824d07d6183
	release: 3.0-master_20200610
	release DTS: 202006092026
	SSL: false
	build type: float
	LFS: 0x0 bytes total capacity
	modules: dht,file,gpio,mqtt,net,node,sjson,tmr,uart,wifi
 build 2020-06-26 04:39 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

### Hardware
ESP8266MOD

![image](https://user-images.githubusercontent.com/13081827/85952882-e5d2f300-b99e-11ea-9af1-b8765676f4cc.png)

**Comment by KT819GM** [comment]
Hello, please read [tmr](https://nodemcu.readthedocs.io/en/dev/modules/tmr/), it had changed, thats why your example is not working. Your example would look something like this:
```lua
tmr.create():alarm(1000, tmr.ALARM_AUTO, function()
print("hello world")
end)
