### ISSUE TITLE
ws2812.writergb scrambles buffer

### ISSUE THREAD

**Issue by makefu** [nodemcu/nodemcu-firmware#321]
Hi, i ran into the problem that the writergb function of the ws2812 module scrambles the buffer it uses by swapping first and second char for each rgb triple. I am using the buffer to hold the state of the LEDs. 

A simple re-assignment of the buffer to another variable does not seem to be enough to preserve the buffer.

Test:
```lua
> buf=string.char(1,2,3,4,5,6,7,8,9)
> buf2=buf
> =buf:byte(1,9)
1	2	3	4	5	6	7	8	9
> ws2812.writergb(7,buf)
> =buf:byte(1,9)
2	1	3	5	4	6	8	7	9
> =buf2:byte(1,9)
2	1	3	5	4	6	8	7	9
```

**Comment by drv53b6** [comment]
yes, she do it. it not bug

**Comment by makefu** [comment]
@drv53b6 i would also be fine with your suggestion, just keep grb , do not scramble the buffer. 
It just needs to be documented that it is not RGB or even provide ws2812.writergb() and ws2812.write() .

**Comment by drv53b6** [comment]
@makefu make forck and request, rorrect both, and code and documentation

**Comment by makefu** [comment]
@drv53b6 here at the stuttgart hackerspace in germany we call this `anhubeln` - trying to make someone else do what you think would be cool to have :D

When i find the time i will try to just revert to the original c code and have the additional c code for rgb still in there. of course it would be better if someone more experienced in writing code would do this haha

**Comment by drv53b6** [comment]
@makefu i can but dont want

**Comment by makefu** [comment]
@drv53b6 your anhubelei was super effective. 
please have a look at my pull request :)
