### ISSUE TITLE
MEM CHECK FAIL!!!

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#322]
I'm getting MEM CHECK FAIL!!! with 0.9.6-dev_20150331 on nodemcu devboard v0.9

**Comment by klukonin** [comment]
Such problems can be a result of physical silicon fail.
Can you make a check on another module?

**Comment by pastukhov** [comment]
Yes, look like something wrong with board.

**Comment by Mic-Key** [comment]
Hi,
may by related to
http://bbs.espressif.com/viewtopic.php?f=7&t=205&hilit=mem+check+fail&start=10#p881
?

**Comment by pastukhov** [comment]
Thanks, Mic-Key!

**Comment by crivano** [comment]
Hi, for me, the solution was to change de connection speed to 9600, after flashing. It is very strange, but connecting at 115200 wasn't working and was showing MEM TEST FAIL!!!. Switching CoolTerm to 9600 just fixes that. As far as I can tell, it makes no sense, but I tested many times and you should too! :)

**Comment by marcelstoer** [comment]
9600 for `master` branch, 115200 for `dev` branch.

**Comment by Sardashti** [comment]
See this video : https://www.youtube.com/watch?v=tMuC0FpZ-Zo
