### ISSUE TITLE
BUG in node.restart()

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#3241]
NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: master
	commit: 8d091c476edf6ae2977a5f2a74bf5824d07d6183
	release: 3.0-master_20200610
	release DTS: 202006092026
	SSL: false
	build type: integer
	LFS: 0x20000 bytes total capacity
	modules: file,gpio,mqtt,net,node,rtctime,sntp,tmr,uart,wifi
 build 2020-08-09 02:10 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

code:-
node.restart()
print("this should not heppen....!")
for i=1,10, 1 do
  print(i)
end 

output:-

this should not heppen....!
1
2
3
4
5
6
7
8
9
10
> 
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 28256, room 16 
tail 0
chksum 0x05
load 0x3ffe8000, len 2560, room 8 
tail 8
chksum 0x40
load 0x3ffe8a00, len 8, room 0 
tail 8
chksum 0x77
csum 0x77

node.restart() should restart the device immediately.....

**Comment by TerryE** [comment]
Yes it should. Read my FAQ.  The restart occurs after the current task finishes.
