### ISSUE TITLE
Issue in Updating Latest AT firmware For esp8266 (Nodemcu)

### ISSUE THREAD

**Issue by gkunalupta** [nodemcu/nodemcu-firmware#3243]
I want the Latest AT firmware, using the Nodemcu dev kit.
I download the [Non-Os SDK AT version 1.7.4 ](https://www.espressif.com/en/support/download/at)and using ESP flash Tool.
My file locations and files are as shown in the figure, But at commands does not run after downloading all the files in the desired locations. As shown in the image.

![Screenshot (240)](https://user-images.githubusercontent.com/48127814/89885276-703a8380-dbe8-11ea-81ae-1f590bb51eaa.png)

Is their an issue with my file locations and files which I selected?
It shows no error while downloading but AT commands do not run.
I have checked Flash Size , SPI speed and all such things they all are correct but I think There might be an issue with the location and files of the file which I select, as

**Comment by KT819GM** [comment]
This git is about nodemcu-firmware not about AT firmware from espressif nor about hardware modules named nodemcu, so not in scope of this project. Sorry
