### ISSUE TITLE
How about the mcp23017 

### ISSUE THREAD

**Issue by asm7100** [nodemcu/nodemcu-firmware#325]
How about the mcp23017(2x8 and irq) instate of the small mcp23008 (1x8)

**Comment by AllAboutEE** [comment]
The mcp23008 also has an IRQ. But sure I can get the mcp23017 done some time next week.

**Comment by asm7100** [comment]
Total top dollers, like your firmware :-)

2015-04-03 6:04 GMT+02:00 Miguel Alvarez <notifications@github.com>:

**Comment by asm7100** [comment]
How long is you with the code for MCP23017?

**Comment by AllAboutEE** [comment]
I haven't even started.

**Comment by AllAboutEE** [comment]
But I can give you my paypal name, and with the right "incentive" I can for sure speed things up.
