### ISSUE TITLE
Broken Makefile when trying to build with all modules

### ISSUE THREAD

**Issue by Edduaardo** [nodemcu/nodemcu-firmware#3252]
Cloning the repository with all submodules with ```git clone --recurse-submodules -b dev https://github.com/nodemcu/nodemcu-firmware.git``` results in the following error on buid:
```
extracting: ESP8266_NONOS_SDK-e4434aa730e78c63040ace360493aef420ec267c/third_party/include/user_config.h
PRUNE libmain.a libc.a
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [Makefile:336: /mnt/c/Users/eduardo/nodemcu-firmware/sdk/.pruned-3.0-e4434aa] Error 2
```

The git clone was made inside a WSL, I don't think is a line end problem on the file. ```git status``` returns nothing. Also no files were modified, I tried to build after the clone was done.

**Comment by KT819GM** [comment]
Hi,
it's not a makefile problem. It's possibly the same thing as mentioned in #2918. WSL2 add's lot of windows stuff into ```~/.bashrc``` or  ```~/.zshrc``` so you should try to use clean version of them or use solution proposed in: https://github.com/Microsoft/WSL/issues/1493 like ```PATH=$(/usr/bin/printenv PATH | /usr/bin/perl -ne 'print join(":", grep { !/\/(c|d)\// } split(/:/));')```
