### ISSUE TITLE
Add HTU21 support to Si7021 module

### ISSUE THREAD

**Issue by thomil** [nodemcu/nodemcu-firmware#3259]
### Missing feature
The current Si7021 driver does not support the very similar HTU21.

I took a shot at doing the necessary changes that I have linked bellow. I'm raising this issue to gauge if there is interest in getting this merged so I can judge if it's worth putting more effort into this change.

### Justification
HTU21 and Si7021 sensors are very similar and adding HTU21 support to the current Si7021 requires little change. There are sensor boards in the wild that look virtually identical with the only difference being the sensor chip used on the board. I personally have received boards with the Si7021 and on the next order I was shipped HTU21 boards, without knowing what exactly I would receive before ordering. Interestingly, both boards are labeled as both "Si7021" AND "HTU21".

Implementing this feature will increase end-user satisfaction who will no longer be surprised when their board advertised as a Si7021 sensor doesn't work because it actually uses a HTU21.

### Implementation proposal

While still a work in progress, I have identified some differences between both chips and slightly adapted the Si7021 code in my branch here: https://github.com/thomil/nodemcu-firmware/commit/f8db38f8597f64d1e35345e9a909b0a2d0cd3f72

The differences I have identified so far are:

1) Differing reset/default values in the user register. Bits 3-5 in the user register on both chips are designated as "reserved", although the power-on value for those bits in the Si7021 are 111, whereas the HTU21 initializes them as 000. Please see the HTU21 datasheet at page 13 and the Si7021 datasheet at page 26 for reference. The current Si7021 code used the power-on values of the user register to check if there is a sensor connected to the I2C bus. I adapted the code to ignore the reserved bits in this check.

2) CMD_READ_PREV_TEMP is not supported on HTU21. On the Si7021 the command to measure the humidity also measures the temperature, and makes its value accessible through the CMD_READ_PREV_TEMP command. This command is not available on the HTU21, and accessing temperature readings must be done by explicitly sending a temperature measurement command. Doing the temperature measurement again has the slight disadvantage of taking up to 50ms to sample the temperature(See page 5 in HTU21 datasheet).

### Outstanding tasks

- I have not yet checked si7021_lua_setting() for compatibility with the HTU21 sensors, since I did not need it for my application. If there is interest in mainlining HTU21 support I'm willing to take a look at it.

Thanks for any input or feedback you might have.

---
Datasheets:
HTU21: https://cdn-shop.adafruit.com/datasheets/1899_HTU21D.pdf
Si7021: https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf

**Comment by marcelstoer** [comment]
In any case it would be helpful to also get feedback from the original author @fetchbot.
