### ISSUE TITLE
tmr.create():alarm() Broken on New (dev d72ea91)

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#3261]
**Device :** ESP8266
```
NodeMCU 3.0.0.0 built on nodemcu-build.com provided by frightanic.com
	branch: dev
	commit: d72ea91ed01518ef0779d7aa998c5c3a9c269d71
	release: 
	release DTS: 202008291943
	SSL: false
	build type: integer
	LFS: 0x40000 bytes total capacity
	modules: file,gpio,mqtt,net,node,rtctime,sntp,tmr,uart,wifi
 build 2020-08-30 03:24 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
```

**Code:-**
```lua
if not tmr.create():alarm(5000, tmr.ALARM_SINGLE, function()
  print("hey there")
end)
then
  print("whoopsie")
end
```

**Error:-**
Lua error: 	stdin:1: bad argument #1 to 'alarm' (boolean expected)
stack traceback:
	[C]: in function 'alarm'
	stdin:1: in main chunk
	[C]: ?
	[C]: ?

**Comment by galjonsfigur** [comment]
Can confirm - commit d72ea91ed01518ef0779d7aa998c5c3a9c269d71 is causing this issue and it has to do with how `alarm` function is done in C code. It looks like becuse of `tmr:start` now accepts arguments, function `tmr_alarm` would have to manipulate the stack somehow before calling `tmr_start` - I could be wrong as I'm not an Lua C API expert.   @vsky279 could you look at this issue?

**Comment by marcelstoer** [comment]
We definitely need to fix this before the next master drop 😞

**Comment by vsky279** [comment]
I'll have a look. Sorry about that.

**Comment by mk-pmb** [comment]
Let's discuss strategies for automated hardware testing on Gitter.

**Comment by vsky279** [comment]
I think the fix is ready to be merged.
