### ISSUE TITLE
The SNTP PLL is bit aggressive

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#3276]
### Expected behavior

The PLL that controls the clock should settle down and track the crystal in a fairly stable fashion.

### Actual behavior

It is a bit sensitive to estimates of the current time. This is especially a problem when the path from the nodemcu system to the actual clock is long and not very stable.

**Comment by nwf** [comment]
I spent a while tweaking the PI controller in `sntppkt`; I wonder if that behaves better in your environment?

**Comment by pjsg** [comment]
With the old PLL, this is the typically performance that I get. 

![image](https://user-images.githubusercontent.com/1508813/163732964-6af4d6fa-9948-456b-aef4-3acdaddf10cd.png)

Over the last 7 days:

![image](https://user-images.githubusercontent.com/1508813/163733004-4f252123-9ff4-4dd5-8bac-acb1e4473647.png)

I don't know what the big negative excursions are. The NTP server didn't change, but the delay time dramatically bigger than normal (around 18ms bigger). This suggests that some more filtering would be productive.
