### ISSUE TITLE
My Nodemcu automatically disconects from wifi after 30 seconds and reconnects again and this happen after every 20-30 seconds .Can someone tell me how to fix this issue??

### ISSUE THREAD

**Issue by yashsaxena024** [nodemcu/nodemcu-firmware#3294]
It shows the following error after every 20-30 seconds. In some cases it gets connect back to wifi but in some i need to press reset button/

How to fix this issue?

UT HERE FOR EXCEPTION DECODER ---------------

Exception (9):
epc1=0x40214c6c epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000037 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffd00 end: 3fffffc0 offset: 0190
3ffffe90:  3fffdad0 3fffff70 00000020 40100a0f  
3ffffea0:  00000001 3ffffee8 3fff08e4 4020d2d8  
3ffffeb0:  3fffff4c 3fffff70 3fff08e4 4020e1f8  
3ffffec0:  3ffe8f99 3fffff70 3fffff28 4020c98e  
3ffffed0:  3fffdad0 3fffff70 3fffff28 4020b625  
3ffffee0:  00000002 3fffff00 3fffff28 4020b674  
3ffffef0:  3fffdad0 3fffff70 3ffe8f99 4020c0fb  
3fffff00:  00220000 3fff070c 80fe8304 3fff0d1c  
3fffff10:  3fff041c 00000002 3fffff00 3ffef200  
3fffff20:  4020e978 80fef158 402151d8 3fff08dc  
3fffff30:  3fff070c 00000000 3ffef12c 3fff09c8  
3fffff40:  00000000 00000000 3ffef12c 3fff0400  
3fffff50:  3fffdad0 80ffff7c 3ffe873d 4020f582  
3fffff60:  00f42400 00000000 3ffef108 402012a3  
3fffff70:  00000030 00000000 81efeffe 00337753  
3fffff80:  00000000 83000000 00000001 40100198  
3fffff90:  3fffdad0 00000000 3ffef248 4020130c  
3fffffa0:  3fffdad0 00000000 3ffef248 40210820  
3fffffb0:  feefeffe feefeffe 3ffe8580 40100cc9  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------
⸮⸮9/⸮*WM: [1] AutoConnect 
*WM: [2] Connecting as wifi client... 
*WM: [3] STA static IP:
*WM: [2] setSTAConfig static ip not set, skipping 
*WM: [1] Connecting to SAVED AP: YS
*WM: [3] Using Password: yash2002
*WM: [3] WiFi station enable 
*WM: [3] enableSTA PERSISTENT ON 
*WM: [1] connectTimeout not set, ESP waitForConnectResult... 
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] AutoConnect: SUCCESS 
*WM: [1] STA IP Address: 192.168.43.237
Connected.... ..

connected:192.168.43.237
*WM: [3] unloading

**Comment by nwf** [comment]
This does not, unless I am mistaken, appear to be output from our firmware.  Unfortunately the name "nodemcu" has come to refer to a lot of esp8266 boards that are not running this, Lua-based firmware.  I believe, as a consequence, you are lost.  Please, in the future, carefully follow the instructions in a project's issue template (not just ours!); notably, you have not included your module's startup banner as requested.  It should look like

```
NodeMCU 3.0.0.0 built with Docker provided by frightanic.com
	branch: dev
	commit: 2fa63a1303493aa66831af5466311436d11cf827
	release: 3.0-master_20200610 +11
	release DTS: 202007071335
	SSL: false
	build type: float
	LFS: 0x0 bytes total capacity
	modules: adc,bit,dht,file,gpio,i2c,mqtt,net,node,ow,spi,tmr,uart,wifi
 build 2020-08-01 15:42 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
```

If your module does not produce output resembling the above, you are indeed lost.
