### ISSUE TITLE
remote upgrade firmware...

### ISSUE THREAD

**Issue by gorec2005** [nodemcu/nodemcu-firmware#33]
will be nice posibility "remote upgrade firmware via wifi or from cloud..."
of course - from nodemcu.previous to nodemcu.next... :-)

**Comment by NeiroNx** [comment]
it possible to write firmware from nodemcu or copy it from file in spiffs? 
Executed program located in memory?

**Comment by clixx-io** [comment]
Yes it is.

I'm actually working on a set of tools called esptools which I will try to
finish off this weekend.

https://github.com/clixx-io/esptools

   - espls - list files
   - espcp - copy files to and from
   - esprm - delete files
   - espcat - show file contents
   - espmv - move files

There's a few problems with remote upgrade however, as far as I know the
nodemcu firmware only allows one server at a time to run on one tcp/ip port.

So it would have to be worked into an application as far as I can see.

**Comment by TerryE** [comment]
Superseded by #806 and #816.
