### ISSUE TITLE
dummyproof bootloader

### ISSUE THREAD

**Issue by timoline** [nodemcu/nodemcu-firmware#331]
Can you please provide a dummyproof bootloader?
something like the espbootloader tries to do...

https://github.com/sebastianhodapp/ESPbootloader

The script checks whether there is already a wifi configured. If not, the configuration mode is started. The ESP8266 provides an access point and webpage listing all available access points plus possibility to enter the wifi password. These settings are stored persistently in the file config.cl and the module connects with to the network to run your normal code.

**Comment by marcelstoer** [comment]
How should what you requested be different from the ESPbootloader?

**Comment by timoline** [comment]
Not much, more stable and  provided, maintained and supported by nodemcu (commu)

**Comment by marcelstoer** [comment]
See https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_en#enduser_setup-module.
