### ISSUE TITLE
Comment on cloning the repository

### ISSUE THREAD

**Issue by quackmore** [nodemcu/nodemcu-firmware#3339]
nodemcu/nodemcu-firmware repository now includes submodules (which is fine)

so pulling down a full copy of all the repository data now requires

git clone --recurse-submodules 

ya, I know, it's trivial but pointing it out hopefully will save some time to someone else 

PS:
love yor job!

**Comment by marcelstoer** [comment]
https://nodemcu.readthedocs.io/en/latest/build/#git
