### ISSUE TITLE
Combine `lua` scripts to `LFS` at the time of building the firmware 

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#3341]
### Missing feature
it is really nice to have a way to Combine `lua` scripts to `LFS` at the time of building the firmware,
so we can flash the ship with all the files in one signal .bin file.

**Comment by chathurangawijetunge** [comment]
any updates

**Comment by TerryE** [comment]
@chathurangawijetunge, compile to LFS and use `esptool`.  That's what I do. You can also do any form of build process including FTP ... into SPIFFS them use the readflash option etc. to roll your own, but unless someone steps up to do the work, you won't get anyone to work on this. Sorry.
