### ISSUE TITLE
LUA module BME280 not work.

### ISSUE THREAD

**Issue by Plazmin** [nodemcu/nodemcu-firmware#3342]
C module included in firmware work OK.

![bme280](https://user-images.githubusercontent.com/62091912/101261122-25172400-3735-11eb-94d2-dd97ec855481.png)

![bme280_1](https://user-images.githubusercontent.com/62091912/101261208-c605df00-3735-11eb-9d03-ee22ef98f5ad.png)

Where is problem?

**Comment by Plazmin** [comment]
Why did you close my request?

**Comment by HHHartmann** [comment]
You choose to ignore the issue template and I cannot see what the issue/question exactly is.

There is a Lua module which has to be used for BME280. the math module you included is only half of the story.

If this is more like a support request please see #1010 .
