### ISSUE TITLE
tmr: softwd can't be disabled in accordance to manual

### ISSUE THREAD

**Issue by wilhelmy** [nodemcu/nodemcu-firmware#3349]
The manual mentions `tmr.softwd(-1)` (or any other negative number) as a means to disarm the watchdog, however the C function claims this is an invalid time.

https://github.com/nodemcu/nodemcu-firmware/blob/4f6792773f93f36a7255cfd28dca7aa6c4aa9552/app/modules/tmr.c#L277

**Comment by HHHartmann** [comment]
Has been fixed with #3326 and is available on dev builds for now.
