### ISSUE TITLE
ESP32-S2 Support

### ISSUE THREAD

**Issue by thesulaj** [nodemcu/nodemcu-firmware#3373]
Is NodeMCU, particularly the dev-esp32 branch, expected to work with the ESP32-S2 module?

When I try flashing a ESP32-S2-Saola-1 dev board from the dev-esp32 branch, this is the output I get:

```
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4000f79a
Invalid chip id. Expected 2 read 0. Bootloader for wrong chip?
ets_main.c 386
```

And when I run `esptool.py chip_id` I get the following:
```
Warning: ESP32-S2 has no Chip ID. Reading MAC instead.
```

Is this due to an error on my part, or is the EPS32-S2 not supported by NodeMCU? Thanks!

**Comment by whynil48** [comment]
> Is NodeMCU, particularly the dev-esp32 branch, expected to work with the ESP32-S2 module?
> 
> When I try flashing a ESP32-S2-Saola-1 dev board from the dev-esp32 branch, this is the output I get:
> 
> ```
> ESP-ROM:esp32s2-rc4-20191025
> Build:Oct 25 2019
> rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
> Saved PC:0x4000f79a
> Invalid chip id. Expected 2 read 0. Bootloader for wrong chip?
> ets_main.c 386
> ```
> 
> And when I run `esptool.py chip_id` I get the following:
> 
> ```
> Warning: ESP32-S2 has no Chip ID. Reading MAC instead.
> ```
> 
> Is this due to an error on my part, or is the EPS32-S2 not supported by NodeMCU? Thanks!

 

Hey buddy, Saw you closed the issue without having any solution here. If you have solved it, Please mention it here.
Thanks in advance.
