### ISSUE TITLE
Memory leak on UART receive when len==0

### ISSUE THREAD

**Issue by LianYangCn** [nodemcu/nodemcu-firmware#3376]
hi,

here,

https://github.com/nodemcu/nodemcu-firmware/blob/d5f0094576a93672a7f46f32d4e8981247fac0ea/components/platform/platform.c#L105-L120

Is here possible that `len == 0` at line 118, if so, `post` (which malloc at line 107) will never be freed

**Comment by HHHartmann** [comment]
It will still be freed in king 168
