### ISSUE TITLE
Redux state container for ESP8226, ESP32 

### ISSUE THREAD

**Issue by shubham-sri** [nodemcu/nodemcu-firmware#3420]
### Missing Feature: NodeRedux - state container
Redux is a predictable state container for JavaScript apps. So we can use the same concept to manage the state of ESP devices. It helps you write applications that behave consistently.

### Justification
The whole global state of your app is stored in an object tree inside a single _store_. The only way to change the state tree is to create an _action_, an object describing what happened, and _dispatch_ it to the store. To specify how the state gets updated in response to an action, you write pure _reducer_ unctions that calculate a new state based on the old state and the action.

### Workarounds
I have translated the logic of Redux in JS to Lua. You can check [here](https://github.com/shubham-sri/node-redux)

**Comment by nwf** [comment]
Closing; further discussion can take place on the PR.
