### ISSUE TITLE
attempt to call field 'newBuffer' (a nil value)

### ISSUE THREAD

**Issue by lw1995** [nodemcu/nodemcu-firmware#3423]
```lua
ws2812.init()
local i, buffer = 0, ws2812.newBuffer(300, 4); buffer:fill(0, 0, 0, 0); tmr.create():alarm(50, 1, function()
  i = i + 1
  buffer:fade(2)
  buffer:set(i % buffer:size() + 1, 0, 0, 0, 255)
  ws2812.write(buffer)
end)
```
I copied the example code on the document directly.
But something went wrong.
Error report：`attempt to call field 'newBuffer' (a nil value)`

**Comment by nwf** [comment]
That's curious and certainly seems like something is amiss.  However, it's very hard to guess what as you appear to have ignored our issue template and, in particular, not said which version of NodeMCU is in use nor what modules your firmware has been compiled against.

**Comment by lw1995** [comment]
Thank you. I've solved this problem






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nodemcu/nodemcu-firmware"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nodemcu/nodemcu-firmware] attempt to call field 'newBuffer' (a nil value) (#3423)





 
That's curious and certainly seems like something is amiss.  However, it's very hard to guess what as you appear to have ignored our issue template and, in particular, not said which version of NodeMCU is in use nor what modules your firmware has been compiled against.

**Comment by HHHartmann** [comment]
The solution is to use the new pixbuf module.

**Comment by nwf** [comment]
If selecting `ws2812` and not `pixbuf` generates a firmware image for which `newBuffer` is `nil`, that's definitely a problem.

**Comment by HHHartmann** [comment]
Not really a problem. The buffer was just moved out of ws2812. pixbuf has a newBuffer method which can be used now.
The ws2812 write can still be used without pixbuf available. Just use the string interface.

I just think we could have done better on change management.

**Comment by nwf** [comment]
Ah, no, I see.  Absent `pixbuf`, `newBuffer` isn't in the rotable, and so is of course `nil`.  I had missed that and thought we were somehow resolving `pixbuf_new_lua` as `NULL` at link time, sorry.

I guess the right thing to have done would have been to have a stub `newBuffer` method that threw an error or something.  Hm,

**Comment by lw1995** [comment]
I found that the reason for this error was the missing Pixel Buffer (PixBuf) module. I have solved the problem the day before yesterday.



---Original---
From: "Nathaniel Wesley ***@***.***&gt;
Date: Thu, Apr 15, 2021 21:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nodemcu/nodemcu-firmware] attempt to call field 'newBuffer' (a nil value) (#3423)




 
Ah, no, I see.  Absent pixbuf, newBuffer isn't in the rotable, and so is of course nil.  I had missed that and thought we were somehow resolving pixbuf_new_lua as NULL at link time, sorry.
 
I guess the right thing to have done would have been to have a stub newBuffer method that threw an error or something.  Hm,

**Comment by lw1995** [comment]
Thank you. I've solved the problem.



---Original---
From: "Gregor ***@***.***&gt;
Date: Thu, Apr 15, 2021 18:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nodemcu/nodemcu-firmware] attempt to call field 'newBuffer' (a nil value) (#3423)




 
Not really a problem. The buffer was just moved out of ws2812. pixbuf has a newBuffer method which can be used now.
 The ws2812 write can still be used without pixbuf available. Just use the string interface.
 
I just think we could have done better on change management.

**Comment by HHHartmann** [comment]
We had a grace period where ws2812.newBuffer was still available but called the pixbuf implementation.
Don't remember if we printed the depreciation message.

**Comment by HHHartmann** [comment]
In general we should think about a way to mitigate api changes. Have the old documentation somewhere and/or include migration pathes. And not only for 1 release but forever. There is so much code out there which is for older versions and migrating it is sometimes quite hard.
