### ISSUE TITLE
Migrate RTD/MkDocs build to Python 3

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#3454]
I wanted to enable the RTD docs build for @jmattsson's  `dev-esp32-idf4` branch so we can announce that branch in the docs early. The build failed with "Could not find a version that satisfies the requirement ziglang>=0.8.0". Checking [the RTD logs](https://readthedocs.org/api/v2/build/14397085.txt) made me realize we're still using Python 2 to build the docs.

Upgrading to Python 3 (in the RTD settings) worked but [the build failed again](https://readthedocs.org/api/v2/build/14397146.txt) but for a different reason. Maybe it's because the [MkDocs version](https://www.mkdocs.org/about/release-notes/#version-0173-2018-03-07) we (or RTD?) use is ancient as well.

**Comment by jmattsson** [comment]
Maybe have a look at https://github.com/readthedocs/readthedocs.org/issues/5474? It looks like the same issue we're hitting, and there seems to be solution(s) there :)

**Comment by marcelstoer** [comment]
WIP https://nodemcu.readthedocs.io/en/update-rtd-mkdocs/

A couple of [changes](https://github.com/nodemcu/nodemcu-firmware/commit/9f633ef78321fb1ed110eb820203e51a057f860e) were required.

**Comment by marcelstoer** [comment]
- [x]  Implemented in the `dev-esp32-idf4` branch, which will land on `dev-esp32` eventually, with #3457.
- [x]  Implemented in the `dev` branch, which will land on `release` eventually, with #3458.

=> done
