### ISSUE TITLE
tls no longing working with google scripts

### ISSUE THREAD

**Issue by mnpaslay** [nodemcu/nodemcu-firmware#3459]
I have many ESP01 wifi chips around my house reporting things such as solar hot water pump, gate open/closed, water softener salt level.  They report to a google sheet using google scripts get.  I had to add the TLS module to get them to work initially, but it seems like maybe the security requirements have changed via google and they all stopped working 6/2021.  When I first set up I did get a response from my code on google.  Perhaps a year ago I stopped getting a response and got error 114, but the data still got through, and now nothing gets though.  The data does post if I use any browser.  I'm about to give up and move to setting up a raspberry PI to rely the data.  Firmware built using the cloud with checkbox for TLS/SSL, file, GPIO, HTTP, net, node, timer, UART, and WiFi. 

The function is below:

```
function sendToSheets()
    http.get('https://script.google.com/macros/s/<googlescriptid>/exec?name=<data>, nil , function(code, data) print(code, data) end)
end
```

**Comment by marcelstoer** [comment]
User support, cross-posted here https://stackoverflow.com/q/68837865/131929
