### ISSUE TITLE
ESP32 How to stop wifi Info logging to console

### ISSUE THREAD

**Issue by PPelaaja** [nodemcu/nodemcu-firmware#3466]
### Expected behavior
No wifi info log to console
### Actual behavior
I (203544) wifi:new:<6,2>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:1
I (304614) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,0>, prof:1
I (305634) wifi:new:<6,2>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:1
I (362574) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,0>, prof:1
I (363594) wifi:new:<6,2>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:1
I (383564) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,0>, prof:1
I (384584) wifi:new:<6,2>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:1
I (388584) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,0>, prof:1
I (389604) wifi:new:<6,2>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:1
I (413564) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,0>, prof:1
I (414594) wifi:new:<6,2>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:1
I (442644) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,0>, prof:1
### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

- Wifi info exist with (dev-esp32) Cloud Build Service and with git code
- I tryed put next code to wifi.init(wifi.c) and different places to SDK code with no success
        #include "esp_log.h"
        esp_log_level_set("wifi", ESP_LOG_WARN);
- My only success way is set Component config-> Default log verbosity to No output,
  but that stop all messages (including errors)

### NodeMCU startup banner
NodeMCU ESP32 built on nodemcu-build.com provided by frightanic.com
	branch: dev-esp32
	commit: eb56f6237ba00c69b4f4e270b8ef4e3fe1d45982
	SSL: false
	modules: adc,bit,can,dac,file,gpio,http,i2c,net,node,ow,spi,tmr,uart,wifi,ws2812
 build 2021-09-23-05-25-53 powered by Lua 5.1.4 on ESP-IDF v3.3-beta1-1738-gb64b37523 on SDK IDF

### Hardware
ESP32-WROOM-32D

**Comment by PPelaaja** [comment]
Aaah. 
node.osprint(false) makes my day.

**Comment by marcelstoer** [comment]
Thanks
