### ISSUE TITLE
Question: Is there a command to get which SSID is currently used?

### ISSUE THREAD

**Issue by luc-github** [nodemcu/nodemcu-firmware#347]
As title : Is there a command to know to which SSID is station currently connected ?
or which SSID is used by wifi.sta.connect() ?

because wifi.sta.status() give status connection, but no information to which SSID/AP, which could be useful when you check the status

**Comment by timoline** [comment]
+1

**Comment by luc-github** [comment]
Ok thanks - so I close this

**Comment by timoline** [comment]
Why is it closed, do you mean it will be implemented?

**Comment by luc-github** [comment]
I do not know - I got answer to my question = not available, so I close issue

**Comment by timoline** [comment]
I want this feature :-)
