### ISSUE TITLE
maybe an issue in app/modules/auxmods.h

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#353]
I was adding a new module and when adjusting the abovementioned header I noticed at the bottom is a cjson entry

``` c
#define AUXLIB_CJSON      "cjson"
LUALIB_API int ( luaopen_ow )( lua_State *L );
```

Should it say `luaopen_cjson`?

HTH

**Comment by nodemcu** [comment]
thank you
