### ISSUE TITLE
Static IP in STATION mode with running DHCP server

### ISSUE THREAD

**Issue by csirk51** [nodemcu/nodemcu-firmware#354]
Hi,
Is there a way to use static IP in STATION mode if the router (which the node is trying to connect) is running a DHCP server? I would like to shorten the wake time (battery powered nodes) between sleeps by using static ip, but I also need the DHCP server for other devices. 
If I use wifi.sta.setip() the status always stays STATION_CONNECTING. 
Thanks

**Comment by jonn26** [comment]
Yes, most routers let you set how many ips are in you dhcp scope. You just need to assign the esp a static IP that is outside the DHCP scope, but still in your subnet.

For example if your subnet is 192.168.1.0/24 and your dhcp scope is 192.168.1.2- 50 (first 49 Ips not including gw), then you just need to assign your esp an ip in the range of 192.168.1.51-254.

**Comment by csirk51** [comment]
Yes of course, I tried static IP which is not in DHCP pool.

**Comment by devsaurus** [comment]
See #719.
