### ISSUE TITLE
How to get the list of ip connected to esp in ap mode.

### ISSUE THREAD

**Issue by kothariketan** [nodemcu/nodemcu-firmware#355]

**Comment by sjfaustino** [comment]
The dev branch has a series of wifi submodule enhancements: https://github.com/nodemcu/nodemcu-firmware/pull/333

What you want is:
wifi.ap.getclient (wifi_ap_listclient)
returns table(mac,ip) of all connected clients

**Comment by devsaurus** [comment]
Closing this since instructions were provided.
@kothariketan Feel free to reopen in case your request is still not resolved.

**Comment by Apprel** [comment]
don't work for me ( 
cl = wifi.ap.getclient (wifi_ap_listclient)
print(cl)
table: 3fff3420

**Comment by BesitzeRuf** [comment]
Please learn how to works with tables in lua...

**Comment by Apprel** [comment]
Ok. BesitzeRuf.

**Comment by BesitzeRuf** [comment]
Just find in https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/wifi.c // Lua: table = wifi.ap.getclient() . Its return int value, but table should be stored in "wifi_ap_listclient", not in "cl" :) Probably it should works like wifi.sta.getap() (https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_en#example-45)

**Comment by BesitzeRuf** [comment]
so working code is

clientList={}
clientList=wifi.ap.getclient()
for k,v in pairs(clientList) do
  print(k,v)
end

**Comment by Apprel** [comment]
@BesitzeRuf thanks a lot dude, without you would not understand!
