### ISSUE TITLE
Problem with system_rtc_mem_read()

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#362]
I need to use the RTC memory for continuity after a deep sleep.
I tested the usage in the SDK and it works fine.

I then created a new nodemcu-firmware module `app/modules/misc.c`
and put there the same function. It does not work the same.

For example `system_rtc_mem_read(64, p, 4)` works but `system_rtc_mem_read(65, p, 4)` causes a restart. Any address not a multiple of 4 causes a restart.

I then tried something that does not restart and the results are not as expected.
```lua
    uint32 wr[8] = {
        0x11111111,
        0x22222222,
        0x33333333,
        0x44444444,
        0x55555555,
        0x66666666,
        0x77777777,
        0x88888888
        };
    uint8 rd[32];

    system_rtc_mem_write(64, wr, 32)

    system_rtc_mem_read(64, p, 4)
// *(uint32 *)rd should be 0x11111111 and it is

    system_rtc_mem_read(68, rd, 4)
//  now *(uint32 *)rd should be 0x55555555 but is 0x22222222
```

My full test function is
```lua
static int misc_rtc_mem_test_str(lua_State* L)	/* DEBUG */
{
    uint8 rd[32];
    uint32 wr[8] = {
        0x11111111,
        0x22222222,
        0x33333333,
        0x44444444,
        0x55555555,
        0x66666666,
        0x77777777,
        0x88888888
        };
    uint8 msg[20];

    luaL_Buffer b;
    luaL_buffinit( L, &b );
    char *p = luaL_prepbuffer(&b);

    system_rtc_mem_write(64, wr, 32);
  
    system_rtc_mem_read(64, rd, 4) ;
    c_sprintf (msg, "64 x%x\n",		*(uint32 *)rd);		c_strcat (p, msg);

//  system_rtc_mem_read(65, rd, 4) ;
//  c_sprintf (msg, "65 x%x\n",		*(uint32 *)rd);		c_strcat (p, msg);

    system_rtc_mem_read(68, rd, 4);
    c_sprintf (msg, "68 x%x\n",		*(uint32 *)rd);		c_strcat (p, msg);

    system_rtc_mem_read(64, rd, 32);
    c_sprintf (msg, "64+0  x%x\n",	*(uint32 *)rd);		c_strcat (p, msg);
    c_sprintf (msg, "64+4  x%x\n",	*(uint32 *)(rd+4));	c_strcat (p, msg);
    c_sprintf (msg, "64+16 x%x\n",	*(uint32 *)(rd + 16));	c_strcat (p, msg);

    luaL_addsize(&b, (uint32_t)c_strlen(p));
    luaL_pushresult( &b );
    return 1;
}
```
and the usage is:
```
> =misc.rtc_mem_test_str()
64 x11111111
68 x22222222
64+0  x11111111
64+4  x22222222
64+16 x55555555
```

**Comment by model101** [comment]
Moin,

when you write "I tested the usage in the SDK and it works fine." what version of the SDK
are you referencing? 
The notes of sdk 1.0.0 (http://espressif.com/new-sdk-release/) mention fixes in rtc read/write.
Nodemcu is still 0.9.5 I think.

Carsten

**Comment by eyaleb** [comment]
I built nodemcu-firmware with SDK 0.9.5p1, 1.0.0, 1.0.1b1, 1.0.1b2 and got the same bad results.
The plain SDK test was done with 1.0b1 and 1.0.1b2.

[later] I now tested the issue with plain SDK 0.9.5p1 and it has the problem!

I am left with the question of how is this so?
Does the nodemcu-firmware repository contain some libraries copied from the SDK?
[testing...] seems so, linking the SDK lib first brings up a few 'undefined reference' errors. So changing the SDK in the build is not a simple swap of the SDK reference.

This is a problem as I do need to use the `system_rtc_mem_*()` functions and so far I did not see any plan to move this firmware to the new SDK.

Eyal

**Comment by devsaurus** [comment]
@eyaleb Please check whether #545 addresses your request and close this issue accordingly.

**Comment by eyaleb** [comment]
I welcome the new functionality and expect many will find it useful. I can now remove my private module.

However, my testing showed that the SDK function itself is buggy in 0.9.5 (it fails unless the argument is a multiple of 4), so a move to a v1 SDK is also required.
