### ISSUE TITLE
WPA2 Enterprise Wifi authentication

### ISSUE THREAD

**Issue by fchanson** [nodemcu/nodemcu-firmware#366]
Is there a way to connect to an Access Point using WPA2 Enterprise ?

**Comment by jeffhuys** [comment]
+1

**Comment by photoprashanth** [comment]
+1

**Comment by cal101** [comment]
Moin,

I suggest asking questions on the forum and leave issues for real issues. You have a broader audience and nodemcu team can concentrate on bugs and RFEs.

Carsten

**Comment by TerryE** [comment]
WPA2 Enterprise Wifi connection isn't currently supported.  Doing so could be a potential feature enhancement, but (a) this would involve a lot of development and (b) IMO, the case for this doesn't stand up.  IoT devices shouldn't be 1st class devices in an Enterprise Wifi.  In the enterprise, surely they should be connected to a BMS or the like on a local building facilities AP, and this BMS should provide an appropriate access into the Enterprise.

**Comment by samer** [comment]
+1

**Comment by universam1** [comment]
+1

**Comment by TerryE** [comment]
I suggest we consider reopening this when the SDK supports this. This sort of functionality can't be sensibly implemented at the Lua firmware level.

**Comment by willd** [comment]
Apparently the SDK now supports WPA2 Enterprise as per this post: https://github.com/esp8266/Arduino/issues/1102

**Comment by Flole998** [comment]
I can confirm that the SDK supports WPA2 Enterprise now. There are also some implementations out there. This issue should be re-opened now.

**Comment by xfoldvar** [comment]
Is there any progress with WPA2 enterprise connection?

**Comment by Flole998** [comment]
Issue was closed and nobody is working on this. There seems to be nothing new.

**Comment by xfoldvar** [comment]
Thanks for your reply anyway.

**Comment by martinius96** [comment]
How is it now? Working or not?
