### ISSUE TITLE
coroutine.yield()

### ISSUE THREAD

**Issue by drv53b6** [nodemcu/nodemcu-firmware#369]
i have this code:
```LUA
local tr
local function onSent(c, pl)
   local trSt = coroutine.status(tr)
   print("sent",tr,trSt)
   if trSt == "suspended" then
      coroutine.resume(tr)
   end
end
local function on_response(connection)
  c=connection
  coroutine.yield() -- this yield alweys ok, status alweys "suspended"
  dofile("print_main_page.lc")
  c=nil
end
tr = coroutine.create(on_response)
conn.tread=tr
c:on("sent", onSent)
coroutine.resume(tr, connection)
```
and inside "print_main_page.lua" have as 1st string:
```LUA
  coroutine.yield() -- after this yield tread status alweys "dead"
  c:send("<html>")
```
1st yield ok, 2nd yield cannot well worck

**Comment by drv53b6** [comment]
so realy imposible make web server with this conn.send() realisation

**Comment by TerryE** [comment]
@drv53b6, the nodeMCU eLua model is event driven.  Use the event system to implement concurrency.  Coroutining across event threads won't work.

**Comment by drv53b6** [comment]
@TerryE but dont have event for geting free memory in send buffer

**Comment by TerryE** [comment]
This is facet of #846.  I will close this specific test case, and address it as part of the general issue.
