### ISSUE TITLE
tmr.delay() is synchronous and blocks the network stack

### ISSUE THREAD

**Issue by lmamakos** [nodemcu/nodemcu-firmware#37]
It would be nice if this suspended the Lua interpreter for the duration of the delay and allowed the network stack to run.  It appears to busy wait?

I think I can avoid this by recasting the code to be event driven and using the tmr.alarm() function with timers instead.  Minimally, the current behavior ought to be documented and perhaps its use discouraged for all but very short delays.

**Comment by layerzerolabs** [comment]
I propose this issue be closed, but the examples updated to include an example non-blocking use of timers as given by Toshik. The blink example does show the use of timers, but it is not clear to newcomers that this is the solution, as evidenced by this issue.

**Comment by jrahlf** [comment]
Can't we change tmr_delay to something like

    static int tmr_delay( lua_State* L )
    {
      static int waiting = 0;
      if(!waiting){
        waiting = 1;
        tmr_alarm(delay_us, tmr_delay);  //sacrifice one of the 6 timers
        lua_stop(); //lstop()?
        return;
     }

    waiting = 0;
    lua_resume();
    }

**Comment by tuanpmt** [comment]
hello,
Can you answer my question: http://stackoverflow.com/questions/28038208/calling-c-function-from-lua-argument
this is my idea, like async for nodejs, i'll resolve a lot of things for connectivity flow:
example idea for mqtt:
```lua
local m
async.waterfall({
 	function(cb)
 		m = mqtt.Client()
 		m:connect("192.168.1.101", 1880, 0, function(conn)
 			cb(nil)
 		end)
 	end,
 	function(cb)
 		m:subscribe("/topic", 0, function(conn)
 			cb(nil)
 		end)
 	end
},
function(err)
	print("finish mqtt workflow\r\n")
end)
```
```

**Comment by nayrangnu** [comment]
I wanted to post a possible solution which I just found [here](https://www.domoticz.com/wiki/ESP8266_WiFi_module). Use `tmr.alarm()` and test on each loop.
