### ISSUE TITLE
Allow for more than 7 timers

### ISSUE THREAD

**Issue by phaseOne** [nodemcu/nodemcu-firmware#373]
Any reason for hard coding 7 timers into the firmware, or is this an arbitrary limit? Not that many applications require more than 7 time based alarms, but the functionality should still exist to create more. At the least, this should be done to reduce confusion. If there is a reason for the limit, it should be explained in the docs.

**Comment by dnc40085** [comment]
it seems to be an arbitrary limit, I added 9 more timers and it didn't have any problem as far as I could tell

**Comment by vowstar** [comment]
I think more than 7 timers is no problem. We should find a new way to define timer Lua API.

**Comment by devsaurus** [comment]
See #709.
