### ISSUE TITLE
UDP server memory leak

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#378]
I'm getting slow memory  leak with my ssdp udp server. Arround of 100 bytes per 20 requests.
Code:
http://pastebin.com/KQq6RXBi

and logs:
http://pastebin.com/vF3SEaXK

**Comment by drv53b6** [comment]
try to not use anonimous functions

**Comment by pastukhov** [comment]
How to do this properly?

**Comment by pastukhov** [comment]
```lua
local function response(connection, payLoad)
        if string.match(payLoad,"M-SEARCH") then
            connection:send(ssdp_response)
            print("sent "..node.heap())
        end
end
UPnPd:on("receive", response(connection, payLoad) )
```
Return 
```lua
bad argument #1 to 'match' (string expected, got nil)
```

**Comment by pastukhov** [comment]
And same leak  with 
```lua
local function response()
     return function(connection, payLoad)
        if string.match(payLoad,"M-SEARCH") then
            connection:send(ssdp_response)
            print("sent "..node.heap())
        end
     end
end
UPnPd:on("receive", response() )
```

**Comment by cal101** [comment]
Moin,

the leakage ist most probably a bug and the avoidance of anonymous functions more
of a work around.

Neverthertheless some lua:

1. function xy(p1,p2) ...end

Defines a named function

2. function (a,b) ... end

Defines an anonymous function

3. xy(1,2) or myfunc()

CALLS a function, so both variants you wrote above CALL the response function
and the RESULT it passed to the on method.

You want:

4. xy

reference the function maned xy.

UPnPd:on("receive", response)

Hope that helps,
    Carsten

**Comment by pastukhov** [comment]
Thanks! The code is working, but memory still leaking.

**Comment by drv53b6** [comment]
И МНОГО ТЫ ТЕСТИРОВАЛ? ПОЛНОСТЬЮ ПАМЯТЬ ПРОПАДАЛА?
ТИТ ТАКОЕ ОЩУЩЕНИЕ ЧТО АВТОР ВСЕГО БОГАТСВА УШЕЛ В ДЛИТЕЛЬНЫЙ ОТПУСКИ ЛИБО ОЧЕНЬ ЗНАНЯТ, ВСЕЯКИЕ НЕУЧИ КОВЫРЯЮТ ПРОЕКТ

**Comment by drv53b6** [comment]
МОЖЕТ БОЛЕЕ РАННИЕ ВРЕСИИ ПОПРОБЫВАТЬ? В КРАЙНЕМ СЛУЧАЕ МОЖНО ПЕРШРУЖАТЬ ПРИБОРЧИК ПЕРЕОДИЧЕСКИ

**Comment by pastukhov** [comment]
За ночь 2 килобайта утекло.

**Comment by drv53b6** [comment]
перегружай по таймеру раз в сутки, ту похоже автор всей системы не появляется чтоб ошибки справлять, всякие бестоловки тока правки делают

**Comment by TerryE** [comment]
@pastukhov, there's absolutely nothing wrong with using anonymous functions.  If you use **ChunkySpy** then you will see that they generate the same code as a local function.  However, avoid using upvalues (e.g. `notifyCount` in your alarm routine) as these don't work intuitively in alarms and prevent garbage collection of the calling chunk.  Better in this case making `notifyCount` a simple global.

But non of this is relevant to your issue.  I'll have a play tomorrow and see if I can produce a simplified  reproducible version.  In the meantime, a simple work around is to reboot the ESP8266 after responding to every 20th call, say.

**Comment by pastukhov** [comment]
Ok, thanks.

**Comment by TerryE** [comment]
The multicast features are still in dev and where only first committed to master ten days ago.  Using a fixed IP and cutting this down to a minimal equivalent

```Lua
--[[Wifi configuration goes here]]
local resp = ("NodeMCU/20150415 pong"):rep(4)
udp=net.createServer(net.UDP)
udp:listen(8266)
print ("listening on "..wifi.sta.getip() .. ":8266")
udp:on("receive", function(sk, d) print ("received")  if d:match("ping245963") then sk:send(resp) end end)
udp:on("sent", function(sk, d) print("sent "..node.heap()) end)
```
this code is absolutely solid and has no leaks on 0.9.5.  I tried various test versions, such as replacing the upvalue `resp` by a global declaration and hoisting the anonymous instantiation of the receive and send functions, but this made no material difference: still no leaks.  

Perhaps this leak has been introduced in the multicast code?  Alternatively, have you any other timers running? Because these could be the source of the leak. 

Sorry, but I can't get this to repeat as a UDP server bug.  I think this leak is elsewhere.

**Comment by pastukhov** [comment]
Ok, i will try without multicast tomorrow.

**Comment by pastukhov** [comment]
I have curious statistic about memory usage in few days
https://docs.google.com/spreadsheets/d/1wwn_Xnv_UpMFI0WZM8BdHxlSmB19UVZOOTp094yEGFk/pubhtml

**Comment by TerryE** [comment]
@pastukhov Artem, the GC runs at the end of any Lua event sequence and pretty much everything that isn't referenced in (or dependent on)  **_G**, **package.loaded** or one of the booked event handers (e.g. a **tmr.alarm()** or an **sk:on()** gets returned to available memory.  For my TCP server that''s everything bar just under 3Kbyte, though the reported number varies a little depending on heap fragmentation.  So you do need to make sure that only active events are booked (and therefore locking in RAM).   Also not the **tmr.alarm()** bug that I reported in  #382.

**Comment by drv53b6** [comment]
@pastukhov  нормально че, нет утечьки, за год статистика нужна чтоб быть уверенным, а вообще хотябы раз в месяц перегружать не помешает чтоб быть уверенным

**Comment by pastukhov** [comment]
I'm getting much better results with latest firmware.
https://docs.google.com/spreadsheets/d/17CdSKppdYZNU1mhTo8jBAtyiNH2-Pl8wqaIKxmbQ75E/pubchart?oid=272110528&format=interactive

**Comment by drv53b6** [comment]
нет никакой утечьки- закрывай
