### ISSUE TITLE
Deauthentication packets

### ISSUE THREAD

**Issue by Mrono** [nodemcu/nodemcu-firmware#380]
Is it possible to send deauth packets?

**Comment by eliabieri** [comment]
+1



-- 

Elia Bieri
whateveryouwant@eliabieri.com

**Comment by cal101** [comment]
I understand your question as a question if it is currently possible to do so.

May I suggest to leave this "issues" list for real "issues" and discuss on
http://www.esp8266.com?

Issues must be read, understood and analyzed before deciding if anything need to be done.
We should not put that extra burden on the nodemcu team but trying to support by providing
fixes and pull requests and keep discussions away from issue list.

I promise to follow that advice, too. ;-)

Carsten
