### ISSUE TITLE
Feature request: Websockets

### ISSUE THREAD

**Issue by urmilparikh** [nodemcu/nodemcu-firmware#384]
Any plan to add support for Websocket client / server?

**Comment by marcelstoer** [comment]
IMO this shouldn't be built right into the firmware.

**Comment by marcoskirsch** [comment]
Wrong layer of the st wrong layer of the stack.

**Comment by marcelstoer** [comment]
Btw, this was brought up before in #30 in denied.

**Comment by urmilparikh** [comment]
Thanks @marcelstoer, I got some clues from that thread. Hopefully will have something working soon!

**Comment by urmilparikh** [comment]
Tried https://github.com/openresty/lua-resty-websocket, not enough memory :(

**Comment by f4t** [comment]
what's the solution for this as of today ?

**Comment by TerryE** [comment]
The previous poster approach might work with the dev140 when we've sorted out the issues.
