### ISSUE TITLE
sleep_type support

### ISSUE THREAD

**Issue by donnib** [nodemcu/nodemcu-firmware#39]
Hi,
Is sleep_type something new in the SDK from espressif ? If so is that something you will support ?

/Mihai

**Comment by vowstar** [comment]
Hello, this is fixed.
```lua
--do nothing
node.dsleep()
--sleep μs
node.dsleep(1000000)
--set sleep option, then sleep μs
node.dsleep(1000000, 4)
--set sleep option only
node.dsleep(nil,4)
```
See also
https://github.com/nodemcu/nodemcu-firmware/commit/5894df1da68460c9bf136023262c7da662a5a4fe

https://github.com/nodemcu/nodemcu-firmware/pull/143

**Comment by nodemcu** [comment]
already implemented.
