### ISSUE TITLE
Can't require modules that include "." in the name

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#391]
The current implementation uses standard eLua code so that `findfile()` at `app/lua/loadlib.c:361` does

```C
  name = luaL_gsub(L, name, ".", LUA_DIRSEP);
```
to map `require "a.b"` onto a search for `a/b` within the load path.  However the ROMfs and SPIFfs are both flat and don't permit subdirectories, so this type of require *must* fail.  

**Recommendation**: comment this line out so that dots are left as dots in loading require files.

**Comment by marcoskirsch** [comment]
For what it's worth, I use file names that contain / in nodemcu-httpserver. They aren't real directories but the FS allows it.

**Comment by TerryE** [comment]
@marcoskirsch, thanks for this.  I couldn't create them using the ESPlorer tool, so I assumed -- wrongly -- that the SPIFfs doesn't allow them.  I'll close this issue, as it isn't require.

**Comment by marcoskirsch** [comment]
nodemcu-uploader allows it.

**Comment by TerryE** [comment]
@marcoskirsch Marco, thanks for this link.  My framework gives me an extended version of these once bootstrapped onto the device, but this tool gives me a simpler way of doing the bootstrap. This way I only need to use `screen` to connect to my virtual comm port during testing to act as a logger.  Thanks.
I might just do a Lua version to plug into my framework.  I am doing everything in Lua so newbies don't have to learnt 2 new languages. Thanks again. :smiley:
