### ISSUE TITLE
OTA firmware update for ESD-12

### ISSUE THREAD

**Issue by mikewen** [nodemcu/nodemcu-firmware#392]
ESD-12 module have 4M Flash, should be able to support OTA update.

It would be awesome if NodeMCU can support OTA firmware update.

**Comment by drv53b6** [comment]
you can write it on lua and publish for free

**Comment by adrianocos** [comment]
news ?

**Comment by drv53b6** [comment]
peple must donate me 1KM9c4pYrN5oB1TVvSvHbRKw1n7fzqoSQm (bitcoin) and i will publish something

**Comment by chadouming** [comment]
This is the kind of shit that should get you ban. The point of making this
project open source is that everyone can help others. Not so you can get a
job.

**Comment by MrAPierce** [comment]
+1

**Comment by TerryE** [comment]
+1

**Comment by BesitzeRuf** [comment]
+1

**Comment by marcoskirsch** [comment]
+1

**Comment by marcelstoer** [comment]
+1, I'm wondering how much he's gonna donate to NodeMCU for providing free firmware to build upon

**Comment by morlac** [comment]
+1

2015-05-11 7:43 GMT+02:00 Marcel Stör <notifications@github.com>:

**Comment by myk3y** [comment]
+1 - this is the material he has to work with... https://www.youtube.com/user/drv53b6/videos

**Comment by drv53b6** [comment]
http://planetwars.aichallenge.org/profile.php?user_id=7423

**Comment by TerryE** [comment]
+1 again -- @drv53b6, your last post was pure spam.

**Comment by drv53b6** [comment]
im top coder here

**Comment by TerryE** [comment]
@vowstar, I feel that it is really getting to the point where the nodeMCU team should consider applying the [blocking user process](https://help.github.com/articles/blocking-a-user/) for drv53b6.

**Comment by myk3y** [comment]
But, but, but... He's a top coder! (Although there's no evidence of that...)

**Comment by drv53b6** [comment]
yes- im the best!

**Comment by vowstar** [comment]
@TerryE We have blocked this user.

**Comment by myk3y** [comment]
Thankyou.

**Comment by TerryE** [comment]
Another OTA duplicate.
