### ISSUE TITLE
Support the main developers with patreon.com

### ISSUE THREAD

**Issue by eliabieri** [nodemcu/nodemcu-firmware#393]
It would be nice if the main developers could set up a patreon account, so I and mybe others can support them financially. I see theres a lot of work to do and maybe theres just not enough time to raise money for their lives and invest much time in this awesome project.
What do you think?

**Comment by vleiswal** [comment]
On 4/28/2015 8:52 AM, Elia Bieri wrote:
>
> It would be nice if the main developers could set up a patreon 
> account, so I and mybe others can support them financially. I see 
> theres a lot of work to do and maybe theres just not enough time to 
> raise money for their lives and invest much time in this awesome project.
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nodemcu/nodemcu-firmware/issues/393>.
>
I will support them too!!! Great work!

Rgds

Vleis

**Comment by TerryE** [comment]
@eliabieri Eilia, I think that Patreon is the wrong way to go -- it's too specific a funding vehicle and not addressing this usecase.  However, it the nodeMCU site were to include an adhoc PayPal payment link then I for one would give them a donation.  Alternative, just remember that they do sell product and by buying one or more of their Dev kits, you are funding them indirectly.

**Comment by ramgarden** [comment]
I second the motion for the ad hoc paypal donation button idea.

**Comment by drv53b6** [comment]
do support me 1KM9c4pYrN5oB1TVvSvHbRKw1n7fzqoSQm  (bitcoin)
im cannot worck without support

**Comment by TerryE** [comment]
@drv53b6, IMO this list is for raising bugs / issues which directly relate to the NodeMCU firmware. It is not a forum for end-developer support, and it is not for begging.

**Comment by drv53b6** [comment]
@TerryE тебе слова не давали

**Comment by benrussell** [comment]
What about using bountysource?

https://www.bountysource.com/teams/nodemcu-firmware/issues
