### ISSUE TITLE
Makefile bug

### ISSUE THREAD

**Issue by drv53b6** [nodemcu/nodemcu-firmware#395]
Makefile bug:
if i change https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/modules.h
nothing will be rebuild

**Comment by marcelstoer** [comment]
You should change https://github.com/nodemcu/nodemcu-firmware/blob/master/app/include/user_modules.h and not `modules.h` I guess.

**Comment by pastukhov** [comment]
I am always doing ```make clean`` before compiling.

**Comment by TerryE** [comment]
See #719
