### ISSUE TITLE
mDNS UDP Can't Receive

### ISSUE THREAD

**Issue by JohnSL** [nodemcu/nodemcu-firmware#398]
I'm trying to use Zeroconf to make an mDNS request. I can send the request just fine (confirmed with Wireshark). However, I can't seem to get back any data. Here's what I've tried to receive the UDP packets:

```lua
ip = "224.0.0.251"
udp=net.createServer(net.UDP)
udp:listen(5353, ip)
udp:on("receive", function(con, pl) print("got data") end)
```

Am I doing something wrong? I've also tried this without providing an ip address to listen.

**Comment by pastukhov** [comment]
You should use 
```lua
net.multicastJoin(wifi.sta.getip(), "224.0.0.251")
```
with recent firmware builds.

**Comment by pastukhov** [comment]
Look at my ssdp experiments https://github.com/pastukhov/nodemcu-ssdp

**Comment by pastukhov** [comment]
Any progress?

**Comment by myk3y** [comment]
@pastukhov I can't get your 'net.multicastJoin' to work - and it isn't in the list of commands on the API.

**Comment by pastukhov** [comment]
Do you use latest source from dev096 branch?

**Comment by myk3y** [comment]
I did: "NodeMCU 0.9.6 build 20150406 "

When I execute the command: > net.multicastJoin(wifi.sta.getip(), "224.0.0.251")
stdin:1: attempt to call field 'multicastJoin' (a nil value)

**Comment by myk3y** [comment]
Doh! No, I didn't - I loaded the Master... retrying with the correct firmware :)

**Comment by pastukhov** [comment]
You can use http://frightanic.com/nodemcu-custom-build/

**Comment by myk3y** [comment]
That's very useful, @pastukhov thanks very much!

**Comment by marcelstoer** [comment]
There's a mDNS module in the `dev` branch now. -> closing
