### ISSUE TITLE
Override Serial communication

### ISSUE THREAD

**Issue by beckmx** [nodemcu/nodemcu-firmware#399]
is there anyway I can first consume the incoming serial data, before the nodemcu firmware can make something? for instance I just want to communicate serially with other mcu

**Comment by TerryE** [comment]
@beckmx, this is really a how do I / help issue that you should ask on a forum such as www.esp8266.com rather than a bug with the firmware.

**Comment by drv53b6** [comment]
```LUA
  uart.setup(0,9600,8,0,1,0)
  uart.on('data', '\000', recv_name, 0)
  uart.write(0, 'C')
  uart.setup(0,9600,8,0,1,1)
  uart.on('data')
```

**Comment by devsaurus** [comment]
See #719.
