### ISSUE TITLE
Decreasing Heap size

### ISSUE THREAD

**Issue by paulcuth** [nodemcu/nodemcu-firmware#40]
Hi,

Firstly, thanks for the great work, not only in creating this project, but also for your responsive updates and fixes. The modules, together with this project, are very exciting indeed.

However, one thing concerns me; I've noticed that as the updates keep coming and the API grows, the heap available to our Lua scripts is decreasing. I noted that, in the first two weeks in December, the available heap dropped by 6% and the updates have kept coming since. Am I correct in assuming that this is a result of the firmware expanding?

If so, is there any way that the API namespaces (for example `ow`, `gpio`, `i2c`) can start unloaded and are only loaded when `require()` is called? That way, libraries that I'm not using won't take up valuable heap space that my scripts could be using.

For example:
```lua
print(gpio)   --> nil
local gpio = require 'gpio'
print(gpio)   --> table
gpio.mode(9, gpio.OUTPUT)
-- etc
```

**Comment by nodemcu** [comment]
heap usage optimized.

**Comment by paulcuth** [comment]
That's great news, but do you have a little more info? How do I utilise the optimisations? Have you implemented require() for hw modules? Link to a commit with more info?

**Comment by nodemcu** [comment]
require can only perform on lua module for now.
the built-in module can not un-required to save ram.
close the issue only reading the title. sorry!

**Comment by TerryE** [comment]
Inactive debate, which has largely been addressed by recent improvements.
