### ISSUE TITLE
SPI pinout

### ISSUE THREAD

**Issue by beckmx** [nodemcu/nodemcu-firmware#403]
Hello, does anybody knows what are the SPI pins? I have the ESP-07 but cannot make it work

**Comment by drv53b6** [comment]
GPIO12 - MISO
GPIO13 - MOSI
GPIO14 - CLK
GPIO15 - CS (with an 10k pulldown to ground so the ESP8266 will boot up)

**Comment by asm7100** [comment]
You set in the software :-)

**Comment by pastukhov** [comment]
How to set it? Any example?

**Comment by beckmx** [comment]
in the nodemcu API is described, however my doubt was resolved with the
first post, those numbers should be on the wiki

2015-05-13 15:53 GMT-05:00 Artem Pastukhov <notifications@github.com>:

**Comment by devsaurus** [comment]
Added to README.md with #647.
