### ISSUE TITLE
dont have way to print flash free space

### ISSUE THREAD

**Issue by drv53b6** [nodemcu/nodemcu-firmware#407]
dont have way to print flash disk free space

**Comment by dnc40085** [comment]
It is not documented in the wiki... but there indeed does exist a command in the file module named file.fsinfo that gets the total file system size, bytes used, and bytes remaining.
here is the lua code to print that info;

local total, used, remain=file.fsinfo() print("\nFile system info:\nTotal : "..total.." Bytes\nUsed  : "..used.." Bytes\nRemain: "..remain.." Bytes\n")

**Comment by dnc40085** [comment]
My mistake I transposed  total and remain
corrected:
local remain, used, total=file.fsinfo() print("\nFile system info:\nTotal : "..total.." Bytes\nUsed : "..used.." Bytes\nRemain: "..remain.." Bytes\n")

**Comment by TerryE** [comment]
Please close your issue :smile:
