### ISSUE TITLE
Does OTA feature supported with current release ?

### ISSUE THREAD

**Issue by crapthings** [nodemcu/nodemcu-firmware#410]
any possible way?

**Comment by GeorgeHahn** [comment]
See #392

**Comment by marvinroger** [comment]
Please write in english @crapthings, so that everyone can understand and discuss. :)

**Comment by vowstar** [comment]
It is possible, but you may lost almost half of filesystem.

**Comment by marcelstoer** [comment]
Either this or #392 should be closed - they're duplicates.
