### ISSUE TITLE
Document file.fsinfo()

### ISSUE THREAD

**Issue by marcoskirsch** [nodemcu/nodemcu-firmware#411]
Per: https://github.com/nodemcu/nodemcu-firmware/issues/407#issuecomment-100753025
... this is missing in the API documentation.

**Comment by TerryE** [comment]
@drv53b6, spamming and unnecessary use of obscentities can get your github account suspended.  Please stop.

**Comment by dnc40085** [comment]
I just added documentation for file.fsinfo()

please don't forget to close the issue.
