### ISSUE TITLE
What could a beginner do  ?

### ISSUE THREAD

**Issue by vautrinr** [nodemcu/nodemcu-firmware#415]
Hello,
I just discovered your product and firmware - which looks very cool - Before buying it I would like to know if you had examples of what a dummie could do with this. :) I have some basic in Lua, C/C++... 

Thanks by advance.

Rémi

**Comment by BesitzeRuf** [comment]
Examples are in folder examples

**Comment by drv53b6** [comment]
https://github.com/nodemcu/nodemcu-firmware/issues/388

**Comment by TerryE** [comment]
Hi, the best place for a beginner to find support and information is on a specialist forum targetting this need.  Try the [ESP8266 forum] (http://www.esp8266.com).  

This isn't really a bugfix issue so you should close this issue :smile:

**Comment by vautrinr** [comment]
Thanks !!!
