### ISSUE TITLE
gateway 0.0.0.0 is unsettable by wifi.ap.setip(cfg)

### ISSUE THREAD

**Issue by kelcon** [nodemcu/nodemcu-firmware#426]

**Comment by dnc40085** [comment]
This should be a simple fix.
Just out of curiosity, why do you need to set gateway to 0.0.0.0?

**Comment by dnc40085** [comment]
The fix has been merged into the dev096 branch, if you compile that branch your issue should be remedied. 
Please don't forget to close this issue.

**Comment by kelcon** [comment]
Thanks.

I would like, to set as non-routable:
http://en.wikipedia.org/wiki/0.0.0.0
