### ISSUE TITLE
wiki and dev096 branch: should I add documentation

### ISSUE THREAD

**Issue by dnc40085** [nodemcu/nodemcu-firmware#430]
Does the wiki only apply to the master branch or does it apply to all branches?
I was wondering because I was going to add descriptions to the wiki for my recently merged pull requests, so as to inform people (who aren't willing to comb the NodeMCU source code) how to use the new features.

Maybe there could be a dev wiki so people who submit PRs could document their additions/changes.

**Comment by vowstar** [comment]
Yes, nice idea.

**Comment by dnc40085** [comment]
Cool, I'll get started on it.
