### ISSUE TITLE
wifi.startsmart not working.

### ISSUE THREAD

**Issue by nodemcu** [nodemcu/nodemcu-firmware#44]
this is due to the sdk 0.9.4
the sniffer api has changed, and no doc right now.

**Comment by mishoboss** [comment]
Is there a documentation about this feature now? Is there a detailed description what packets need to be sent in order to do smart configuration? Can this be done from non-esp8266 device?

**Comment by rubberbird** [comment]
Any news on this? Still not working for me

**Comment by marcelstoer** [comment]
@nodemcu Do you want to close this now since 0.9.x days are finally over? If please make sure the API documentation in the wiki is up to date.

**Comment by nodemcu** [comment]
this is outdated. see #596, #653
