### ISSUE TITLE
"not enough memory" to compile bmp085 module using 096

### ISSUE THREAD

**Issue by 8n1** [nodemcu/nodemcu-firmware#440]
It's not possible to compile the bmp085.lua using the latest build(0.9.6 - 20150406) from the dev096 branch because of "not enough memory". 
It works just fine under 0.9.5(20150213).

**Comment by marcelstoer** [comment]
You can [build the NodeMCU firmware yourself](https://github.com/nodemcu/nodemcu-firmware#build-option) and disable all the modules you don't need thereby freeing some space. Or you can build the firmware with http://frightanic.com/nodemcu-custom-build/. Disclaimer: that's my site.

**Comment by 8n1** [comment]
Hey nice one! I already thought about building the firmwary myself. Thanks for sharing. I'll give it a try.

**Comment by znsoft** [comment]
try to split bmp module to many small linear modules less then 50 lines of code, and remove comments.

Offtop: WOW i`ll get to favorite this one web builder.  Cool !

**Comment by 8n1** [comment]
hmm. havn't thought about splitting the module itself. Anyhow this shouldn't be neccessary to use it, right?
I already noticed that splitting up code into smaller parts helps a lot. And in fact it's the only way I' m able to use a large number of modules at once right now on 0.9.5. (actually not at once, but one by one)

The other things you mentioned are not new to me too, but thanks!

**Comment by 8n1** [comment]
This is no longer a issue since the the latest firmware builds have a lot more ram available. 
Which is pretty awesome, btw.
