### ISSUE TITLE
dht_lib isn't returning reasonable values on dev096

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#474]
Hi, i'm trying to use dhl_lib from libraries and getting:
```lua
> dofile('dht22_test.lua')
Temperature: 614.4 deg C
Temperature: 1137.9 deg F
Humidity: 24.0%
```
But ```yet-another-dht11.lua``` from examples is working fine
```lua
> print("DHT22", dofile("yadht22.lua").read(2, true))
DHT22	298	225
```

**Comment by MarsTechHAN** [comment]
Sorry for that... The running speed has already changed and created some timing issue.
Now we are taking steps on turning lua lib into a C one. (But it still cannot works well when engage DHT22= =)

**Comment by MarsTechHAN** [comment]
The data is incorrect, but check passed= =
We are so puzzled about it......

**Comment by pastukhov** [comment]
Thanks for dht module!
