### ISSUE TITLE
Interrupts: "down" edge behaves as "both"

### ISSUE THREAD

**Issue by Suxsem** [nodemcu/nodemcu-firmware#479]
Hi. I have just tested this code on my esp8266 01:
```
gpio.mode(4,gpio.INT)

function pincb(level)     
    print("interr!")
end

gpio.trig(4,"down",pincb)
```

Well...i get the "interr!" debug string on RISING AND FALLING edges. As if I put "both".
No problem with "up" edge!

Can you test please?

**Comment by Suxsem** [comment]
No one?

**Comment by znsoft** [comment]
its a contact bounce (relay chatter; relay flutter), try this tmr.delay(700000) after print() work fine!
 i not found english doc but there is on russian: https://ru.wikipedia.org/wiki/%C4%F0%E5%E1%E5%E7%E3_%EA%EE%ED%F2%E0%EA%F2%EE%E2

**Comment by marcelstoer** [comment]
Good information about the debounce subject is here: http://esp8266.co.uk/tutorials/introduction-to-the-gpio-api/#debouncing

**Comment by Suxsem** [comment]
Thanks... I found it odd because with "up" i don't have this problem...

**Comment by TerryE** [comment]
Bounce is usually a electrical manifestation a mechanical mechanism such as a relay.  You will get mechanical bounce at the relay-open side but usually this won't give rise to false signals.  

Whatever the issue, it's nothing to do with nodeMCU.  Please close this call. Thank-you.

**Comment by Suxsem** [comment]
Ok, thank you :)
