### ISSUE TITLE
Unreadable message after restart

### ISSUE THREAD

**Issue by vudangngoc** [nodemcu/nodemcu-firmware#481]
After restart MCU by node.restart(), at console of ESPlorer show some strange text like:
B!ժ�:6����;KB�����
JC��3j2��)���������
"ʏr��:6�����R����
I cannot read those text, maybe my laptop lack some kind of font (I use Ubuntu 14.04). So that I don't know its have some information or just nothing. Please correct me.

**Comment by TerryE** [comment]
A regular issue.  Search the esp8266.com forum for 76800 to find many topics discussing this feature.  It's nt a bug per se.  Please close this issue.
