### ISSUE TITLE
net.createConnection() return nil

### ISSUE THREAD

**Issue by vudangngoc** [nodemcu/nodemcu-firmware#482]
I build latest code from both dev and dev096 and copy code from example but it doesn't work as expected 
```
> local conn = net.createConnection(net.TCP, 0)
> print(conn)
nil

```

**Comment by TerryE** [comment]
What's the firmware bug?  Use the [nodeMCU forum](http://bbs.nodemcu.com/) or the English [ESP8266.com forum](http://www.esp8266.com/viewforum.php?f=17) for applications support.

**Comment by vudangngoc** [comment]
I check this bug with branchs dev and dev096, both of its have this issue

**Comment by TerryE** [comment]
`createConnection()` fails if your WiFi isn't connected.

**Comment by vudangngoc** [comment]
I think my MCU connected to wifi
![createconnection](https://cloud.githubusercontent.com/assets/9317574/8159973/e38a6358-1395-11e5-8921-2cbaacdda299.png)

**Comment by pastukhov** [comment]
```lua
sk=net.createConnection(net.TCP, 0)
    sk:on("receive", function(sck, c) print(c) end )
    sk:connect(80,"192.168.0.66")
    sk:send(
"GET / HTTP/1.1\r\nHost: 192.168.0.66\r\nConnection: keep-alive\r\nAccept: */*\r\n\r\n"
    )
```
from http://www.nodemcu.com/docs/net-socket-module/#net-socket-module-connect

**Comment by vudangngoc** [comment]
You can see my code is similar with first line of your example, but it doesn't work as my screenshot

**Comment by pastukhov** [comment]
But where is```    sk:connect(80,"192.168.0.66")```?

**Comment by vudangngoc** [comment]
net.createConnection(net.TCP, 0) return nil so that I cannot call sk:connect(80,"192.168.0.66")

**Comment by jorgempy** [comment]
i believe the problem is the 'local' keyword. i appears you are trying it in the repl, in the repl each line has it's own scope, so a local var is nil in the next line. You should try either not using local or putting it in a file a running it using dofile.

**Comment by TerryE** [comment]
> in the repl, in the repl each line has it's own scope, so a local var is nil in the next line
@jorgempy,   I was puzzled abut this bug. Thanks for pointing out what should have been obvious.  However, one subtle amendment, it is syntactically complete chunks that Lua executes in "-i" mode.  You can tell when the chunk isn't complete because you get the `>>` prompt instead of the `>` one.

**Comment by vudangngoc** [comment]
the local keyword make conn variable have scope within one code line. I put all code to do - end block and it work. Thank you very much!

![image](https://cloud.githubusercontent.com/assets/9317574/8232400/997c2786-15f9-11e5-8107-d6b448b30b93.png)

**Comment by jorgempy** [comment]
@TerryE yes, chunks... thanks for the correction, and for the do .. end suggestion ;)
