### ISSUE TITLE
How to test Smartconfig?

### ISSUE THREAD

**Issue by adoph** [nodemcu/nodemcu-firmware#493]
I tried using smartconfig, but never succeed. I can not find the information to test smartconfig. I know there are many versions of ESP-Touch. I'm not sure the problem is nodemcu or  App. Can you provide information to help me?

**Comment by MarsTechHAN** [comment]
One of the issue is... fix the smartconfig

So... now we are taking step on it...But we have not finished...
If you want to use ESPTOUCH, you can make your own bin，
look it up->https://github.com/obuil/NodeMcu

**Comment by vowstar** [comment]
Waiting our v1.1.2 branch, we will import esptouch and use espressif's open sourced app.

**Comment by adoph** [comment]
I look forward to your new version. Thank you.

**Comment by Air000** [comment]
if the v1.1.2 branch support AirKiss?

**Comment by MarsTechHAN** [comment]
@Air000 Yes

**Comment by vowstar** [comment]
@Air000 airkiss is OK, test v0.9.6 branch and see documents.

**Comment by vowstar** [comment]
Smart config is OK. Close #493.

**Comment by pastukhov** [comment]
i'm getting 
```
> PANIC: unprotected error in call to Lua API (stdin:3: bad argument #2 to 'format' (no value))
```
with wifi.smartstart example from documentation on  today v0.9.6

**Comment by Air000** [comment]
@vowstar I test the smartconfig with firmware 0.9.6-dev_20150704. But fail with reboot:

> dofile("smartconfig.lua")                                 
> Success. SSID:Terry3G ; PASSWORD:msjjsns                  
bB��ʦ�Sb9�1�)]�1�)�!�N�hC                                   
NodeMCU 0.9.6 build 20150704  powered by Lua 5.1.4          
lua: cannot open init.lua

**Comment by Air000** [comment]
And I compile a dev112, which even not print the "Success" info. wifi.sta.status() would change from 1 to 4.

Then I used the wifi.sta.config() to connect to ap, but failed with wifi.sta.status() = 4: STATION_CONNECT_FAIL

**Comment by marcelstoer** [comment]
Feel free to re-open if you're still seeing this with the latest `dev` branch. Note that smartconfig is now turned OFF by default.
