### ISSUE TITLE
Firmware mess-up

### ISSUE THREAD

**Issue by brightmoon03** [nodemcu/nodemcu-firmware#498]
When I  downloaded the flasher and firmware, and plugged in my node MCU through USB,  I hit the start button and it started to work but then it said that there is a connection timeout error. Now my Node MCU seems to have half of it's firmware on it and the blue LED isn't flashing on and off like it used to. Can  anyone help?

**Comment by MarsTechHAN** [comment]
I believe you use the "FLASH_DOWNLOAD_TOOLS_v1.2_150512" which release by the Espressif which dont support Auto Download.

Try this out
```html
https://github.com/nodemcu/nodemcu-flasher
```

**Comment by vowstar** [comment]
And needn't press any button.

**Comment by brightmoon03** [comment]
When I plug in the Node MCU to both my Mac and my PC, my computers won't recognize it. And the blue led only flashes once, when you plug it in.

**Comment by MarsTechHAN** [comment]
You may need to install the driver, the chip is called CP2102

**Comment by brightmoon03** [comment]
I already installed the driver on my Mac. Do I need to install it on my PC? 

Thanks, Samuel Martin

**Comment by saitejalakkimsetty** [comment]
@brightmoon03 I had similar issues before. I always endup reinstalling the driver, flash the espressif firmware on it and then install the nodemcu firmware. If I skip installing the espressif firmware, sometimes it works, sometimes it doesn't.

**Comment by TerryE** [comment]
See #719.
