### ISSUE TITLE
Setting many gpio.modes consecutively causes chip to hang

### ISSUE THREAD

**Issue by liquiddandruff** [nodemcu/nodemcu-firmware#514]
Came across this recently. Wonder what's the reason for this?

```lua
for i = 1, 10 do
    print("setting pin " .. i .. " as an OUTPUT")
    gpio.mode(i, gpio.OUTPUT)
    --tmr.delay(100000) --uncommenting this sets all pins from 1 to 9 without hang, hangs still on 10
end
```

**Comment by MarsTechHAN** [comment]
9 and 10 only available on Amica Board, and if you set 9/10 on other ESP8266 modules(like NodeMCU Dev kit 0.9), it will make the flash unable to work.
[Beacuse in QIO mode, GPIO9/GPIO10  are data channel.And amica using DIO]

So which board you use? Can you take a picture of it?

**Comment by liquiddandruff** [comment]
Ah yes, it actually hangs on both 9 and 10 for my esp201s and esp12es. Setting the pin modes in a loop from 1-8 is ok now.

**Comment by vowstar** [comment]
Don't touch the pin which UART uses.
