### ISSUE TITLE
Add a function to show the nodemcu build info.

### ISSUE THREAD

**Issue by jiegec** [nodemcu/nodemcu-firmware#530]
Something like vim --version, including the current nodemcu version, whether the modules are enabled.. built on which time... And add a rule to contributing by issues: put all these information first. In this way, we can easier to know whether the code has fixed in newer dev versions.

**Comment by MarsTechHAN** [comment]
You can create a PR... 
Simply add a function and add #define on optional file.

**Comment by jiegec** [comment]
Ok, but i am not at home until the tomorrow... And i may not be able to touch my pc because of the final exam -_-

**Comment by MarsTechHAN** [comment]
@jiegec You can program with you phone, at least it is a Unix BSD Device(If you use iOS) or Linux (Amdroid)

**Comment by marcelstoer** [comment]
>  ...including the current nodemcu version, whether the modules are enabled.. built on which time

This is related to https://github.com/nodemcu/nodemcu-firmware/issues/449#issuecomment-109283562 in which I documented how my public cloud build handles this.

**Comment by jiegec** [comment]
@marcelstoer Yes, that's the same, just need a small PR to include a small function in it.
