### ISSUE TITLE
CI build for dev112 & dev120 fails

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#532]
As per https://travis-ci.org/nodemcu/nodemcu-firmware/builds/69487853#L2112 the `dev112` branch is currently broken.

**Comment by dnc40085** [comment]
I compiled and burned dev112 and every time I reset the chip I get non-ascii characters. no info on the chip, no nothing, just non-ascii characters

**Comment by felixcameron** [comment]
I did the same, the output is ascii but at 115,000bps I think

**Comment by dnc40085** [comment]
I tried it with the default baud rate (9600) and when I tried connecting to it at 9600, 74880, 115200 baud rates I got nothing. I also tried changing the default rate to 115200 and got the same results.

**Comment by marcelstoer** [comment]
Guys I appreciate your feedback and tests but the subject of this issue is the failing CI build. Even if your local builds at least compile it's important for me that the reference build on Travis is green.

**Comment by vowstar** [comment]
We will try to pass the build, need more testing...

**Comment by georgkreimer** [comment]
This is what I get on an ESP-01 at 115200
rl��r��#�n������p�<����8��ǒ��lp�nn��;�nĒ���b�$  rrp�n��܀��l���b�n��n�䎀l�p��nn����l`��#�n�$��l`�8`rn|��n����l`�~����#�n�$���nn���l`nn��܀������b�n��n�$��������8��nn���l`

**Comment by pastukhov** [comment]
Same on ESP-201

**Comment by marcelstoer** [comment]
I just updated the issue title because the exact same issue exists in the new dev120 branch. See https://travis-ci.org/nodemcu/nodemcu-firmware/builds/70753912 I hope you find the time to look into this soon.

**Comment by vowstar** [comment]
The problem is in lwip, sdk 1.x broken the wifi due to unkown problem with open-source lwip, when we use espressif's closed source lwip, wifi works. Still finding solutions. Now CI may works.

**Comment by georgkreimer** [comment]
@vowstar Any easy way to switch to the espressif lwip?

**Comment by marcelstoer** [comment]
https://travis-ci.org/nodemcu/nodemcu-firmware/builds/70897645 is proof that the CI build is fixed.

**Comment by georgkreimer** [comment]
@marcelstoer Have you gotten the latest build to run on an actual ESP8266?

**Comment by marcelstoer** [comment]
Haven't tried. That isn't relevant for this issue though as it's about the CI build failing.
