### ISSUE TITLE
Issue with communication between two esp's using arduino uno 

### ISSUE THREAD

**Issue by thrinasco** [nodemcu/nodemcu-firmware#536]
Hi,

This is venkat,Please ,I would request you to clear one of my doubt.i was using the following library for communication  
https://github.com/INEXTH/Arduino-ESP8266_libs

Server is created and when i am starting server to make communication between them iam getting the following error which was marked.

AT+CIPSTART=(4)("TCP"),("192.16ø.4.1"),(80)
Link typ ERROR

I am doing these commuinication using two esp8266 with two arduino boards.

​
![link](https://cloud.githubusercontent.com/assets/12268500/8540833/ca1cc8b2-24a6-11e5-9247-ce2ff563d64b.png)

**Comment by thrinasco** [comment]
help me out

**Comment by benrussell** [comment]
User has filed duplicate bug report here, where it belongs:

https://github.com/INEXTH/Arduino-ESP8266_libs/issues/3


Suggest closing this issue as not relevant to nodemcu project.

**Comment by MarsTechHAN** [comment]
Also... Here is NodeMCU's Issue List. Why not try NodeMCU : )

**Comment by devsaurus** [comment]
See #719.
