### ISSUE TITLE
expose ssl aes

### ISSUE THREAD

**Issue by sauloal** [nodemcu/nodemcu-firmware#540]
Would it be possible to expose:
app/ssl/crypto/ssl_aes.c

so that we can use public key encryption to send data under insecure connections?

regards

**Comment by peon374** [comment]
I would like to do encrypted auth to cloud service and this would help me too.

**Comment by marcelstoer** [comment]
It's IMHO a bit unfortunate AES isn't part of the [crypto module](https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_en#crypto-module) but buried in the SSL stuff.

**Comment by dfeinzeig** [comment]
I thought I saw mention that the esp8266 has optimizations for aes?

**Comment by TerryE** [comment]
@dfeinzeig, yes it does, but the API is not documented.  If you wish to retro-engineer it and develop the enhancement then we would welcome this, but in the meantime those actually developing the core firmware need to set their own priorities.

**Comment by devsaurus** [comment]
See related PR against `dev`.
