### ISSUE TITLE
Achilles and the tortoise, 1.2 SDK 

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#543]
What about 1.2 SDK version?

**Comment by MarsTechHAN** [comment]
You can have a try : )

**Comment by fabianhu** [comment]
Did a short test drive (compile the dev). 
Ended up on a tree.
Could not get communication with device over serial port.

**Comment by MarsTechHAN** [comment]
@fabianhu  You tried the SDK 1.2? Can you explain detail phenomenon?

**Comment by fabianhu** [comment]
Just exchanged the link to the SDK within my already installed toolchain. 
After downloading the compiled nodemcu, I could not establish connection with ESPlorer.
I tried several re-compiles and used [https://github.com/pfalcon/esp-open-sdk] newest version to install toolchain again, it brings SDK 1.2.0 with it.
The module sends a 
```
ets_main.c 
 ets Jan  8 2013,rst cause:1, boot mode:(3,7)
```
with 74880 baud on reboot.
No communication with ESPlorer - tried with all baudrates from dropdown. (GPIO 0 floating!)
Sorry, I do not have more findings yet.

**Comment by TerryE** [comment]
We are now on 1.4
