### ISSUE TITLE
New GPIO Method.

### ISSUE THREAD

**Issue by roccomuso** [nodemcu/nodemcu-firmware#546]
Couldn't be useful add in the GPIO Module the method: gpio.toggle()
To switch the state of a GPIO pin?

Great job ;)

**Comment by creationix** [comment]
I'm not sure that would be useful enough to be a dedicated API.  You do know that you can read output pins right (I didn't till I read the bitlash examples)?  Simply write the `not` of the read to toggle.

**Comment by roccomuso** [comment]
Yeah i know it of course. It's just for completeness, read, write, toggle. Classic operations for a general purpose pin.

**Comment by MarsTechHAN** [comment]
I believe this is useless... Why dont you just use gpio.mode?

**Comment by nodemcu** [comment]
gpio.mode changes like direction but toggle changes state, or pin level.
but in sdk level there is no toggle function , so to do this have to read and write, this change pin mode from output to input and output again, without user awareness, maybe cause some problem? glitch
?

**Comment by eyaleb** [comment]
Are you sure that reading an output pin changes the mode? I thought it just reads the register which, for output pins, holds the last state set.

**Comment by nodemcu** [comment]
opps, this is old setup, it will not put into input state by nodemcu firmware according to this commit #df3c82391ffbe71223ddc6cd6f1d3e38989c7b3b
https://github.com/nodemcu/nodemcu-firmware/commit/df3c82391ffbe71223ddc6cd6f1d3e38989c7b3b#diff-2eeba06bdd37586901dca4f122de1cf0L132

**Comment by TerryE** [comment]
Nope.  It's one line of Lua.  Not going to implement.  If someone proposes a PR then we might consider it.

**Comment by dvv** [comment]
Still +1 for toggle.
The rationale of toggle is i) _atomicity_ and ii) to down the toggle "execution" time (allows for faster bitbanging). The latter of course can be dirty worked around with a variable kept in sync with pin state.
