### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by Diaoul** [nodemcu/nodemcu-firmware#55]
I think an MQTT library makes sense for this firmware and IoT stuff. I found [this library](https://github.com/geekscape/mqtt_lua), what would it take to port it? Unfortunately I don't know any LUA.

**Comment by kmpm** [comment]
:+1:

**Comment by clixx-io** [comment]
Can LUA call C++? Also MQTT usually has callbacks.

**Comment by tuanpmt** [comment]
Testing: http://www.esp8266.com/viewtopic.php?f=19&t=1278

**Comment by vowstar** [comment]
Cool!

**Comment by zendes** [comment]
Very interested in this too. :-)

**Comment by Diaoul** [comment]
Is there a build with the mqtt branch? I'd like to give it a shot.
How does it compare with native mqtt in terms of reliability?

**Comment by Suxsem** [comment]
Wow wonderfull!
Just a couple of questions about the USAGE DEMO:
1) when the m:on("offline",...) callback is called?
2) what is the "conn" param in m:on("receive", function(conn, topic, data)  ?

**Comment by nodemcu** [comment]
conn means the client created by mqtt.Client,
and should use on("message")

**Comment by tuanpmt** [comment]
@Diaoul Update bin file here: http://www.esp8266.com/viewtopic.php?f=19&t=1278

**Comment by nodemcu** [comment]
mqtt branch merged to master
