### ISSUE TITLE
http server - setting headers

### ISSUE THREAD

**Issue by roccomuso** [nodemcu/nodemcu-firmware#557]
In the simple http server example, how to send a response to the client setting the headers?

Where may i find a complete documentation?

**Comment by TerryE** [comment]
@roccomuso, this is absolutely nothing to with NodeMCU.  This is straight HTTP protocol stuff that you will find in the RRCs, Wikipedia and many tutorials on this subject.  This isn't the place to seek this sort of help.

**Comment by marcelstoer** [comment]
This issue list is for bugs/features of the firmware. Please ask general Lua/NodeMCU questions at http://www.esp8266.com/viewforum.php?f=17 or http://bbs.nodemcu.com/c/nodemcu.

**Comment by zerog2k** [comment]
the example is here:
https://github.com/nodemcu/nodemcu-firmware/blob/master/lua_modules/http/http-example.lua#L30-L33
