### ISSUE TITLE
Interrupt GET esp8266

### ISSUE THREAD

**Issue by entozoon** [nodemcu/nodemcu-firmware#567]
Is it possible to interrupt a get? For example if it is currently receiving lot of data, is it possible to run
node.restart() or wifi.sta.disconnect() so as to free it up?

Currently my ESP8266 just hangs until the data is finished being received. I'd rather not have to reset the chip and have it reconnect to wifi all over again.

**Comment by TerryE** [comment]
This is a howto Q for the esp8266.com Lua forum or StackOverflow.  It's not an firmware issue for this list.   If you close this issue and post to esp8266.com, I can answer there. :smile:

**Comment by entozoon** [comment]
Fair enough Terry, thank you:
http://www.esp8266.com/viewtopic.php?f=13&t=4120
