### ISSUE TITLE
Saving current UART0 baud rate to EEPROM as default baud rate

### ISSUE THREAD

**Issue by 4refr0nt** [nodemcu/nodemcu-firmware#57]
If we set new baud rate with command "uart.setup()" - it's for current session only and after module reboot we must use default baud rate 9600 again.
New version of uart.setup:
uart.setup( id, baud, databits, parity, stopbits, echo, PERMANENT )
if permanent=1, then uart used new baud rate permanently, also after module restarted
(exactly AT-based firmware v0.20 SDK 0.9.4 command "AT+IPR")
Its feature very important for using ESP8266 with additional external MCU (Arduino, RaspberryPi, and so on)

**Comment by paulsweb** [comment]
I can't seem to permanently change the baud rate using the above method. I tried both
=uart.setup(0,115200,8,0,1,1,PERMANENT)
and
=uart.setup(0,115200,8,0,1,1,1)
both changed the baud rate until the next reset or power cycle and then it returned to 9600.
I'm running NodeMCU 0.9.6.
Any ideas.

**Comment by cal101** [comment]
Set it in init.lua. Its not persistent.
