### ISSUE TITLE
AP disconnections when phone is connected

### ISSUE THREAD

**Issue by wordsforthewise** [nodemcu/nodemcu-firmware#580]
When I connect my phone to SOFTAP or STATIONAP mode, it constantly disconnects and reconnects.  It doesn't seem to do this on my computer (although sometimes it sporadically disconnects), but it always happens on my phone.  I'm just testing it with this small lua code:
```Lua
wifi.setmode(wifi.SOFTAP)
local cfg = {}
cfg.ssid = "myfi"
cfg.pwd = "mystical"
wifi.ap.config(cfg)
local srv=net.createServer(net.TCP, 3000)
print('connect to \''..cfg.ssid..'\', password \''..cfg.pwd..'\', ip '..wifi.ap.getip())
cfg = nil
srv:listen(80,function(conn)
  conn:on("connection",function(client) print("conn") end)
  conn:on("disconnection",function(client) print("discon") end)
  conn:on("reconnection",function(client) print("recon") end)
  conn:on("sent",function(client) print("sent") end)
  conn:on("receive", function(client,request) print("recieve") end)
  end)
```
I'm thinking that some push updates on my phone are screwing it up, but I have no idea if it's even possible to debug in lua, and I don't know where to start debugging it in c.  If anyone has advice for figuring out how to debug it in c let me know.

**Comment by MarsTechHAN** [comment]
Because ESP's hot spot is not available to Internet. Some kind of phone will constantly drop connection and try other hot spot.

**Comment by wordsforthewise** [comment]
Ah I see.  Is there a way to use the ESP into fooling the phone so it doesn't disconnect?

**Comment by MarsTechHAN** [comment]
I dont have a good enough idea...

**Comment by marcelstoer** [comment]
Still an issue with the SDK 1.5.1 used in the `dev` branch? If so please reopen.
