### ISSUE TITLE
many function definitions don't use the ICACHE_FLASH_ATTR

### ISSUE THREAD

**Issue by aguaviva** [nodemcu/nodemcu-firmware#582]
Examples: all the Lua interpreter, mqtt, spifs, all the modules, coap...

If I understood correctly this keyword is necessary so the function gets executed from ROM and doesn't get copied to RAM before executing it.

**Comment by creationix** [comment]
Isn't there a performance impact of this?  Are we still at a point where we want more free ram and less free CPU?

**Comment by marcoskirsch** [comment]
@creationix I would say yes.

**Comment by aguaviva** [comment]
it should be configurable so everyone can choose what they want, no need to make compromises.

Also the whole sdk uses that keyword all over the place, including the networking code

**Comment by nodemcu** [comment]
@aguaviva 
we made some modification to the stock sdk from espressif,
put every function .text into ROM, even if there is no "ICACHE_FLASH_ATTR".
recently also .rodata into ROM, thanks to @jmattsson.
so, if you want your function in the RAM, you should add "ICACHE_RAM_ATTR" explicitly.

**Comment by aguaviva** [comment]
Excellent! Thanks for clarifying and for the great job.
