### ISSUE TITLE
Support for m2tklib

### ISSUE THREAD

**Issue by mazloumi** [nodemcu/nodemcu-firmware#593]
Hi,

would it be possible to support m2tklib? This library supports menues on top of the ug8lib library: https://code.google.com/p/m2tklib/

Thanks,
Nima

**Comment by devsaurus** [comment]
I guess it's feasible to integrate m2tklib. Also I'm not aware oft any related activity, so you could give it a try. Your contribution would be very appreciated by the community.

**Comment by devsaurus** [comment]
I'm closing this for now.
Everybody feel free to reopen in case there's WIP on this topic.
