### ISSUE TITLE
getpeer() returns junk during :on("disconnection".

### ISSUE THREAD

**Issue by jabza** [nodemcu/nodemcu-firmware#601]
Currently socket:getpeer() returns junk during disconnection, ideally this could be used to tell will client has disconnected.

c:on("disconnection",function(c)
    ip, port = c:getpeer()
    print(ip..port)
    end)

Output:
c�c��RS�f�NS�f׎�j���

**Comment by djphoenix** [comment]
Tested on latest `dev`, after `disconnection` getpeer returns `nil, nil` (as in docs).
Considering outdated -> close.
