### ISSUE TITLE
ds18b20.lua | Handling difference between DS18S20 and DS18B20

### ISSUE THREAD

**Issue by windows97** [nodemcu/nodemcu-firmware#610]
Looks like DS18B20 only works proper with ds18b20 (having FAMILY CODE == 0x28).
DS18**B**20  (FAMILY CODE == 0x28) has a 12bit resolution w/ 2^(-4) lsb = 0,0625 which is correclty applied.
![2015-08-21 19_35_04-](https://cloud.githubusercontent.com/assets/3279299/9414846/c6345702-483b-11e5-9018-35e85d5364cb.png)
*derived from http://datasheets.maximintegrated.com/en/ds/DS18B20.pdf*

DS18**S**20 (FAMILY CODE == 0x10) has a 9bit resolution w/ 2^(-1) lsb = 0,5 which is not handled correctly.
![2015-08-21 19_34_34-](https://cloud.githubusercontent.com/assets/3279299/9414847/c634cc50-483b-11e5-94d8-6791c721ec8c.png)
*derived from http://datasheets.maximintegrated.com/en/ds/DS18S20.pdf*

This factor should be handled according to the FAMILY CODE.

**Comment by nickandrew** [comment]
I fixed the code in `lua_examples/onewire-ds18b20.lua` ... oh hang on, there's more code under `lua_modules` ...

**Comment by nickandrew** [comment]
2nd commit pushed. Does this resolve your issue?

**Comment by nickandrew** [comment]
3rd commit pushed; thanks @TerryE.
