### ISSUE TITLE
UDP destination port unreachable 

### ISSUE THREAD

**Issue by khalilifar** [nodemcu/nodemcu-firmware#616]
Hello,
It seems program has a weird bug that i can't seem to understand
I have created a udp server that listens on port 6767 to receive udp packets
it works fine for a while and receive udp packets and does what i need it to do but then after couple of days while module is still working and sending data it seems it's not able to receive anymore packets

And monitoring the network with wireshark I see that it sends destination port unreachable ICMP error.

What could be the problem ? something wrong with https://github.com/nodemcu/nodemcu-firmware/blob/master/app/include/lwip/icmp.h ?

Is there anybody else with the same problem ?

**Comment by marcelstoer** [comment]
This must have been on a very old firmware, hasn't received any comments and does not provide enough hints of a firmware bug -> closing.
