### ISSUE TITLE
running nodemcu project on Eclipse

### ISSUE THREAD

**Issue by sudry6** [nodemcu/nodemcu-firmware#617]
in my Eclipse workspace i get the following directories under nodemcu-firmware.
![nodemcu](https://cloud.githubusercontent.com/assets/13771563/9492776/68c029fe-4c03-11e5-8a60-318c0112425f.jpg)

i'm not familiar with that, but i believe that in the examples directory each .lua file represents another project. if indeed, how can i select the desired project to be compiled and run? 
are there any instructions for that?
in the Eclipse Make Target window i have the following options: all, clean, clobber, flash and luainit.
![image](https://cloud.githubusercontent.com/assets/13771563/9492963/dd6b1844-4c04-11e5-999d-bc3512f84297.png)

when i press on all and flash compilation is done successfully and also flash of the ESP8266, but how can i know which project is running? i get gibberish in the COM port which is connected to the device.
thanks
M.S.

**Comment by Aeprox** [comment]
The files in lua_examples are supposed to be run on the module, not compiled in it. As a regular user, there's no need to build your own firmware. 

Use a program like esplorer or luatool to upload these .lua examples to the modules and execute them.
