### ISSUE TITLE
running nodemcu multi-file project on ESPlorer

### ISSUE THREAD

**Issue by sudry6** [nodemcu/nodemcu-firmware#619]
i found a project i'd like to run using the ESPlorer.
the project contains 3 files: init.lua, WebServer.lua and header.htm
when i try to run it i got a message that the WebServer.lua file is not found.
how should i link between the files?
thanks
MS

**Comment by jiegec** [comment]
First you need to put these files in esp8266. Anyway, it seems that it should be asked elsewhere? Stackoverflow or ESPlorer?

**Comment by TerryE** [comment]
+1 @sudr6, this is a beginner's issue that is best addressed on an application support forum such as esp8266.com or StackOverflow.  It not within the scope for this issues list.
