### ISSUE TITLE
MQTT Client: Last Will and Testament RETAIN flag ignored

### ISSUE THREAD

**Issue by matteovigni** [nodemcu/nodemcu-firmware#641]
I noticed that even if I set the retain flag to 1 while setupping the last will and testament it is still sent with retain flag to 0.
I quickly checked the source and I think that the problem is that the last will and testament function in app/modules/mqtt.c ignores the retain parameter (and maybe the qos too). It's not very clear to me where it should be used so I can't propose a patch, but I think that it should be quite easy for someone who knows how the MQTT module works.

**Comment by karrots** [comment]
Should be fixed by pr #718 & #697. Please verify against the `dev` branch using the build service.

**Comment by devsaurus** [comment]
Confirm that the retain flag for `client:lwt()` works with current `dev`.
