### ISSUE TITLE
Unable to set DNS with wifi.ap.setip()

### ISSUE THREAD

**Issue by rubberbird** [nodemcu/nodemcu-firmware#650]
I am trying the following, but DNS is not being set. Is this possible, if not how can it be added?

> -- Set IP Address config
> ipCfg = {
>> ip="192.168.2.1",
>> netmask="255.255.255.0",
>> gateway="192.168.2.1",
>> dns="8.8.8.8"
>> }
> 
> -- Set IP to SOFtAP
> wifi.ap.setip(ipCfg)

**Comment by reischle** [comment]
I work around that issue with a local UDP/DNS proxy:
http://www.areresearch.net/2015/09/generic-udp-proxy-for-nodemcu-esp8266.html
That comes with a few downsides, so I'd also like to see that fixed.

**Comment by marcelstoer** [comment]
What makes you think you can set the nameserver in the config object? http://nodemcu.readthedocs.org/en/dev/en/modules/wifi/#wifiapsetip says you can't.
