### ISSUE TITLE
wifi.startsmart() causes hard reset

### ISSUE THREAD

**Issue by rubberbird** [nodemcu/nodemcu-firmware#653]
I have the below firmware

NodeMCU custom build by frightanic.com
	branch: master
	commit: bb9dd62882b89d40f5d0df2c009c972f64b7f965
	SSL: false
	modules: node,file,gpio,wifi,net,tmr,uart
 	built on: 2015-09-15 06:56
  powered by Lua 5.1.4

Using the ESP App v2.1

When my login details are found, the device hard resets. 

Error from debug mode:

Fatal exception (9):
epc1=0x4022b9e9, epc2=0x00000000, epc3=0x00000000, excvaddr=0x015e0035, depc=0x00000000

**Comment by marcelstoer** [comment]
Feel free to re-open if you're still seeing this with the latest `dev` branch. Note that smartconfig is now turned OFF by default.

**Comment by Anudeep09** [comment]
How to enable samartconfig in firwware ..? i am using bin files to flash fimware

**Comment by marcelstoer** [comment]
See http://nodemcu.readthedocs.io/en/dev/en/support/ and http://nodemcu.readthedocs.io/en/dev/en/modules/wifi/#wifistartsmart.
