### ISSUE TITLE
SPI Flash > 512k

### ISSUE THREAD

**Issue by 3s1d** [nodemcu/nodemcu-firmware#66]
Hi Folks,
everything works great, except  the correct flash size. I've got an Olimex Dev Board lying around. 
(see https://www.olimex.com/Products/Modules/Ethernet/MOD-WIFI-ESP8266-DEV/open-source-hardware#) It's got an W25Q16BVSSIG (2MB) Flash onboard. 
Everything works using:  '''#define FLASH_512K'''
However, as I change the define in user_config.h from 512k to 2MB the following error ouccurs and the firmware is not usable:

ERROR in flash_read: r=1 at 40280000
ERROR in flash_read: r=1 at 40281000
ERROR in flash_read: r=1 at 40282000
ERROR in flash_read: r=1 at 40283000
ERROR in flash_read: r=1 at 40284000
ERROR in flash_read: r=1 at 40285000
ERROR in flash_read: r=1 at 40286000
ERROR in flash_read: r=1 at 40287000
[...]

Nice Work!
Juergen

**Comment by alinleonard** [comment]
I have the same module .
Can you trow me in the right direction how to change the SPI flash size ? 
I know how to change it in nodemcu-flasher , how about the firmware?

**Comment by nodemcu** [comment]
it is auto

**Comment by alinleonard** [comment]
ok good to know. That makes things much easier

**Comment by TheCDB** [comment]
I have the same problem, but with Ai thinker development board. But much weirder.

I'm able to use Nodemcu programmer (esp8266flasher) and I can write at firmware and iot.bin without a problem. I can write nodemcu with the instruction INTERNAL://NODEMCU. This all works. But when I try to write a file image of nodemcu, It writes without any errors, but the esp 12 will start up with the Error in flash_read sequence.  Don't have a clue how to solve this. Seems some flash has to be blanked ?? Error goes away after flashing at firmware.

![image](https://cloud.githubusercontent.com/assets/12904156/8174081/3e02aa06-13d8-11e5-977e-60760f284dbd.png)

This is the board I use. Any help would be greatly appreciated.
