### ISSUE TITLE
Net module doesn't work in specific build

### ISSUE THREAD

**Issue by zdrc** [nodemcu/nodemcu-firmware#663]
My build was node, file, tmr, wifi, net, and cjson from master through frightanic. It seems the net module doesn't work in that build. I've rebuilt the same build a few times and they all don't work. I can't pinpoint exactly what's going on but the problems seems to occur with the sk:on(...) function.

edit: it actually now seems that SSL doesn't work, and that is what's causing the problem. It seems like the connection just hangs. If create a socket with SSL not enabled than it gives me a response (can't post because unauthorized)

**Comment by marcelstoer** [comment]
https://github.com/nodemcu/nodemcu-firmware/issues?q=is%3Aissue+is%3Aopen+ssl -> Pretty sure this is a dup of #520.

**Comment by TerryE** [comment]
+1
