### ISSUE TITLE
nodemcu一连上air_kiss版smartConfig就重启。求帮助。

### ISSUE THREAD

**Issue by i319962** [nodemcu/nodemcu-firmware#668]
dev的固件 nodemcu_float_0.9.6-dev_20150704.bin
nodemcu一连上smartwifi就重启。~~有人见过么，代码如下

```Lua
wifi.setmode(wifi.STATION)
wifi.startsmart(1, function() print("smart config success!") end)
```

已经换过N块芯片，都存在这个问题，初步排查是固件的问题，求解决。
PS:腾讯官网也已经放出8266air_kiss的包，不知道是否有用，仅供参考。

**Rough  Translation (Google translate)**
dev firmware: nodemcu_float_0.9.6-dev_20150704.bin
nodemcu connected by smartwifi reboot on restart. People have seen this \<code\>
The chips have been replaced. and there is still this problem. Our preliminary investigation is that this a firmware problem.  We are seeking solutions.
The Espressif official website has also been released the 8266 air_kiss bugfix, I do not know whether it is useful. For information purposes only.

**Comment by marcelstoer** [comment]
With the original Chinese contributors leaving this project I'm afraid your issue won't be addressed unless you describe it in English.

**Comment by rxf992** [comment]
建议你直接用esp的sdk c 代码方式开发。

在 2015-09-25 10:58:03，"i319962" <notifications@github.com> 写道：


dev的固件 nodemcu_float_0.9.6-dev_20150704.bin
nodemcu一连上smartwifi就重启。~~有人见过么，代码如下

wifi.setmode(wifi.STATION)
wifi.startsmart(1, function() print("smart config success!") end)

已经换过N块芯片，都存在这个问题，初步排查是固件的问题，求解决。

PS:腾讯官网也已经放出8266air_kiss的包，不知道是否有用，仅供参考。

**Comment by TerryE** [comment]
This won't work with the 0.96 firmware are currently working on a SDK 1.3 (poss 1.4 update) which should fix this.  We won't fix SDK bug in this build.  So closing this call
