### ISSUE TITLE
Which ESP module supports the extra GPIOs as per new gpio map?

### ISSUE THREAD

**Issue by ashubhatt** [nodemcu/nodemcu-firmware#669]
According to new gpio map: Extra gpios like GPIO 3, GPIO 1, GPIO 9 and GPIO 10 are shown.

Which esp8266 module supports this GPIOs?

Further, can the tx,rx pins be utilized as normal GPIOs?

**Comment by TerryE** [comment]
@ashubhatt, this is really a topic for one of the support forums such as esp8266.com.  This list is for issues specifically relating to the nodemcu firmware.

**Comment by ashubhatt** [comment]
Oh.. My bad.
Will be careful next time.

**Comment by TerryE** [comment]
No, not your bad. Just the wrong place to ask *this* Q :smile:
