### ISSUE TITLE
Document sntp module

### ISSUE THREAD

**Issue by karrots** [nodemcu/nodemcu-firmware#671]
```sntp``` module not documented in wiki.

Syntax to my untrained eyes looks to be:
```sntp.sync(server, sucesscallback(unixtimestamp), errorcallback(string))```

**Comment by jmattsson** [comment]
I documented it [in our local repo's wiki](https://github.com/DiUS/nodemcu-firmware/wiki/sntp-module-documentation) before it all got merged into NodeMCU. If you have the time, could you copy it over to the dev096 NodeMCU wiki page? Same goes for the RTC modules. Thanks!

**Comment by karrots** [comment]
One note about the documentation mentioned. It looks like the word anycast is used where multicast should be used.

**Comment by jmattsson** [comment]
@karrots That is fully intentional (see [RFC 2030](https://www.ietf.org/rfc/rfc2030.txt) for details). Anycast != multicast.

**Comment by karrots** [comment]
ok I see multicast server discovery instead of the multicast service delivery I was thinking. Gets a bit confusing when there are two ways to use multicast.
