### ISSUE TITLE
onewire power problems - bus left in bad state

### ISSUE THREAD

**Issue by nickandrew** [nodemcu/nodemcu-firmware#676]
I'm working on a pull request to fix this.

The onewire_write() call with power set to 0 changes the pin mode to OUTPUT and a low voltage. This is bad because the bus should normally be high, and low is used to signal the start of a transaction.

Examples:

```c
void onewire_skip(uint8_t pin)
{
    onewire_write(pin, 0xCC, 0);           // Skip ROM
}
```

Looking at the code for onewire_write() ...

```c
  if ( !power) {
    noInterrupts();
    DIRECT_MODE_INPUT(pin);
    DIRECT_WRITE_LOW(pin);
    interrupts();
  }
```

There seems to be a problem here. DIRECT_MODE_INPUT is defined as `GPIO_DIS_OUTPUT(pin_num[pin])` which disables output for the pin. But DIRECT_WRITE_LOW calls GPIO_OUTPUT_SET which re-enables output!

Here's my plan to fix. In the code blocks which test `power`:

```diff
   if (!power) {
     noInterrupts();
-    DIRECT_MODE_INPUT(pin);
-    DIRECT_WRITE_LOW(pin);
+       platform_gpio_mode(pin, PLATFORM_GPIO_INPUT, PLATFORM_GPIO_FLOAT);
     interrupts();
   }
```

Which I think was what was intended. The onewire_write() calls with power set to 0 in the firmware should change to 1. If you really need no power, call them yourself. There's also onewire_depower() which I assume is intended to remove all power from the bus. This won't work if there's a recommended weak pullup resistor on the bus.

Attached is my logic analyser trace of the problem. 1wire is the 1-wire bus. Channel-4 is used to trigger the trace, and distinguish the test phases.

Phase 1: bus reset until about 800 us.

Phase 2: ow.write(pin, 0xcc, 1) leaving bus high at about the 1.9 ms mark

Phase 3: ow.write(pin, 0xcc, 0) leaving the bus low. All 1-wire devices on the bus will reset which is not good, because 0xcc is supposed to leave all devices selected.

Here's the test script I used:

```lua
function owtest2()
    pin = 1
    ow.setup(pin)
    tmr.delay(50000)
    gpio.mode(4, gpio.OUTPUT)
    gpio.write(4, gpio.LOW)
    ow.reset(pin)
    ow.write(pin, 0xcc, 1)
    gpio.write(4, gpio.HIGH)
    ow.write(pin, 0xcc, 0)
    gpio.write(4, gpio.LOW)
    gpio.write(4, gpio.HIGH)
end
```
![d1-input-mode-tests](https://cloud.githubusercontent.com/assets/7175/10266688/3adc664c-6abc-11e5-8412-36279a4180c6.png)

### DS18B20 and parasitic power

DS18B20 (and other) devices on the 1-wire bus can be powered by 3.3v or rely on parasitic power from the bus, or both. If there are any parasitic power devices on the bus, a strong pullup is needed on the bus during temperature conversions. This is often the microcontroller itself, but that fails when more than a few devices are connected to the bus.

The ESP8266 can source a maximum 12mA on each pin. The DS18B20 draws a maximum 1.5mA, which means an absolute maximum of 8 parasitic devices on the bus - but in practice the maximum will be smaller, as the voltage drop on the bus would be unacceptably low. Maxim recommends using a MOSFET attached to another output to provide power to the bus during temperature conversions.

The current onewire.c driver doesn't support a 2nd output for mosfet. But due to the timing constraints of the strong pullup (it must be enabled within 10 uS of starting a conversion) I think the driver should be changed in future to have this as an option.

**Comment by TerryE** [comment]
Fix merged.
