### ISSUE TITLE
mqtt LWT qos and retain parameters are parsed incorrectly

### ISSUE THREAD

**Issue by NPohl** [nodemcu/nodemcu-firmware#679]
When using the flowing command, the will message doesn't have it's retain flag set (even though it should be...)
```lua
m:lwt("topic", "message", 0, 1)
```
By looking into the code, it looks like the parameters aren't parsed correctly by the mqtt_socket_lwt function (in app/modules/mqtt.c). There is missing a `stack++;`somewhere before the following lines
```c
  if ( lua_isnumber(L, stack) )
  {
    mud->connect_info.will_qos = lua_tointeger(L, stack);
    stack++;
  }
  if ( lua_isnumber(L, stack) )
  {
    mud->connect_info.will_retain = lua_tointeger(L, stack);
    stack++;
  }
```
Thus the second parameter will be used as message **and** qos parameter...

I checked this by changing the line to the following, and it works (but the last will message is "0" then)
```lua
m:lwt("topic", 0, 1)
```
Please fix this!

Thanks

**Comment by karrots** [comment]
This can be closed.
