### ISSUE TITLE
ip routing in stationap mode

### ISSUE THREAD

**Issue by krachlatte** [nodemcu/nodemcu-firmware#683]
Hi, 

I recompiled the firmware with ip forwarding enabled in lwipop.h.

anyone willing to fix or enhance the firmware?

There is no option to add static routes

i have a test setup where it is possible to route across the stationap but the client cannot send trafik back

wifi.station 192.168.8.139<-> esp8266<-> wifi.ap 192.168.11.1 client 192.168.11.3

it is possible to pong from 192.168.8.0 Network to 192.168.11.1 but not from client 192.168.11.3 for 

example. It looks like that the Packets are not properly forwarded, from the lient i can reach 192.168.11.1 and 192.168.8.139, but not 192.168.8.1 for example, .139 an .11.1 is the esp8266 itself

It looks like it is because you cannot have two default gateways on one device. we would need to be able to add routs to the routing table, is this even possible

Many thanks

**Comment by richrd** [comment]
Big :+1: for this.

**Comment by devyte** [comment]
@krachlatte There are 2 places in the firmware where the relevant #define IP_FORWARD 1 has to be enabled. If memory serves:
app/include/lwipopts.h and
app/include/lwip/opt.h
Did you enable in both?

**Comment by devyte** [comment]
Ok, I managed to get this to work without routing on the ESP, see #104 .
