### ISSUE TITLE
how to use html templating engine (question)

### ISSUE THREAD

**Issue by lwrbakro** [nodemcu/nodemcu-firmware#685]
Is it possible to compile the firmware with this templating engine?
https://github.com/bungle/lua-resty-template

**Comment by rickvanbodegraven** [comment]
I highly doubt you'd want to do something like this on a platform like the
nodemcu. Wouldn't recommend doing it.

2015-10-09 10:26 GMT+02:00 lwrbakro <notifications@github.com>:

**Comment by TerryE** [comment]
+1.  NodeMCU does not support the standard `io` library, so you'd need to convert this to the `file` library, but apart from this the code should compile with `luac.cross` however, I'd doubt that you will have enough RAM to run a templated application.  You'll have to wait for the next generation of ESP chip at least.
