### ISSUE TITLE
Reset to default settings

### ISSUE THREAD

**Issue by zeuszxzx** [nodemcu/nodemcu-firmware#69]
Add the possibility to revert to the default settings (Delete all files and settings).
For example GPIO2 MUST LOW at the start.

**Comment by vowstar** [comment]
GPIO2 MUST keep HIGH at start. But we plan to do it in other ways, such as user key, lua function, etc. .
![SCH](https://raw.githubusercontent.com/nodemcu/nodemcu-devkit/master/Documents/NODEMCU_DEVKIT_SCH.png)

**Comment by zeuszxzx** [comment]
Do this by hardware. Not function.
There were times when performing hovering  INIT.LUA

**Comment by vowstar** [comment]
Hi,
We will consider detect some pin at start before run INIT.LUA, Such as GPIO4 ,GPIO16 or other pins. Imagine some pin keep in LOW level for more than 5 seconds, revert to the default settings and format the file system.

**Comment by TerryE** [comment]
I think that this falls into the dead / won't fix category.
