### ISSUE TITLE
DS18b20 lib to be used with DS18s20/1820

### ISSUE THREAD

**Issue by nekhbet** [nodemcu/nodemcu-firmware#712]
Is it possible to use the same lib to read the temperature from DS18S20/1820 ? The readings are pretty way off with the current library.

**Comment by marcelstoer** [comment]
This issue list is not a support forum but reserved for firmware bugs. There are a couple of Lua scripts out there for the DS1820 family e.g. https://github.com/ok1cdj/ESP8266-LUA/blob/master/Thermometer-DS18B20-Thingspeak/ds1820.lua and right in this repository https://github.com/nodemcu/nodemcu-firmware/tree/master/lua_modules/ds18b20.
