### ISSUE TITLE
Unable to send multicast UDP packets

### ISSUE THREAD

**Issue by xhs** [nodemcu/nodemcu-firmware#715]
I'm trying to implement mDNS in Lua.

With the information I got from [Issue 398](https://github.com/nodemcu/nodemcu-firmware/issues/398) and [nodemcu-ssdp](https://github.com/pastukhov/nodemcu-ssdp), I can now receive and parse mDNS queries successfully. But I am unable to send response to the multicast address (224.0.0.251).

Here's the testing code:
```lua
wifi.setmode(wifi.STATION)
wifi.sta.config('ssid', 'password')
ip = wifi.sta.getip()
print(ip)
net.multicastJoin(ip, '224.0.0.251')
sock = net.createConnection(net.UDP, 0)
sock:connect(5353, '224.0.0.251')
sock:send('test broadcast', function() print('Sent') end)
```

I can see "Sent" printed but get nothing in Wireshark.

Tested on master branch and dev branch.

Is there anything I should do before sending multicast packets?
Or does NodeMCU support this at all?

**Comment by pastukhov** [comment]
I will test tomorow

**Comment by nanikjava** [comment]
I've tested this on my ESP12E DevKit 1.0 with the following firmware

NodeMCU 0.9.6 build 20150704  powered by Lua 5.1.4

and I can't see it in Wireshark too. When I use Linux machine to multicast using the command

iperf -c 224.0.0.251 -u -T 32 -t 3 -i 1

I can see it in Wireshark.

Is this a bug ?

**Comment by pastukhov** [comment]
Try with more fresh FW.

**Comment by pastukhov** [comment]
1.4 version is actual now.

**Comment by 3dot3** [comment]
This is highly related to issue #596:https://github.com/nodemcu/nodemcu-firmware/issues/596
Smartconfig only doing half of the job because of this issue.

**Comment by nanikjava** [comment]
@pastukhov not sure I understand what you mean "Try with more fresh FW" as I flashed the latest file from https://github.com/nodemcu/nodemcu-firmware/releases https://github.com/nodemcu/nodemcu-firmware/releases/tag/0.9.6-dev_20150704

**Comment by karrots** [comment]
Those releases are old and outdated. Test a fresh 'dev' branch build from http://frightanic.com/nodemcu-custom-build/

**Comment by klokik** [comment]
Fresh build, same bug

**Comment by 3dot3** [comment]
hope sdk1.5 upgrade will solve this.

**Comment by nickandrew** [comment]
Once again, the "releases" are leading people astray.

**Comment by marcelstoer** [comment]
@klokik You did use the `dev` branch rather than `master`, right?

**Comment by klokik** [comment]
Right. I used a mentioned earlier service.

**Comment by marcelstoer** [comment]
> I'm trying to implement mDNS in Lua.

We've had an [mDNS module](http://nodemcu.readthedocs.org/en/dev/en/modules/mdns/) in the `dev` branch for a while now -> closing.
