### ISSUE TITLE
Different results computing hmac in different platforms

### ISSUE THREAD

**Issue by drio** [nodemcu/nodemcu-firmware#723]
Hi all, 

I'm having problems matching the results of computing the hmac on the same
string/key between nodemcu and another platform (python 2.7). I was wondering
if anyone else has run into this and may want to help me out. Details here:

From nodemcu:

`Lua 5.1.4 on SDK 1.4.0`

```lua
print(crypto.toHex(crypto.toBase64("md5", "message", "secret")))
62575131
```

From Python (Python 2.7.10). The version here is important as strings in python2 
are just bytes.

```python
import hashlib
import hmac
import base64

message   = "message"
secret    = "secret"
# Note: defaults to md5
signature = base64.b64encode(hmac.new(secret, message).digest())
signature2 = hmac.new(secret, message).hexdigest()
print message, secret, signature, signature2
```

output:
```
message secret fg0HZ3dTEhVLoW/Tr5dxog== 7e0d0767775312154ba16fd3af9771a2
```

My idea is to sign all the requests coming from my esp8266 so they can be verified at the other end.

**Comment by jmattsson** [comment]
Your issue is that you're not actually using crypto.hmac() in your command.
``> print(crypto.toHex(crypto.hmac("md5", "message", "secret")))``
``7e0d0767775312154ba16fd3af9771a2``
``> print(crypto.toBase64(crypto.hmac("md5", "message", "secret")))``
``fg0HZ3dTEhVLoW/Tr5dxog==``

**Comment by drio** [comment]
:sweat:  Thank you @jmattsson
