### ISSUE TITLE
OMA Lightweight M2M

### ISSUE THREAD

**Issue by 4refr0nt** [nodemcu/nodemcu-firmware#74]
Enabling support <a href="http://fr.slideshare.net/zdshelby/oma-lightweightm2-mtutorial">LWM2M</a> communcation protocol in NodeMCU firmware by using <a href="https://github.com/sbernard31/lualwm2m ">lualwm2m</a> (lualwm2m is a Lua binding for client side <a href="https://github.com/eclipse/wakaama">liblwm2m/wakaama library</a>)
Server side: <a href="https://github.com/jvermillard/leshan">Leshan</a> is a OMA Lightweight M2M server and client implementation

I can implements leshan server-side part of software (partial, only ESP8266 specific values) into <a href="https://github.com/4refr0nt/ESPlorer">ESPlorer</a> for fast and easy developing IoT applications based on ESP8266+NodeMCU+Lua

![image](https://cloud.githubusercontent.com/assets/550871/5609700/7623b766-94c8-11e4-8eaf-4413d663ecb4.png)

**Comment by nodemcu** [comment]
I've google-ed some lwm2m, but still don't know how to get to the module behind NAT from internet.
lwm2m based on coap which is UDP.
do you have some more info of lwm2m, and compare to mqtt. pros&cons

**Comment by 4refr0nt** [comment]
So you planing use mqtt as default and only one M2M protocol in NodeMCU?

**Comment by nodemcu** [comment]
not decided yet. maybe use MACRO to control? 
put coap,mqtt and net module together is not a good idea I think. eats up every bits of ram.
or maybe NodeMCU-COAP, NodeMCU-MQTT?

**Comment by 4refr0nt** [comment]
We needed simple way for control other device connected to ESP8266 GPIO, send telemetry data from sensor without lot of lua code. We needed M2M protocol integrated into NodeMCU firmware NOW. It may be mqtt or any other. May be new NodeMCU protocol... Long-time-developing will be killing NodeMCU.
P.S. See https://github.com/tuanpmt/esp_mqtt

**Comment by nodemcu** [comment]
for the COAP support.
please checkout https://github.com/nodemcu/nodemcu-firmware/tree/coap
you have to build the bin from code.

**Comment by nodemcu** [comment]
now coap module is merged to master.

**Comment by mjkoster** [comment]
"I've google-ed some lwm2m, but still don't know how to get to the module behind NAT from internet.
lwm2m based on coap which is UDP."

You can keep a UPD return tunnel open to a LWM2M device by sending a LWM2M registration update from the device to the server frequently enough to prevent the NAT from timing out (usually 60 seconds).

So set up the LWM2M registration update to occur every 30 seconds and the LWM2M server should be able to reach the device behind the firewall.

Cheers,

Michael

**Comment by TingChinLin** [comment]
I have already  bind "https://github.com/sbernard31/lualwm2m" in nodemcu.
Where should i update my nodemcu firmware for lwm2m?
