### ISSUE TITLE
wrong mac address

### ISSUE THREAD

**Issue by dwery** [nodemcu/nodemcu-firmware#749]
```wifi.ap.getmac()``` reports the mac as ```1a:xx:xx:...``` while it's actually ```18:xx:xx:...``` on the network 

dev branch @ d8c6fe0b25142f6ae866c18c3bcb3d0538d4baaf

**Comment by dnc40085** [comment]
The MAC address for the AP interface starts with `1a:xx:xx...` and the MAC address for the STATION interface starts with `18:xx:xx...`
if you use the command `print(wifi.sta.getmac())` it should print the MAC address that you are seeing on your network.

**Comment by dwery** [comment]
thank you!
