### ISSUE TITLE
Compile nodemcu-firmware on Eclipse Kepler in Windows

### ISSUE THREAD

**Issue by davctv** [nodemcu/nodemcu-firmware#759]
Hello everybody,

I'm trying to compile the nodemcu firmware on windows. I downloaded the source code here
(https://github.com/nodemcu/nodemcu-firmware) and imported in eclipse kepler.
When I press the CLEAN button in Make Target it give me:

10:16:22 **** Build of configuration Default for project nodemcu-firmware ****
make clean
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=[C:\eclipse-cpp-kepler-SR2-win32\eclipse;C:/Program Files/Java/jre1.8.0_40/bin/client;C:/Program Files/Java/jre1.8.0_40/bin;C:/Program Files/Java/jre1.8.0_40/lib/i386;C:\Program Files\PC Connectivity Solution\;C:\Program Files\STMicroelectronics\st_toolset\asm;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\ARM\ADSv1_2\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Intel\DMIX;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Common Files\Roxio Shared\DLLShared\;C:\Program Files\Common Files\Roxio Shared\9.0\DLLShared\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microchip\MPLAB C30\bin;C:\Program Files\LibreOffice 3\program;C:\Program Files\Skype\Phone\;C:\Program Files\COSMIC\CXSTM8_EVAL;C:\Program Files\COSMIC\CXSTM8_32K;C:\Program Files\LibreOffice 3\program;C:\Program Files\CodeSourcery\Sourcery_CodeBench_Lite_ARM_EABI\bin;C:\Espressif\xtensa-lx106-elf\bin;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Python27]

10:16:22 Build Finished (took 43ms)

I have searched on the web but I didn't find a guide or a method to compile under windows and eclipse the nodemcu firmware..

What are the program/compiler needed to get everything work?
SDK espressif
MinGW
Python27
PyhtonSerial

Do you have a link or something which can help me?

Thanks
Davide

**Comment by marcelstoer** [comment]
See #719.
