### ISSUE TITLE
Bridge Access Point and Station network.

### ISSUE THREAD

**Issue by vvikas** [nodemcu/nodemcu-firmware#763]
I am using STA to connect to WiFi and AP to create a new WiFi connection.
I want to amplify my original WiFi signal by using STA network via AP network,
but there seems to be no way to bridge these two interfaces.

**Comment by vvikas** [comment]
@nodemcu

**Comment by dnc40085** [comment]
Are you trying to use an ESP8266 as a wifi repeater/range extender?

**Comment by vvikas** [comment]
Thanks, will try it.

**Comment by evgi9** [comment]
@vvikas  Any news on this issue?

**Comment by dnc40085** [comment]
@vvikas Did it work?

**Comment by vvikas** [comment]
I tried it. It worked but only for a small duration then it just disconnects from the Station Network. Nothing conclusive but maybe the device power needs to be increased.

**Comment by davemaster** [comment]
Try sending a periodic data to the ES8266. This will keep connection alive.
