### ISSUE TITLE
Change regex in the getap doc

### ISSUE THREAD

**Issue by bixente57** [nodemcu/nodemcu-firmware#766]
In wifi.sta.getap() example, there is this code to get ap's infos:
``local ssid, rssi, authmode, channel = string.match(v, "([^,]+),([^,]+),([^,]+),([^,]+)")``

When you call getap() with show_hidden=1, this regex will match nothing.

I recommand using * intead of +:
``local ssid, rssi, authmode, channel = string.match(v, "([^,]*),([^,]*),([^,]*),([^,]*)")``

Note: new to GitHub, not sure this is the place to enhance the doc.

**Comment by jmattsson** [comment]
@marcelstoer This sounds like something for your TODO list :)

**Comment by marcelstoer** [comment]
Done. See https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_en#wifistagetap
