### ISSUE TITLE
two get_configs in wifi sta

### ISSUE THREAD

**Issue by darkskiez** [nodemcu/nodemcu-firmware#773]
when get_config was added to ap it was added into the sta table..

This crashes the device:
for key,value in pairs(wifi.sta) do print("found member " .. key);end

**Comment by darkskiez** [comment]
NodeMCU 0.9.6 build 20150704  powered by Lua 5.1.4

**Comment by jmattsson** [comment]
Please see #719. This issue is fixed in the dev branch.
