### ISSUE TITLE
Total flash memory

### ISSUE THREAD

**Issue by domingosl** [nodemcu/nodemcu-firmware#783]
Running: 
```lua
l = file.list();
for k,v in pairs(l) do
  print("name:"..k..", size:"..v)
end
```
Im getting:
name:index.html, size:79
name:main.lua, size:3492
name:fooTest.lua, size:2115
name:configServer.lua, size:439

The total size of all my files is greater than the 4kB of flash storage of the ESP. What am I missing here?

**Comment by TerryE** [comment]
Sorry but this falls under #719, so I am closing this.   Please read this issue to see why.  However, the flash storage isn't 4Kb.  Not sure where you got this from.  The storage assigned to SPIFFS is the number of whole pages between the end of the firmware and the end of the flash.  The size of the firmware depends on the number of modules that you compile in, and the size of the flash can eother be 512kB, 1mB or 4mB depending on the module.
