### ISSUE TITLE
pull #777 causes problems

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#785]
With this recent PR applied `screen` does not respond to normal CR (requires ^J).
Upload with `luatool.py` (0.6.4) also fails, probably for the same reason.

Reversing the change fixes the problem.

**Comment by marcelstoer** [comment]
Dup of #784.

**Comment by devsaurus** [comment]
@eyaleb if possible, please check whether #786 improves the situation for your setup with `luatool.py`.

**Comment by eyaleb** [comment]
Tested #786 and now both screen and luatool.py work.
