### ISSUE TITLE
DHT11 temperature integer only

### ISSUE THREAD

**Issue by tgreening** [nodemcu/nodemcu-firmware#798]
I noticed that we are only getting the integer value for the temperature.  Should there be a decimal portion too?  

I am using 0.9.6 float and a 4k7 resistor too.

**Comment by nickandrew** [comment]
Change to firmware built from `dev` branch and try again. 0.9.6 isn't supported any more.

**Comment by tgreening** [comment]
I am sorry I am using 0.9.6-dev_20150704.

**Comment by nickandrew** [comment]
Ok, please upgrade your firmware (e.g. using the build service) and try again.

**Comment by marcelstoer** [comment]
> I am sorry I am using 0.9.6-dev_20150704.

Take note of #719 and build the firmware with http://nodemcu-build.com/.

**Comment by tgreening** [comment]
I built from the dev branch:
NodeMCU custom build by frightanic.com
	branch: dev
	commit: 33e41a633ec0ad9e2438877515839cf80e1e3dfc
	SSL: false
	modules: node,file,gpio,wifi,net,i2c,tmr,adc,uart,ow,bit,u8g,cjson,dht
 build 	built on: 2015-11-30 14:31
 powered by Lua 5.1.4 on SDK 1.4.0

And still have the the same issue:
status,temp,humi,temp_decimial,humi_decimial = dht.read(1)
   if( status == dht.OK ) then
     print(temp_decimial)
     print("DHT Temperature:"..temp..";".."Humidity:"..humi)
   elseif( status == dht.ERROR_CHECKSUM ) then
     print( "DHT Checksum error." );
   elseif( status == dht.ERROR_TIMEOUT ) then
     print( "DHT Time out." );
   end

temp_decimial is always nil.

**Comment by nickandrew** [comment]
@tgreening Thanks.

I looked through the dht module code and it looks okay offhand.

Are your temp and humi values reasonable?

Instead of calling `dht.read(1)`, try calling `dht.readxx(1)` and tell us the results.

**Comment by nickandrew** [comment]
Looks like app/dhtlib/dht.c could do with
  * Removal of duplicate code
  * Early check the checksum, and do it once rather than scattered through the code.

**Comment by nickandrew** [comment]
Oh, I just checked the DHT11 and DHT22 datasheets. If you have a DHT11, it only has integral temperature resolution anyway.

**Comment by tgreening** [comment]
Nick,
That's interesting the datasheet I have said it was floating point precision.  I guess it was a mistake.
Sorry!
Tony 


    On Monday, November 30, 2015 9:25 PM, Nick Andrew <notifications@github.com> wrote:
 

 Oh, I just checked the DHT11 and DHT22 datasheets. If you have a DHT11, it only has integral temperature resolution anyway.—

**Comment by nickandrew** [comment]
Yeah, DHT11 is 8 bits and 1°, whereas DHT22 is 16 bits and 0.1°

Please close this issue.
