### ISSUE TITLE
bmp085 module not working

### ISSUE THREAD

**Issue by zlo2k** [nodemcu/nodemcu-firmware#80]
Try to use this module, but ES make reboot with garbage in console. I try 9.4 binary and 9.5.
ES ver. 01 v90. Try to connect on GPIO0 and GPIO2 (pins 3,4).
Thank you.

**Comment by luismanson** [comment]
not sure if i have the same problem, it just sits there doing nothing, i had this issie a few hours ago and after plugin vcc a few times it worked fine :/

**Comment by zlo2k** [comment]
I think is hardware issue, my module is died finaly. Bug not confirm now.
