### ISSUE TITLE
Incorporating a library?

### ISSUE THREAD

**Issue by Bazmundi** [nodemcu/nodemcu-firmware#807]
* I have tried putting luagravity onto my ESP-01 but it appears that I don't have enough memory.  

* The instruction from luagravity author was to rename:

https://github.com/fsantanna/luagravity/blob/master/init.lua

* as:

luagravity.lua

* I import onto the ESP-01 fine using ESPlorer.

* When I write a small program to try out the install it always comes up with:

>node.compile("luagravity.lua")
stdin:1: not enough memory

* It isn't obvious that the file would burn so much memory.  Is this the compiler choking the chip?  Am I able to compile the file to *.lc offboard and then save it onto the ESP-01?  Is it as simple as adding to the lua_modules and rebuilding?   Is it just not possible to port luagravity onto the ESP-01?

* Any help appreciated.

Cheers,
A

**Comment by marcelstoer** [comment]
See #719.
