### ISSUE TITLE
Unstable Access Point

### ISSUE THREAD

**Issue by mhddurrah** [nodemcu/nodemcu-firmware#808]
Hello,

we are using "nodemcu_integer_0.9.6-dev_20150704" build of nodemcu to create an access point to use it in our company switch module, we set up an httpserver, mqtt client.
access point doesn't run in a stable manner, my mobile keeps connecting and disconnecting.

is this a firmware issue or a hardware issue, or what configuration to set to make it work well.

**Comment by marcelstoer** [comment]
See #719 .
