### ISSUE TITLE
RFD - Add GDB debugging support

### ISSUE THREAD

**Issue by nickandrew** [nodemcu/nodemcu-firmware#819]
I'm not proposing to do this myself - at least not yet - but I'm not aware of any current or prior discussions on adding gdb support, so here's an issue to discuss it.

In the past I have found single-step debugging occasionally invaluable to diagnose problems. Embedded devices are harder to debug than programs running under a general-purpose OS, but debugging capabilities are more valuable when the cost of tweaking the firmware is many slow build-reflash-boot-observe sequences.

I looked for projects to enable ESP8266 debugging, and I found three in various stages of completeness: Project Gus openocd https://github.com/projectgus/openocd , Cesanta's work at getting GDB going: https://blog.cesanta.com/esp8266-gdb and Espressif's esp-gdbstub: https://github.com/espressif/esp-gdbstub

The latter work seems the most complete and straightforward to add to NodeMCU.

From their README:

> This stub works both under FreeRTOS as well as the OS-less SDK and is able to catch exceptions and do backtraces on them, read and write memory, forward [os_]printf statements to gdb, single-step instructions and set hardware break- and watchpoints. It connects to the host machine (which runs gdb) using the standard serial connection that's also used for programming.

The ESP8266 chip provides only a single breakpoint and watchpoint, but that's a hardware limitation. If multiple software breakpoints are to be used, the code will need to execute from iram rather than flash and I don't know how to achieve that.

**Comment by marcelstoer** [comment]
Fixed with #1506.
