### ISSUE TITLE
Add mesh support

### ISSUE THREAD

**Issue by ziotibia81** [nodemcu/nodemcu-firmware#824]
Since SDK 1.3 Espressif added mesh support.
It might be nice to have access to the API to handle this type of network.

Documentation here:
http://bbs.espressif.com/viewtopic.php?f=51&t=929

**Comment by TerryE** [comment]
Yes, I know.  Are you volunteering to develop this?  If so then we'd be interested in your PRs.

**Comment by ziotibia81** [comment]
I have not enough C skills to develop this by myself. I could help on testing phase.

**Comment by nickandrew** [comment]
@ziotibia81 See #719.

You could start by reading the spec and documenting a reasonable lua API for the SDK functions.

**Comment by nickandrew** [comment]
Closed, awaiting PR.
