### ISSUE TITLE
documentation directory ?

### ISSUE THREAD

**Issue by ghusson2** [nodemcu/nodemcu-firmware#829]
As the project is rethinking the documentation, maybe it could be the right time for reorganization ?
For example a documentation directory with :
doc
- file history (project history, hardware, persons involved)
- file readme
- file howto_begin
- file howto_contribute (pull requests proposal, donate, official hardware maybe ?, CONTRIBUTING.md)
- file official_faq (from unofficial FAQ :)
- file links (with read further, blog tutorials and examples, ...)
- dir examples (merge/reorganize example and lua_examples and lua_modules ?)
- dir tutorial (maybe one day populated ?)

**Comment by marcelstoer** [comment]
Will be part of #774 .

**Comment by ghusson2** [comment]
Ok, i thought RTD was just in code markdown but it is a doc building system. I should move my comment to issue #774 and delete this issue #829 ?

**Comment by marcelstoer** [comment]
You can leave it here. We can't fix all at once anyway and will work in small steps.

**Comment by marcelstoer** [comment]
See https://github.com/nodemcu/nodemcu-firmware/tree/dev/docs and http://nodemcu.readthedocs.org/en/dev/.
