### ISSUE TITLE
BIG THANK

### ISSUE THREAD

**Issue by ghusson2** [nodemcu/nodemcu-firmware#830]
After an explanation of project status and continuation, see issue #719, and since nobody is full time paid for NodeMCU and since NodeMCU is provided for free (MIT license), I wanted to say a **BIG THANK to all the people involved in this project**. NodeMCU is for me the best solution for DIYers around ESP8266. The killing feature is the remote telnet for uploading lua scripts ! For me NodeMCU is putting what is Arduino to the next step. I propose for end users like me : **show your thankfulness** here for the guys that are doing a good work for (no) nuts ! **Just say a small thank**, they will love it.

**Comment by nodemcu** [comment]
Thanks @ghusson2, but it's still not an issue:), so I close this.
