### ISSUE TITLE
tsl2561

### ISSUE THREAD

**Issue by michelcourbon** [nodemcu/nodemcu-firmware#831]
in module tsl2561 / dev branch :  the chip address isn't 0x29 ?? result is : stack error not enough memory and  shutdown the nodemcu
work fine for me at 0x39 !! and adafruit tsl2561 board.. proposition : add security with the detection function in init .. for example

function find_dev(i2c_id, dev_addr)
     i2c.start(i2c_id)
     c=i2c.address(i2c_id, dev_addr ,i2c.TRANSMITTER)
     i2c.stop(i2c_id)
     return c
end

**Comment by TerryE** [comment]
I am not sure what the purpose of this post is.  But whatever, it seems to fall within the scope of #719, so I am closing this issue.
