### ISSUE TITLE
Fix the NodeMCU Wikipedia article

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#832]
https://en.wikipedia.org/wiki/NodeMCU contains 

> NOTICE: Active development is suspended that is KAPUT!

and is generally of low quality IMHO.

Can I ask one of the English native speakers like @TerryE, @jmattsson or @nickandrew to overhaul that article?

**Comment by TerryE** [comment]
I've fixed the inaccuracies. See its [history](https://en.wikipedia.org/w/index.php?title=NodeMCU&action=history)

**Comment by TerryE** [comment]
I am now tracking this article wearing my Wikipedian hat.  We should really keep this open as a general tracker as doing so sort of breaks Wikipedia's rules.
