### ISSUE TITLE
One Wire DS2408 set state problem

### ISSUE THREAD

**Issue by MarcoH2013** [nodemcu/nodemcu-firmware#834]
Hello community,

today I tried to work with a DS2408 and NodeMCU.
https://datasheets.maximintegrated.com/en/ds/DS2408.pdf
I used https://github.com/queezythegreat/arduino-ds2408/blob/master/DS2408/DS2408.cpp as example.

```Lua
local pin = 3
local addr = '29-example'
local DS2408_CHANNEL_WRITE_CMD   = 0x5A

function set_state(state)
    ow.setup(pin)

    if (ow.reset(pin) == 1) then
        ow.select(pin, addr)
        ow.write(pin, DS2408_CHANNEL_WRITE_CMD, 1)
        ow.write(pin, state, 1)
        ow.write(pin, bit.bnot(state), 1)

        if (ow.read(pin) == 0xAA) then
            if (ow.read(pin) == state) then
                return true
            end
        end
    else
        return false
    end
end

print(set_state(0x02))
```

Setting the state works ok. After it is set, One Wire sends a 0xAA to confirm (Works) and the next byte is the state what the IOs currently have.
As you can see I compare the 2nd byte with the original state in my code.
I always get 0x0 as 2nd byte what is wrong...

Anyone any idea what is going on?

Kind regards,
Marco

**Comment by TerryE** [comment]
Marco, You've really come to the wrong place to get this type of support.  Please read #719 to understand why.  Your best bet is a developer support forum such as SO or esp8266.com.  But make sure that you are using the latest dev or master build with just the modules that you need.  The referenced issue explains how to do this.
