### ISSUE TITLE
SSL securing and certificate verification

### ISSUE THREAD

**Issue by kyberpunk** [nodemcu/nodemcu-firmware#837]
Hello

Is there any way to verify server certificate thumbprint in NodeMCU? If not, please implement it. The SSL securing is not complete without this functionality. The new SDK should support it.

The ESP should have the ability to securely send data to cloud (for example Azure IoT Hub, I have already implemented secured MQTT connection and it works, but without certificate verification).

Thank you

**Comment by pjsg** [comment]
Please see the new ticket #1090

**Comment by TerryE** [comment]
Coding this as the issue is being tracked more fully at #1090.
