### ISSUE TITLE
 tmr 1000 does not exist

### ISSUE THREAD

**Issue by clienthax** [nodemcu/nodemcu-firmware#84]
when running the telnet.lua example

====Wicon, a LUA console over wifi.==========
Author: openthings@163.com. copyright&GPL V2.
Last modified 2014-11-19. V0.2
Wicon Server starting ......
telnetorig.lua:34: tmr 1000 does not exist
>

**Comment by pipi61** [comment]
Hi!
tmr.alarm, tmr.stop has new paramater: ID
check wiki:
https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_en#tmralarm

**Comment by clienthax** [comment]
Thanks!

**Comment by clienthax** [comment]
@nodemcu it may be worth updating the examples for this as well as they still use the old function.
