### ISSUE TITLE
Add crypto.fromBase64()

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#844]
As it says on the tin.

**Comment by xvh** [comment]
It would be nice if you add also crypto.fromBase64. Now I must use base64.dec() function from base64 module in lua modules.

**Comment by TerryE** [comment]
Oops got my to and from mixed up.  The to already exists.

**Comment by TerryE** [comment]
OK. I've got this working.  I'll push it once we've moved `dev` up to SDK 1.5.

**Comment by devyte** [comment]
Hi, I'm wondering whether this will get added soon? I know that stability is the current priority, but this would help with a few things on the lua side.

**Comment by TerryE** [comment]
I've got the patch working locally but the consensus was to split out the conversion routines into  separate lib.  Need to finish the GPIO stuff first :sweat:

**Comment by TerryE** [comment]
PR #1072

**Comment by marcoskirsch** [comment]
This never made it into the firmware?

**Comment by TerryE** [comment]
As far as I recall, it did.

**Comment by marcelstoer** [comment]
#1072 introduced a new module `encoder` which contains this. See http://nodemcu.readthedocs.io/en/latest/en/modules/encoder/#encoderfrombase64
