### ISSUE TITLE
Is the COAP message ID supposed to be seeded or not?

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#847]
I've just been going through the modules and noticed that the COAP initialisation invokes the following:

```C
void coap_setup(void)
{
    message_id = (unsigned short)rand();      // calculate only once
}
```
without first doing an `srand(system_get_time())` or whatever.  Is this deliberate?

**Comment by TerryE** [comment]
The truth of the matter is that COAP is moribund through lack of a maintainer.  All of the COAP bugs are really just a fact of this.  My recommendation is that unless we can find someone who is willing to step up here, we should move this formally to a `ǹot supported` folder and withdraw it as an option for 1.5 if and until we can find a volunteer to sort this.  We can also close all coap issues.. Anyone picking this up can search the closed issues and reopen any that are felt to be worth tracking.

**Comment by jmattsson** [comment]
A quick change from `rand()` to `os_random()` would fix this particular issue. Assuming that rand isn't already going through to os_random (which is a hardware (p?)rng) - I haven't checked.

**Comment by TerryE** [comment]
Yup but there are other open issues pending for months and one is to the effect that COAP as implemented is unusable.  As I said IMO its moribund and I don't have the bandwidth to fix it, do you?

**Comment by marcelstoer** [comment]
A fix for one-of-several issues is still better than none at all I'd argue -> #1401.
