### ISSUE TITLE
please add support for 250000 baud

### ISSUE THREAD

**Issue by firefox0815** [nodemcu/nodemcu-firmware#856]
hi and thanks for your great work. 

i am trying to write some dmx messages via uart but i think the baudrate of 250000 Bd is not currently supported. in detail, the baudrate seems not to be changed. I have seen that for the arduino project and Ulrich Radig made an implementation for the WLAN Art-Net Node project. So i think the es8266 should be able to do 250000 Bd. Can you please add that rate?

Cheers and best regards

**Comment by TerryE** [comment]
No sorry. Can't do.  It does support 230,400 which is probably close enough to work.
