### ISSUE TITLE
ENDUSER_SETUP_AP_SSID must be defined even if the module is not being used.

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#863]
@robertfoss, If you are not using End User Setup (i.e `LUA_USE_MODULES_ENDUSER_SETUP` is not defined in user_modules) then the make still fails if `ENDUSER_SETUP_AP_SSID` is not defined.  This shouldn't happen.  Before its first use: `ENDUSER_SETUP_AP_SSID:643` there should be conditional logic to define it to be an empty string or equiv if undefined.

**Comment by robertfoss** [comment]
Agreed. I will supply a PR.

**Comment by TerryE** [comment]
Thanks Robert :smile:
