### ISSUE TITLE
Do the nodeMCU AP functionality goes OFF for a sec when connecting to a new AP?

### ISSUE THREAD

**Issue by domingosl** [nodemcu/nodemcu-firmware#867]
If I connect my cellphone to a wifi network created by nodemcu (let call it wifiA) in stationap mode, and then I make the nodemcu to connect to a wifi network (wifiB) without telling him to close wifiA, my cellphone disconnects from wifiA, and then I have to manually reconnect it to wifiA. It makes me think that nodemcu goes on tilt for a few seconds when trying to connect to a wifi network, and my cellphone modem just disconnects since the network dies for a few seconds, is this true?

If I repeat the experiment using my computer instead of my cellphone, it does not disconnects from wifiA when node is connecting to wifiB, it remains connected as it should, maybe the computer modem is more "patience" and waits a little longer before closing the connection?

**Comment by TerryE** [comment]
Please see #719 and you will understand why I am closing this issue.  This is a list for developers of the firmware and there are other forums for Lua developers on the ESP8266 to ask questions.
