### ISSUE TITLE
ucg getStrWidth returning error

### ISSUE THREAD

**Issue by FrankX0** [nodemcu/nodemcu-firmware#880]
Function ucg:getStrWidth always returns an error:
_bad argument #4 to 'getStrWidth' (string expected, got no value)_

Issue is located in ucg.c (lucg_getStrWidth):
> const char *s = luaL_checkstring( L, (1+3) + 1 );

should be replaced by

>  const char *s = luaL_checkstring( L, 2 );

**Comment by devsaurus** [comment]
Thanks for reporting @FrankX0.
Please review #881 accordingly and let me know whether your issue is fixed there.

**Comment by FrankX0** [comment]
Issue is fixed.
Thanks!
