### ISSUE TITLE
Travis SDK contains a lot of bloatware

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#884]
We copied the SDK used for Travis CI from George Hahn's repository.  It's 32Mb extra in ours.  Given that it's already a blob in our Repo, it's not worth changing at this time but if we do need to change it in the future 
-   Don't use GZ encoding; use XZ.  This is just _so_ much more efficient.  OK, compression takes ages, but we only uncompress during a Travis CI build and this is as fast as GZ uncompression.
-   Lose all of the unused stuff in the tarball -- that is only retain that which is needed to build nodemcu.  This includes c++ compiler, libraries and includes; gdb; all of the sources not used in our make.

This will more than half the size of the `.tar.xz` file compared to the `.tar.gz` version.

**Comment by djphoenix** [comment]
Fixed by #1743
