### ISSUE TITLE
SNTP module retries while a DNS lookup is in progress

### ISSUE THREAD

**Issue by joux3** [nodemcu/nodemcu-firmware#889]
SNTP module contains automatic retries for sending the request using UDP. However, the timer for packet resending is set before a possible DNS request has finished.

Reproduction, that causes a reset on a freshly booted chip ([result](https://cloud.githubusercontent.com/assets/9249/12038583/1fa0de1e-ae62-11e5-9847-d1b6e3642823.png)):

```
-- setup wlan not to work
wifi.setmode(wifi.STATION)
wifi.sta.config("nonexistant", "doesntmatter")

sntp.sync("guaranteedtofail.com", function() end, function() 
    print("failed to get time") 
end)
```

Root cause seems to be, that a resend timer is set before DNS lookup finishes ([code](https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/sntp.c#L343-L345)). This results in `sntp_dosend` being called with the `server` variable possibly not being set, if the DNS request has not finished in the first timer interval. That causes the socket send to most probably fail, which results in `cleanup` cleaning all possible state. This state is then accessed in the call to `sntp_dns_found` once the DNS lookup finishes. This eventually results in a `NULL` dereference.

A workaround is to use `net.dns.resolve` manully before calling `sntp.sync`.

The fix seems pretty straightforward: set the timer only after the DNS request has completed succesfully. For now I'm a bit busy so I can't promise a pull request with the fix in the very near future.

**Comment by pjsg** [comment]
This no longer seems to be a problem. The sntp code was extensively modified since this ticket was filed. 

If it still a problem, then please reopen.
