### ISSUE TITLE
Provide access to all the fields in the rst_info structure

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#900]
With the 1.5 SDK, the function system_get_rst_info now returns data that looks plausible. Can the node.bootreason() be updated to return the additional data (probably as extra return values). This could be made backwards compatible.

**Comment by TerryE** [comment]
Will do :smile:

**Comment by pjsg** [comment]
This might be useful in debugging the spiffs crash....

**Comment by jmattsson** [comment]
Funny you should say that... that's what I just did. PR inc.

**Comment by jmattsson** [comment]
PR #924

**Comment by nickandrew** [comment]
This is all merged? So closing.
