### ISSUE TITLE
Would it be possible to send custom data through smart config?

### ISSUE THREAD

**Issue by matoushybl** [nodemcu/nodemcu-firmware#904]
Hi, I'd like to ask if it would be possible to somehow add sending custom data sending through smartconfig. It would be a nice feature for for example setting up MQTT broker IP.

Thanks.

**Comment by dnc40085** [comment]
I took a look at the Smart Config API section in the [SDK Programming Guide v1.5](http://bbs.espressif.com/download/file.php?id=1027) and I did not find any hint of being able to pass user data via Smart Config. Maybe you could setup the ESP8266 to host a web page to configure the MQTT broker IP.
