### ISSUE TITLE
MQTT secure handshake fail

### ISSUE THREAD

**Issue by TheB1ackSheep** [nodemcu/nodemcu-firmware#912]
I setup MQTT server using mosquitto with SSL and try to connect with NodeMCU with 
```
m:connect(MQTT_HOST, MQTT_PORT, 1)
```
I also bind on:connect and print "success" after connected but the server tell me this when NodeMCU is connecting
```
New connection from 110.171.33.26 on port 1883.                                                                                                          
OpenSSL Error: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure                                                                 
OpenSSL Error: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure                                                                         
Socket error on client <unknown>, disconnecting.  
```
I think I have to specific ca to the node but how?

P.S. I can connect to the server with insecure connection.
P.S.2 I try to use MQTT client in my laptop. it has to specific my server ca file to make a connection success.

**Comment by nickandrew** [comment]
This looks like a #719 issue.

**Comment by TerryE** [comment]
+1
