### ISSUE TITLE
TM1829 module missing in master & dev

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#920]
Just noticed that #686 is missing in master & dev. I couldn't find any notes as to why this could be intentional. Was it simply forgotten in the recent 1.4 upgrade and the necessary branch/PR clean-up (PR was directly merged to master)?

**Comment by jmattsson** [comment]
I'm not aware of any reason why it should be excluded. I'd say it was simply missed in the cleanup.

**Comment by TerryE** [comment]
+1 My bad.

**Comment by devsaurus** [comment]
Thought it was still awaiting some kind of check/verification since it never got in touch with a recent SDK on `dev`.

**Comment by TerryE** [comment]
Yup, I did ask the contributors to resubmit, but I should have followed it up.

**Comment by marcelstoer** [comment]
@h3ndrik can you please take care of that.

**Comment by h3ndrik** [comment]
thanks. submitted new pull requests for master #983 and dev-branch #984
