### ISSUE TITLE
dht: allow pin 0

### ISSUE THREAD

**Issue by dvv** [nodemcu/nodemcu-firmware#922]
https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/modules/dht.c#L15

The condition forbids using DHT on pin 0.
Is it intended?

TIA

**Comment by TerryE** [comment]
Thanks Vladimir.  This is a clear issue. I've assigned it to vowstar as he was the main contributor.

**Comment by vowstar** [comment]
Yes, Pin 0 is fast possible to use on DHT, I will test it in this week.
