### ISSUE TITLE
Bug in rotable handling

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#929]
This is an elua bug but I'll post it here first.  There are two parts (i) a bug and (ii) inefficient coding.  Since I've got to fix the first, I may as well fix the second as well. In `lauxlib.c:luaL_findtable ()` the third argument is a table name which can be of the form `rotable.some_extremely_long_table`.  Lines 410:415 handle the embedded '.' case and in this case would pass a length of 7 rather than the strlen which is 34.  However at `lrotable.c:23` a strlen check is made against `LUA_MAX_ROTABLE_NAME` (32).  The rotable name length is 7 but the strlen is 34 so this test fails and the function `luaL_findtable()` will invalidly return NULL.  This strlen is also redundant is that the strnmp limits the comparison to the supplied length anyway.

The dumb coding in that this is a linear scan and hence will check n/2 false matches in general before a true match.  You want the if test in the loop to short circuit with the least-cost potent test, and so:

``` patch
--- a/app/lua/lrotable.c
+++ b/app/lua/lrotable.c
@@ -20,10 +20,8 @@ extern const luaR_table lua_rotable[];
 void* luaR_findglobal(const char *name, unsigned len) {
   unsigned i;

-  if (c_strlen(name) > LUA_MAX_ROTABLE_NAME)
-    return NULL;
   for (i=0; lua_rotable[i].name; i ++)
-    if (*lua_rotable[i].name != '\0' && c_strlen(lua_rotable[i].name) == len && !c_strncmp(lua_rotable[i].name, name, len)) {
+    if (lua_rotable[i].name[0] == name[0] && lua_rotable[i].name[len] == '\0' && !c_strncmp(lua_rotable[i].name, name, len)) )  {
       return (void*)(lua_rotable[i].pentries);
     }
   return NULL;
```

The second test might cause unaligned read exceptions so this might run faster if I swap the terminator and strncmp tests around.  With our current rotables list this reordering shortcircuits the `if` test  over 90% of the time. 

I am not going to issue a PR since I am doing other rotable stuff for this tasking interface and will sweep this up here.

**Comment by jmattsson** [comment]
I'm probably missing something here, but if the longest a rotable name can be is 32 (presumably due to fixed array size), why is it invalid to return NULL if the scanned-for name is 34 long?

**Comment by TerryE** [comment]
In my example the rotable is `rotable` which is 7 chars long, but the function returns NULL rather than the rotable address.

**Comment by jmattsson** [comment]
Aaaah, right. Embedded dot. Now I'm with you.

**Comment by TerryE** [comment]
I've never made this change!!  Added to my TODO.
