### ISSUE TITLE
BUG in node.bootreason()?

### ISSUE THREAD

**Issue by chegongcai** [nodemcu/nodemcu-firmware#931]
There is my code:
flag=node.bootreason()
print("reason is:")
print(flag)
The flag always is 2, I had tried to let it startup from normal startup by power on, wake up from deep-sleep and external system reset.

static int node_bootreason (lua_State *L)
{
  struct rst_info *ri = system_get_rst_info ();
  lua_pushnumber (L, rtc_get_reset_reason ());
  lua_pushnumber (L, ri->reason);
  if (ri->reason == REASON_EXCEPTION_RST)
  {
    lua_pushnumber (L, ri->epc1);
    lua_pushnumber (L, ri->epc2);
    lua_pushnumber (L, ri->epc3);
    lua_pushnumber (L, ri->excvaddr);
    lua_pushnumber (L, ri->depc);
    return 7;
  }
  else
    return 2;
}

**Comment by TerryE** [comment]
Can you please use the issue that is already open #900 rather than opening duplicates. Also please use styling to format code.
