### ISSUE TITLE
Rebaselining the nodeMCU Lua official FAQ

### ISSUE THREAD

**Issue by TerryE** [nodemcu/nodemcu-firmware#937]
If we are going to move the FAQ into the distro, then we can hardly call it unofficial (see #449 for previous issue).  This is to discuss the necessary changes to prepare the FAQ for moving into the official document set.

**Comment by marcelstoer** [comment]
"How to write a new module" (inspiration from http://desperate-programmers.com/2016/01/19/creating-a-new-nodemcu-user-module/) would be a page of its own rather than an FAQ question, right?

**Comment by TerryE** [comment]
Yes I t hunk that we need to split the FAQ into two parts: one for Lua developers and one for C module developers.

**Comment by TerryE** [comment]
@marcelstoer Marcel, thanks for this.  What I suggest is that we open a new issue to role forward any open points and to act as a discussion framework for the next round of enhancements.  What would be good is if we could get an active discussion going with some of the more experienced Lua developers to get their feedback on the issues that trip them up and address these within a FAQ framework, but let's have this discussion on the new issue.

**Comment by marcelstoer** [comment]
Sure, I wouldn't mind, feel free to open a new issue. For the stuff _I_ am interested in I opened and will continue to open dedicated issues (#1861 & #1862 for now).
