### ISSUE TITLE
nodemcu v0.9 for arduino IDE error

### ISSUE THREAD

**Issue by jajaspider** [nodemcu/nodemcu-firmware#939]
![12](https://cloud.githubusercontent.com/assets/16714415/12345833/726de2b8-bb91-11e5-9341-0dd29edb4829.PNG)
warning: espcomm_sync failed
error: espcomm_open failed
two error
OS : Windows 7
IDE : Arduino IDE 1.6.4

plz help me

**Comment by TerryE** [comment]
Please send #719. This will point you to the forums where you ask this type of Q.
