### ISSUE TITLE
Clean up the HTTP client module

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#941]
See https://github.com/nodemcu/nodemcu-firmware/pull/887#issuecomment-171936376:
- write documentation
- move examples from README to examples dir

**Comment by jmattsson** [comment]
Somewhere/somewhen I volunteered to write the API docs for it. I've got it on my todo list, either this weekend or early next.

**Comment by jmattsson** [comment]
I've added module docs to `newdocs`

**Comment by jmattsson** [comment]
Considering the module docs include examples, should they perhaps just be removed from the readme? (as opposed to moved elsewhere)

**Comment by devsaurus** [comment]
Guess so, #771 also proposes to remove examples from the README.
My approach is to have code *snippets* in the module docs, but to store full-fledged scripts that can actually be executed in `lua/examples`.

**Comment by TerryE** [comment]
I think that the current code snippets can be very misleading.  I would prefer every module to have at least one full-fledged script which demonstrates best practice in using the module, and that this is in `lua_examples` _not_ `lua/examples`.

**Comment by marcelstoer** [comment]
Indeed, as per #771 and #772 full-fledged examples, not to be mixed up with the snippets in the docs, should be removed from README.
