### ISSUE TITLE
SD Card interfacing

### ISSUE THREAD

**Issue by laxmimerit** [nodemcu/nodemcu-firmware#948]
Hello,
        where can I get sd card interfacing with esp8266 example in lua language?

**Comment by TerryE** [comment]
This is the wrong place to ask this sort of Q. See #719 for links to forums which are aimed at providing applications programming help.  However we don't current provide a Lu programmable interface to standard SD cards, just the on-module Flash memory.

**Comment by cjdg** [comment]
is there any plan to include an sd card interface?

**Comment by TerryE** [comment]
Nope. Sorry.

**Comment by marcelstoer** [comment]
> is there any plan to include an sd card interface?

It'd be nice to have I agree. Guess we'd welcome PRs of a ported SD lib like https://github.com/esp8266/Arduino/tree/master/libraries/SD. The WeMos folks prefer Arduino over NodeMCU and have Arduino examples for all their cool shields (-> Micro SD http://www.wemos.cc/Products/micro_sd_shield.html).

**Comment by marcelstoer** [comment]
Arnim is looking into this #1321.
