### ISSUE TITLE
string.format("%.2x",val) behavior

### ISSUE THREAD

**Issue by 1am** [nodemcu/nodemcu-firmware#97]
Hi,

I've been trying out the nodemcu-firmware which is really great! I've found one thing which is a bit strange when the same code is executed on a desktop and ESP-8266.
The following line
```
string.format("%.2x",num)
```
prints out "*%.2lx*" instead of a 2 byte hex. On the other hand he following:
```
string.format("%x",num)
```
Prints a correct hex value - of course without the preceeding zero which is easy to fix with a if check for 8bit intigers. I don't know if this is an issue since of ESP's limitations but I've found this behavior a bit strange.

**Comment by nodemcu** [comment]
```lua
string.format("%.2x",num)
```
is this for float? float number is not supported.

```lua
print(string.format("%2x",255))
```
maybe
