### ISSUE TITLE
Error reading an array in lua

### ISSUE THREAD

**Issue by djsharpless** [nodemcu/nodemcu-firmware#989]
Can someone shed some light on why this doesn't work? My device shows Lua 5.1.4 and this works fine on windows.

tab = {1,2,3}
tab[1] = 1
t = tab[1]  -- ERROR

**Comment by devyte** [comment]
Hi,

I just tested this in my nodemcu, also with lua 5.1.4, and it works fine
for me.

Are you running from a .lua? .lc? Esplorer command line? Did you build your
own firmware, or used the build service?

**Comment by dvv** [comment]
May we look at the whole session? And verbose error

**Comment by jmattsson** [comment]
This is not the right place for this question. Please see #719 for links to more appropriate forums.
